### ISSUE TITLE
Can't install Ubuntu on Chromebook 14 

### ISSUE THREAD

**Issue by jessejay96** [dnschneid/crouton#1116]
I've been attempting to install Ubuntu on my Chromebook HP 14 using crouton. I was following a tutorial on cnet, but I'm running into trouble. When i type command sudo -e ~/Downloads/crouton -t unity" all i get is this large message.

```
#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file of the source repository, which has been replicated
# below for convenience of distribution:
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#    * Neither the name of Google Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This is an indirect script. The actual installer will be downloaded, cached,
"/var/tmp/crouton.XXhGl4cZ" 87 lines, 3653 characters
```

Even when i try to open Crouton to look over the files it has i get this large message. I already tried factory resetting and reentering into developer mode, but still nothing. I think the installer may have come up before, but unknowingly i exited the shell so i think that maybe part of my issue. Any ideas?

Cnet tutorial (http://www.cnet.com/how-to/how-to-run-both-chrome-os-and-ubuntu-on-a-chromebook/)

**Comment by nasrshahbaz545** [comment]
I tried same, but faced 

Quote: sudo sh ~/Downloads/crouton -r trusty -t unity,keyboard,extension
Your version of Chromium OS is extraordinarily old.
If there are updates pending, please reboot and try again.
Otherwise, you may not be getting automatic updates, in which case you should
post your update_engine.log from chrome://system to http://crbug.com/296768 and
restore your device using a recovery USB: https://goo.gl/AZ74hj
chronos@localhost / $ 
Unquote

Please help! I do not have any experience of coding or  . . . . . I tried to access into dev mod before, but after pressing ctrl + refresh + power buttons, it took me to the arror message, there i pressed ctrl + D ..... nothing happened. I've shared my screenphoto here http://acca-material.eu5.org/nasr/photo.jpg pls check and if you could help me insatall ubuntu. Thank you!

**Comment by DennisLfromGA** [comment]
@nasrshahbaz545 - 
- The link to your *[screenphoto](http://acca-material.eu5.org/nasr/photo.jpg )* doesn't work.
- What system are you using: a Chromebook, Chromebox, etc. ?
- What is the model: Asus Chromebook Flip, HP Chromebook 11, etc. ?
- Once you get into Developer mode and enter a shell terminal session, what does `cat /etc/lsb-release` show ?
