### ISSUE TITLE
Change Software Sources for Chroot After Installing

### ISSUE THREAD

**Issue by Ranctifier** [dnschneid/crouton#1224]
I have Ubuntu 14.04 (trusty) installed on my Chromebook, I'm not sure when but it was months ago.

I particularly like the convenience of using "sudo sh crouton -u -n trusty" from crosh rather than having to enter the chroot for updating.

I noticed that at least one of the software sources for my chroot are from the previous LTS (precise).

Obviously I can update inside the chroot without those precise mirrors by changing the repositories in synaptic.

I tried using something like "sudo sh crouton -u -n trusty -m http://mirrors.kernel.org/trusty" but it doesn't do anything, so clearly my approach is wrong.

Is there a way to reflect that change to crouton or at least manually specify the software sources when running "sudo sh crouton -u -n trusty" ?

**Comment by Ranctifier** [comment]
Here:

(trusty)myname@localhost:~$ croutonversion
crouton: version 1-20141118113718~master:0708c122
release: trusty
architecture: amd64
targets: xfce
host: version 6310.61.0 (Official Build) stable-channel parrot

**Comment by dnschneid** [comment]
Sorry, I feel like a bit of a dunce here.  The precise sources are added by the xorg target to downgrade some X11 libraries.  There should be an apt preferences in place to *not* use those sources for anything else.  If it's getting in the way, please let us know; otherwise, it's the thing that is keeping your video accelerated.
