### ISSUE TITLE
xiwi confuses the keyboard layout

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1275]
xiwi appears to pass through post-Chromium-keyboard-layout keypresses, which then confuses X11.  That is, if you use a keyboard layout that maps s -> r and r -> p, pressing the S key in xiwi will result in an R keypress in X11.  If you are then silly enough to set up the same keyboard layout inside of X11, that R will then be helpfully translated into a P by X11.

xiwi should send raw keypresses, disregarding any keyboard layout settings.

**Comment by dylanPowers** [comment]
Is this related to certain key combo's not being passed? Things like super+enter, super+space, super+arrows, and super+num don't work. Or because they're connected to actions in chromium OS should I forget about them working how I want?

**Comment by dafyddg** [comment]
I have successfully updated my xfce on trusty crouton installation on the HP 14" Chromebook with the xiwi and extension targets. Everything works fine except that using the German keyboard layout a large number of keys (special characters, punctuation) yield incorrect characters. Several keys produce the same characters. Updating again with the x11 target removes xiwi and also the normal German character mapping.
Is there a fix for this? If so, details would be appreciated. I have not seen one so far. Thanks.

**Comment by drinkcat** [comment]
Looks like we may need to use the key's code string to guess the key:

Pressing semicolon with US keyboard:
`Key UP: C:Semicolon/KC:ba/KS:3b searchstate:0` (outputs a semicolon)
And pressing it with CH(FR) keyboard (should be a 'é'):
`UP: C:Semicolon/KC:de/KS:27 searchstate:0` (outputs a quote, no matter the layout in the chroot)

Provided crbug.com/425156 is fixed. Need to check how Chromoting does it, too.

**Comment by drinkcat** [comment]
So, Chrome Remote Desktop uses `GetCode()` (the string above).

The NaCl module will need to translate this string to a X11 keycode (i.e. key position on the keyboard).

What we need to do is to modify the protocol to pass X11 keycodes, instead of keysyms (translated symbol, layout-dependant), so that the crouton X11 server can do the appropriate translation. This means we need to bump the protocol version to `VF2`. Unfortunately, the extension is completely broken when it comes to error reporting: it cannot distinguish between protocol errors, version mismatch, or "normal" disconnect. And we cannot break compatibility with "old" chroots unless we have clear and user friendly reporting.

I started working on this, but it's going to take a bit of time to implement and test properly.

So, instead, for a smooth transition, I'm going to maintain compatibility in the extension with `fbserver` version `VF1` and `VF2`, then think about an appropriate way to throw a warning, and finally drop support for `VF1`.

**Comment by appsforartists** [comment]
This is also helpful if you've swapped Alt and Ctrl (to be get more Mac-like keybindings in Chrome).  Otherwise, you'll end up in a situation where pressing a key does Alt in xiwi and ctrl in proper X11.

**Comment by stsquad** [comment]
@drinkcat do you have a WIP branch I can look at (and maybe help with)...

**Comment by dnschneid** [comment]
Merged.  Any remaining issues should be in new bugs.
