### ISSUE TITLE
Upgrading from xorg to xiwi on precise is broken

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1294]
As highlighted [here](https://github.com/dnschneid/crouton/issues/1274#issuecomment-68442881), upgrading from xorg to xiwi on precise is broken.  This is because precise brings in the -lts backport packages, but we blindly try to use the non-backport dummy.

**Comment by dnschneid** [comment]
Nope.  Unfortunately, Unity on Trusty on ARM doesn't have a nice 2D fallback; it switches to software 3D rendering which is sloooow.  This is the primary reason why trusty hasn't replaced precise as the default release yet...

**Comment by ubuntunoob** [comment]
Because I am having difficulty running Crouton Integration with xiwi and precise, I found a reasonable alternative to make switching between the two operating systems easier.

 I came across the following from an individual (Penn Taylor) which permits switching between Ubuntu and Chrome using only the ctrl-esc keys.

Run this command from within the chroot:

sudo sh -c "echo \"(xbindkey '(control Escape) \\\"croutoncycle next\\\")\" >> /etc/crouton/xbindkeysrc.scm"

(That should be all one long line, with a space between >> and /etc.)

Then log out of the chroot. When you start it up again, you'll be able to use ctrl+escape to switch back and forth. ﻿

**Comment by ubuntunoob** [comment]
Regarding broken upgrade to xiwi, I was able to install the missing dependencies and get precise working with crouton integration.

sudo apt-get install xorg-video-abi-11 xserver-xorg-core

sudo sh ~/Downloads/crouton -t extension -u

**Comment by tedm** [comment]
Just a note - on the ARM system, xorg-video-abi-11 is not a valid package, and the latest crouton will update to the current xserver-xorg-core.

If intel precise / xfce / xiwi users still need to manually pull in the xorg-video-abi-11 package, perhaps this should re-open? 

Also won't a -u still update all targets in /etc/crouton/targets ? if the DE, or xiwi are updated, and extension is in /etc/crouton/targets, it shouldn't need a manual specific update, or did something change?

**Comment by ubuntunoob** [comment]
I was unable to load precise at all with the xiwi extension because of missing dependencies.

sudo sh ~/Downloads/crouton -t xiwi,xfce

For this reason I loaded a stripped version with only the xfce extension, which loaded successfully.

sudo sh ~/Downloads/crouton -t xfce

With this install precise would run, but not with Crouton Integration in a window

I then downloaded the missing dependencies

sudo apt-get install xorg-video-abi-11 xserver-xorg-core

As you pointed out, xorg-video-abi-11 was detected as not being a valid package, but the install automatically found the correct one.

Because I wanted it to work with Crouton Integration in a window I then updated it with extension

sudo sh ~/Downloads/crouton -t extension -u

sudo startxfce4

This was successful and I now have precise working in a Chrome window.

Perhaps the extension update was unnecessary, as it had previously been attempted with the first install that was unsuccessful because of the missing dependencies..

**Comment by tedm** [comment]
@ubuntunoob when you say "loading" are you creating a brand new chroot, or do you already have an existing chroot that you are updating, or updating targets on? My understanding is that if the target xiwi is installed or updated on a chroot, that the extension target is pulled in, and any subsequent -u upgrades of the chroot will upgrade all targets associated with the chroot.

**Comment by ubuntunoob** [comment]
By loading I mean that I am creating a chroot on a virgin chromebook.

The first attempt with xiwi was unsuccessful because of unmet dependencies. Although it likely created the chroot, I couldn't run precise.

I then loaded the unmet dependencies, but before running with sudo startxfce4, I updated and added the extension target, which may or may not have been necessary.

**Comment by DennisLfromGA** [comment]
On Tue, Jan 20, 2015 at 4:28 PM, ubuntunoob <notifications@github.com>
wrote:

> The first attempt with xiwi was unsuccessful because of unmet dependencies.


I believe it *was* necessary but I think I would have done '-t xiwi -u'
instead.
Probably didn't really matter if *any* target was specified since '-u' will
update all existing targets which already included both 'xiwi' and
'extension' like @ted mentioned.



-- 
*DennyL@GMail*

**Comment by tedm** [comment]
@ubuntunoob ok, gotcha. Well this should eventually work on a fresh install:

sudo sh ~/Downloads/crouton -t xiwi,xfce

as long as the decision to support precise and xiwi on ARM is valid, and this #1294 is still open. I can test if anyone needs it. Updating with today's crouton is still working well with ARM and precise.

**Comment by ubuntunoob** [comment]
In late December 2014 the following would create a new working precise chroot

sudo sh ~/Downloads/crouton -t xiwi,xfce

In early January 2015, 2 weeks later it would not because of missing dependencies.

In your post you stated  ok, gotcha. Well this should eventually work on a fresh install:

I was wondering what you meant by use of the word "eventually".

**Comment by tedm** [comment]
@ubuntunoob The developers working on Crouton are among the best, and most responsove, and eventually resolve everything. The fact that this is an open issue, means it is on their radar and will likely be resolved hopefully very soon (from experience as a user and fan, they fix things fast). Since Crouton launched there were a couple of times I was down due to my particular setup and I felt totally lost, but things did get fixed, and I think this will get fixed soon. I'm sorry about using the word "eventually" I should have said that I hope it gets fixed by the developers fast, because us precise / xfce users can be in a bind or have to make alternate chroots or not use xiwi until it is resolved.

**Comment by AdmiralAsshat** [comment]
By some miracle I did manage to get precise working with extension by manually installing the dependencies.

However, having played with it, I'd like to issue a warning to all people running ElementaryOS / pantheon desktop:  don't install xiwi. The performance on the elementary chroot takes a nosedive with xiwi/extension installed, bordering on unusable. And this is on Pixel specs.

At this point I'm debating keeping ElementaryOS's chroot separate and setting up a xiwi chroot just for running XAMPP and Android Studio.

**Comment by dnschneid** [comment]
Note: xiwi also needs dmz-cursor-theme.  I think we need to clean up what gets installed in xiwi/xorg/xephyr vs x11-common.
