### ISSUE TITLE
[INSTALL] I'm a newbie

### ISSUE THREAD

**Issue by D3dou** [dnschneid/crouton#1301]
Hey,

before discovering the crouton's extension for Chrome, i already have installed crouton and ubunutu on my chromebook.

Now i would like make this extension work on my chrome but,
i'm stuck at this step : 2. Add the extension or xiwi version to your chroot.

What do i have to do here ? I don't understand the point :-/

Thanks in advance for your help.

**Comment by ivangolubev** [comment]
the same problem with me

**Comment by tedm** [comment]
adding the xiwi target to your existing chroot will bring in the `extension` target so you can just type at a crosh / shell prompt:

sh -e ~/Downloads/crouton -t xiwi

Be sure you have the latest crouton, and also ensure you have retrieved v2 of the Chrome Extension app in the store.

If you're on precise, and Intel, you may need to use the trusty release for now.

**Comment by ivangolubev** [comment]
I've used your tip, but the chrome extension is still disconnected.

I have installed ubuntu on acer-c720 via: 
sh ~/Downloads/crouton -t unity -r trusty
then installed extension
then followed your tip.

here is the info about my computer:
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20141231011135~master:992afe3e
release: trusty
architecture: amd64
targets: unity
host: version 6310.68.0 (Official Build) stable-channel peppy 

What am I doing wrong?

**Comment by tedm** [comment]
you need to add xiwi as the first target at this time per open issues #1198 and #1274 (duplicate/closed)

so did you add xiwi first like:

sudo sh ~/Downloads -t xiwi,unity -u -r trusty

**Comment by ivangolubev** [comment]
Thank you very much, works charmingly now.

**Comment by D3dou** [comment]
Okay, i think i'm really really noob...

It doesn't seems to work, even after this command :
sh -e ~/Downloads/crouton -t xiwi
or this one :
sudo sh ~/Downloads -t xiwi,unity -u -r trusty

I can still launch ubuntu with crosh but it seems to be not visible by crouton for chrome... what am i doing wrong ? :-/

**Comment by ivangolubev** [comment]
I forgot to tell: there was a small mistake, try:
sudo sh ~/Downloads/crouton -t xiwi,unity -u -r trusty

**Comment by tedm** [comment]
@ivangolubev Thank you for correcting my typo. I fixed my mistake above.

@D3dou My first post had an error which @ivangolubev fixed, the command line in his post above should work.

**Comment by dnschneid** [comment]
@tedm you're missing the -u for the first command as well.

@D3dou try `sudo sh -e ~/Downloads/crouton -u -t xiwi`, and if that fails, please post the output of `sudo edit-chroot -al`

**Comment by tedm** [comment]
@dnschneid Thanks, I will begin recommending `-u` to upgrade all targets.

**Comment by dnschneid** [comment]
That's the only way to do it...

**Comment by tedm** [comment]
Right, for upgrading targets. But when creating brand new chroots with the xiwi target, or adding xiwi to an existing chroot (chroot is updated, -t xiwi,... is first time target install), is -u still required in those cases?

**Comment by dnschneid** [comment]
If the chroot already exists, you have to specify -u.

**Comment by tedm** [comment]
Got it. Thanks.

**Comment by D3dou** [comment]
Thanks for your help but it's still not good for me :-(

command : sudo sh ~/Downloads/crouton -t xiwi,unity -u -r precise
error logs :
W: Failed to fetch https://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

command : sudo sh ~/Downloads/crouton -u -t xiwi
error logs :
W: Failed to fetch https://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

command : sudo edit-chroot -al
output :
name: precise
encrypted: yes, unlocked
Enter encryption passphrase for precise: 
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20141231011135~master:992afe3e
release: precise
architecture: armhf
targets: xiwi,unity,keyboard
host: version 6310.68.0 (Official Build) stable-channel daisy_spring 
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by D3dou** [comment]
Any ideas ? :-/

**Comment by tedm** [comment]
@D3dou just some addl. data points - I'm running precise on ARM but xfce, not unity. 

If you have the space, you could try unity on trusty with xiwi, or if you can use xfce, xiwi and xfce work great together on the arm with precise.

**Comment by dnschneid** [comment]
You appear to have attempted to install the Chrome browser in your ARM chroot.  Remove that from the sources.list.d and try again.

**Comment by D3dou** [comment]
Sad, i don't like the graphic interface for xfce, the font is really ugly and disproportionate...
I guess i will continue with the regular way :-(

**Comment by dnschneid** [comment]
Woohoo!

**Comment by tedm** [comment]
@dnschneid Wasn't there an issue opened way back to check if the installer was running in a chroot? and if so, exit with a message?

**Comment by dnschneid** [comment]
Nope.  You could open a separate bug on that if it's a problem.

**Comment by MLP10V3R99** [comment]
I need some serious help... Could someone please help me?

**Comment by DennisLfromGA** [comment]
yes ;)

On Tue, Mar 24, 2015 at 9:57 PM, MLP10V3R99 <notifications@github.com>
wrote:

> I need some serious help... Could someone please help me?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1301#issuecomment-85783747>.
>



-- 
*DennyL@GMail*

**Comment by mathuin** [comment]
@MLP10V3R99 your best bet on getting this level of assistance is from the IRC channel.  It's on the FreeNode network and it's named #crouton.  For your specific situation, it sounds like you're not yet in developer mode.  Follow the links and instructions on the README.md for crouton, starting from the Prerequisites section, and I think you'll get to the finish line quickly!  Good luck!

**Comment by mhoffma** [comment]
so I have this crouton working perfectly with startxfce4 when I just install touch,xfce trusty.  I backed up my chroot after getting it to work nicely.  And then I do the update command you gave above but I get the frustrating can't connect message:


usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,touch,xfce
host: version 8872.76.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Fri Jan 6 23:48:33 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.


So I log into my enter-chroot bash

and try to launch it by hand I get the same thing.

(trusty)mmh@localhost:~$ croutonversion 
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,touch,xfce
host: version 8872.76.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Fri Jan 6 23:48:33 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Any help would be greatly appreciated this tool set rocks, and I think the unified desktop version would rock even more.....

**Comment by DennisLfromGA** [comment]
@mhoffma,

It looks like you were trying to *launch* your chroot instead of update it.

To *update* it, use this instead: `sudo sh ~/Downloads/crouton -n trusty -u`
Then after it updates successfully just *launch* it with: `sudo startxfce4 -n trusty`

*Hope this helps,*
-**DennisL**

**Comment by mhoffma** [comment]
figured it out thanks, forgot to install the extension in chrome.
