### ISSUE TITLE
HiDPI + System scaling

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1322]
The extension seems to still react to system scaling when HiDPI is set.  I'm not sure this is a good thing, since it tends to result in very odd zoom sizes.

Is it possible to ignore system zoom settings?

**Comment by dnschneid** [comment]
OK this definitely should be fixed.  For example: using system scaling to go to 1920x1275 results in xiwi attempting to run at 3840x2550, which actually fails and causes all sorts of problems.

**Comment by drinkcat** [comment]
Can you have a look at `InitContext` lines in the console log, with different system scaling? I'm not sure if what Chromium OS is feeding us is correct...

**Comment by dnschneid** [comment]
Window size unchanged throughout:

```
HiDPI disabled, 100% sys zoom: InitContext 977x631s1 (device scale: 2, zoom level: 1)
HiDPI disabled, 110% sys zoom: InitContext 977x631s1 (device scale: 2, zoom level: 1)
HiDPI disabled,  90% sys zoom: InitContext 977x631s1 (device scale: 2, zoom level: 1)
HiDPI disabled,  50% sys zoom: InitContext 977x631s1 (device scale: 1, zoom level: 1)
HiDPI  enabled, 100% sys zoom: InitContext 1954x1262s2 (device scale: 2, zoom level: 1)
HiDPI  enabled, 110% sys zoom: InitContext 1954x1262s2 (device scale: 2, zoom level: 1)
HiDPI  enabled,  90% sys zoom: InitContext 1954x1262s2 (device scale: 2, zoom level: 1)
HiDPI  enabled,  50% sys zoom: InitContext 977x631s1 (device scale: 1, zoom level: 1)
```

So yeah, the data is complete garbage.

**Comment by drinkcat** [comment]
By `50% sys zoom`, you mean 1920x1275? And `100% sys zoom` is the default 3840x2550? (I get actual resolutions and not percentages on my stable peppy, maybe it's different on your platform/channel)

If that's the case, the device scale looks ok to me...

> so if you enable hi-dpi mode then system scale to pixel-exact, you get a ridiculous resolution.

And, in what case does this one happen?

**Comment by dnschneid** [comment]
Sorry, I mean pixel size zoom.  So 100% is 1280 and 50% is 2560 (pixel exact).

Hi-DPI + slightly-zoomed out mode (1600x1062) results in a crouton resolution of 3200x2124.
Hi-DPI + fully-zoomed-out results in an attempted mode of double-max resolution (5120xwhatever), which fails.

**Comment by drinkcat** [comment]
Okay. The 100% one is good, that's the default system zoom, and the device scale is correct (2 device pixels per DIP, see https://developer.chrome.com/native-client/pepper_dev/cpp/classpp_1_1_view#a52759c57da28a6c06a5da23d28519287). You can enable/disable hidpi mode safely.
```
HiDPI disabled, 100% sys zoom: InitContext  977x 631s1 (device scale: 2, zoom level: 1)
HiDPI  enabled, 100% sys zoom: InitContext 1954x1262s2 (device scale: 2, zoom level: 1)
```

The 50% one also looks good. If you are having problem with it, could you provide a trace? (InitContext line and around it...). device scale is 1, so hidpi cannot be enabled (or if it can, it makes no difference...)
```
HiDPI disabled,  50% sys zoom: InitContext  977x 631s1 (device scale: 1, zoom level: 1)
HiDPI  enabled,  50% sys zoom: InitContext  977x 631s1 (device scale: 1, zoom level: 1)
```

I guess the issue is that `device scale` is also 2 for percentages slightly above 50% (e.g. 1600x1062)... IIRC maximum X resolution is 4096x4096...

A perfect fix would be to prevent the hidpi mode to go any higher than the native resolution (2560 in this case). But I'm not sure if we can detect that when system scaling is on...

An acceptable alternative would be to prevent hidpi when the resulting full screen size would be too large (that is, taking display size as reference, and not the current window size).

**Comment by nilswiersma** [comment]
Are there any updates on this? I'm facing exactly this issue (running a 2560x1700 device in 1920x1275, which crashes the extension for HiDPI). It would be great to be able to set xiwi applications to the native resolution, while not running chromium in native.

I tried figuring out a solution -- shouldn't it be possible to simply add a field in the extension which allows for manual resolution or scale setting in kiwi.cc?
