### ISSUE TITLE
DVD Playback issues

### ISSUE THREAD

**Issue by GuillermoArjun** [dnschneid/crouton#1367]
It's me again,

So I've got myself an extra disc drive for my ASUS C300M and thought I'd break it in with season 1 of The Wire, but after trying to play the files with VLC I started encountering some issues.

From scouring all over, I found that I needed to install the dvd codecs, but even after that it still won't work and I get this output.

Playback failure:
DVDRead could not read -1/4 blocks at 0x18.

I was wondering then, is this an issue with crouton, or something beyond?

All the best,

Will

**Comment by imbigfella** [comment]
Native DVD support is something that Google has fell short on.  I was extremely hopeful when I saw the new criat feature of this repository.  I was thinking "Finally, a simple method to close the gaps in ChromeOS,"  like local printer support, SMB shares and DVDs/Audio CDs.  As yet I have also been unable to get Audio CDs or DVDs to play using crouton.

I work in the Education field as the Director of Technology for a small school district and we are looking heavily at Chromebooks as a solution for teachers as well as students.  One hesitation we have had is the inability to play DVDs which we already have purchased.  Thought has been put into digitalizing all of our optical media, but the copyright question then gets brought into play, especially  when storing the files on Google Drive where they are accessible to more than one user at a time.

**Comment by imbigfella** [comment]
So, I decided to play with this some more tonight.  I was hoping that I could dd a ISO from a DVD, but there was no loving from the linux gods.  During my quest to get my USB DVD player working on Crouton, I noticed that /dev/sr0 was chmodded to 660(rw,rw,-), so I changed it to 664 (rw,rw,r).  Then ran an apt-get install ubuntu-restricted-extras to get the libdvdcss2 but I get this error:

```
Package libdvdcss2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```
Also, running the command 
```
cvlc :start-time=1 --stop-time=4 dvd:///dev/sr0 vlc://quit
```
results in 
```
************************************************
**                                            **
**  No css library available. See             **
**  /usr/share/doc/libdvdread4/README.css     **
**  for more information.                     **
**                                            **
************************************************

main input error: ES_OUT_RESET_PCR called

```

I'm no programmer, I don't even pretend to be one, unless my boss is asking. This is very much a side project, but there is a real interest in playing DVDs from a Chromebook.  I don't ever expect a Non-developer mode device to be able to accomplish this relatively simple task, due to the ```/dev/sr0``` not giving the default user read access (though I would love to be proved wrong).  I don't see why it there hasn't been a fix for this somewhere out there.

**Comment by imbigfella** [comment]
And gotit...
```
sudo apt-get install libdvdread4
sudo /usr/share/doc/libdvdread4/install-css.sh
```
Now my Chromebook can play DVDs through the External Drive.
Credit goes to JoKeR on [http://askubuntu.com/questions/501277/cannot-play-dvds-on-ubuntu-14-04]

**Comment by dnschneid** [comment]
Thanks for sharing!  Maybe add it to the wiki?

**Comment by alangumer** [comment]
# play DVD crouton - Ubuntu 14-04
sudo apt-get update
sudo apt-get install vlc

#run install libdvd -- @imbigfella
sudo apt-get install libdvdread4
sudo /usr/share/doc/libdvdread4/install-css.sh

# give permission to your user to play DVD -- https://github.com/dnschneid/crouton/issues/1906
sudo usermod -a -G cdrom myuser
# reload your user group
exec su -l myuser
#run VLC
vlc
