### ISSUE TITLE
Feature Request: enter-chroot should be aware of multiprofiles

### ISSUE THREAD

**Issue by beaufortfrancois** [dnschneid/crouton#1410]
Right now, `~/Downloads` maps the first logged in user Downloads folder which is great except when you use multiple accounts at the same time. See https://support.google.com/chromebook/answer/6088201?hl=fr&source=genius-rts

It would be great if `enter-chroot` could be aware of the profiles we use and map accordingly the `~/Downloads` folder.

**Comment by DennisLfromGA** [comment]
I have multiple accounts setup on my HP Chromebook 14 and I've noticed some interesting 'features' when using them. When switching into each account, if you open the 'Files' app, it shows that account's  Downloads folder and their files. But, if you open a shell (Ctrl+Alt+T) in that account, it uses the first logged in user's account and shell AND ~/Downloads folder. I assume this is intended but I don't know how 'crouton' could get around it this since it seems to use only the first logged in user's shell.

I have a short [screencast](http://goo.gl/dAcX3p) ( Thanx Francois :) showing this behaviour that demonstrates the above - I hope ;) 

-DennisL

**Comment by tedm** [comment]
On the stable channel, ARM, I don't have the ability to bring up multiple accounts yet, but I can understand the issue. In the chroot, ~/Downloads is given ownership of first linux user and their corresponding group (tedm:1001), perms: 710. In a crosh shell at /home/user/chronos, Downloads is owned by chronos:chronos-access with same perms. When additional user desktops are opened on Chromium OS, is the UID:GID shared, or unique? I'm also baffled that ~/Downloads is now a ~/tmp dir with the caution that things may be deleted by the system. We were warned of this lack of permanence earlier on, but traditional desktop users (Mac/Windows), may find this concept disconcerting, as it's moving away from having some safe local storage.

**Comment by dnschneid** [comment]
It looks like multiple users get mounted to /home/chronos/u-\*.  Could someone with multiple login post the output of `ls -ld /home/chronos/u-*`?  Non-logged in users have empty directories owned by root.

It looks like we can get the names of the users via `/home/chronos/Local State`, but then what?  Subfolders of ~/Downloads for each account?  Stick with the current behavior but expose multiple login in the /etc/crouton/shares syntax?

**Comment by DennisLfromGA** [comment]
Here's `ls -ld /home/chronos/u-*`:
```
chronos@localhost ~ $ ls -ld /home/chronos/u-*
drwx------  2 root    root           4.0K Dec 17 20:44 /home/chronos/u-3b401bc5aa4d191164fa6cba9ae581a9aa5300ab
drwx------  2 root    root           4.0K Jan 20 16:39 /home/chronos/u-8ce66e0b815d066f1e7b0190a0f2cb2ff3ca8dd5
drwx--x--- 34 chronos chronos-access  20K Feb 14 21:19 /home/chronos/u-fd50f5f5604ec5bcdbe4558e7d9fbbfd313bc00d
```
----
I like the idea of using `/etc/crouton/shares` syntax, I've set some up and they work well - in a single user environment at least..

**Comment by dnschneid** [comment]
Are you multiply logged in?  Could you switch users and run the command again?

**Comment by DennisLfromGA** [comment]
No, I wasn't multiply logged in, revised output:
```
chronos@localhost ~ $ ls -ld /home/chronos/u-*
drwx--x--- 29 chronos chronos-access 12K Feb 14 21:26 /home/chronos/u-3b401bc5aa4d191164fa6cba9ae581a9aa5300ab
drwx--x--- 32 chronos chronos-access 12K Feb 14 21:26 /home/chronos/u-8ce66e0b815d066f1e7b0190a0f2cb2ff3ca8dd5
drwx--x--- 34 chronos chronos-access 20K Feb 14 21:26 /home/chronos/u-fd50f5f5604ec5bcdbe4558e7d9fbbfd313bc00d
```

**Comment by dnschneid** [comment]
Yay!  No access issues.

**Comment by DennisLfromGA** [comment]
Nope, and they are indeed the geniune article:
```
chronos@localhost ~ $ ll /home/chronos/u-*/Downloads
/home/chronos/u-3b401bc5aa4d191164fa6cba9ae581a9aa5300ab/Downloads:
total 12K
drwxr-xr-x 2 chronos chronos 4.0K Feb 14 21:38 HOLD/
-rw-r--r-- 1 chronos chronos    0 Feb 14 21:40 TheLockharts.were.here

/home/chronos/u-8ce66e0b815d066f1e7b0190a0f2cb2ff3ca8dd5/Downloads:
total 8.0K
-rw-r--r-- 1 chronos chronos 0 Dec 16 16:07 Dennis.was.here

/home/chronos/u-fd50f5f5604ec5bcdbe4558e7d9fbbfd313bc00d/Downloads:
total 12K
-rw-r--r--  1 chronos chronos    0 Dec 16 16:07 Denny.was.here
drwxr-xr-x 11 chronos chronos 4.0K Feb 14 21:37 HOLD/
```

I created `*.was/were.here` files in each, respective `Downloads` folder.

**Comment by tedm** [comment]
@DennisLfromGA So if 2 or ore users are simultaneously logged in, is crosh / shell / su root available anymore from either user(s?)

**Comment by DennisLfromGA** [comment]
@dnschneid - That `/home/chronos/Local State` is *very* interesting, good find. :+1:

@tedm - Not quite sure I understand your question but, when you enter a shell from any of the logged-in user's Desktop, you get the first logged-in user's shell (`.bashrc`, `~/Downloads`, etc.).

**Comment by tedm** [comment]
Thanks Dennis, I guess that makes sense and can work well for a single-user / multiple account setup.

**Comment by beaufortfrancois** [comment]
How about something like this below when user is in multiple profiles mode?

```bash
$ sudo enter-chroot
$ cd ~
$ ls -ld */*
drwx--x--- 18 francois 1001 24576 Feb 16 09:17 Downloads/photos
drwx--x--- 18 francois 1001 24576 Feb 16 09:17 beaufort.francois@gmail.com/Downloads/photos
drwx--x--- 18 francois 1001 24576 Feb 16 09:17 john.doe@gmail.com/Downloads/music

```

**Comment by dnschneid** [comment]
That's an option, but we also need to consider what the associated syntax for the /etc/crouton/shares file would be.

**Comment by DennisLfromGA** [comment]
> That's an option, but we also need to consider what the associated syntax for the /etc/crouton/shares file would be.

Well, I took a stab at it and wallah... it's working.
Granted, the naming conventions and directory linking may need some changes/work but it's a start.
I put together a little explanatory file here - '[shares-info.txt](http://pastebin.com/H58BmLDK)' for your perusal.

I've just been testing it with all three user profiles logged in, I'll see what happens when some are not, etc.

Let me know what needs work and I'll be glad to oblige.

-DennisL

**Comment by DennisLfromGA** [comment]
I did run into a problem with my share links, it worked the first time as the '[shares-info.txt](http://pastebin.com/H58BmLDK)' file above shows but once rebooted, the chroot wouldn't  start. I traced it down to line number 526 in `enter-chroot` that reads:

`mkdir -m 700 -p "$src"`

I changed it to:

`[ ! -d "$src" -o ! -h "$src" ] && mkdir -m 700 -p "$src"`

and the chroot started and all the links work.
I don't know if this is a good solution though, I'll defer to you experts for that answer.

**Comment by ibrado** [comment]
I know this is old, but since it's still open... :-D

I replaced the following (line 692 currently, near "Bind-mount the stuff..."):
```
    localdownloads='/home/chronos/user/Downloads'`
```
with
```
    localdownloads=""
    if [ -x "/usr/bin/jq" ]; then
        activeuser=$(jq -r .LastActiveUser /home/chronos/Local\ State)
        localdownloads=$(jq -r ".profile.info_cache | to_entries[] | select(.value.user_name == \"$activeuser\") | \"/home/chronos/\(.key)/Downloads\"" /home/chronos/Local\ State)
    fi
    if [ "$localdownloads" = "" ]; then
        localdownloads='/home/chronos/user/Downloads'
    fi
```
which makes ~/Downloads the download folder of the user who first starts the chroot. (I didn't install `jq` but am not sure if it has always been there, thus the test.)

Personally though, I kinda prefer linking each account's Downloads folder as a subfolder, i.e. the output of 

`echo sudo mkdir -p /mnt/stateful_partition/crouton/shared/Downloads; jq -r '.profile.info_cache | to_entries[] | select(.key != "Default") | "sudo ln -s /home/chronos/\(.key)/Downloads /mnt/stateful_partition/crouton/shared/Downloads/\(.value.user_name)"' /home/chronos/Local\ State
`

and

`echo "#downloads ~/Downloads"; jq -r '.profile.info_cache | to_entries[] | select(.key != "Default") | "shared/Downloads/\(.value.user_name) ~/Downloads/\(.value.user_name)"' /home/chronos/Local\ State
`

e.g. in a crosh shell,

```
sudo mkdir -p /mnt/stateful_partition/crouton/shared/Downloads
sudo ln -s /home/chronos/u-123458435b8ec8abcdedcddbd9e7155102a67890/Downloads /mnt/stateful_partition/crouton/shared/Downloads/myworkemail@example.com
sudo ln -s /home/chronos/u-123459e6abcde851c24f81f6566ef0519e767890/Downloads /mnt/stateful_partition/crouton/shared/Downloads/mypersonalemail@example.com
```

and in /etc/crouton/shares:

```
#downloads ~/Downloads
shared/Downloads/myworkemail@example.com ~/Downloads/myworkemail@example.com
shared/Downloads/mypersonalemail@example.com ~/Downloads/mypersonalemail@example.com
```

though I use "Personal" and "Work" instead of the email addresses since I only have 2 logins. This way I can access either (all) download folders, especially as the work account requires it to be logged-into first.

Hope this helps!
