### ISSUE TITLE
Use xiwi from crosh

### ISSUE THREAD

**Issue by jbaum98** [dnschneid/crouton#1421]
It is possible to install programs using linuxbrew in the plain crosh without installing an entirely new operating system with crouton. However, right now you can only run command line programs. Is there a way to connect to the Chromebook window server from the crosh?

**Comment by dnschneid** [comment]
See #1.  You can sort of do it.  It's a pain to get working, especially without a chroot (there are other projects floating around that do just that).  And very soon it will stop working, as soon as Freon rolls out.

**Comment by jbaum98** [comment]
What exactly is Freon? And what sort of other projects are there to do this? Sorry for all the questions but I appreciate your help and knowledge.

**Comment by dnschneid** [comment]
Freon is the new display server for Chromium OS, under the [ozone](http://www.chromium.org/developers/design-documents/ozone) project, eliminates X11 from the Chromium OS stack.
Other projects running stuff natively (to my knowledge) are [dev-install](http://www.chromium.org/chromium-os/how-tos-and-troubleshooting/install-software-on-base-images), chromebrew, and a couple other minor projects here and there.  See if dev-install works for you; otherwise, I recommend just sticking with a minimal (core) chroot...
