### ISSUE TITLE
/usr/local/chroots/precise is not an ext filesystem.

### ISSUE THREAD

**Issue by dev-edo** [dnschneid/crouton#1441]
says it all up top. I have done this before and it worked. Reset my chromebook and it does not work

**Comment by dnschneid** [comment]
Can you post the command you're trying to run?  Are you doing anything with /usr/local to change where it is stored?  Please also post the output of `cat /etc/lsb-release`

**Comment by DennisLfromGA** [comment]
@dnschneid,

Not sure if this is related since I don't know what command @dev-edo was using but I just ran into a problem when trying to rename/move a chroot and got a similar error message.

I can submit this as a new bug if need be.

`sudo edit-chroot -m 1-trusty trusty` is failing with the error:
 `Chroots can only be moved to ext filesystems.`

It looks like it's using:
 df -T /home/chronos/user 
instead of 
 df -T /mnt/stateful_partition/crouton/chroots/

I'm not sure if it's a `getmountpoint` function problem or what, sorry.

I have a verbose log of the error here - [edit-chroot-m.log](http://pastebin.com/SAD5ihWi).

-DennisL

**Comment by tedm** [comment]
@DennisLfromGA I just upgraded my crouton and chroots, and am able to move them with the exact command you used, no errors.

**Comment by DennisLfromGA** [comment]
Just tried it again and got the same results. :-1:

**Comment by tedm** [comment]
time to upgrade to an arm system ;)

**Comment by DennisLfromGA** [comment]
Those new tekra's look pretty nice... :+1:

**Comment by dnschneid** [comment]
@DennisLfromGA thanks for narrowing that down.  It was a logic inversion on when to check the filesystem type (it's not supposed to check for renames).  Anyway, fixed in master.  Hopefully that was OP's issue.

**Comment by DennisLfromGA** [comment]
@dnschneid - Thank you for the sleuthing and quick fix.
