### ISSUE TITLE
External monitor blacks out when lid is closed

### ISSUE THREAD

**Issue by kas** [dnschneid/crouton#1486]
When I shut the lid in chromeos, the external monitor attached stays alive (this is the behavior I'm after).
When I shut the lid in crouton (elementary OS), both screens go black and when I open the lid I am greeted by the lock screen on the external monitor, and the chromebook monitor is black.
When I shut the lid in crouton, the chromebook actually goes to sleep after a while!
Anyone else have any frustration with this?

**Comment by theblacklion** [comment]
Are you being greeted by the lock screen of elementary OS? In Luna I had to
make sure that it stays on with an external monitor attached via
dconf-editor. In Freya this still does not work for me. In Crouton I've the
same problem as running it on my work laptop.

Ken Schnall <notifications@github.com> schrieb am Di., 10. März 2015 um
17:37 Uhr:

**Comment by kenschnall** [comment]
Yep I'm running Luna and right after opening the lid, Luna is black.  I move my mouse a bit and the lockscreen shows up.

Can you help me with dconf-editor?  After googling around I downloaded dconf-tools -- but I have no idea how to edit the specific settings like you said.

**Comment by tedm** [comment]
@kenschnall Luna is Ubuntu based, right? If you're OK with having ChromeOS control your screen power management, you may want to:

(as superuser) $sudo apt-get remove xscreensaver

**Comment by kenschnall** [comment]
@tedm Luna is Ubuntu-based, yes.  I think that having Chrome OS control my screen power management is what I'm after (ie, keep screen on/no lockscreen when chrome senses external monitor and lid is closed).

I followed your advice and removed xscreensaver, but I had VERY odd behavior after removing it.  After removing it from Luna, when I'd switch back to Chrome OS there would be very horrible glitches with the screen and actually pages wouldn't load in chrome (or refresh).  I tried opening the settings and it would display a blank white window.

After installing xscreensaver again, those issues are gone, but when I close the lid in Luna the external screen still shuts off (so back to the original issue).

**Comment by tedm** [comment]
@kenschnall I'm not sure about Luna, but with xfce, removing or purging xscreensaver allows Chrome to manage the chroot's screen and power settings.

If you feel comfortable, you may want to try apt-get purge xscreensaver, or dpkg -P xscreensaver, as apt-get remove, leaves the config files that perhaps Chrome OS is picking up with Luna.

**Comment by kenschnall** [comment]
@tedm You're right, after putting xscreensaver back on and playing around a bit I am still having the horrible glitches in chromeos after using Luna for a while in a session.

**Comment by tedm** [comment]
@kenschnall If it turns out that you have to let Luna control power to the system, there is a croutonpowerd [-i] utility that will inhibit Chrome OS's power daemon, you may want to experiment with that.

**Comment by kenschnall** [comment]
@tedm It took some playing around with, but the weird glitches in Chrome OS occur with ANY linux setup (I tried 12.04 elementary OS, 14.04 xfce/unity/lxde and they all gave glitches in Chrome OS after closing the lid in linux and going back to Chrome OS).

but powerd was the culprit!

This link will come in use to anyone else having Chrome OS glitches after shutting the lid while in linux:
https://github.com/dnschneid/crouton/issues/5
notice that the command is "sudo stop powerd" not powerm.

So there are no Chrome OS side effects when I shut the lid in linux now, because I essentially shut down the power manager service (powerd, I'm not sure if this triggers the Chrome OS power manager or that powerd is the only power manager service and Chrome OS + linux share it?).
I plan on making a startup script so that the powerd service is ended automatically until I can figure out how to let powerd successfully suspend without causing Chrome OS to glitch out.

Any suggestions are welcomed.  I hope this information has helped others who were in the same predicament as me and don't want to not be able to shut their lid while using linux.

**Comment by tedm** [comment]
@kenschnall It's great that you have a working system, but I think the right way would be to have a chroot power management system that co-exists with powerd (leaves it running, or inhibits as necessary, but doesn't kill it) so that when a chroot isn't running, Chrome can turn down the power per the user settings.

Take a look at the croutonpowerd options if you get a chance:

https://github.com/dnschneid/crouton/blob/master/chroot-bin/croutonpowerd

**Comment by drinkcat** [comment]
@kenschnall : As @tedm suggests, is running `croutonpowerd -i` in the chroot enough to inhibit powerd?

**Comment by kenschnall** [comment]
@drinkcat Running croutonpowerd -i in the chroot (ctrl+alt+t -> shell -> sudo enter-chroot -> croutonpowerd -i) nor in the actual Unity environment correctly inhibits powerd (when I shut the lid in Unity and then open the lid and switch to chrome os, the chrome os is unusable.  I can switch back to Unity and use Unity fine though).

sudo stop powerd is the only command that seems to inhibit it, letting me shut the lid in Unity and use chrome os fine.

**Comment by dnschneid** [comment]
If powerd has a dbus interface that forces dock mode, we should make a way for crouton to use that (croutonpowerd -ii or something).  Not sure why the dock mode logic gets disabled when on a separate VT though, unless powerd is generating a suspend message and Ubuntu is handling it somehow.

**Comment by AdamDanischewski** [comment]
I had the same problem recently, both displays and externally attached USB storage devices also shutdown when the lid is closed -- I didn't look into it but croutonpowerd did not fix it for me.  
sudo  stop powerd  ## fixed it  

Acer C720 
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6946.55.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue May 26 16:21:19 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Trusty version 1-20150516123952~master:8f7245cc

**Comment by joaoherberto** [comment]
This worked for me..  
https://www.liberiangeek.net/2013/12/daily-ubuntu-tips-do-nothing-when-laptop-lid-is-closed/

**Comment by Laksa19** [comment]
[SLOVED]
Setting from dconf editor
org.gnome.settings-daemon.plugins.power

https://launchpadlibrarian.net/230423792/Screenshot%20from%202015-12-18%2014%3A39%3A27.png
