### ISSUE TITLE
Display switched red to blue color

### ISSUE THREAD

**Issue by ahoehl** [dnschneid/crouton#1491]
Hi,
after a fresh install of crouton on an ACER ARM Chromebook (CB5-311) the display of the whole desktop has a blue tint, colors that should be red are displayed in blue. The issue only occurs in Ubuntu (tried 12.10 and 14.04), in ChromeOS colors are displayed correctly. The problem occured directly after the new installation of Crouton, no additional apps where installed. I had run crouton earlier on the same machine without this issues.

chronos@localhost / $ sudo enter-chroot -n trusty croutonversion
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150304145447~master:550afdb3
release: trusty
architecture: armhf
xmethod: xorg
targets: xfce
host: version 6680.64.0 (Official Build) stable-channel nyan_big 
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

All the best
Alex

**Comment by DennisLfromGA** [comment]
I think that using the 'xorg' xmethod instead of 'xephyr' on the ARM Chromebooks may be part of the problem. Normally the ARM Chromebooks should use 'xephyr' by default but you can force 'xorg'.
Checkout this issue and comment: https://github.com/dnschneid/crouton/issues/1455#issuecomment-76579207

**Comment by ahoehl** [comment]
Hi Dennis,
thanks for your quick feedback. Unfortunately I am not the computer expert I would like to be. I have been checking the web how to switch from Xorg to Xephyr - and am now totally confused. Would you be able to advise how to switch to Xephyr? (in chroot, in ubuntu?).
Thanks a lot,
Alex

**Comment by DennisLfromGA** [comment]
@ahoehl,

Sure, no problem.

You can force the xmethod by specifying it first in line when you enter your targets. 
After your chroot is installed, you can still install and change the xmethod the same way with an update.
For your existing 'trusty' chroot, do this:

     sudo sh ~/Downloads/crouton -n trusty -t xephyr -u

That should put the 'xephyr' xmethod first so that when you enter:

     sudo startxfce4

It should open up in 'xephyr'; you'll use the same switching method -
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward

----

I'm not sure about your Chromebook (CB5-311) but 'Freon' will be used going forward, it's rolling out to the different platforms now. When and if it does hit yours, 'xephyr' won't be allowed, you'll have to use 'xiwi'. Here's a remark from the 'xephyr' target itself -

    xephyr target does not work with Freon. Use xiwi instead.

**Comment by ahoehl** [comment]
Hi Dennis, 
thanks a lot for your help. Xephyr works, all colors back to normal.t
Once Freon is rolled out, I assume I need to use the same command, just replace "xephyr" with "xiwi". Correct?
Thanks
Alex

**Comment by DennisLfromGA** [comment]
Yup, correct.

**Comment by belardi** [comment]
Had the same issue on a HP chromebook 14 (c14xc) and it works like a charm now. Thanks @DennisLfromGA !
