### ISSUE TITLE
VirtualBox USB Management with udev fix 

### ISSUE THREAD

**Issue by Timvrakas** [dnschneid/crouton#1500]
I was initially unable to access USB devices from within my Windows 7 VM. Virtualbox could not see any devices.

The issue had to do with udev. Virtualbox installs a udev rule file (into chroot), which runs a script (/lib/udev/VBoxCreateUSBNode.sh) that adds the USB devices to /dev/vboxusb, and sets file permissions (root:vboxusers). But the script is not present in Chrome OS /lib/udev, and that is where udev runs, not in chroot. Another issue was the vboxusers group only exists in the chroot, so the permissions are not correctly set.

I was able to fix this by manually adding the USB devices and setting permissions manually, but I will have a real fix soon I hope. something for the wiki :)

Just thought someone stumped on this might like a heads up.

**Comment by Timvrakas** [comment]
WOOO! Issue #1500!!! (That is a LOT of issues and now I feel bad for being one of them)

:)

**Comment by drinkcat** [comment]
For reference wiki page is here: https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration . I haven't tested it, but it looks sound.

@Timvrakas : Thanks for the wiki page.

**Comment by Watney** [comment]
@Timvrakas I'm unable to access USB devices in my Win7 VM. 

I installed VirtualBox following [this guide](https://help.ubuntu.com/community/VirtualBox/Installation) which adds the virtualbox.org repo. Consequently, there are some key differences from the Wiki. (My hunch is that you installed VB from the Ubuntu repo.) 

Firstly, ``VBoxCreateUSBNode.sh`` is located in the chroot at ``/usr/share/virtualbox``.  It's not possible to copy this outside the chroot because the file system is locked. 

Second, the ``60-virtualbox.rules`` file is located in ``/etc/udev/rules.d``. Unlike the Wiki, the VirtualBox rules file doesn't specify a usergroup. I'm reluctant to hack on the rules and add the 3-digit number GID per the Wiki. 

Lastly, please check my thinking: at the time that the udev rules are re-loaded in ``rc.local`` and ``60-virtualbox.rules`` is activated, the path to ``VBoxCreateUSBNode.sh`` is *outside* the chroot, correct? If this is correct, the the shell script must be located in the corresponding (writable) directory in Chrome OS. 

If, however, the chroot is already mounted when the rules are re-loaded, the script does *not* have to be moved outside the chroot. Thanks for your help!

**Comment by Timvrakas** [comment]
I use the auto start scripts, so I forgot that most people don't have RW access to the root file system.
It should be possible to rework it though. Perhaps put `VBoxCreateUSBNode.sh` in `/usr/local/`
then change the rules file to `sh /usr/local/VBoxCreateUSBNode.sh`

That is where the rules file is supposed to be. If you followed the udev instructions wiki, that file should get copied to the shared `/run/udev/rules.d`, and then executed from outside the chroot.

If you look at your `VBoxCreateUSBNode.sh`, the user is most likely an optional argument, it defaults to vboxusers (which wont work). You could change the default in the script, or tack on the GID in the rules file. 

You are right about that, however, I would not recommend accessing files within the chroot from `/run/crouton`. The `/usr/local` is better practice IMHO.

Thanks!

**Comment by Watney** [comment]
@Timvrakas thanks so much. I'll work on it, probably early next week. I'll let you know if I run into trouble. You've been a tremendous help. Thanks!!

**Comment by vsukul** [comment]
@Timvrakas thanks for the guide! I followed the instructions you wrote (have the autostart script running as well), but i'm still unable to get attached usb devices (flash drives, etc.) to show up. Oddly enough, it lists my webcam under webcams in vbox though. I'm running XFCE, xiwi, trusty. Any ideas? i'm not sure what isn't working...

**Comment by Timvrakas** [comment]
run `ls -l /dev/`  (within chroot) and look at the line for vboxusb after plugging in a USB device. It should show up and have vboxusers as the group. If not, check that the rules file was copied to `/run/udev/rules.d`. You could check `dmesg` after pluggin in a device and look for errors.

FYI, I have a rules file for you Watney:
https://gist.github.com/Timvrakas/d43fe840d9fc336cae7b

I may replace the method on the wiki with this, I is persistent across chrome OS updates, and does not require rw-rootfs.sh to be run.

**Comment by Watney** [comment]
@Timvrakas thanks for the updated [Wiki guide](https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration). It worked perfectly. I successfully connected my ScanSnap scanner via the USB port and configured the wireless connection. I could have never done this without your help. Thanks so much!!!

-----------------------------------------

I'll leave a comment for Google search. A ScanSnap iX500 scanner can connect to a Windows PC via USB 3.0, 2.0, or 1.0. Since the supplied USB cable accommodates USB 3.0, and since a Chromebook Pixel has USB 3.0 ports, the scanner attempts to connect at the higher speed. 

VirtualBox doesn't support USB 3.0, only 2.0 or 1.0. Consequently, a Win7 VM will not recognize the iX500 with the OEM cable. The workaround is to use a USB 2.0 cable, and the VM will recognize the scanner.

**Comment by mojo6911** [comment]
I am trying to get this working on a Toshiba Chromebook 2 running elementary with precise. I followed the directions, and everything seemed to work without any errors, but nothing is shown in VirtualBox as a usb device. I can see the device with lsusb.

**Comment by Watney** [comment]
@mojo6911 bear with me, but if you installed VB from the VB website, as opposed to Ubuntu, you must also install an extra package and add yourself as a user to the VB group. There's a helpful discussion at [Ubuntu](http://askubuntu.com/questions/25596/how-to-set-up-usb-for-virtualbox). 

So, for starters, let's make sure you've got the basic requirements ready to go.

**Comment by Timvrakas** [comment]
What is the result of `ls -l /dev/vboxusb`?
Are there any error messaged in `dmesg` when you plug in a device?

**Comment by Watney** [comment]
@Timvrakas thanks for jumping in to help!!! I only know what I've learned from you :)
