### ISSUE TITLE
change keyboard distribution on X11 session on a xiwi application

### ISSUE THREAD

**Issue by jlchulilla** [dnschneid/crouton#1574]
Hi,

First of all, I would like to thank all the people involved in crouton project. It transforms an efficient secondary laptop into a full-fledged PC, cheap, secure and great :)

Now, my problem:

Croutonized ubuntu works like a charm for me. xiwi-enabled croutonized ubuntu works too.

However, when I launch a xiwi-enabled independent app, keyboard map doesn't work anymore. I write in Spanish, so I need that ñ and accents work

Does anybody know how to solve it?

Thanks in advance!

**Comment by mark-hahn** [comment]
I'm chasing a problem right now where the chromebook keyboard mapping
doesn't get to xiwi, either desktop or independent apps (
https://github.com/dnschneid/crouton/issues/1558).   It is probably the
same problem you are having.

Unfortunately I don't know this stuff well and it would be really nice if
someone who does know this stuff could help.  Like maybe whoever wrote the
keyboard target.

**Comment by Aln-Bdx** [comment]
I have a similar issue. My keyboard doesn't work under xiwi, but works fine under X11 target.
After several tests, I discover under  xiwi  that  if I press  a key more than  ten seconds , so  the letter comes  at  screen . Because  of  repetition  no way to use ... 
Curious , but return key , &, tab, ctrl, work fine.

my configuration : 

crouton: version 1-20150404180843~master:66d0393b
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,xfce,lxde,xiwi,xorg,e17,chrome-dev,extension
host: version 6931.0.0 (Official Build) dev-channel squawks_freon 
kernel: Linux localhost 3.10.18 #1 SMP Tue Mar 31 03:42:32 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Thanks a lot for your  help .

**Comment by mark-hahn** [comment]
I'be made some progress on this.  If you do `setxkbmap -model chromebook` inside a desktop the keyboard target is loaded properly.  You can tell if it is loaded by doing `setxkbmap -print -verbose 10`.  Unfortunately the search-key combos still don't work.  So now I'm debugging the chromebook symbols/layout file.

You are supposed to be able to set the `model:chromebook` before you go into the xiwi window/tab by setting `/etc/default/keyboard` to 

```
XKBMODEL="chromebook"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS=""
```

and running `udevadm trigger --subsystem-match=input --action=change`.  That hasn't worked yet for me.  Maybe rebooting will load the `model` properly.  When I do get this working I'll add this step to the wiki for the keyboard target.

This is going slow for me because I don't know Linux.  I bought a chromebook pixel and it is too late to return it.  (grin).  I need to do source editing so I have to get home/end/pgup/pgdn/backspace working.  I find it weird that tons of crouton users aren't bitching about this.  Maybe they all use vim.

**Comment by Aln-Bdx** [comment]
I resolved my problem. I indicated in my google account to not correct automatically while i am typing in a web field. My keyboard return in live under xiwi.

**Comment by jlchulilla** [comment]
When I open entire unity desktop, keyboard mapping work with normal applications, but not inside the terminal. I had unity installed before install xiwi, so maybe it is the difference between your installation and mine own one

**Comment by jlchulilla** [comment]
OK, I was twice wrong.

1. the problem I am describing is not connected with keyboard mapping. I have applied what mark-hahn suggested and now the keyboard mapping is correct (thanks, mark!!), but accents still doesn't work :(

2. open entire unity desktop doesn't solve the problem. I was totally wrong :(

I am totally lost about why accents don't work on xiwi-powered unity. When I used unity without xiwi, it works seamessly, accents included. But after I installed xiwi target, accents stop to work. On the other hand, unity without xiwi target don't let share clipboard between unity and chromeOS

**Comment by divx118** [comment]
@jlchulilla  
> unity without xiwi target don't let share clipboard between unity and chromeOS
If you have the extension installed which get automatically gets pulled in when you install xiwi it should. Try starting your chroot with `sudo startunity -X xorg` clipboard sharing should work. When you want clipboard sync without xiwi target, you will need to explicitly install the extension target, so add it to the targets. For example creating a trusty chroot with unity and clipboard sync with XMETHOD xorg `sudo sh ~/Downloads/crouton -r trusty -t unity,extension`

**Comment by mark-hahn** [comment]
> I have applied what mark-hahn suggested and now the keyboard mapping is correct 

That is good news for me because it shows I'm on the right path.  I'll go ahead and do a PR for the keyboard target wiki.

Unfortunately my mapping still doesn't work but it may be something trivial.

**Comment by jlchulilla** [comment]
OK, I tried several solutions but for no avail

1. I uninstalled xiwi with `sudo sh -e crouton -u -t x11`. Unity started to work again as supposed, and I could use áccents and ñ, which are mandatory if you want to write in Spanish
2. Then, I installed `extension` with `sudo sh -e crouton -u -t extension`. Clipboard exchange between chromeOS and unity works again, but accents stopped to work
3. I also tried to run `sudo startunity -X xorg`, but it returned `/mnt/stateful_partition/crouton/chroots/precise does not contain XMETHOD 'xorg'`.

I am totally clueless about why `extension` or `xiwi` are not able of using accents or other special characters. I really would appreciate any help or hint

**Comment by harryprince** [comment]
＠jlchulilla I have faced the same problem,and I have install all things, however, it tells me 
```
/mnt/stateful_partition/crouton/chroots/harryzhu does not contain target 'xiwi'
```

**Comment by dnschneid** [comment]
@jlchulilla: depending on your platform, you might be using xephyr and not xorg.

Currently, keyboard layouts aren't synced, and international layouts can things--see #1457.  The best way I've found is to edit your ~/.xiwirc file to call whatever commands switch the layout to be what you want it to be.  That file gets run automatically whenever you start a single-app xiwi session.

**Comment by procastinoso** [comment]
So, this was an issue for me too, I want to use spanish layout. I did what mark-hahn said,

I changed in  /etc/default/keyboard: 
  XKBLAYOUT="es"

and added to ~/.xiwirc:
  sudo -H udevadm trigger --subsystem-match=input --action=change

Now my layout is working fine.

Thanks!
