### ISSUE TITLE
no gpu acceleration -- toshiba chromebook 2

### ISSUE THREAD

**Issue by jeff-regier** [dnschneid/crouton#1581]
I installed crouton on a Toshiba Chromebook 2 (Intel processor), most recently with the following command: 

chronos@localhost / $ sudo sh ~/Downloads/crouton -u -r trusty -t unity,xiwi,xorg,extension,audio,core

But there's no GPU acceleration for applications run in Ubuntu: vlc player is too slow to show video, and Unity animations are choppy. Is there a way to fix it?

Thanks!

**Comment by mark-hahn** [comment]
> vlc player is too slow to show video

I'm just curious but why would you play video in a crouton chroot when
chromeos plays it so well?

**Comment by DennisLfromGA** [comment]
@jeff-regier,

I imagine you are using 'xiwi', run `sudo edit-chroot -al` to find out.
You can add the 'xorg' target and use it instead of 'xiwi' if you like.
Enter: `sudo sh ~/Downloads/crouton -t xorg -n trusty -u`
Then enter your chroot using: `sudo startunity -X xorg`.
Most likely, you won't need the `-X` since 'xorg' should now be the default xmethod.

**Comment by jeff-regier** [comment]
@DennisLfromGA Thanks for the solution. It's working really well now!

@mark-hahn  vlc plays some file types that chrome os doesn't, has more controls, and I'll probably be logged into Ubuntu more often than not, so vlc is my default. The chrome os player is nice too though!

**Comment by mark-hahn** [comment]
>  vlc plays some file types that chrome os doesn't,

May I suggest plex?  It is awesome, especially with chromecast.

**Comment by batman1111** [comment]
Stop

**Comment by mark-hahn** [comment]
Stop?
