### ISSUE TITLE
Failed to download debootstrap.

### ISSUE THREAD

**Issue by btcoughlin** [dnschneid/crouton#1591]
i have a Samsung 303c chromebook 
i keep getting this message for 2 days now 

chronos@localhost / $ sudo sh ~/Downloads/crouton -e -t xfce
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
Choose an encryption passphrase for precise: 
Please confirm your passphrase: 
Generating keys (move the mouse to generate entropy)...
done
Installing precise-armhf chroot to /usr/local/chroots/precise
Downloading latest debootstrap...
http://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz:
2015-04-07 18:26:03 ERROR 504: Gateway Timeout.
Download from Debian gitweb failed. Trying latest release...
2015-04-07 18:26:04 URL:http://ftp.debian.org/debian/pool/main/d/debootstrap/ [4420/4420] -> "-" [1]
Failed to download debootstrap.
Check your internet connection or proxy settings and try again.
chronos@localhost / $ 

i have also tried non encripted and also i can copy the html link http://ftp.debian.org/debian/pool/main/d/debootstrap/ and im able to download the info in that ftp page  i have no fire wall and no proxy set

**Comment by dgrilli** [comment]
I can confirm the issue. 
Sometime anonscm.debian.org is not working and the secondary option by debian ftp repository is broken because a bug in bootstrap script.

The sed line that try to get the version of debootstrap archive has a character mistake :

sed -ne 's ^.*\(debootstrap_[0-9.]*.tar.xz\).*$ \1 p' \

should be: 
sed -ne 's ^.*\(debootstrap_[0-9.]*.tar.gz\).*$ \1 p' \

I am not an expert developer so I hope someone can fix this bug.

**Comment by dnschneid** [comment]
You're right, it looks like Debian's FTP switched from xz to gz.  The J in [line 29](https://github.com/dnschneid/crouton/blob/master/installer/ubuntu/bootstrap#L29) also needs to be changed to a z accordingly.

**Comment by frederic-parrenin** [comment]
I got the same error message today when I wanted to install vivid.
Is there any workaround? 
Right now, this bug seems like a blocker for somebody wanting to install crouton.
