### ISSUE TITLE
Support Freon on ARM devices

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1606]
We need to support Freon on ARM devices, otherwise they'll be stuck without a native X server (i.e., xiwi-only).

modesetting should be used instead of fbdev on freon (fbdev won't work).

Implementing in the freonarm branch.

**Comment by yebyen** [comment]
What is the status of this?

Before your latest set of changes 8 days ago, I was able to get xephyr going on my Samsung Chromebook running 43 and frecon by making a lot of similar changes.  Looks like you are touching things related to the EXYNOS target, same hardware, do you have any use for a tester?

What does "because apt" mean related to libegl/libgles in the latest commit messages on freonarm...

Is there ES2 hardware acceleration support forthcoming in Crouton (ARM) because of the frecon change, or is there still some other blocker which you can foresee?  I've just powerwashed down to stable ChromeOS because of a crash bug that seems to affect dev and beta channels at the moment (which are now on ChromeOS 43, which is frecon.)  I remember reading once that you would never get hardware acceleration support in crouton because the Mali driver would only accept connection from one client at a time, and to Crouton that client is ChromeOS, but I have no idea if that was even remotely accurate or not.  I think you have crouton supporting HW accel on other hardware targets already (possibly on chromebook pixel.)

I have [T1914](https://phab.enlightenment.org/T1914) open with the E19 team on Phabricator, trying to get a compositing window manager running on this machine from some target that supports GLES-only operation, whether it means booting another target outside of ChromeOS, with ARM-MALI driver I installed by hand onto an SD card, special compile flags, it would be terrific if we can figure this out in Crouton first.

**Comment by dnschneid** [comment]
There's no way that the xephyr target could possibly work on Freon.  Also, I don't think the Samsung Chromebook on 43 is on Freon yet...but if you are, extra testing of the branch (day-to-day use, reporting issues you run into) would be much appreciated.

"because apt" was me running into dependency issues with the packages, and apt's poor dependency resolution suggesting bad fixes to the problems.  Unfortunately, there's still only software rendering.

It's quite possible that frecon could allow for hardware rendering in crouton (at least via the mali gles driver, and then possibly glamor on top of that for the rest of X11), but I haven't tried.  The issue before was that there was no proper DRM switching implemented in the driver, and that's been totally blown away by the move to Freon.

The focus of this issue will be to make sure native X11 runs as ARM devices start to transition to Freon.  Once native X11 is working, someone should definitely look into GPU acceleration...

**Comment by yebyen** [comment]
I upgraded to dev again from stable, and it does not seem to be on frecon.  I am surprised, because I'm sure I saw it before.  "<Ctrl>+<Alt>+<F2> and see if you get a "Welcome to frecon!" message."  Oh well.  At least xephyr will work for me now.  I swear it said "yes! frecon... we got it!" last time, it was definitely installed.

I downgraded to stable because of the crash bug I mentioned, my dad described the same issue, but right now back to 43.0.2357.5 dev, upgraded again, and either frecon has been removed from dev channel, or I guess it's possible it only ever was implemented in a dream I had (and nothing good happened as a result.)

**Comment by yebyen** [comment]
I bet dad's machine is on frecon.  Can still test things if you want, if that's the case.

**Comment by yebyen** [comment]
Have just noticed my own samsung chromebook (been switched to dev channel again for a few days) after the latest update is also, again, now on frecon

FYI!

**Comment by tedm** [comment]
On the 2012 Snow Fremont ARM, stable is still at 42 with no freon/frecon. However, even though there's a chance my next Chromebook may be an ARM, I'm not sure why xiwi can't just be the default?

An accelerated default xorg would be nice on ARM, but with so many options out there, it seems that the performance oriented crouton user is likely going to choose a non-ARM platform. The ARM runs netflix on the Chrome side, and has no annoying fan to rattle and break, but for a desktop replacement, the performance seems to be with the non ARM systems.

Or am I missing something?

**Comment by dnschneid** [comment]
I think dev channel on Snow is currently testing freon on a subset of systems, so each time you switch to dev you may or may not get Freon.

**Comment by tedm** [comment]
Thanks, I am making recovery sd cards, as I need a stable system this week to show another instructor how lamp/xampp/wamp/wordpress is running on Crouton, but after that I may move to beta or dev if I can recover if necessary.

@yebyen since xiwi can run in full-screen, what are some of the requirements you have for a native xorg on the ARM? I'm curious, because I'm wondering if there are some games or apps that require it that I haven't checked out yet.

**Comment by kingdonb** [comment]
There is a good reason or two not to use xiwi, for one thing when I tried the freonarm branch of crouton last week, to get an X11 session running on frecon very nearly worked fine already.  I am pretty sure after reading the changes that @dnschneid put in from this week, he addressed the "very nearly" stuff and from a glance, it will work fine now.  I have to try it again to be sure.

Two, do you ever pick up and grab a window by pressing alt and click-dragging?  This is a common shortcut so you don't need to squint and select the titlebar (in e17), and in xiwi it just doesn't work.  I'm not sure if it can be fixed.  Besides that, I don't want Chrome reminding me that I can escape from fullscreen in the middle of a presentation if my mouse cursor happens to reach the top of the screen.  (Not that any venue where I might be presenting soon is really prepared to handle laptops with HDMI, but I digress...)

Three, it's very awkward switching in and out of xiwi, comparatively.  Flipping back and forth to chrome with `Ctrl`+`Alt`+`<-` and `Ctrl`+`Alt`+`->` is very smooth.  Exiting Xiwi to return to a Chrome browser tab with the fullscreen escape is quirky and error-prone.  I have some moderately strange behavior in E17 when my screen changes its geometry.  Sometimes I lose the display and can't get back to it.

These things are probably all worthy of a bug report individually, but for my experience the xephyr way (or the new kms-framebuffer on frecon way, if it's not called xephyr anymore) is already less problematic and I just prefer it.

Also, I disagree that ARM is poorly performing, or that it's less worthy of great support!  Battery life is my number one qualification in a laptop, right before price.  E17 runs nicely on computers from the year 2000, and it's not like you need a powerhouse to operate a terminal or a tmux.  That discussion though certainly belongs anywhere other than this issue.  Other changes in the dev channel seem to make `Ctrl`+`Alt`+`T` Chrome shell less attractive for heavy use, too, I really just want to hide for the most part that I'm even running ChromeOS and just use X11, until I need that for browsing the web.

**Comment by tedm** [comment]
@kingdonb Thanks for the extensive notes. I did not realize that @dnschneid had made this progress on frecon as I'm on the stable channel, where it has not yet rolled down to yet.

I don't use most of the things you are using, like e17, as I prefer xfce, as it installs faster and needs no env. settings added to run if, if the target is added after xfce (I should write this up), and alt tab is much quicker for me than the keystrokes you mention, but I understand and acknowledge your use cases.

I have a lot of old running computers, including a 2006 dell notebook running mint as a home server, but with unaccelerated graphics natively and in xiwi, and for the same prices, it seems like folks would  (are) jumping to the 50% higher octane scores of other platforms, unless, like us, they really wanted the ARM despite the decreased performance of some recent newer models, like the new Toshiba model 2s with nice FHD screens, but many notice they are slower (they are), than previous models. Some of the newer Intel based models are getting long battery life as well.

**Comment by kingdonb** [comment]
Alt-tab is not what I'm talking about.  You can set windows to Auto-raise and switch focus by pointing.

Alt-clickdrag is something you can do in XFCE, too, to move panes around on the screen (but I'll bet, not with xiwi)

Even in Gnome:
http://superuser.com/questions/428974/how-to-enable-dragging-windows-with-alt-click-in-gnome-3-gnome-shell

Another important question is, can hardware acceleration support be added to either xiwi or freon?  (Or, put another way, does either approach entirely preclude the possibility that someday hardware acceleration will work on it (without rewriting from scratch?))

**Comment by kingdonb** [comment]
(I am yebyen)

Alt-arrow combinations also don't work in Xiwi, fyi.  It is quicker to get a window out of your way with alt-down (or bring it to the front with alt-up) than it is to alt-tab.  This shortcut might not work in XFCE even under the best of conditions, but it's an Enlightenment default key combo and it at least doesn't work under Xiwi.  Regrettably I don't have my chromebook here and I can't say for sure that it works under (frecon|xephyr), but I was using Xiwi last night and I noticed that.

There are clearly advantages and disadvantages to each implementation.

**Comment by yebyen** [comment]
Well, today when I tried, all of those alt-things worked fine in xiwi.  Maybe ChromeOS fixed upstream.

The only thing that didn't work is alt+down alt+up in xiwi when not fullscreened.  A different keysym (seems to produce [B   [A  instead of alt+down, alt+up).  Alt+clickdrag works fine, in fullscreen or windowed mode it passes through to the xiwi target fine.  Alt+tab is intercepted as you'd expect in windowed mode, and passes through in fullscreen mode.

Thanks!
