### ISSUE TITLE
Trouble switching from ChromeOS to Kubuntu

### ISSUE THREAD

**Issue by LindseySparks** [dnschneid/crouton#1627]
I just installed Kubuntu and had everything working fine a few days ago. I have been using ctrl + alt + back/forward to switch between the OS's. For reference I am on a Acer Chromebook 11 CB3-111.

However today for some reason, when I try to switch from ChromeOS to Kubuntu it enters the Developer Console instead.

I researched this problem and the only "solution" I have found is to press ctrl + alt + refresh to exit the developer console. But every time I switch back to Kubuntu I have to keep doing this work around. And it doesn't really work anyways. When I try to start a new Firefox window it says it isn't responding because it's already running. ctrl + alt + shift + foward/back doesn't do anything either.

So how can I get these keyboard shortcuts working like they used to?

Thanks.

**Comment by DennisLfromGA** [comment]
@LindseySparks - 

'`Ctrl+Alt+Forward`' will always put you in the Developer Console, by design.

When using the 'xorg' xmethod, 'crouton' is designed to switch between Chrome OS and your chroot(s) using '`Ctrl+Alt+Shift+Forward/Backward`'. Note the '*Shift*' key is part of that combo.

If the above '*Shift*' isn't working, it might be a good idea to update your chroot.

If you can't move back and forth with the recommended key combo, then you may have to revert to the older methods -

To get to Chrome OS, use: '`Ctrl+Alt+Forward`' then '`Ctrl+Alt+Backward`'. 
To get to the first chroot, use: '`Ctrl+Alt+Forward`' then '`Ctrl+Alt+Refresh`'.
