### ISSUE TITLE
Kali linux freezes when launched

### ISSUE THREAD

**Issue by PaulBorensztein** [dnschneid/crouton#1639]
Hello everyone,

I've just finished installing Kali with crouton. But when i enter sudo startxfce4, i get to the kali first screen but can't move my mouse nor use the keyboard. I assume it's because kali freezes... I have an Asus C300 4gb ram. Does any one knows how to fix it ?

Thanks in advance, 
Cheers !

**Comment by divx118** [comment]
Can you give the output of `sudo enter-chroot -n kali croutonversion`

**Comment by PaulBorensztein** [comment]
Oh i don't understand anything anymore.. I re-installed Kali exactly the same way i did the first time, now i don't even launch kali i have this "Fatal error : no screens found"... Do you know why and how to fix it ? Do you still need the output ? 

Thanks !

**Comment by divx118** [comment]
@PaulBorensztein Probably https://github.com/dnschneid/crouton/issues/1505 However to be sure can you post the output of `sudo enter-chroot -n kali croutonversion`
If it is indeed the above mentioned issue then you can update your chroot with `sudo sh ~/Downloads/crouton -n kali -u -t xiwi` Then it will use a chromeos window to run your chroot in, instead of using xorg.  
Please close this issue if it is the same as https://github.com/dnschneid/crouton/issues/1505, because it is already tracked there. Thanks.

**Comment by PaulBorensztein** [comment]
So after doing 
sudo sh ~/Downloads/crouton -n kali -u -t xiwi 
 
I got it working, thanks. 

Just before i close the issue, i have a last question. Will it slow the perfomances if I use Kali installed like that instead of the "regular" way ? Is there any possibilities to make it like most of the other people ? 

Thanks :+1:

**Comment by divx118** [comment]
Not much, since you also will not have gpu acceleration with xorg in kalli. For now kali and debian wheezie won't work with xorg, however work is being done to fix it. Keep an eye on #1505 .

**Comment by PaulBorensztein** [comment]
Alright, thanks a lot mate for fixing my issue. I'll definitly keep an eye on #1505, I close this issue. 
Thanks again ! :)

**Comment by PardeepKaur1211** [comment]
every time when i start a kali in vmware,it freezes. I am unable to open anything when this occurs. 
plz give me any solution regarding this.
