### ISSUE TITLE
trouble switching between chroot and Chrome since update

### ISSUE THREAD

**Issue by Pluk12** [dnschneid/crouton#1646]
Hi,

Ever since my Chromebook updated this weekend, I cannot switch between my chroot and chrome OS anymore like I used to. Ctrl-Alt-Backward does not work anymore. Also, Ctrl-Alt-Forward does not give the usual screen when in Chrome OS. Did google change shortcuts with the update? 

I updated my chroot and it works fine in itself, but no switching possible... Do I need to update something else? 

Thanks!

**Comment by divx118** [comment]
Ctr-Alt-Shift Backward/Forward is the key combination to use. Notice the `Shift`

**Comment by christopherschroeder** [comment]
I noticed this change in commands as well -- now a couple of combinations seems to work (e.g., ctr+alt+shift+backward to cycle back and forth or ctr+alt+shift+forward to cycle through both sides, as well as, at least on my Acer C720, the refresh key). Strange.

**Comment by divx118** [comment]
That is not strange at all. It has been the method for quite some time now.

**Comment by christopherschroeder** [comment]
I knew it was the method for switching on machines with an ARM processor (see, e.g., the < Tips > section in < http://www.cnet.com/how-to/how-to-run-both-chrome-os-and-ubuntu-on-a-chromebook/ > ), but I never had to include < shift > until the Chromebook update this past weekend -- did the update change anything else?

**Comment by divx118** [comment]
It has since some time be the way to switch between chroots on all architectures. The latest update will probably added freon. Which also removes vt switching on chromeos, so you can't use ctr-alt F(x) to switch vt's which was possible in the past and made it possible to use another key combination to switch between chroots and chromeos.

**Comment by RoosZwart** [comment]
I'm on a Toshiba CB30-102, running Ubuntu 14.04 with xfce.

Me too I used to switch using ctrl-alt-backward until yesterday. Today this didn't work anymore, but what is more: my screen reaction was severly lagging (was there no more hardware acceleration?): a very slow response or no response upon clicking files, no visual response upon typing something in my browser (input did register because when I hit enter there was an immediate response), etc.

Updating the chroot using the latest crouton changed nothing. So I made a back-up of my chroot, did a powerwash, restored my chroot and updated it, and the problem seems to have vanished.
