### ISSUE TITLE
Login bug/server bug? , forcing unmount is giving trouble also, Please Help! Thanks!

### ISSUE THREAD

**Issue by samtechnewbie** [dnschneid/crouton#1659]
![screenshot 2015-04-22 at 7 28 18 pm](https://cloud.githubusercontent.com/assets/12076362/7288342/2e6b0f0e-e92e-11e4-8366-85631c7bce92.png)

 output not looking so good either: 
chronos@localhost / $ sudo enter-chroot -n precise trusty croutonversion
Entering /mnt/stateful_partition/crouton/chroots/precise...
-su: 1: trusty: not found
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
Sounds/looks like you might have two chroots and there's some confusion.
Enter: `sudo edit-chroot -al` and show us see the output.

**Comment by divx118** [comment]
Try updating your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting  
The command to show your croutonversion should be `sudo enter-chroot -n precise croutonversion` so no trusty in between precise ... croutonversion.
@DennisLfromGA He is missing the croutonversion output when using sudo startunity, so for sure the chroot needs to be updating. Who was that again that made the pull request https://github.com/dnschneid/crouton/pull/1542 ;)

**Comment by samtechnewbie** [comment]
sorry for the late reply i'll type type the commands  and tell you guys the outcome when get back tp my computer.  For now '' duty'' calls. Thanks for the quick replies!

**Comment by samtechnewbie** [comment]
Alright here's what I got 
![screenshot 2015-04-23 at 3 35 14 pm](https://cloud.githubusercontent.com/assets/12076362/7306942/97df0166-e9ce-11e4-84ce-2a50d3830ab6.png)

**Comment by DennisLfromGA** [comment]
@samtechnewbie - Your chroot is really *old* so please follow @divx118's advice mentioned above - https://github.com/dnschneid/crouton/issues/1659#issuecomment-95630731

**Comment by samtechnewbie** [comment]
alright i updated chroot and here's my outcome

 chronos@localhost / $ sudo enter-chroot -n trusty croutonversion
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20141208100324~master:7b8ffff0
release: trusty
architecture: amd64
targets: unity
host: version 6812.75.2 (Official Build) stable-channel squawks 
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
@samtechnewbie - 

If you compare the croutonversion number and date in this comment https://github.com/dnschneid/crouton/issues/1659#issuecomment-95712702 with the one in your last comment https://github.com/dnschneid/crouton/issues/1659#issuecomment-95732779, they're the same. I don't think the crouton update you attempted worked.

I also noticed in your very first comment https://github.com/dnschneid/crouton/issues/1659#issue-70282041 that there may be two chroots - trusty and precise. 
- In the screenshot, when you attempt to `startunity` without a chrootname, it enters trusty.
- When you attempt to `startunity` with the chrootname of precise, it enters precise.

That's why I asked you to run: `sudo edit-chroot -al` so we could see everything installed and go from there.

However -
To update your precise chroot, do this: `sudo sh ~.Downloads/crouton -u -n precise`
To update your trusty chroot, do this: `sudo sh ~.Downloads/crouton -u -n trusty`

**Comment by samtechnewbie** [comment]
You were right ! I did have 2 chroots for some odd reason I updated trusy chroot to start my long-missed unity everything is working now ! Thanks for the help :+1: 

![screenshot 2015-04-24 at 7 28 30 am](https://cloud.githubusercontent.com/assets/12076362/7318687/36bd1360-ea54-11e4-81c7-fa3338c6a29a.png)

**Comment by DennisLfromGA** [comment]
Great, glad we could help.

**Comment by divx118** [comment]
@samtechnewbie If it is working now then please close the issue. Thanks in advance. It will save the moderators some time.
