### ISSUE TITLE
Manage screen/keyboard/mouse by hacking the file descriptors

### ISSUE THREAD

**Issue by ccaapton** [dnschneid/crouton#1675]
Currently chrome, frecon and crouton are not interacting very. For instance:
 - crouton can not be started within frecon, and quite a bit of code is written to make sure it never happen
 - keyboard shortcuts need special treatment in different interfaces
 - keyboard/mouse leak/grab problem. the LD_PRELOAD mitigates the problem but far from solved

So I'm thinking about a daemon which can gather all the gpu/keyboard/mouse file descriptors together and do central management. So:
 - It listens to all 3 fd for keyboard. Always get keyboard event no matter if x11/frecon grab the keyboard or not.
 - Force grab keyboard in the side daemon(not sure if necessary though)
 - drm master set/drop management in unified way, without interacting with x11/frecon/chrome

Here is the way to get hands on fd, at least I can think of:
1. LD_PRELOAD, fork/exec to inherit fd from parent, then send to central daemon via socket/dbus. Easy but only work for X11, possibly on frecon, never for chrome. I tried on X11 and it worked
2. lsof + GDB attach, fork/exec, send out fd to central daemon
3. A central daemon grab fd from all party by directly manipulating /dev/mem like this: http://phrack.org/issues/51/5.html, I have no idea how complex/risky it would be ...

Just my 2 cent:) comments welcome

**Comment by ccaapton** [comment]
And a side note: "/dev/tty0 not exist" bug can be solved by adding "-seat 1" to Xserver command args. There is no need for hacking "open()" in freon.c if that is added. But "-seat 1" will make Xserver not respond to SIGUSR1.

**Comment by dnschneid** [comment]
Some neat techniques in there, but I'm not sure it's worth the invasiveness.  There's crbugs to fix the need to grab input devices and to fix frecon's accidental handling of the shift shortcut, and I'm not aware of a strong need to use frecon over crosh in general.

Xserver has to respond to SIGUSR1 so that it can release the GPU, so we can't change that either.

What would be useful is if the keyboard shortcut config were in a central location, so that people who want to tweak it can do so without having to deal with croutontriggerd vs. xbindkeys, but I don't think that's the problem you're trying to solve here.
