### ISSUE TITLE
Setting user language on gnome results in black screen

### ISSUE THREAD

**Issue by szczys** [dnschneid/crouton#1680]
I've just done a fresh install of crouton gnome-desktop under trusty and and am getting a black screen with cursor when logging in after changing the user's default language.

To reproduce:
- use search key to pull of launcher, type "account" and select "User Accounts"
- There will be one user with Language not set, choose "English" from that box
- Log out and back in and you will get black screen with cursor and nothing else

Fix:
- enter chroot (sudo enter-chroot -n trusty)
- edit /etc/default/locale file (it didn't exist for me)
- put the following two lines in this file. Log out and then "startgnome"

```
LANGUAGE=en
LANG="en_US.utf8"
```

**Comment by sprc** [comment]
Brilliant!

I (and others) have been getting this black screen with a cursor for some time. I'm not going through the steps you describe to create the issue but this was the fix, so my hypothesis is that something has a pre/post apt-get action that can automatically bork this. It would be great if we could get something into crouton to keep this from happening.

**Comment by dnschneid** [comment]
Huh!  That's a good find.  We should add something like that by default.

**Comment by tedm** [comment]
may depend on the DE target, e17, for example, I think prompts for language on first start.

**Comment by aurey2244** [comment]
I still have problems, it just shows a black screen for 7 sec and then stops with this error:
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
[dix] Could not init font path element /usr/share/fonts/X11/misc, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/Type1, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150519153807~master:30cf02c9
release: trusty
architecture: armhf
xmethod: xephyr
targets: gnome
host: version 6812.88.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 12:23:49 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

any help, maybe its because im running this on arm

**Comment by mikaicebe** [comment]
Hi there:
I also got into this problem(on hp 11 G1,arm).Then I tried a new crouton but it did not work. And I also tried to edit the locale file but it did not exist.
any help,maybe it's really the fault of language.

**Comment by berkough** [comment]
I had the same problem... editing/creating the /etc/default/locale file did the trick though.  Thanks!

**Comment by Cpont63** [comment]
Before I begin, know that I'm a total noob.

When I attempt to edit the /etc/default/locale file (I used `edit /etc/default/locale`), I get this message:
`Warning: unknown mime-type for "/etc/default/locale" -- using "application/octet-stream"
Error: no write permission for file "/etc/default/locale"`

When I try to force the command with `sudo edit /etc/default/locale`, I get this error:
`Warning: unknown mime-type for "/etc/default/locale" -- using "application/octet-stream"
Error: no "edit" mailcap rules found for type "application/octet-stream"`. Am I doing this wrong? How can I fix it?

**Comment by dwaindibbly** [comment]
To create a file use:
`touch` then a space, then type the path to the non-existent file, then press ENTER/RETURN
