### ISSUE TITLE
cant start xfce after update

### ISSUE THREAD

**Issue by giliammc** [dnschneid/crouton#1690]
when i run sudo startxfce4 
i get
![screenshot 2015-04-29 at 6 24 02 pm](https://cloud.githubusercontent.com/assets/10850574/7403633/27acc1fc-ee9d-11e4-90d0-62715cc81118.png)

**Comment by divx118** [comment]
Update your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by giliammc** [comment]
i tried to update it and this is what happened
![screenshot 2015-04-30 at 2 25 21 pm](https://cloud.githubusercontent.com/assets/10850574/7420769/c3eb59f0-ef44-11e4-8cf6-176d84137148.png)

**Comment by divx118** [comment]
@giliammc For some reason you need libelf-bin package.
You could try the following.
```
$ sudo enter-chroot -n trusty
$ sudo apt-get update
$ sudo apt-get install libelf-bin
$ sudo apt-get upgrade
$ exit
```
If everything executed with no errors update your chroot again.

**Comment by giliammc** [comment]
it says unable to locate packages libelf-bin

**Comment by divx118** [comment]
Sorry typo `sudo apt-get install libefl-bin`

**Comment by giliammc** [comment]
i got
![screenshot 2015-05-01 at 7 17 40 pm](https://cloud.githubusercontent.com/assets/10850574/7439129/c76e6fe8-f036-11e4-81e7-2656032e1d86.png)

**Comment by giliammc** [comment]
so i ran "sudo apt-get -f install" and got

**Comment by giliammc** [comment]
![screenshot 2015-05-01 at 7 20 25 pm](https://cloud.githubusercontent.com/assets/10850574/7439145/26de77b6-f037-11e4-8f9b-d70ad9d10f5a.png)

**Comment by giliammc** [comment]
i created a chroot with no xiwi and it seems to work just fine, is their a way to switch back to the old way
of using ctrl,alt,forward,refresh

**Comment by divx118** [comment]
@giliammc No, ctr-alt-shift Forward/backward is the keyboard shortcut to use and has been a long time. That ctrl,alt,forward,refresh also worked was, because you could switch vt that way. When chromeos switches to freon vt switching will not be working any more.

**Comment by divx118** [comment]
Why did you add the ppa from https://launchpad.net/~enlightenment-git ?

**Comment by giliammc** [comment]
it was to install a terminal emulator, should i remove it ? if so how do i do that in the command line

**Comment by divx118** [comment]
Well I don't know exactly what you did in your chroot. The enlightenment ppa is meant for installing as the name already says for installing enlightenment on ubuntu 14.04, 14.10 http://ubuntuportal.com/2015/02/how-to-install-enlightenment-e20-desktop-environment-in-ubuntu-14-04-14-10.html
I created a new chroot to see if the ppa breaks something when updating, but it seems it doesn't. I just could update the chroot with no problems when the ppa was added. You did something that messed up the update. I also could install e20 and terminology package nothing broke the updating chroot.  
You could try removing terminology, that seems the package that has the problem looking at your second post. However this is a bit of a wild guess since I don't know if you have maybe other ppa's added or installed packages from external source. See below how to remove that package if the last command is executed with no errors try updating your chroot again.
```
$ sudo apt-get remove --purge terminology
$ sudo apt-get update && sudo apt-get upgrade
```

BTW If you can't successfully update your chroot you will not be able to start xfce, so this must be solved first.

**Comment by giliammc** [comment]
$ sudo apt-get remove --purge terminology
$ sudo apt-get update && sudo apt-get upgrade
 
ran without errors, i tried to update my chroot again and got the same error

**Comment by giliammc** [comment]
i fixed it by removing the packeges that could not be verified
