### ISSUE TITLE
How to make my Crouton xfce environment run on startup?

### ISSUE THREAD

**Issue by jessica1d** [dnschneid/crouton#170]
I'd love for there to be a way for a command (e.g. "sudo startxfce4 -b") to be run when my Chromebook starts up. What would be the most "correct" way to do this? I ALWAYS want my Crouton XFCE setup to boot up when my Chromebook does. Possibly even before I log in! Security, shmecurity. (Though it would be even neater if XFCE would prompt me for a login and password...)

Any thoughts? Crouton is by far the easiest way of getting a "full" Linux desktop environment on a Chromebook; if only it would run at startup, it'd be just about perfect...

**Comment by DennisLfromGA** [comment]
> You can disable rootfs verification in Chromium OS and add startxfce4 -b to the Chromium OS's /etc/rc.local. 

> **The major caveat (aside from security) is that you will stop getting auto-updates**, and the only way to start getting updates again will be to restore your system via USB key (be sure to back up your chroot if you decide to do so).

That hasn't been my experience at all, on every Chromebook that I've disabled rootfs verification and made the root file system read-writable [Cr-48, Acer C710, HP Chromebook 14 (falco)], *I've still gotten Chrome OS auto-updates*. I haven't heard from anyone that this has caused auto-updates to stop. 

If anyone has had a different experience with this, I'd be most interested in speaking with them to see if indeed removing rootfs verificaiton is the root cause.

**Comment by ashtell** [comment]
I have a cb3-111 and I don't have a /etc/rc.local file.  @tedm , did it work when you tried making it?

**Comment by DennisLfromGA** [comment]
@ashtell - See ['Autostart crouton chroot at ChromeOS startup'](https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup) for one alternative.

**Comment by lefterav** [comment]
Hi, I think it's not just an alternative, it's the best solution to the problem. And if it doesn't work, you should have a file in /tmp named crouton-$PID.log (the $PID will be whatever process number started it) that will show you where it failed.
