### ISSUE TITLE
Mouse Pointer not working

### ISSUE THREAD

**Issue by YoshiDudeRox** [dnschneid/crouton#1774]
OK so I tried to install Synaptic Package Manager but it failed and messed up my ubuntu installation so I updated my chroots to try and fix it when I entered precise it updated (I meant to click trusty) now the scroll wont work the trakpad will still click but other that that its useless

**Comment by SnarkBoojum** [comment]
Confirmed here, running chrome:
Version 43.0.2357.65 beta
Plate-forme 6946.44.0 (Official Build) beta-channel daisy_freon
Micrologiciel Google_Snow.2695.117.0
and:
crouton: version 1-20150519153807~master:30cf02c9
release: sid
architecture: armhf
xmethod: xorg
targets: lxde,cli-extra,core,audio
host: version 6946.44.0 (Official Build) beta-channel daisy_freon 
kernel: Linux localhost 3.8.11 #1 SMP Tue May 12 21:41:03 PDT 2015 armv7l GNU/Linux
freon: yes

**Comment by SnarkBoojum** [comment]
The mouse is still not behaving perfectly, but it's now usable.

crouton: version 1-20150519153807~master:30cf02c9
release: sid
architecture: armhf
xmethod: xorg
targets: lxde,cli-extra,core,audio
host: version 6946.53.0 (Official Build) beta-channel daisy_freon 
kernel: Linux localhost 3.8.11 #1 SMP Wed May 20 15:08:43 PDT 2015 armv7l GNU/Linux
freon: yes

**Comment by dnschneid** [comment]
@YoshiDudeRox please post the output of `croutonversion`

**Comment by YoshiDudeRox** [comment]
I had to reinstall linux but now its fixed

On Fri, May 29, 2015 at 2:12 AM, David Schneider <notifications@github.com>
wrote:

> @YoshiDudeRox <https://github.com/YoshiDudeRox> please post the output of
> croutonversion
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1774#issuecomment-106718953>.
>



-- 
Always remember that you are absolutely unique. Just like everyone else.

**Comment by SnarkBoojum** [comment]
It blocked again today...

**Comment by SnarkBoojum** [comment]
Today it doesn't block : it's just slow. But what's interesting is that when I go back and forth between chrome and lxde, the chrome pointer doesn't disappear : it just stays where it is, and I get another one.

And by "it just stays where it is", if I move a window one it, it stays on top like a real mouse pointer. It's just that it doesn't move.

Does that help understanding what happens?

Oh, by the way, I think I changed a few things since last time :
crouton: version 1-20150519153807~master:30cf02c9
release: sid
architecture: armhf
xmethod: xorg
targets: lxde,cli-extra,core,audio
host: version 7077.20.0 (Official Build) dev-channel daisy_freon 
kernel: Linux localhost 3.8.11 #1 SMP Thu May 28 21:42:48 PDT 2015 armv7l GNU/Linux
freon: yes
