### ISSUE TITLE
Trouble mounting network drive

### ISSUE THREAD

**Issue by reeved** [dnschneid/crouton#1810]
Alright so I managed to browse my network drive using `smb://networkaddress` and then inputting my username and password.

I then attempted to permanently mount it via this guide: http://ubuntuhandbook.org/index.php/2014/08/map-network-drive-onto-ubuntu-14-04/

Everything worked fine till the last step.

I did `sudo mount -a` but all I got was this: 
`mount error: cifs filesystem not supported by the system`
`mount error(19): No such device`

I googled the error and followed the advice of some people where it worked by reinstalling cifs and restarting but none of that worked.
Help?

**Comment by DennisLfromGA** [comment]
Details are here: #262

**Comment by divx118** [comment]
@DennisLfromGA If it is what reeved is trying from inside a chroot, why should this be #262.
@reeved Are you indeed using a chroot created by crouton on a chromebook? If so, can you post the output of croutonversion?
BTW to be able to browse your samba shares in the filemanager you need to open some ports on chromeos see https://github.com/dnschneid/crouton/issues/1142#issuecomment-92858589 Maybe that will be enough for you.

**Comment by DennisLfromGA** [comment]
@divx118 - Maybe I'm wrong but I thought '[How To Map A Network Drive Onto Ubuntu 14.04 Permanently](http://ubuntuhandbook.org/index.php/2014/08/map-network-drive-onto-ubuntu-14-04/)' was an Ubuntu issue that has little to do with 'crouton'.

**Comment by dnschneid** [comment]
@DennisLfromGA: no, this is an issue related to crouton.  Please don't tag things with 262 unless they're unquestionably irrelevant to crouton.

@reeved: cifs requires a kernel module that is not compiled into the Chromium OS kernel by default.  You can either compile the kernel module (see the wiki for details), or use a userspace library to mount the filesystems.

**Comment by DennisLfromGA** [comment]
My bad, believe I'll never do it again :(

**Comment by DennisLfromGA** [comment]
@reeved - I don't know if this tidbit will be of help but there's an app on the Chrome OS side that now provides for this: [Chrome App that lets you mount and browse any SMB/CIFS file system in the Files App](https://plus.google.com/+FrancoisBeaufort/posts/AUvJw6VjTd2)  
It might be possible to make your connection(s) on the Chrome OS side and then, with the use of the `/etc/crouton/shares` file, make your connection(s) appear in your chroot(s).  
See [Sharing files and folders between ChromeOS and your chroot](https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders) for more info. about the 'shares' file.

**Comment by divx118** [comment]
@DennisLfromGA Thanks for the link. I was waiting for such an app. Last time I searched for something like that it wasn´t available yet.

**Comment by DennisLfromGA** [comment]
@divx118 - No problem.
( I'm trying to reprieve myself after the 262 reference snafoo ;)

**Comment by reeved** [comment]
Thanks for the information guys and @DennisLfromGA I saw that a couple of hours after posting this. What a coincidence :P

**Comment by divx118** [comment]
For mount -t cifs you will need the appropriate kernel modules see https://github.com/dnschneid/crouton/wiki/How-to-mount-network-shares-on-Chromebook-(sshfs,-cifs,-nfs-etc)
IMO this can be closed now.

**Comment by pearlmam** [comment]
I hate to open up an old thread, but IMO this thread is not closed, although there is some good info here. I am having the same issue as the OP. I am able to browse the smb share in my chroot, and using the many availiable ChromeOS I am able to browse the shares on the ChromeOS side.

My issue is that I want to automatically mount the smb share on the chroot side in any way possible. There still is no support for mount.cifs on the kernel and  I really don't want to mess with the kernel in order to get cifs-utils to work at this point. Maybe in the future with more time... I cannot figure out where ChromeOS mounts the share in order to use "/etc/crouton/shares file, make your connection(s) appear in your chroot(s)." I am also unsure what "use a userspace library to mount the filesystems" means. 

Thanks for your help, hopefully some of you are still around to see this.

**Comment by divx118** [comment]
@drinkcat what is the actual bug here? I know it doesn't work out of the box in a crouton chroot. However with some effort it can be made to work in different ways. [see here](https://github.com/dnschneid/crouton/wiki/How-to-mount-network-shares-on-Chromebook-(sshfs,-cifs,-nfs-etc))
Is it an issue to let the [chromeos smb app](https://chrome.google.com/webstore/detail/network-file-share-for-ch/ndjpildffkeodjdaeebdhnncfhopkajk) (which is really slow with file transfers) to work with the /etc/crouton/shares file?

**Comment by drinkcat** [comment]
Sorry I probably went too fast while trying to triage old issues. Looks like it can be closed indeed. Thanks!

**Comment by divx118** [comment]
No problem just was double checking you :)
