### ISSUE TITLE
Ubuntu 15.10!

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#1817]
Ubuntu 15.10 is being "released". Support would be nice :smile_cat:

**Comment by 1rocketdude** [comment]
probably same challenges as 15.04. That whole systemd thing. Would be great, but someone smarter than I needs to attack it.

**Comment by firestar115** [comment]
Um... what systemd thing... :confused:

**Comment by bdshaffer73** [comment]
Anyone know if there's foreseeable support for 15.10, or do we have to wait for the next LTS release?

**Comment by tonyxue** [comment]
It is the systemd matter. Systemd requires its PID to be 1 but we cannot do that for a chroot as we have Chrome OS already started with its init process occupying PID1.

The foreseeable support is when Chrome OS update all stable version kernels to 3.8. Only unstable channel of some hardware is on 3.8 right now. 3.8 provides PID Namespace which we can create a separate PID namespace which everything starts with PID 1 for the chroot. Then systemd would work.

However, if that's happening , we don't even need chroot anymore.

If you are interested in PID namespace, see the pull request: https://marc.info/?l=linux-kernel&m=135526066121436&w=2

**Comment by firestar115** [comment]
Whoah. How would you NOT need a chroot? My mouth is permanently open right
now. I have my chrome book on dev channel, so HOW would I do that?

**Comment by bdshaffer73** [comment]
Thanks @tonyxue!

**Comment by bdshaffer73** [comment]
@tonyxue Just read through that pull request.. That was way over my head but I think I got the gist of the message, agreeing with what you said. Still, very advanced work.

**Comment by mark-hahn** [comment]
> How would you NOT need a chroot?

My curiosity is set on stun also.

**Comment by dnschneid** [comment]
crouton would use containers instead of the chroot command.  You still need the same kind of stuff.  See #364

**Comment by mark-hahn** [comment]
I noticed that thread petered out in June.  Does this mean there is less
interest in it now?

I have a question.  LXC offers greater security through isolation.  What is
the practical advantage of this over chroot?  It can't be for system
security because once you go into developer mode you chromebook is insecure
by nature.

Also, why would I want to have less access to chromeos?  I want to have the
power to do anything I want up to and including screwing everything up.  It
is my machine.

**Comment by tonyxue** [comment]
> I noticed that thread petered out in June.  Does this mean there is less
interest in it now?

I think it's more of now we're waiting for 3.8 to be universal.

> I have a question.  LXC offers greater security through isolation.  What is
the practical advantage of this over chroot?  It can't be for system
security because once you go into developer mode you chromebook is insecure
by nature.

You have a more isolated environment so if you have a ubuntu installed, things work more like they do in a 'direct' ubuntu environment. I believe it would be more helpful when you're building up development environments. I personally believe it would be more or less similar to the usage of Vagrant as people want a completely independent and isolated dev environment that can be configured in the same standard quickly and can be destroyed easily.   

> Also, why would I want to have less access to chromeos?

Well, I don't think chroot will be then completely gone. So if you want the connection between two environments, you can still use chroot.

**Comment by mark-hahn** [comment]
Thanks.  Makes sense.

**Comment by 1rocketdude** [comment]
having ChromeOS and a distinct linux environment that is switchable using the Vulcan death grip is the magic of crouton. My hope is that 15.04 or 16.04 is supported. I'm willing to be the guinea pig. I may need a new Chromebook as I doubt kernel 3.8 will ever be ported to a lumpy chromebook.

thanks for all the great tools. Makes life enjoyable.

**Comment by bdshaffer73** [comment]
>thanks for all the great tools. Makes life enjoyable.

Agreed!

**Comment by sn0e** [comment]
One can get Wily with systemd to work using PID namespacing. A kernel with CONFIG_PID_NS is required. I don't know how common this is, but kernel 3.14 on my 2015 Pixel has it.

Something like jchroot is needed to perform the PID namespace change. When we have that, we can start systemd inside a wily root as pid 1:

```bash
sudo mount-chroot wily
sudo jchroot /run/crouton/mnt/stateful_partition/crouton/chroots/wily /bin/systemd
```
Unfortunately, when running the second command, the touchpad or keyboard stops working. Possibly #1994 happens. I work around it by running these in a VT following them by a `sudo restart ui`, but I 
guess plugging in an external mouse should work as well.

With this running in one window, we can open another and enter the chroot:
```bash
sudo nsenter -t $(pidof systemd) -p -m -u -r
```

In there, a pretty "complete" Wily is running, with systemd for starting and stopping services etc. We can even cleanly shut down the chroot by running `systemctl poweroff`. After stopping everything systemd exits, allowing one to run `unmount-chroot wily` without hassle.

**Comment by firestar115** [comment]
@sn0e I noticed sometimes when I'm creating a new chroot I can only use my touchpad and nothing else (laptop keyboard, external keyboards/mice) and I have to use the onscreen keyboard. Possibly linked?

**Comment by sn0e** [comment]
@firestar115 I've since found out that it does not happen if all `systemd-udev*` services are masked (disabled) before entering the chroot. I've worked a bit more on this and added it to `enter-chroot` in PR #2474

**Comment by dnschneid** [comment]
I think this is duplicate with the xenial stuff.
