### ISSUE TITLE
Autostart-crouton-chroot-at-ChromeOS-startup not working

### ISSUE THREAD

**Issue by caffeineaddiction** [dnschneid/crouton#1819]
crouton: version 1-20150519153807~master:30cf02c9
release: precise
architecture: armhf
targets: cli-extra
host: version 6946.55.0 (Official Build) stable-channel veyron_jaq
kernel: Linux localhost 3.14.0 #1 SMP Tue May 26 17:55:54 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes

https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup

Step 1: Remove rootfs verification & reboot (works)
Step 2: place config script in the /etc/init (works)
Step 3: place 'crouton.init' in ~/Downloads (works)
Step 4: reboot to implement changes (does not work)

After attempting to follow instructions on wiki I attempted to write my own upstart script but it didnt seem to work. I then wrote `echo 'something' > /tmp/upstarttest` in an upstart script ... no log file was created.
It seems like Step 1 gave me read/write access ... but that the files i copy into /etc/init never get executed

My end goal is I would like to boot up the computer (booted up not logged in) and have it run ubuntu and listen on port 22 for ssh into the ubuntu chroot. I followed https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton and have the ssh part up and working ... now I just need to get autostart working.

Edit: Fixed typo

**Comment by tonyxue** [comment]
I think the wiki is a bit outdated and the new frecon feature is making things changed? Confirm with @dnschneid ?

**Comment by divx118** [comment]
@caffeineaddiction I assume `echo 'something' > /temp/upstarttest` is a typo and should be `echo 'something' > /tmp/upstarttest`

**Comment by caffeineaddiction** [comment]
@divx118 yes, a typo (here and not in testing.conf double checked)

**Comment by DennisLfromGA** [comment]
@caffeineaddiction - If `crouton.conf` is in `/etc/init/` then it should work as long as your `~/Downloads/crouton.init` file has valid parameters. Can you show us what `~/Downloads/crouton.init` contains?

**Comment by caffeineaddiction** [comment]
@DennisLfromGA 

The following is a copy of my ~/Downloads/crouton.init
http://codepad.org/8DljdbSp

**Comment by DennisLfromGA** [comment]
Okay, that looks good as long as you have 'trusty' chroot installed with a gnome desktop target.
If you've left debugging on, the default, you should have a file in `/tmp` named `crouton-$PID.log` (the $PID will be whatever process number started it) that will show you where it failed.

**Comment by caffeineaddiction** [comment]
@DennisLfromGA that might be the issue right there ... 
I changed line 24 and 26 so that it is set to `precise` I am pretty sure I do not have gnome installed.  When setting up the chroot I used `sudo sh ~/Downloads/crouton -t cli-extra`  what would I put in place of `START_DE=startgnome` in that case?

**Comment by DennisLfromGA** [comment]
@caffeineaddiction - Nope, `startcli` won't work anymore if your system is now using Freon.
You should be able to replace `startgnome` with `enter-chroot` to get a chroot shell prompt.

**Comment by DennisLfromGA** [comment]
@caffeineaddiction - Also, you might want to take a look at this issue comment for your situation - https://github.com/dnschneid/crouton/issues/1493#issuecomment-86295638
If that's something you want, then change line 33 to of your ~/Downloads/crouton.init file to `enter-chroot -b sleep infinity`.

**Comment by caffeineaddiction** [comment]
@DennisLfromGA 

updated init - http://codepad.org/kQXFPuVq

rebooted, still not working.  It doesnt seem like the upstart is even running, how would I go about check to see if the scripts are running at all?

**Comment by DennisLfromGA** [comment]
See this https://github.com/dnschneid/crouton/issues/1819#issuecomment-109032340, it log file should tell you what's going on.

**Comment by DennisLfromGA** [comment]
Is 'xiwi' installed? Do this to find out - `sudo enter-chroot cat /etc/crouton/xmethod`

**Comment by caffeineaddiction** [comment]
@DennisLfromGA 

`sudo enter-chroot cat /etc/crouton/xmethod`

yields

`chronos@localhost / $ sudo enter-chroot cat /etc/crouton/xmethod
Entering /usr/local/chroots/precise...
cat: /etc/crouton/xmethod: No such file or directory
Unmounting /usr/local/chroots/precise...
Sending SIGTERM to processes under /usr/local/chroots/precise...`

**Comment by DennisLfromGA** [comment]
Okay, you didn't enter any gui targets when you installed your chroot -

  `sudo sh ~/Downloads/crouton -t cli-extra`

so 'xiwi' didn't get installed, which is probably okay since you only want a command shell.
I'm afraid the `crouton.conf` file is designed to run gui desktops so it may not work for you.

You could modify the file to put in only the command you need, let me work on that a little and I'll get back to you.

**Comment by newbieUK** [comment]
I am having similar issues. I have Gnome desktop, trusty installed, xiwi installed and I can see the script in etc/init.  This i the code: .http://codepad.org/cdwbeIkv

I would really like to get this to work - I'm presuming you do everything in the ChromeOs?

Any help much appreciated!  Thanks,

**Comment by DennisLfromGA** [comment]
@newbieUK - I looked at the output file above and it's using the original `crouton.init` file which is meant to be an example of various possibilities. I would suggest creating a `crouton.conf` file with only the following contents, just to keep things simple -
```
DELAY=1
CHROOT=trusty
START_DE=startgnome
XMETHOD=xiwi
RUN_STATE=y
```

**Comment by DennisLfromGA** [comment]
@caffeineaddiction,

> I'm afraid the crouton.conf file is designed to run gui desktops so it may not work for you.

I've updated `crouton.conf` to now accommodate a CHROOT_APP.
It can be used for things like `startxiwi` or, in your case `enter-chroot`.

Re-download it using:
```
curl -Lk --connect-timeout 60 -m 300 --retry 2 "https://gist.github.com/DennisLfromGA/6443733/download" | tar -xzO > ~/Downloads/crouton.conf
```

Then change one of the four following lines to when you want it to start -
```
#start on starting ui          # 1st - starts when the user interface begins
#start on started ui           # 2nd - starts when the user interface appears
#start on login-prompt-visible # 3rd - starts when the login screen appears
 start on start-user-session   # 4th - starts when the user logs in - DEFAULT
```

Then replace your `/usr/local/crouton.init` file with the following:
````
START_DE=enter-chroot -b
CHROOT_APP=sleep infinity
````

Then reboot and it should start, you can check the DEBUG log in /tmp to verify.

**Comment by newbieUK** [comment]
Many thanks for the advice; I have amended the Crouton.init file as you
suggest, but it has not made a difference.

Crouton.conf is in the ChromeOs side and was installed using a Crosh shell;
however, there is log file in the temp folder. Any further ideas? Thank
you.

**Comment by DennisLfromGA** [comment]
> I would suggest creating a crouton.conf

@newbieUK - *My apologies*, I should have said "create a `crouton.init` file with only the following contents, just to keep things simple -"

DELAY=1
CHROOT=trusty
START_DE=startgnome
XMETHOD=xiwi
RUN_STATE=y

The `crouton.conf` file, in it's entirety, needs to be placed in `/etc/init/`, per the wiki page.

And yes, *all* of this is done on the Chrome OS side.

Let's keep this conversation going in your original thread at https://github.com/dnschneid/crouton/issues/1809#issuecomment-109614667

**Comment by caffeineaddiction** [comment]
downloaded the new crouton.conf file and moved it to /etc/init/
changed crouton.init to the following codepad.org/4VxgYVUf

still no love

**Comment by caffeineaddiction** [comment]
also tried with `CHROOT=precise`

**Comment by DennisLfromGA** [comment]
@caffeineaddiction -
> also tried with CHROOT=precise

You have a 'precise' chroot so that line shouldn't be needed, but it can't hurt either.
It should **not** be set to trusty though.

> still no love

Cute, but I'd like to see the output of your DEBUG log that's created `/tmp/`.
You should have a file in /tmp named crouton-$PID.log (the $PID will be whatever process number started it) that will show you where it failed.

**Comment by caffeineaddiction** [comment]
`I'd like to see the output of your DEBUG log that's created /tmp/.`

codepad.org/NSLdb1iy

**Comment by DennisLfromGA** [comment]
>  NO external control file found, using internal defaults.

It can't find one of the two possible external control files and the `crouton.conf` file still refers to `startxfce4` which you don't have.
You have to do one (or more) of three things to start your chroot automatically:  
1. edit `/etc/init/crouton.conf` and change when you want the chroot to start, what the chroot's name is, and what desktop or program you want to start, plus other optional parameters
2. create a `/usr/local/crouton.init` file with the chroot's name, the desktop or program you want to start, plus other optional parameters
3. create a `~/Downloads/crouton.init` file with the chroot's name, the desktop or program you want to start, and other optional parameters

Most likely, you'll want to do \#1 to change when the chroot starts and \#2 to use your own `/usr/local/crouton.conf` file.

**Comment by tedm** [comment]
am confused about this. by entering developer mode, the prompt received (on the toshiba intel chromebook 2) is that you are removing root fs verification, so is step one machine or chromeos version specific?

Second, does this work? And what is the benefit of waiting 10 seconds?

**Comment by DennisLfromGA** [comment]
@tedm,

>by entering developer mode, the prompt received (on the toshiba intel chromebook 2) is that you are removing root fs verificatio

I'm no expert but putting a Chromebook into Developer mode removes rootfs verification so that you can, optionally, make changes to it and they won't get rejected. Using the `rw-rootfs` script makes the rootfs read-writable so that you can then add things to `/etc/init`, etc.

> so is step one machine or chromeos version specific?

It is *not* Chrome OS version specific, it should work on all Chromebooks that have the rootfs read-writable.
I'm not sure what you mean by *'machne'* specific, exactly...

> Second, does this work? And what is the benefit of waiting 10 seconds?

Well, it's evidently *not* working for @caffeineaddiction - but it *does* work, lots of people have reported success.
I don't see any real benefit of waiting 10 seconds in this scenario but to each his own, that's why I made it an option.
Sometimes, after logging in, I like to wait until everything gets loaded and the system settles down before I kickoff a chroot but @caffeineaddiction is trying to do it *before* logging in.

**Comment by caffeineaddiction** [comment]
@DennisLfromGA 

I did #1 and #2 per your comment above.
`/etc/init/crouton.conf` is now codepad.org/UneklBml updates on line 17,48,49,50
`/usr/local/crouton.init` is now codepad.org/juNyKfcj

on reboot it doesnt seem to be starting up the chroot and it is no longer creating any log in `/tmp`

**Comment by DennisLfromGA** [comment]
@caffeineaddiction,

- Your `/etc/init/crouton.conf` file looks okay for what you are trying to do, however, you didn't need to modify lines 48-50, that's what the `/usr/local/crouton.init` file is for.  
*Please remove the changes made to lines 48-50*.  
- Your `/usr/local/crouton.init` file changes the DELAY to 1 but leaves the other parameters the same so that's fine.

You should definitely be getting the DEBUG file `/tmp/crouton-$PID.log`, you did before so if you're not getting one now something is drastically wrong with `/etc/init/crouton.conf`.

**Comment by DennisLfromGA** [comment]
@caffeineaddiction,
One thing to note - when you start the chroot like you have, you won't notice *anything*. No window or tab will open, it won't switch displays, etc. What you can do to determine if it's running is open the Developer Console using <kbd>Ctrl+Alt+F2</kbd>, enter 'chronos' at the prompt, and then run: `ps -ef | grep precise` and see if returns your 'sleep infinity' process.

**Comment by tedm** [comment]
@DennisLfromGA By machine specific, I'm wondering if anyone has used it on the Toshiba cb 2, one guy tried back in March, but it wasn't working for his system then. I think it was mmcblkx being different on some systems. I can give you /dev/proc settings for the Toshiba.

I looked at the script, and it probably has a 50/50 chance of working as is, but note that a crouton user has had to enter dev mode, but may have done other things as well, and crouton has sometimes set them backwards (or recommended them to be set backwards) from default dev mode. 

I wouldn't recommend the use of unset and set for existing chrome os env variables, but explicitly read them and set them to 1 or 0 as needed.

I'm willing to give it a go, as I have no valuable data on my cb 2. Would be very helpful if you were on IRC so we could learn what breaks, if anything though.

**Comment by DennisLfromGA** [comment]
@tedm - As the song says "I'll be there..."

**Comment by tedm** [comment]
OK, this works GREAT, and is an incredible milestone as I can boot the system, and the chroot is right on top (I'm using xiwi / xfce / trusty) on the Toshiba Intel cb 2 fhd 4gb/16gb. The documentation needs some work, and the crouton.init file only needs a couple or few of the 52 lines in the current file, and the initial r/w script didn't work, but a manual permutation/extraction of the script did work. Thanks Dennis!!

**Comment by DennisLfromGA** [comment]
> OK, this works GREAT - **GREAT!** ;)  

> The documentation needs some work - **TRUE**  

> the crouton.init file only needs a couple or few of the 52 lines in the current file - **MAYBE**
but a lot of users would get it wrong without some (okay, a lot) of examples.

> the initial r/w script didn't work - **DOUBTFUL**
you needed to use 'sudo' to copy anything in to `/etc/init/`.

> Thanks Dennis!! - ***You're Welcome*** @tedm

**Comment by DennisLfromGA** [comment]
@caffeineaddiction - I apologize for hi-jacking your thread with the above. Please let me know how it goes...

**Comment by caffeineaddiction** [comment]
`Please remove the changes made to lines 48-50.` - revert changes or delete them all together?
`One thing to note - when you start the chroot like you have, you won't notice anything.` SSH access should work from another computer if chroot is up though ... if i log in and start it manualy SSH is immediatly availible ... unless chrome is blocking something before login SSH should be accessible if chroot is up.

**Comment by tedm** [comment]
Dennis, while this is fresh in my mind, here are my comments that you may
want to integrate in some way to the existing docs. I'll use **COMMENTS**
so you can quickly flag them:

Method and scripts to invoke a crouton chroot session at ChromeOS startup.
**COMMENTS** change startop to startup/poweron/boot
------------------------------

*In order to do this, please note that* -

*1.* You first need to *REMOVE* rootfs verification and *reboot* to make
the rootfs read-writable. **COMMENTS** I think it's more specifically
enabling read/write to the Chrome owned partition. I think of (And I could
be incorrect here) that removing rootfs verification is removing the signed
boot = 1, and while this may be a part of what we're doing, that is also
done for other things like booting any non-signed code like Chrubuntu or
Arch from sd card, etc., so with regards to a crouton user, we have to
enable r/w on the crosh filesystem, independent of what someone did prior
(I think a lot of folks have tried Chrubuntu, then gone on to Crouton, arch
and other niche things, less so)...


Check out this script 'rw-rootfs
<https://gist.github.com/DennisLfromGA/6690677>' for one method of doing
that.

   - *PLEASE USE THIS SCRIPT WITH CAUTION - AND AT YOUR OWN RISK,
   'make_dev_ssd.sh' *
   -
- ***COMMENTS** unless someone read your rw-rootfs script, they would not
   know what 'make_def_ssd.sh' is, I didn't and was confused by this.*
   -
* HAS BEEN KNOWN TO CAUSE RESETS AND WIPE DATA ON SOME CHROMEBOXES !*
   - *NOTE*: This script will now *unset* 'dev_boot_signed_only' if
   **COMMENTS mention it will set it to 0 which it may well have been anyways,
   and if it was set to 1, it will now set it to 0, this is less secure than
   1, in that unsigned boot code can now run, but you can set it back when
   traveling, or when your chromebook is not physically secure, and unlike dev
   mode turning off and on, it won't wipe anything by turning back on, you
   just won't be able to use the feature (at least editing) without it being
   set to 0.
   -
   - it is set to ensure booting an unverified rootfs.
   - To obtain the file rw-rootfs, in a cros shell (crosh) do:

curl -Lk --connect-timeout 60 -m 300 --retry 2
"https://gist.github.com/DennisLfromGA/6690677/download" | tar -xzO >
~/Downloads/rw-rootfs


   - Then do: sudo sh ~/Downloads/rw-rootfs
   -
   - **COMMENTS** Note that when this is done succesfully, they should get
   a warning box from ChromeOS that they are on there own, and there is not a
   reboot prompt, so be sure to do it. Also, not sure why it didn't work for
   me, but I just copied and pasted your code, which has the sudo there? Can
   recheck that later.
   -


   - Make sure you *reboot* to put the 'rootfs' in a read-write state.

*2.* Then, you have to place one or possibly two custom config scripts in
the /etc/initfolder.


**COMMENTS** I would just put the editable 4 or 5 fields at the top of
/etc/init/crouton.conf The 2nd config file, as you mention is confusing,
especially when only 2-5 of the parameters are likely to be tweaked - IMHO
here.

The first script, 'crouton.conf
<https://gist.github.com/DennisLfromGA/6443733>', is the one that will
kick-off a crouton chroot without having to open a shell manually at
ChromeOS startup.
The second script, 'mnt-crouton.conf
<https://gist.github.com/DennisLfromGA/11072037>', is only needed if you
are using @drinkcat's 'separate-partition branch' to mount the CROUTON
partition at /var/crouton.

   - To obtain the file crouton.conf, in a cros shell (crosh) do:

curl -Lk --connect-timeout 60 -m 300 --retry 2
"https://gist.github.com/DennisLfromGA/6443733/download" | tar -xzO >
~/Downloads/crouton.conf


   - To obtain the file mnt-crouton.conf, in a cros shell (crosh) do:

curl -Lk --connect-timeout 60 -m 300 --retry 2
"https://gist.github.com/DennisLfromGA/11072037/download" | tar -xzO >
~/Downloads/mnt-crouton.conf

*3.* Next, you can optionally place a file named 'crouton.init
<https://gist.github.com/DennisLfromGA/aa1c92ebe77c3df4ca84>' in your
~/Downloads folder or the chroot parent folder for external control.
If you choose *not* to use the external control file 'crouton.init
<https://gist.github.com/DennisLfromGA/aa1c92ebe77c3df4ca84>', then you may
need to edit the CHROOT and START_DE variables in /etc/init/crouton.conf.

   - To obtain the file crouton.init, in a cros shell (crosh) do:

curl -Lk --connect-timeout 60 -m 300 --retry 2
"https://gist.github.com/DennisLfromGA/aa1c92ebe77c3df4ca84/download"
| tar -xzO > ~/Downloads/crouton.init

*4.* Finally, *reboot* once more to implement the changes and you're good
to go...
------------------------------
<https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup#-additional-notes-and-information>##
Additional notes and information

The 'crouton.conf <https://gist.github.com/DennisLfromGA/6443733>' file,
installed in /etc/init, allows you to start a crouton chroot session at one
of four different points in the boot/startup process as shown below:

#start on starting ui          # 1st - starts when the user interface begins
                               #     + only 1 chroot will run in this mode
                               #     + must use XMETHOD: 'xorg' or 'xephyr'

#start on started ui           # 2nd - starts when the user interface appears
                               #     + only 1 chroot will run in this mode
                               #     + must use XMETHOD: 'xorg' or 'xephyr'

#start on login-prompt-visible # 3rd - starts when the login screen appears
                               #     + only 1 chroot will run in this mode
                               #     + must use XMETHOD: 'xorg' or 'xephyr'

 start on start-user-session   # 4th - starts when the user logs in - DEFAULT
                               #     + multiple chroots could run in this mode
                               #     + can use any XMETHOD:
'xiwi','xorg' or 'xephyr'
                               #     + ensures user ~/Downloads is available

You'll note that the last or 4th option is the default since it will start
after you're logged in so that you can use your ~/Downloads folder in both
your chroot and in ChromeOS like you normally would in crouton, it also
allows you to use any XMETHOD: 'xiwi', 'xorg' or 'xephyr'.

*If you want to start your crouton chroot earlier in the boot/startup
process, just remove the remark character '#' in the first column.*
*NOTE: use only one startup point, prepend the others with the remark
character: #*

There are now six parameters that are set by default but can be edited or
changed by the external control file 'crouton.init'. These parameters are:

 1) DELAY=10
 2) CHROOT=precise
 3) START_DE=startxfce4
 4) CHROOT_APP=none
 5) XMETHOD=default
 6) RUN_STATE=y

------------------------------

The optional 'crouton.init
<https://gist.github.com/DennisLfromGA/aa1c92ebe77c3df4ca84>' file, placed
either in the ~/Downloads folder or the chroot's parent folder, allows you
to adjust the same four variables without changing the above mentioned
config file each time. The parameters are:

 1) DELAY - in seconds, default is '30'
 2) CHROOT - installed chroot name, default is 'trusty'
 3) START_DE - crouton start* script, default is 'startkde'
 4) CHROOT_APP - enter desired chroot application to run
 5) XMETHOD - Override the default XMETHOD, default is 'xiwi'
 6) RUN_STATE - use 'n' for No, default is 'y' for Yes

Note that these values are slightly different than those found in the
'crouton.conf' file, I've adjusted them for my use but they can be edited
to suit your needs.

Please make sure you adhere to the format currently used in the
'crouton.init' file, comments are okay but the variables have to start in
the first column.
------------------------------




*Caveats to this approach: 1. These changes need to be done outside your
chroot in Crosh. 2. Each time you get a new ChromeOS update, you have to
again remove rootfs verification and place a copy of the 'crouton.conf'
and, optionally, the 'mnt-crouton.conf' file in /etc/init. 3. This
will not work on encrypted chroots since they require a password to be
entered.*


***COMMENTS** The rest is good, I still have some questions about the
shared ~/Downloads folder and what would happen with different users, etc.,
but I'll use it awhile before commenting on the last half or third of the
docs. They probably make good sense.*


*Thanks so much Dennis. This is the best Chromebook/Linux exeperience I've
had yet. It's getting close to perfect!!*

**Comment by DennisLfromGA** [comment]
@tedm - I think we've hi-jacked @caffeineaddiction thread long enough, let's do this off-line in the future.

Thanx though, I'm working on it now.

**Comment by tedm** [comment]
@DennisLfromGA OK, got it.

@caffeineaddiction Sorry. For ssh, enable iptables and manually start sshd per the wiki server docs section. If you need exact wording for /etc/rc.local for iptables and/or starting ssh let me know, and I'll copy and paste from my blog server chromebook.

**Comment by caffeineaddiction** [comment]
@tedm per op SSH and iptables has been set up and is known working

**Comment by caffeineaddiction** [comment]
Been busy the last two weeks and finally got a chance to sit down and play with this project again.  I am happy to say that after following dnschneid's advice `Please remove the changes made to lines 48-50` it is not working.

I can now SSH into Ubuntu with out having to log in at the chrome log-in prompt.  Thank you very much for the help.

**Comment by dnschneid** [comment]
That was @DennisLfromGA for the record...
