### ISSUE TITLE
VPN Connection using OpenConnect

### ISSUE THREAD

**Issue by anthonylai** [dnschneid/crouton#182]
Hi,

  Would I be able to connect t VPN using OpenConnect?  If not, do we have other alternatives to establish VPN connections?  I installed uml-utilities and also downloaded the vpnc-script from http://www.infradead.org/openconnect/vpnc-script.html.

  I installed it, and after numerous of attempts, it worked once.  But I have no luck afterwards.

  Essentially, when it is not working, it could not find device tun2 and SIOCSIFMTU

  Any help is greatly appreciated, as I really need this to work to be able to make the Chromebook Pixel useful.

  Thanks.
Sincerely,
Anthony
# Log when it is not working

alai@localhost:~$ sudo openconnect --disable-ipv6 -u XXXXX --script /etc/vpnc/vpnc-script VPNSERVER
Attempting to connect to XXX.XXX.XXX.XXX:443
SSL negotiation with VPNSERVER
Connected to HTTPS on VPNSERVER
GET VPNSERVER
Got HTTP response: HTTP/1.0 302 Temporary moved
Attempting to connect to XXX.XXX.XXX.XXX:443
SSL negotiation with VPNSERVER1
Connected to HTTPS on VPNSERVER1
GET VPNSERVER1
Got HTTP response: HTTP/1.0 302 Object Moved
SSL negotiation with VPNSERVER1
Connected to HTTPS on VPNSERVER1
GET VPNSERVER1/+webvpn+/index.html
Please enter your username and password.
Password:
POST VPNSERVER1/+webvpn+/index.html
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connect Banner:

Cannot find device "tun2"
Cannot find device "tun2"
Cannot find device "tun2"
Cannot find device "tun2"
SIOCSIFMTU: No such device
Connected tun2 as XXX.XXX.XXX.XXX, using SSL
Established DTLS connection
# Log when it is working (only once)

alai@localhost:~$ sudo openconnect --disable-ipv6 -u XXXXX --script /etc/vpnc/vpnc-script VPNSERVER
Attempting to connect to XXX.XXX.XXX.XXX:443
SSL negotiation with VPNSERVER
Connected to HTTPS on VPNSERVER
GET VPNSERVER
Got HTTP response: HTTP/1.0 302 Temporary moved
Attempting to connect to XXX.XXX.XXX.XXX:443
SSL negotiation with VPNSERVER1
Connected to HTTPS on VPNSERVER1
GET VPNSERVER1
Got HTTP response: HTTP/1.0 302 Object Moved
SSL negotiation with VPNSERVER1
Connected to HTTPS on VPNSERVER1
GET VPNSERVER1/+webvpn+/index.html
Please enter your username and password.
Password:
POST VPNSERVER1/+webvpn+/index.html
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connect Banner:

Connected tun2 as XXX.XXX.XXX.XXX, using SSL
Established DTLS connection

**Comment by zaheermkn** [comment]
Fri Jan 29 22:13:57 2016 NMDVPN 2.1.4 i686-pc-mingw32 [SSL] [LZO2] [PKCS11] built on Apr 25 2011
Fri Jan 29 22:13:57 2016 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Fri Jan 29 22:13:57 2016 NOTE: NMDVPN 2.1 requires '--script-security 2' or higher to call user-defined scripts or executables
Fri Jan 29 22:13:57 2016 NOTE: --fast-io is disabled since we are running on Windows
Fri Jan 29 22:13:57 2016 LZO compression initialized
Fri Jan 29 22:13:57 2016 Control Channel MTU parms [ L:1560 D:140 EF:40 EB:0 ET:0 EL:0 ]
Fri Jan 29 22:13:57 2016 Socket Buffers: R=[8192->8192] S=[8192->8192]
Fri Jan 29 22:13:57 2016 Data Channel MTU parms [ L:1560 D:1450 EF:60 EB:135 ET:0 EL:0 AF:3/1 ]
Fri Jan 29 22:13:57 2016 Local Options hash (VER=V4): 'bc07730e'
Fri Jan 29 22:13:57 2016 Expected Remote Options hash (VER=V4): 'b695cb4a'
Fri Jan 29 22:13:57 2016 Attempting to establish TCP connection with 183.207.232.43:80
Fri Jan 29 22:13:57 2016 TCP connection established with 183.207.232.43:80
Fri Jan 29 22:13:57 2016 Send to HTTP proxy: 'CONNECT 176.126.237.214:80 HTTP/1.0'
Fri Jan 29 22:13:57 2016 User-Agent: Opera/9.80 (J2ME/MIDP; Opera Mini/528.16 (iPhone; U; CPU iPhone OS 3.0 like Mac OS X; en-us; compatible; Googlebot/870; U; en) Presto/2.4.15
Fri Jan 29 22:13:57 2016 Host:www.mts.in/
Fri Jan 29 22:13:57 2016 X-Online-Host:www.mts.in/
Fri Jan 29 22:13:57 2016 HTTP proxy returned: 'HTTP/1.0 302 Moved Temporarily'
Fri Jan 29 22:13:57 2016 HTTP proxy returned bad status
Fri Jan 29 22:13:57 2016 TCP/UDP: Closing socket
Fri Jan 29 22:13:57 2016 SIGTERM[soft,init_instance] received, process exiting


have you any solution for openvpn HTTP/1.0 moved in vpnbook config.
