### ISSUE TITLE
installing skype and minecraft on trusty xfce

### ISSUE THREAD

**Issue by EvanDawesome** [dnschneid/crouton#1821]
Hey so me and my friend are total beginners at this whole chromebook linux installation process and I was wondering if someone could walk me through how to install programs like these on xfce. Is there a simple way to do this? I know we have to use terminal or something but there is no clear tutorial I could find online for my problem. Anyway thanks for your time. Sorry for sounding so unintelligent too. :(

**Comment by firestar115** [comment]
I have made a script about installing Minecraft. Copy these lines line-by-line into a terminal to install Minecraft. Answer any prompts with "y", [ENTER], or OK.
```shell
#!/bin/bash
cd ~
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo mkdir /usr/share/Minecraft
cd /usr/share/Minecraft
sudo chown -hR $USER .
chmod -R 775 .
wget https://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.jar
wget http://i.imgur.com/NqFHo.png
cd ~/Desktop/
```
And copy this one all together:
```shell
cat > Minecraft.desktop << "EOF"
[Desktop Entry]
Name=Minecraft
Exec=java -jar /usr/share/Minecraft/Minecraft.jar
Icon=/usr/share/Minecraft/NqFHo.png
Type=Application
Categories=Game;Games;
Comment=
Path=
Terminal=false
StartupNotify=false
EOF
```

**Comment by EvanDawesome** [comment]
thank you! do you know how to get skype on xfce? If so then it would make my day.

**Comment by firestar115** [comment]
Try http://ubuntuhandbook.org/index.php/2014/06/skype-4-3-install-in-ubuntu-1404/ it's unity not xfce but you can get it to work with faneggleing. (prononced fan-negg-ull-ing. Not sure hot to spell :laughing: )

**Comment by EvanDawesome** [comment]
ok lol

**Comment by EvanDawesome** [comment]
hey I was wondering how do i get to the software and updates window

**Comment by EvanDawesome** [comment]
so its not my chromebook that is why I am just responding now because i could not get a hold of my friend. Anyway when she types the command above it is not working here is a picture. 
![problem](https://cloud.githubusercontent.com/assets/12673522/7997341/34709800-0ae0-11e5-9115-401049b714f6.jpg)

**Comment by firestar115** [comment]
That is because you are in crosh.
Go into the actual chroot using sudo startxfce4. You do not need to
enter #!/bin/bash by the way :)

On 6/4/15, EvanDawesome <notifications@github.com> wrote:
> so its not my chromebook that is why I am just responding now because i
> could not get a hold of my friend. Anyway when she types the command above
> it is not working here is a picture.
> ![problem](https://cloud.githubusercontent.com/assets/12673522/7997341/34709800-0ae0-11e5-9115-401049b714f6.jpg)
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1821#issuecomment-109104556


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by EvanDawesome** [comment]
i thought terminal was control alt t?

**Comment by EvanDawesome** [comment]
also for the skype installation it asks to go to software and updates window. where is that?

**Comment by firestar115** [comment]
Are you just reading the instructions are are you doing it yourself? If you
are doing it yourself can you send me a screenshot?

     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by firestar115** [comment]
Yes, CTRL+ALT+T is crosh. Once it loads, type shell. Once that loads, type
sudo startxfce4. Then press CTRL+ALT+T again and the terminal you copy into
will show.

     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by firestar115** [comment]
Here's a better explaination:
```shell
crosh> shell
chronos@localhost / $ sudo startxfce4
```
And once that is loaded, in a terminal type this:
```shell
(trusty)EvanDawesome@localhost ~ $ sudo apt-...
```
and those lines.

**Comment by EvanDawesome** [comment]
ok thanks. Also i am doing it myself. I think I know what to do now. On the skype installation page you sent me it says this." b.) Open “Software & Updates” and enable Canonical partners repository under Other Software tab."How would I get to the software and updates window?

**Comment by EvanDawesome** [comment]
also it may take some time until the person who has the chromebook wakes up so i cant run it now. She will wake up around 3 hours and then I can skype her what to do. This is in case your wondering why I don't try it now and tell you the results.

**Comment by firestar115** [comment]
```shell
sudo apt-get install gedit
gksudo gedit /etc/apt/sources.list
```
Now remove `#` from these entries:
```
# deb http://archive.canonical.com/ubuntu trusty partner
# deb-src http://archive.canonical.com/ubuntu trusty partner
```
Now do step c:
```shell
sudo apt-get update
sudo apt-get install skype
```

**Comment by firestar115** [comment]
So, a rundown here:
```
crosh> shell
chronos@localhost / $ sudo startxfce4
(wait for chroot to load and open terminal)
(trusty)EvanDawesome@localhost ~ $ sudo apt-get install gedit
(press yes when it asks)
(trusty)EvanDawesome@localhost ~ $ gksudo gedit /etc/apt/sources.list
```
Then remove the lines I talked about, then close gedit
```
(trusty)EvanDawesome@localhost ~ $ sudo apt-get update
(trusty)EvanDawesome@localhost ~ $ sudo apt-get install skype
```

**Comment by EvanDawesome** [comment]
so we finally got a chance to try it and when she typed sudo start xfce4 it does not launch. We think it has something to do with her not so good internet connection at time though. This is because we have not changed anything and some things she trys to do using the internet on other devices does not work. Could this be the problem? Here is a picture.
![problem 2](https://cloud.githubusercontent.com/assets/12673522/8047076/c784086c-0df5-11e5-9668-98fedf6915ee.jpg)

**Comment by EvanDawesome** [comment]
We are gonna try it again at my place tomorrow but I just wanted some thoughts about it.

**Comment by EvanDawesome** [comment]
and to reply to your skype post thank you.

**Comment by firestar115** [comment]
Are you typing `sudo startxfce4` or `sudo start xfce4`?

**Comment by EvanDawesome** [comment]
i forget. We are supposed to use the second one right?

**Comment by firestar115** [comment]
No, you use the first one without the space. `start *` is used for processes like chrome os sound, as mentioned in my wiki page (Using JACK for SimpleScreenRecorder)

**Comment by EvanDawesome** [comment]
so we finally got together again to run crouton but I believe we shall have to take the second option you  gave us. I was trying to figure it out though. I know <path> is the path to either the chromebooks or the lixuxs download folder because that is where the crouton is running from. I dont know however what the <to> and <crouton> mean. 

This seems to be download folder for both chrome and linux "/home/chronos/user/Downloads/"

**Comment by firestar115** [comment]
That is correct. If your crouton file is in Downloads, type sudo sh
~/Downloads/crouton -u -n trusty. But starting the chroot you just go
sudo startxfce4.

On 6/13/15, EvanDawesome <notifications@github.com> wrote:
> so we finally got together again to run crouton but I believe we shall have
> to take the second option you  gave us. I was trying to figure it out
> though. I know <path> is the path to either the chromebooks or the lixuxs
> download folder because that is where the crouton is running from. I dont
> know however what the <to> and <crouton> mean.
>
> This seems to be download folder for both chrome and linux
> "/home/chronos/user/Downloads/"
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1821#issuecomment-111755789


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by EvanDawesome** [comment]
ok so that resets the path it runs from?

**Comment by firestar115** [comment]
No, It runs from / if you execute sudo sh ~/Downloads/crouton, which
is what you should do. If you run cd ~/Downloads then sudo sh crouton
it will run from ~/Downloads.

On 6/14/15, EvanDawesome <notifications@github.com> wrote:
> ok so that resets the path it runs from?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1821#issuecomment-111843967


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by EvanDawesome** [comment]
ok I'll tell you after we get a chance to try that. Thanks so far

**Comment by firestar115** [comment]
Check this out! http://www.omgchrome.com/skype-for-web-beta-now-available-worldwide-messaging-works-on-chromebooks/

**Comment by divx118** [comment]
Off topic @firestar115 Only IM no calls for chromebooks.

**Comment by EvanDawesome** [comment]
so she opens crosh and she types shell followed by sudo sh ~/Downloads/crouton and they types sudo startfxce4. Same error though. Why can it not open dev/tty0 (no such file or directory.) Do we need to reinstall xfce4? I hope not.
![image](https://cloud.githubusercontent.com/assets/12673522/8218947/4e281442-14fb-11e5-92cf-eac47cee8f3a.png)

**Comment by firestar115** [comment]
Do sudo sh ~/Downloads/crouton -u -n trusty. The whole thing, not just
up to crouton.

On 6/17/15, EvanDawesome <notifications@github.com> wrote:
> so she opens crosh and she types shell followed by sudo sh
> ~/Downloads/crouton and they types sudo startfxce4. Same error though. Why
> can it not open dev/tty0 (no such file or directory.) Do we need to
> reinstall xfce4? I hope not.
> ![image](https://cloud.githubusercontent.com/assets/12673522/8218947/4e281442-14fb-11e5-92cf-eac47cee8f3a.png)
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1821#issuecomment-112952818


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by EvanDawesome** [comment]
oh.. oops that makes a lot more sense

**Comment by firestar115** [comment]
No problem! The (only) reason I know how to do this is because I've
been programming for 5 years. I don't blame you ;)

On 6/17/15, EvanDawesome <notifications@github.com> wrote:
> oh.. oops that makes a lot more sense
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1821#issuecomment-113027648


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by EvanDawesome** [comment]
now in terminal its asking for a password. what would that be? I remember when we first set up linux on her chromebook it asked in crosh to give a username and password which she is using when it asks for one however when she types it, it replies with command not found. Is there a certain command to enter a password?

**Comment by firestar115** [comment]
When you type in any command as 'sudo' it will ask for the sudo
password which is the password for the primary user when you set up
the chroot. If it says command not found, look it up on google:
"command not found: apt-add-repository" or whatever it is.

On 6/19/15, EvanDawesome <notifications@github.com> wrote:
> now in terminal its asking for a password. what would that be? I remember
> when we first set up linux on her chromebook it asked in crosh to give a
> username and password which she is using when it asks for one however when
> she types it, it replies with command not found. Is there a certain command
> to enter a password?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1821#issuecomment-113667209


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by EvanDawesome** [comment]
So "apt-get" should be a recognized command?

**Comment by firestar115** [comment]
If `sudo apt-get update` does not work, check your spelling. Skype cannot be installed on a chromebook. I'll get a video for you soon on how to install stuff :wink:

**Comment by EvanDawesome** [comment]
ok thanks : )

**Comment by firestar115** [comment]
Off-Topic: You can screenshot with CTRL+F5 for taking pictures of
what's going wrong.

On 6/20/15, EvanDawesome <notifications@github.com> wrote:
> ok thanks : )
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1821#issuecomment-113799707


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by EvanDawesome** [comment]
Does it immediately save it as a file type? Like no pasting in a photo editor?

**Comment by firestar115** [comment]
Yes, it saves as Screenshot-[DATE]-[TIME].png

On 6/21/15, EvanDawesome <notifications@github.com> wrote:
> Does it immediately save it as a file type? Like no pasting in a photo
> editor?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1821#issuecomment-113909693


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by EvanDawesome** [comment]
ok tell me when you have the video.

**Comment by EvanDawesome** [comment]
when should I expect the video on installing skype and minecraft?

**Comment by firestar115** [comment]
In a while because I can not find my camera

**Comment by EvanDawesome** [comment]
ok thanks

**Comment by firestar115** [comment]
Sorry about the video, I can't do it. Just create a chroot
```shell
crosh> shell
chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t xfce -n minecraftAndSkype
```
and paste this into a file named MinecraftSetup.sh in your Downloads folder:
```shell
#!/bin/bash
cd ~
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo mkdir /usr/share/Minecraft
cd /usr/share/Minecraft
sudo chown -hR $USER .
chmod -R 775 .
wget https://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.jar
wget http://i.imgur.com/NqFHo.png
cd ~/Desktop/
cat > Minecraft.desktop << "EOF"
[Desktop Entry]
Name=Minecraft
Exec=java -jar /usr/share/Minecraft/Minecraft.jar
Icon=/usr/share/Minecraft/NqFHo.png
Type=Application
Categories=Game;Games;
Comment=
Path=
Terminal=false
StartupNotify=false
EOF
```
then go into your chroot
```shell
sudo startxfce4 -n minecraftAndSkype
```
and open a terminal to do `chmod 755 ~/Downloads/MinecraftSetup.sh` and then `./Downloads/MinecraftSetup.sh`.

After that, do:
```shell
sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner
sudo apt-get update && sudo apt-get install skype
```
That should be it! If you have any issues, send a picture.

**Comment by firestar115** [comment]
Oh and use `mousepad` instead of `gedit`.

**Comment by EvanDawesome** [comment]
ok I will try this as soon as I can with her.

**Comment by EvanDawesome** [comment]
and what do you mean by mousepad and gedit?

**Comment by firestar115** [comment]
In xfce the default editor is mousepad, gedit is not usually installed.

On 7/23/15, EvanDawesome <notifications@github.com> wrote:
> and what do you mean by mousepad and gedit?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1821#issuecomment-124335579


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by EvanDawesome** [comment]
is there a command to install it?

**Comment by firestar115** [comment]
Sudo apt-get install gedit. Get it? Gedit? Get it? No?

**Comment by EvanDawesome** [comment]
ok thanks. Hopefully I will do this with her this week if she has her computer with her.

**Comment by EvanDawesome** [comment]
My friend kinda bailed on the whole idea so we never got it done. However I would like to thank you a ton for all the help you have given me. :) :+1:

**Comment by jayfeather9477** [comment]
Hey firestar what do you mean when you say copy this one all together I really want to get Minecraft on my chrome book and I want to know how thanks

**Comment by Cringes** [comment]
> Hey firestar what do you mean when you say copy this one all together I really want to get Minecraft on my chrome book and I want to know how thanks

This is an incredibly old thread, requesting close to prevent any future bumps.

**Comment by andysam151** [comment]
i tried to install and run minecraft and everything was working perfectly until i hit play on the launcher screen and it crashed with this crash report:
[00:00:38 INFO]: Launching game
[00:00:38 INFO]: Unpacking natives to /home/andysam151/.minecraft/versions/1.9.4/1.9.4-natives-2772957460612
[00:00:39 INFO]: Launching in /home/andysam151/.minecraft
[00:00:39 INFO]: Half command: /usr/lib/jvm/java-7-openjdk-armhf/jre/bin/java -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Djava.library.path=/home/andysam151/.minecraft/versions/1.9.4/1.9.4-natives-2772957460612 -cp /home/andysam151/.minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar:/home/andysam151/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/home/andysam151/.minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar:/home/andysam151/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/andysam151/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/home/andysam151/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar:/home/andysam151/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/home/andysam151/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/home/andysam151/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/home/andysam151/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/home/andysam151/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/home/andysam151/.minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar:/home/andysam151/.minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar:/home/andysam151/.minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar:/home/andysam151/.minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/andysam151/.minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/home/andysam151/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/home/andysam151/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/home/andysam151/.minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/home/andysam151/.minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar:/home/andysam151/.minecraft/libraries/com/mojang/realms/1.8.19/realms-1.8.19.jar:/home/andysam151/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/andysam151/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/andysam151/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/andysam151/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/andysam151/.minecraft/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar:/home/andysam151/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar:/home/andysam151/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar:/home/andysam151/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar:/home/andysam151/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar:/home/andysam151/.minecraft/versions/1.9.4/1.9.4.jar net.minecraft.client.main.Main
[00:00:39 INFO]: Looking for orphaned versions to clean up...
[00:00:39 INFO]: Looking for old natives & assets to clean up...
[00:01:06 ERROR]: Game ended with bad state (exit code 1)
[00:01:06 INFO]: Ignoring visibility rule and showing launcher due to a game crash
[00:01:06 INFO]: Deleting /home/andysam151/.minecraft/versions/1.9.4/1.9.4-natives-2772957460612
 
please help i love minecraft

**Comment by EvanDawesome** [comment]
Sorry dude I never solved this issue. My friend gave up on it so I lost access to the chrome book and I will never know if it would have worked for me. You should ask Firestarter he is very intelligent in this area.
