### ISSUE TITLE
Select audio output device in volume command

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1827]
`cras_test_client --dump_server_info` dumps the output list, and `cras_test_client --select_output 8:1` selects one (in this case, output ID 8:1).

It would be useful if the volume script provided easy access to this.

It might also be worth checking if there's a DBUS-y way to do that, to avoid needing to use cras_test_client, although realistically the binary will always be there.

@samueldr, any interest? :P

**Comment by dnschneid** [comment]
Ah, [the DBUSy way](https://github.com/dnschneid/crouton/issues/373#issuecomment-26665572).

**Comment by samueldr** [comment]
I do wonder if it wouldn't be a better idea to [write an alsa plugin](https://chromium.googlesource.com/chromiumos/third_party/adhd/+/master/cras/src/alsa_plugin/) that actually implements "proper" alsa-like switching, if there is even a thing like that. The volume script is great because it (now) does not go against the alsa stuff, it embraces and wraps around it. Anything that speaks alsa should be able to do the same thing that the script does.

Implementing those controls at alsa-level, if even possible (I do not know much about alsa) would allow those controls to seep through to the other available alsa tools, and, depending on how pulse works, it might even be possible to allow control through it.

Whatever happens, adding audio output/input selection through the volume script looks like a great idea.

**Comment by dnschneid** [comment]
That would definitely be the ideal solution, and Chromium is always open to patches :)
