### ISSUE TITLE
Unclear when to use -p PREFIX and when to use -c CHROOTS

### ISSUE THREAD

**Issue by j6k4m8** [dnschneid/crouton#1839]
`-c` appears to exist only in the `edit-chroot` flags, and `-p` otherwise. Could the two of these be reducible to one flag (as the name of the `chroots/` directory is always `PREFIX + 'chroots'`) for the sake of command-line friendliness?

**Comment by dragonloverlord** [comment]
I completely agree with j6k4m8 these two options should really be simplified.

**Comment by dnschneid** [comment]
Actually, it `-p` for the installer and `-c` otherwise.  But yes, it's inconsistent.  The main issue is that the installer needs to install bin files, and everything else needs to just operate on chroots, which you could place anywhere.

We could add `-p` to all of the hostbin commands, although mount-chroot and unmount-chroot would need their current usage of -p to be changed.  Not really sure that's useful, because I suspect people think more about where their choots are located rather than what folder contains a "chroots" folder.

Probably more useful would be to add `-c` to the installer, so you can install the bin files to the prefix but put the chroots elsewhere.  This shouldn't be too hard.

**Comment by j6k4m8** [comment]
I think this is mostly solved now?

**Comment by DennisLfromGA** [comment]
Cool, if you're satisfied with the explanation I'll close it now.
