### ISSUE TITLE
feature request: open in host

### ISSUE THREAD

**Issue by hsharrison** [dnschneid/crouton#1860]
I'm not sure if ChromeOS even exposes this kind of thing... but after using Chromebooks for a while I've begun to use Chrome as a general purpose file viewer for certain file types. I have lines like `google-chrome "$file"` in many of my scripts. This works fine in an X11 chroot, but when I'm in a xiwi chroot or just using the terminal in a Secure Shell window, it obviously doesn't work (or not the way I'd like at least, opening a ChromeOS tab rather than opening Chrome within xiwi).

It would be nice to be able to open up a new host ChromeOS tab pointing to some URI. Anyone know if this is possible? I'm picturing something like

```
host-chromeos file.pdf
```

to parallel `host-x11` and `host-dbus`. The path might need to be translated which could messy, but otherwise it seems to be a question of whether or not ChromeOS has a command to open a URI. Obviously extensions can open new tabs...

**Comment by dnschneid** [comment]
There's `croutonurlhandler`, but that won't work for local file urls...

**Comment by hsharrison** [comment]
Ah, interesting, I missed that. What's the problem with local files? Just #1604 or something more difficult? If we can pass `http://` addresses we should be able to pass `file://` addresses, no?

Hmm, I tried playing around with it and I get `Error timeout` every time I use `croutonurlhandler`. Am I doing it wrong? `croutonurlhandler www.google.com`, `croutonurlhandler http://www.google.com` same result.

**Comment by dnschneid** [comment]
There's two parts to the problem.  One is that the extension currently launches urls via the standard window.open command, which can't do file:// or chrome:// URLs, so that will have to be changed to use the tabs API (not so hard).

The bigger issue is that you're trying to access files that are inside the chroot, which is only accessible via root outside the chroot.  So there'd need to be some way to channel the file outside of the chroot.  Maybe playing with temporary bindmounts, or maybe via just starting a [temporary web server](https://github.com/AdamDanischewski/bashttpd).

**Comment by shippy** [comment]
Let's assume that I have a configuration that moves everything to ~Downloads before calling `croutonurlhandler` with a `file://` address, so I sidestep the second issue. What changes would the first part require?

Is it more than changing the call on [`host-ext/crouton/background.js:431`](https://github.com/dnschneid/crouton/blob/master/host-ext/crouton/background.js#L431) to `chrome.tab.create({url: payload})` + adding `"tabs"` to the `permissions` array in `host-ext/crouton/manifest.json`?

Unsure how to test whether that works, otherwise I'd file a PR.

**Comment by dnschneid** [comment]
I think you can use chrome.tab.create without the tabs permission.  If you take the host-ext/crouton directory and dump it into a folder in Downloads, then grab the built nacl module (kiwi.pexe) from your user profile and put it in there too, you should be able to go to about:extensions, disable the crouton extension, enable developer mode, and "load unpacked extension" that folder you just made to try out your changes.

**Comment by shippy** [comment]
Yup, works like a charm - `croutonurlhandler -n file:///home/chronos/user/Downloads/orwell.pdf` opens the file in a new tab, as expected. (In the process, I had to figure out that my user profile is `/home/chronos/user/` and that it is inaccessible from the chroot - all of which might be obvious, but isn't in the documentation, at least as far as I can tell. I'm not sure where it should be.) Filing a PR.

**Comment by dnschneid** [comment]
OK, one half is merged.  Now for the harder half? :)

**Comment by dnschneid** [comment]
BTW, I don't think moving into ~/Downloads is the way to go.  Maybe channel it over the websocket or use the shell-based web server.

**Comment by shippy** [comment]
It's appropriate for my purposes (opening mutt attachments, mostly), but probably not generalizable - certainly not for #1604.

That said, I think *properly handling relative paths in calls* is a different feature than *opening read-only files in ChromeOS from a chroot*. Couldn't this be accomplished by a script (let's call it `croutonfilehandler`, although it can be an `-f` flag on `croutonurlhandler`) that does the following:

1) Copy file to a temporary location defined in `/etc/crouton/shares`
2) Calls `croutonurlhandler` with the proper absolute path.

I'm not entirely sure how `/etc/crouton/shares` works. It loads only when `enterchroot` is invoked, right? But if a folder is set up in `/tmp/` and symlinked to a directory in `/mnt/stateful_partition/crouton/shared`, this should persist throughout the session and clean up afterwards? 

But that seems like a very primitive solution, and probably not what you mean by temporary bindmounts, though. As for temporary web server, it seems a little too complex a solution for the problem?

**Comment by dnschneid** [comment]
> As for temporary web server, it seems a little too complex a solution for the problem?

```
cat - "$pdfpath" <<EOF | nc -l 8080
HTTP/1.1 200 OK
Content-Type: application/pdf

EOF
```

Then navigate to [http://localhost:8080/](http://localhost:8080/) and observe how complex that was :)

**Comment by DennisLfromGA** [comment]
That works but I had to prefix port 8080 with `-p `.
