### ISSUE TITLE
Automounting drives without authentication

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#1908]
In my LXDE Trusty chroot, on every unsuspend I get a password prompt asking to remount the SD card.

I get a similar password prompt whenever I insert a DVD.

What is the proper way to avoid having to authenticate for every drive remount?

**Comment by MeneerJansen** [comment]
You might even consider to turn off auto-mount in your chroot completely. ChromeOS auto-maount too and the two mount can "bite" eactother sometimes (see #1920). What I did in my Ubuntu 14.04 'Trusty' w/ Gnome 3 chroot is:

1. sudo dconf-editor

2. Browse to org.gnome.desktop.media-handling and disable automount (and automount-open)

3. Do that both as root and "yourself".

Good luck! :)

**Comment by tista500** [comment]
@cefn I really don't know how LXDE's file-manager control auto-mounting with udisks2, but on my nautilus (Gnome's file-manager) may pull udisks2 trigger via Gnome's policykit backend.

If it would not be quite different, you should first define the policy for udisks2.

#### 1. Add new policy to `/etc/polkit-1/localauthority/10-vendor.d/10-crouton-udisks2.pkla`
Add this policy into the end of file (This file is policykit setting, so root can read/write only). On Trusty, it may employ systemd 204 and systemd will watch these mount actions. But I don't know why systemd want to interrupt on our suspend cycles without any changes of seat instead of session (seat must be 0 always though)... nautilus actually wants this right to permit the re-mount.
```
[Allow attaching devices to another seat]
Identity=*
Action=org.freedesktop.udisks*.filesystem-mount-other-seat
ResultAny=yes
ResultInactive=yes
ResultActive=yes
```
As you know, "answers yes all" is so bad as security, so you should remove those after finishing tests.

#### 2. Save and Reboot

#### 3. Unmount your SD card manually
Before getting start the testing, you should unmount your card since it still be handled with chrome's media-handler backend. If your card has a block-name as `/dev/mmcblk1p1` (2nd mmc and primary 1st partition), umount like `sudo umount /dev/mmcblk1p1`.

#### 4. mount your SD card via file-manager
I don't know how it does on LXDE's file-manager, but anyway could you mount it without any password confirmations? and if could, please check unmount via file-manager as well. So if your file-manager calls udisks2 to mount it as "user-side-mount", mount-point must be defined by udisks2 (like `/media/USER/UUID`).

#### 5. Go suspend and resume
Unplug AC, and close the lid. Then after a couple of seconds, open it. So could you mount your card without any password confirmations (basically suspend hooks unmount automatically due to power-down the card socket)?

Regards.
