### ISSUE TITLE
utopic black screen when switching back to chrome os

### ISSUE THREAD

**Issue by SteveAdams86** [dnschneid/crouton#1914]
Hi,

I realise support for utopic is experimental but I came across a bug where switch back to chrome os using  ctrl alt left i get stuck on a black screen with nothing showing or unable to do anything but hold power to force a reboot. I am  using an acer c720 with i3 4gb ram. My chroot first started out as trusty and then using the ubuntu os its self i used the terminal to update to 14.10 (utopic). I am using the x11 version i beleive its called to be able to use hardware acceleration for games and better performance.

I also noticed i couldnt get ubuntu running using sudo startutopic after i had updated to utopic, how ever it would start using sudo start unity, Im not so bothered by this but just putting it out there. 

What i am after if possible it either a way to get back to trusty from utopic without deleting my current set up and starting over, or a way to fix the black screen when i am finished using ubuntu?

Many thanks,
Steve

**Comment by tista500** [comment]
@SteveAdams86 Yes, I had a similar issue on Utopic (on my Asus C200 BayTrail X11/freon).

So let me know,
>  where switch back to chrome os using ctrl alt left i get stuck on a black screen with nothing showing or unable to do anything but hold power to force a reboot

Isn't that "Ctrl + Alt + Shift + F1 (Left-Arrow)?

> My chroot first started out as trusty and then using the ubuntu os its self i used the terminal to update to 14.10 (utopic).

After upgrading to Utopic inside your chroot, then you did updating crouton as well?

> I also noticed i couldnt get ubuntu running using sudo startutopic after i had updated to utopic

Isn't it "sudo startunity"?

And I think it's quite unreal to downgrade your utopic to trusty... Unfortunately I suggest that you should backup your works to somewhere and re-install trusty, even if you could get better graphic performances with utopic (I don't know really it is though...). Since Utopic and newer release has newer systemd 208 or higher so you would get much more "downsides" with chroot environment.

Regards.

**Comment by SteveAdams86** [comment]
Thanks Tista for your reply! In the end I just deleted the chroot and reinstalled good old trusty! It works perfectly now thanks. 

This can be marked as closed I guess
