### ISSUE TITLE
Can I access files in chroot from chromeos?

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1932]
I want to try saving source files from the chrome dev tools (inspector) in chromeos.  I need to specify a directory in my chroot.  I tried putting a symlink in Downloads but that doesn't show up in the chromeos file picker.

Any ideas?

**Comment by mark-hahn** [comment]
I had used a symlink pointing to the path `/root/test` which couldn't work because the symlink would be interpreted in the chromeos context.  So then I changed the symlink to point to `/mnt/stateful_partition/crouton/chroots/myChroot/root/test` and it still didn't work.

**Comment by DennisLfromGA** [comment]
@mark-hahn - Maybe the wiki '[Sharing files and folders between ChromeOS and your chroot](https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders)' might be of help; `/etc/crouton/shares` is probably not widely used but is a built-in feature of crouton.

**Comment by mark-hahn** [comment]
Thanks.  I should have known to check out the wiki.

**Comment by mark-hahn** [comment]
OK, for future reference I got this to work 

- follow [wiki instructions](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton) to create SSH server in your chroot
- open chromeos files dialog
- add sftp service to files dialog (see `+ Add new services`)
- Use sftp service to add localhost

Now you can access any file in your chroot from the chromeos files dialog

**Comment by DennisLfromGA** [comment]
@mark-hahn - Thanx for the feedback and a solution, it works great!

**Comment by thinknervous** [comment]
I have tried this and when I mount the chroot I get the following:
"WARNING: /etc/rc.local failed with code 127"
Here are the current contents of my rc.local:

#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

mkdir -p -m0755 /var/run/sshd
/usr/sbin/sshd
/sbin/iptables -I INPUT -p tcp --dport 22 -j ACCEPT

exit 0

I've looked around for help on this and tried rearranging the lines and using different ports, all to no avail. I'm using 14.04.5 and I'm admittedly very much an Ubuntu n00b.

Help??

**Comment by DennisLfromGA** [comment]
@the-pete,

Run each of the three command strings as root in your chroot and see if you get any failure messages.
That might at least tell you which more (or more) is failing.

*Hope this helps,*
-**DennisL**

**Comment by thinknervous** [comment]
Hmm... I've gotten rid of the error message by changing it to this:

mkdir -p -m0755 /var/run/sshd 
mkdir -p -m0755 /usr/sbin/sshd
/sbin/iptables -I INPUT -p tcp --dport 22 -j ACCEPT

Previously /usr/sbin/sshd/ yielded "command not found."

The error also goes away if I combine the first two lines:
mkdir -p -m0755 /var/run/sshd /usr/sbin/sshd

Somewhere along in this process I had a server automatically show up and autopopulate the SFTP server service in Chrome OS, but it still failed to connect [connect() failed -1 111]. Now that won't show up anymore either. Not sure how I got it to even work that much.

**Comment by DennisLfromGA** [comment]
@thinknervous,

> mkdir -p -m0755 /usr/sbin/sshd

That will fail or break things since `/usr/sbin/sshd` is the ssh server daemon you're trying to launch.
It's an executable and not a directory. If it tells you 'command not found' then make sure you've installed the ssh server first. 

Also before starting the ssh server I would run the `iptables` commands first to ensure the ports that need to be open are open.

If you haven't already, please read @mark-hahn's suggestions above and refer to this wiki for more details: ['Running servers in crouton'](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton)

*Hope this helps,*
-**DennisL**
