### ISSUE TITLE
Gnome 3.16 on Trusty?

### ISSUE THREAD

**Issue by seanhig** [dnschneid/crouton#1934]
I upgrade Gnome on Trusty to 3.16, and for the most part it is fine... except when it comes to updates.

I followed the instructions for installing Gnome 3.16 on Trusty, and added the PPA... and it works just fine with crouton... but now when I try to run crouton -u it fails every time.  The only way I can complete an upgrade is to remove the "gnome" entry from the targets file in /etc/crouton... but then I can't startgnome anymore from outside the chroot.  And I can't get it to launch startgnome -X xiwi... it only works in tab mode, or XOrg mode.

Is there a way I can update my chroot that uses Gnome 3.16?

Thanks.

**Comment by tista500** [comment]
@seanhig How did you upgrade gnome 3.16 on Trusty? In general, Trusty employs systemd 204, but most of Gnome 3.16 core packages should depend on systemd 217 or higher. And Trusty didn't have `libsystemd0` package as well. I imagine that you would try some PPAs to upgrade Gnome packages, or rebuilt lots of packages against systemd 204, however, you'd better to introduce your upgrading method first. And if you had some problems to update crouton, you should show logs what was remained on crosh window when you failed to update.

Regards.

**Comment by seanhig** [comment]
Thank you for the considered response.  I didn't realize what I had done was so obscure.

I basically did this to install Gnome 3.16:
(from: http://sourcedigit.com/15453-download-and-install-gnome-3-16-on-ubuntu-14-1014-04-systems)

    sudo add-apt-repository ppa:gnome3-team/gnome3-staging
    sudo add-apt-repository ppa:gnome3-team/gnome3
    sudo apt-get update
    sudo apt-get dist-upgrade

I don't use a lot of gnome apps... just the terminal really... and sublime.  I upgraded mostly for the shell.

The crouton update fails trying to upgrade the gnome target (no surprise):

    gnome-themes-standard is already the newest version.
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     gnome-session-fallback : Depends: gnome-session-flashback but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.
    Failed to complete chroot setup.
    Unmounting /mnt/stateful_partition/crouton/chroots/trusty-next...

If I remove the gnome target manually from the targets file, the update will work of course.  But I will lose the startgnome script in crosh.  I could not figure if there was a way to startgnome in xiwi from within the chroot. 

I suspected the issues are with older, supported gnome dependencies in conflict with what is installed for 3.16.  No idea how to fix that with crouton.  Would be nice if I could turn off the gnome target upgrade without losing the startgnome script in the crosh.  I don't think I need crouton to upgrade my gnome if I don't want it to :)

**Comment by tista500** [comment]
@seanhig Ah, I see. you mean Gnome 3.12. Please see contents of PPA: https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging?field.series_filter=trusty And Gnome3-staging PPA is to be placed as "tests and fixing bugs for next release cycle of Ubuntu Gnome".

Then in your log:
```
The following packages have unmet dependencies:
 gnome-session-fallback : Depends: gnome-session-flashback but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
It describes everything.

###### Reason.1
Trusty's current `gnome-session-fallback` 3.8 has `gnome-session-flashback`, but flashback package would break dependencies against 3.12 Gnome environment so, apt would stop installing.

###### Reason.2
That PPA didn't have any gnome-session package which should be merged into 3.12 Gnome environment so, you couldn't get newer gnome-session-flashback anywhere.

###### Best way to fix
The most finest way is that you build all of gnome-session packages from source what was pulled form  Utopic's main repository. Could you do it yourself manually?

###### Better way to fix
Download some deb packages to solve your dependencies from Utopic's main repo. I won't suggest it since this method would lead new dependency problems to be fixed by hand via both dpkg and apt.

###### Temporal way to finish installation
The easy (means dirty) hack may pass through installation issue by editing installer.

So which do you want to do? 

Regards.

**Comment by seanhig** [comment]
Thank you for such a detailed explanation.  Funny that I never verified the version of Gnome.

I decided Trusty was too old for all of that trouble, so after reading a few other posts here, I decided to upgrade that snapshot to utopic and then vivid and see what happened.  Much to my surprised, this worked.

After the upgrades, I tried the crouton upgrade again, and failed where it does for everyone in vivid #1706, and so I followed your prepare.sh instructions.  Although I was not able to complete the crouton upgrade (another error associated with xorg video drivers, perhaps related to an intel driver I installed in trusty)... but Xiwi and Xorg are both working fine again.  The important stuff seemed to complete.  

So for now I shall quit while I am ahead, with 3.14.4, and go back to work :)

**Comment by tista500** [comment]
OK. I'm glad you could come back to Gnome desktop. :)

We still have a lot of things to solve but at least Gnome Shell 3.14 would invite us to the shell out of the box even if some components were "half-baked"...

Regards.

** P.S.**
If you'd finished to ask, close this issue please. And Vivid problems would be discussed on #1706 thread as well.
