### ISSUE TITLE
Most Function Keys Not Working As "F" Keys.

### ISSUE THREAD

**Issue by ianbarton** [dnschneid/crouton#1944]
I have installed Trusty with Xfce4 and xiwi, but not the keyboard target. Since my main use is Emacs, I want the function keys to work as traditional "F" keys. The first three keys "<-, -> and refresh" work correctly as F1-F3. However, all the rest work as Chromebook keys. If I run xmodmap -pke in a terminal,  the keys appear to be mapped as "F" keys e.g.

```
keycode  73 = F8 NoSymbol F8
```

My /etc/default/keyboard contains:

```
XKBMODEL="pc105"
XKBLAYOUT="gb"
XKBVARIANT=""
XKBOPTIONS=""
```

Is there anyway to fix this?

**Comment by ianbarton** [comment]
Update. It seems that the Search key plus the F keys work. However, I have a duplicated F8 key (no F7). I'll double check to make sure that this isn't something in my setup.

**Comment by darcyparker** [comment]
I have a similar/same issue with a Debian stretch chroot and I do have the `keyboard` target installed.  I am not able to use the Function keys using the `search` key to trigger F keys.  For example F2 does not work in `xfce4-terminal` when I am running it in a `xiwi` window.

`F11` seems to be captured by the crouton integration extension because it toggles showing me the different X windows I have open.  Based on this, I wonder if the crouton integration extension is consuming the F keys?

**Comment by stsquad** [comment]
This used to work for me on my UK Pixel but it seems to have regressed recently. I currently get XF86ApplicationRight and XF86Display keys for my local Emacs running standalone in an XIWI window. My remote Emacs sessions getting nothing.
