### ISSUE TITLE
Changing internal resolution on Toshiba CB2

### ISSUE THREAD

**Issue by cactuar** [dnschneid/crouton#1966]
Hello,
first of all thank you for your great work which led me to buy a Toshiba Chromebook 2 as a portable emacs machine :-)
There is just a little issue I cannot fix: setting ChromeOS internal resolution to 1536x846 makes fonts inside xiwi applications look blurry, as if X used that resolution instead of its native resolution (xrandr report it to be 1536x846).  I tried to change it with xrandr or with setres, but nothing happens (it seems that the framebuffer dimension gets bigger, but not its actual resolution).
Am I missing something (1536x846 should be a virtual resolution, so the actual screen resolution is always 1920x1080, is it right?) or is this how it is supposed to work?

Thank you again

**Comment by tista500** [comment]
@cactuar I'm not sure what you want to do for display resolution though, try this inside the chroot:
```
xrandr --output eDP1 --scale 1x1 --fb 1920x1080 --panning 1920x1080
```
But I don't use Xiwi, so it might be different from X11/freon in various options.

In general, Modern Desktop Environments like Gnome, Unity, Kdesktop, and so, we won't suggest such X11 server-side-scaling for the purpose of "font-scaling". since these DEs have client-side "font-scaling" and "HiDPI-scaling" techniques already. So you should use them to get better readability on High resolution displays.

Regards.

**Comment by cactuar** [comment]
Hello, thank you very much for your answer! I tried with (changing my output name)

```bash
xrandr --output default --scale 1x1 --fb 1920x1080 --panning 1920x1080
```

but an error occurs:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  26 (RRSetCrtcTransform)
  Value in failed request:  0x3f
  Serial number of failed request:  21
  Current serial number in output stream:  22
```

Concerning the last part of your message, I don't think I understood it well, sorry. For what I know (and I may be wrong) Chrome OS upscale or downscale its internal resolution with CTRL+ALT+(+/-) while its real resolution stays the same: while ui size changes, font rendering is smooth and clear. I would expect xiwi to always use 1920x1080 (my screen native resolution), while it reports 15366x846 (the internal resolution) and fonts are a little blurry.

Thanks again

**Comment by tista500** [comment]
@cactuar 
> I tried with (changing my output name)
> ```
> xrandr --output default --scale 1x1 --fb 1920x1080 --panning 1920x1080
> ```

`--output` flag sets "physical connected devices" or "Virtual device". Is "default" listed in the output of `xrandr`? For example, Intel i915 and modern graphic chipset has usually something like `LVDS1, eDP1, SDVO, HDMI1, VGA1 and VIRTUAL1` and so. The "default" was the primary output device of Xiwi?

Regards.

**Comment by cactuar** [comment]
This is the output of xrandr (when internal res is 1920x1080 and xiwi is fullscreen):
```
Screen 0: minimum 256 x 256, current 1920 x 1080, maximum 32767 x 32767
default connected 1920x1080+0+0 270mm x 203mm
   1024x768       85.0 +   75.0     70.1     60.0  
   2048x1536      85.0     75.0     60.0  
   1920x1440      85.0     75.0     60.0  
   1856x1392      75.0     60.0  
   1792x1344      75.0     60.0  
   1600x1200      85.0     75.0     70.0     65.0     60.0  
   1680x1050      84.9     74.9     69.9     60.0  
   1600x1024      60.2  
   1400x1050      85.0     74.8     70.0     60.0  
   1280x1024      85.0     75.0     60.0  
   1440x900       59.9  
   1280x960       85.0     60.0  
   1360x768       59.8  
   1152x864      100.0     85.1     85.0     75.0     75.0     70.0     60.0  
   832x624        74.6  
   800x600        85.1     72.2     75.0     60.3     56.2  
   640x480        85.0     72.8     75.0     59.9  
   720x400        85.0  
   640x400        85.1  
   640x350        85.1  
   kiwi_1920x1080_60   59.8* 
```

Do you think there is some problem with my X11 configuration?
Thank you

**Comment by tista500** [comment]
I can't understand the result since a native mode which has 1920x1080 is named `kiwi_1920x1080_60`, and the others are 4:3 aspects mixed... :(

So give it a try:
```
xrandr --output default --scale 1x1 --mode kiwi_1920x1080_60
```

Regards.

**Comment by cactuar** [comment]
It's really strange, it tells me:
```
xrandr: cannot find mode kiwi_1920x1080_60
```

**Comment by tista500** [comment]
Sorry for my delayed response. Because I've added Xiwi into my crouton.

And I can confirm your issue properly.
Basically, `kiwi_xx_x_xx_xx` mode seems to be changed dynamically due to follow the changes of upstream window-manager (and ChromeOS's display-server as well). And ChromeOS seems to handle such "change resolution with Ctrl & -/+" by damned "old-style" X11 handler like "xrandr" so, on my Asus C200, the rendering quality on both GUI and fonts were NOT quite different between ChromeOS and gnome-shell/Xiwi, means both of them seemed "blurry", "poor" and "ugly" when we changed resolution on ChromeOS. Anyway I think we should not change resolution of Xiwi intentionally...

The crouton devs might be able to fix this issue, but I think we'd better to post the feature-request to upstream that Chrome should fork the HiDPI scaling feature from Gnome3. The ChromeOS's scaling feature seemed quite poor obviously.

Finally I now haven't any clue to solve this...

Regards.

**Comment by cactuar** [comment]
Thank you very much for your patience :-)
Let's hope someone from the Crouton team will take a look at this issue.

Thank you again

**Comment by dnschneid** [comment]
Unfortunately, it's really hard for crouton to determine the real resolution of the screen.  Chromium has like 3 levels of scaling and only reports two variables (I think).  @drinkcat tried to improve this for a while and concluded that it's easier to get a PhD (and then went and did that).

I'll keep it open until Dr. Inkcat confirms that it's infeasable to fix.

**Comment by cactuar** [comment]
Thank you very much for your answer!

**Comment by drinkcat** [comment]
Yeah. 1.25 scaling is tricky. If we switch to wayland interface, I think we might be able to get a better experience (e.g. get the crouton UI to be displayed at 1920x1080 even though the "fake" resolution is 1536x864).

Closing this, I don't think we can do much in xiwi.

**Comment by drinkcat** [comment]
(actually, let's leave this open...)

**Comment by drinkcat** [comment]
It looks like pressing HiDPI in the extension actually does the right thing: the crouton UI shows up at 1920x1080, without scaling, and text looks sharp.

We should make HiDPI the default in the extension, at least for 1.25 scale devices.
