### ISSUE TITLE
Can't download Crouton on my Chromebook even though I already put it in developer mode.

### ISSUE THREAD

**Issue by Rlop1** [dnschneid/crouton#1969]
I can't download Crouton. I put it in developer mode and tried to download but it didn't work. I even made sure it was in developers mode by doing the process a second time. Which just brought me back to the first screen like before. Meaning I was in developers mode the first time I tried. But it still won't download. 
Btw, I have a Chromebook 14.

**Comment by tonyxue** [comment]
What do you mean by 'cannot download'?
Did you mean there is no response after clicking ``` https://goo.gl/fd3zc```? Or no response after running ```sudo sh ~/Downloads/crouton```?

**Comment by Rlop1** [comment]
Like I press it and it says "this file type is not supported".

**Comment by dnschneid** [comment]
Yeah, you can't run it by clicking the download in the browser; you have to run it from the shell.  Please see the README or any of the tutorials online.

**Comment by XXLILNASTY420** [comment]
so i would like to put khali linux on my chromebook. i have downloaded  the crouton file and all the nescesarry items needed befor putting it in crosh. once i have typed in shell and im in my dev command, i typed in sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce. but once i hit enter it says it cant open
home/chronos/user/downloads/crouton. how do i bypass this.

**Comment by DennisLfromGA** [comment]
@XXLILNASTY420,

Your command: 
- `sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce`

should work if typed in correctly, just make sure 'Downloads' is capitilized and you have a current copy of `crouton` in `~/Downloads`.

This issue was closed a couple of years ago....
If you can't get it working I'll borrow a quote from the author:
"Please see the README or any of the tutorials online."

*Hope this helps,*
-**DennisLfromGA**

**Comment by hdew12354** [comment]
you guys really are life-savers, you know that right?
