### ISSUE TITLE
Cannot install crouton 

### ISSUE THREAD

**Issue by helpm3** [dnschneid/crouton#2028]
After downloading a new version of crouton and trying to install i get the following:
sudo sh -e ~/Downloads/crouton kde

Downloading latest crouton installer...
######################################################################## 100.0%
Your version of Chromium OS is extraordinarily old.
If there are updates pending, please reboot and try again.
Otherwise, you may not be getting automatic updates, in which case you should
post your update_engine.log from chrome://system to http://crbug.com/296768 and
restore your device using a recovery USB: https://goo.gl/AZ74hj

What do I have to do to resolve this issue?

**Comment by DennisLfromGA** [comment]
The error may be due to using incorrect syntax, you need to prefix any targets with a '-t', like:
`sudo sh ~/Downloads/crouton -t kde`

You may also want to specify other parameters like '-r trusty -t kde,keyboard,xiwi', etc.
You can get a list of releases using:
`sudo sh ~/Downloads/crouton -r list`
You can get a list of targets using:
`sudo sh ~/Downloads/crouton -t list`

Take a look at the [README](https://github.com/dnschneid/crouton/blob/master/README.md) for help with this and other possibilities.

**Comment by drinkcat** [comment]
@helpm3 : Can you post the output of `cat /etc/lsb-release` outside of the chroot?
