### ISSUE TITLE
Run a *working* ssh server inside chroot

### ISSUE THREAD

**Issue by SnarkBoojum** [dnschneid/crouton#203]
I would like to be able to login remotely in my chroot ; apparently it isn't just a case of installing the ssh server...

**Comment by zopefiend** [comment]
After following the instructions above, as well as adding host information on each chroot's ~.ssh/config file,  I continue to see several errors, for example ...

With three chroots (chroot1, chroot2, chroot3), when I attempt, from chroot1:

ssh user1@chroot2 -p 2222
Name or service not known

ssh user1@chroot2
connect to localhost port 2222: Connection refused

Please advise re. what subtle bit of config is missing?

**Comment by zopefiend** [comment]
BTW, this appears to succeed:

ssh user1@127.0.2.1

It asks for password, then proceeds to open an ssh terminal session ... on whichever chroot was mounted first, regardless of the unique IP address assigned to a named chroot, and the unique ssh port # set for the corresponding chroot.

**Comment by zopefiend** [comment]
Got it. It turns out that even though the instructions here:

https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton

explain how to open a port # (for iptables), that IF you decide to use a non-standard port #,, as many suggest, and is required in this case, for each chroot to have a dedicated port #,  then you also have to edit the file:

 /etc/ssh/sshd_config

so that when sshd runs, it know what port to listen on. 

It would be helpful if there were an sshd command line option to set the port #, in sync with the iptables -dport option. If that exists, TFMs being what they are, if would likely take a PhD research project to dig it out.
