### ISSUE TITLE
Pixel Sudden Death 

### ISSUE THREAD

**Issue by vladimirvivien** [dnschneid/crouton#2048]
This morning my pixel died while I was in the middle of using it with the familiar "Chrome OS is missing or damaged."  I followed the recovery steps, but the machine refused to boot.

So my question to the community: can crouton directly (or via using certain chroot features) damage the chromeos kernel?  Have you guys heard of such situations where crouton causes kernel damage ?  Are there certain things (such as fiddling with kernel) that are sure ways to kill the OS that others should be aware of?

I like crouton, and think it's a great utility.  It  was the ONLY reason I actually bought a chromebook to run Linux. So  If anyone can shed light, that would be helpful.  Thanks.

**Comment by millserd** [comment]
I have had this same issue...0x5b no bootable kernel found on disk. Official recovery options do not work. RMA was the only solution offered by tech support. I am on my second pixel and just 2 days ago I received this same error. I bought the pixel for the same reasons (to run crouton) and would love a solution as well.

**Comment by tista500** [comment]
Greetings,

Unfortunately I haven't ever seen such situations on both Asus C200 and Acer C720... :(

I'm not sure whether you guys are talking about initrd (and/or vmlinuz) or not though, in general, crouton never wants to attack those contents as long as you force to do deep hack (I suppose).

> Official recovery options do not work

It seems to break EFI/BIOS and/or firmware. But we usually need to pull the "white screw" out from motherboard to unlock the firmware protection in most of chromebooks. Might this issue be related to the hardware specific (1st-gen pixel) problem?

I'm sorry I don't have any solutions and I hope someone could have a clear answer.

Regards.

**Comment by vladimirvivien** [comment]
@tista500 I have (had) a pixel 2, second gen released earlier this year.  As @millserd this affects the kernel.  Searching the web, this seems to be a common things with chromebooks that are not running croutons.  I was wondering if anyone else has ran into that error while using crouton.

**Comment by tista500** [comment]
@vladimirvivien,

> As @millserd this affects the kernel.

Ah. My previous post meat the 'kernel' as well:

 > I'm not sure whether you guys are talking about initrd (and/or vmlinuz) or not though

Initrd is the compressed minimum file-system used until vmlinux have reached to mount the internal primary storage. And vmlinuz is the compressed linux kernel core to be executabe. After chainloading to internal storage, /lib/modues directory gets meaning.

And then again:

> Official recovery options do not work

This words, for me, sounds like "If that happened, we could not get to boot the Factory Recovery USB Media anymore". If so, the problem should be focued to EFI and/or frimware (much more, /boot directory,too ?) since that USB doesn't concern how damage had been inside the internal sotrage. AFAIK it always wipes out (cean-ups) all of data in internal storage.

Anyway this issue needs guru, right? :smiley: 

Regards.

P.S sorry for my english...

**Comment by vladimirvivien** [comment]
@tista500 No problem.
Yes, the issue could be hardware releated.  The machine does not boot at all.  Even after following recovery instructions, it still doesnt.  It could very well be a defect with the hardware. 

I did modified kernel modules to add headers to support VirtualBox.  That is why I was wondering if this could be related to changes I made while using crouton or crouton itself.  I wanted to hear the community's take on this.  Thanks for sharing.

**Comment by divx118** [comment]
Well loading kernel modules for virtualbox shouldn't "brick" your chromebook. What could get a Chrome OS is missing or damaged: messing with the partitions on your ssd flashing a wrong kernel or make the rootfs rw and mess that up. Also ssd hardware failure could be a cause. However if you don't have a hardware damaged ssd it should be fairly simple to get your chromebook up and running with a USB recovery. If you don't have a usb recovery you can make one on a linux computer see https://support.google.com/chromebook/answer/1080595?hl=en Under "Troubleshoot Chromebook recovery" click "I'd like to recover from a Linux computer." and follow the instructions there.
Then boot into recovery and use the usb stick you created.

**Comment by vladimirvivien** [comment]
@divx118 I suspect an SSD hardware failure. I tried recovery with usb and sd card (created from different machines MacOs and another chromebook) neither worked. I talked to Google and they were cool about it (I wonder if they know about defective hardware issues).

**Comment by divx118** [comment]
@vladimirvivien Yep probably is. Since it happened in the middle of using. You don't have to be concerned it is crouton or virtualbox kernel modules related, because they don't mess with your chromeos. The only way I know it can happen is what I mentioned above. However that wouldn't need to be done in a chroot, you could also do those things in a crosh shell in dev mode.

**Comment by vladimirvivien** [comment]
@divx118 thanks for pointing this out.

**Comment by WiWa** [comment]
Just happened to me 5 hours ago in my chroot :cry:

**Comment by millserd** [comment]
I'm starting to believe enabling dev mode which gives full root access my be part of the main problem...

**Comment by vladimirvivien** [comment]
This is sad.  Looks like an expensive experiment gone wrong.  Gonna have to get a different machine for my day to day work.  Was really looking forward to using the pixel for a long time.  it's nice machine.

**Comment by vladimirvivien** [comment]
By the way, this Google + page has some more stories about this issue https://plus.google.com/communities/115469536385756566576/s/0x5b%20no%20bootable%20kernel%20found%20on%20disk

**Comment by vladimirvivien** [comment]
According to comments from that page (see above), the common thread in all comments (except 1):
- crouton + kernel headers updates + virtual box
Which I did no my machine couple of days before it died.
Can anyone confirm here as well ?

**Comment by GrandZinck** [comment]
My Pixel (2015) died as well with 0x5b no bootable kernel found on disk. The death was correlated with updating crouton with a fix for the black screen issue when switching from Chrome OS to a trusty instance using xorg. This may well be a problem with Pixels in general but thought I'd post it here just to add a datapoint.

**Comment by MattElmer** [comment]
I am having the same issue with my HP 14.  I installed the virtualbox headers as well.  This is after having the SSD replaced by HP due to an unrecoverable "0x5a No bootable storage device in system."  I thought that was a simple hardware failure, but now I'm not so sure.

**Comment by vladimirvivien** [comment]
I got a new chromebook RMA'd since Google think its hardware failure.  I am thinking about running chroot of the SSD.  If you've done that successfully let me know, though i am concerned about speed.

**Comment by Seablade** [comment]
For the record, currently on my third pixel for this reason as well.  I haven't installed Crouton on this one, and thus far has lasted longer than either of the other two, but likewise part of why I got it was so that I could run Crouton/Linux/VirtualBox/Vagrant for development work.  Again not sure if Crouton had anything to do with it, or if it was simply a hardware issue, but it adds another data point I suppose.

**Comment by seanhig** [comment]
This just happened to my 2015 Pixel LS as well.  Recovery doesn't work, same errors.  Google largely not very helpful... had to go back to my macbook pro... now I'm wondering why I left.  Apple is annoying, but at least they can build a reliable OS and hardware.  Google seems capable of neither.  ChromeOS stable is BETA, at best. Every update breaks something.  Right now CRD doesn't work on the pixel... the one machine Google actually makes... it is pathetic. And I've never had a laptop this expensive die in under 8 months.  The ChromeOS experiment is a failure.  Sloppy and unreliable.  Pixel 2 is a fail.

**Comment by BraadMartin** [comment]
Hate to say it, but this just happened to my 2015 Pixel LS also. It was about 3.5 months old. Google Support was excellent with me and a replacement is on the way, but what a shame! Crouton on the Pixel for dev work is such a perfect combo. Hopefully the replacement device holds up.

**Comment by DennisLfromGA** [comment]
I don't have a Pixel 1 or 2 (bummer) but I'm wondering if anyone here has tried to boot the previously installed OS on the alternate kernel/root pair by  changing the kernel priority:

`cgpt prioritize /dev/sda -i 2/4` [YMMV] 

You could also do the newer '[Powerwash and Revert](http://liliputing.com/2014/11/chrome-os-lets-change-mind-os-upgrades.html)' operation but that's more drastic since it'll wipe all user data.

I think either method should work and allow an upgrade -

goto `chrome://help` then click the '*Check for and apply updates*' button

that would overwrite the bad kernel.

I know I've done this when things got borked occasionally.

The difficult part is getting access to a terminal shell, I've sometimes booted an external OS (via Ctrl+L) and then run the 'cgpt' command on the affected drive.

Just throwing this out there as maybe another way out of this situation.
I'd be glad to here if this works or not for anyone...

**Comment by Seablade** [comment]
@DennisLfromGA Problem is, I don't think that is possible in the problem mentioned, as you can't even powerwash at this point from the SSD failure.  Even doing a restore from external drive fails as it can't write to the internal by that point, so pretty sure by the same logic changing the boot partition on it will not work.

I remember I have booted an external OS though, and gotten lots of fun messages about drive failure on dmesg one time, I think it was on the first failure I had.

As an update for the thread, I have installed crouton on this guy, and while I have installed VirtualBox, I haven't used it as much as instead of using that for Vagrant I am doing some dev work using the AWS backend instead.  All that being said so far this machine has lasted me about 5 months give or take IIRC.  I think my last swap was in August.

**Comment by DennisLfromGA** [comment]
@Seablade - I think the alternate kernel/root partition would still be intact and viable - might be worth a try at least.

**Comment by harryshawk** [comment]
Been using Crouton for a few years.. no problem. but I had the Sudden Death a few days ago.. 

Was in ChromeOS, X closed a tab, and that was it.. screen went to Black, and I tried to force restart.. ended up with 00x5b error. Note you can press the TAB key to see the full error. 

Upon trying the recovery  option with several diff. brands. of USB Sticks and SD cards it failed.. You can do F2 or F3 to see error report and log file.. 

This is from my log.. it seems it can't mount the file system on the stick... 
![samus error log can not mount file system](https://user-images.githubusercontent.com/25712065/34359863-7f24f578-ea29-11e7-915c-1e62ee68203a.jpg)

**Comment by DennisLfromGA** [comment]
@harryshawk,

The '**0x5b**' error is a bad one, I had it myself once on my Acer C710.
We run into it occasionally on the Chromebook Central forum, [here's one such comment](https://productforums.google.com/d/msg/chromebook-central/1Hqrk95bYpo/rhONsn5cBgAJ)
 that might help -

> Ajit: this error: "recovery_reason: 0X5b No bootable kernel found on disk" usually means your SSD is faulty and needs to be replaced.  

> *You could try up to 25 __hard resets__ in a row*:
https://support.google.com/chromebook/answer/3227606?hl=en  

> But that only rarely fixes the problem.  

> *__Some SSD's are replaceable, some SSD's are not.__ You will have to use your Chromebook model # to find out if the SSD can be replaced, otherwise, the entire motherboard will need to be replaced.*

I know it may sound a little silly but it did work for me so I can attest to it.*

*Hope this helps,*
-**DennisLfromGA**
