### ISSUE TITLE
Add destination size test

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2108]
If the partition size is less than 4 GB, spit out a warning.  If free space is less than 2GB, spit out a warning.

Can determine whether the former is due to a Chrubuntu install by using 
`mount -o ro rootfs-c /tmp/somewhere` and grepping /tmp/somewhere/etc/lsb-release.

**Comment by DennisLfromGA** [comment]
RE: ChrUbuntu

I have ChrUbuntu installed (using partitions 6 & 7) on my Acer C710 and my `/etc/lsb-release` contains:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
```
So maybe grepping for 'Ubuntu' might work.

What also might work is to check if the size(s) of partitions 6 &/or 7 are larger than 1, similar to what the ChrUbuntu install scripts do. That way, no matter what is installed, it will flag that these partitions are custom sizes and not default. This is the case on my HP Chromebook 14 where I have one of the hugegreenbug's distros installed.

**Comment by DennisLfromGA** [comment]
> If the partition size is less than 4 GB, spit out a warning. If free space is less than 2GB, spit out a warning.

I was wondering what partition is important here, is it the stateful_partition or the partition the chroot(s) is on - if they're different? 
I have what I guess are unusual systems in that they have a (crispy) CROUTON partiton where all my chroots are installed, among other things. I guess if you use $CHROOTS then it'll check the right partition wherever it is.

Anyway, I think something like the following might work -
```
    PARTITION="/" # For STATEFUL_PARTITION 
-or-
    PARTITION="$CHROOTS" # For CHROOTS PARTITION

    SIZE_MAX=4
    AVAIL_MAX=2
    SIZE=$(df -m $PARTITION | awk 'FNR == 2 {print $2}')
    AVAIL=$(df -m $PARTITION | awk 'FNR == 2 {print $4}')

    [ "$SIZE" -gt "$SIZE_MAX" ] || \
    echo "- Your partition is rather small ($(($SIZE / 1000))GB - usually ${SIZE_MAX}GB or more is needed..."
    [ "$AVAIL" -gt "$AVAIL_MAX" ] || \
    echo "- Your available space is rather small ($(($AVAIL / 1000))GB - usually ${AVAIL_MAX}GB or more is needed..."
```
If this is anywhere close to what you had in mind I'll submit a PR - after a little more work of course.

**Comment by dnschneid** [comment]
True, the partition that the chroot would be installed on is the important part.  You should be able to use something akin to the code that checks for ext filesystems to figure out what exactly to check.  Also I think your code is checking for 4 and 2MB filesystems :)

Go ahead and start PR and I'll give more detailed feedback.

Thanks again for picking up the pie!

**Comment by DennisLfromGA** [comment]
@dnschneid - I've created a couple of routines to check space and chrubuntu in `installer/main.sh` and `installer/functions` but I'm afraid they are in two different 'patch-XX' branches (because I don't know what I'm doing :/ ). I could submit a PR for each I guess but they really belong in just one PR.

The proposed changes are here: [main.sh](https://github.com/dnschneid/crouton/compare/master...DennisLfromGA:patch-3) and here: [functions](https://github.com/dnschneid/crouton/compare/master...DennisLfromGA:patch-2?diff=unified&name=patch-2).
In `main.sh`, I left in a couple of test params, commented out.
In `functions`, I also left in a few ideas I had but wasn't sure if they really belong in there, commented out.

Let me know if I should go ahead and submit the PR's or wait for critiques and comments, etc.

**Comment by divx118** [comment]
@DennisLfromGA The way I do it, is keep my fork updated https://help.github.com/articles/syncing-a-fork/ then create a new branch on which I will be working. Submit a pull request from that branch. 
If I see it correctly now, your fork is behind crouton. So I would update that first see link above. Then create a new branch make your changes on that and then submit the pull request.

**Comment by DennisLfromGA** [comment]
@divx118 - Thanx for the advice. 
I do it all on the github site, not from a terminal but I'll try to see if I can follow your suggestions online.

**Comment by DennisLfromGA** [comment]
Okay, I think I got my fork synced and made a new branch with the file changes here: [size-tests](https://github.com/dnschneid/crouton/compare/master...DennisLfromGA:size-tests)

**Comment by DennisLfromGA** [comment]
@dnschneid,
As reluctant as I am to submit the size-test PR (due to the usual number of embarrassing changes needed, etc.), I'll go ahead and do it if '[size-rests](https://github.com/dnschneid/crouton/compare/master...DennisLfromGA:size-tests)' looks like a decent start and the '[update fork](https://github.com/dnschneid/crouton/commit/9908ce46ccf034ce2530da7ddbc09916dbee92fc)' part won't be a problem. 

If the 'update fork' part does present a problem, I'll delete my 'crouton' fork, re-fork it, and submit a PR with just the relevant files (main.sh & functions) included.

When you get a chance, let me know how best to proceed and I'll do it.

Thanx again,
-DennisL

**Comment by DennisLfromGA** [comment]
I guess no news is good news so I submitted PR https://github.com/dnschneid/crouton/pull/2240.
