### ISSUE TITLE
Can't start crouton on latest arnoldthebat special build

### ISSUE THREAD

**Issue by cmason37** [dnschneid/crouton#2126]
Log:
[   209.448] (II) intel(0): SNA compiled: xserver-xorg-video-intel 2:2.99.910-0ubuntu1.6 (Timo Aaltonen <tjaalton@debian.org>)
[   209.448] (WW) Falling back to old probe method for fbdev
[   209.448] (II) Loading sub module "fbdevhw"
[   209.448] (II) LoadModule: "fbdevhw"
[   209.449] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[   209.449] (II) Module fbdevhw: vendor="X.Org Foundation"
[   209.449]    compiled for 1.15.1, module version = 0.0.2
[   209.449]    ABI class: X.Org Video Driver, version 15.0
[   211.604] (EE) intel(0): [drm] failed to set drm interface version: Permission denied [13].
[   211.604] (EE) intel(0): Failed to claim DRM device.
[   211.605] (II) UnloadModule: "intel"
[   211.605] (EE) Screen(s) found, but none have a usable configuration.
[   211.605] (EE) 
Fatal server error:
[   211.605] (EE) no screens found(EE) 
[   211.605] (EE) 

Also found  issues #524 & #1777, which seem to be just like this one.

**Comment by mrkapqa** [comment]
hello i am having similar problem


wheezy - kde 

on acerc720 using latest crouton installer.

cannot start X-Server.


problem only with wheezy - not with jessie.

**Comment by mrkapqa** [comment]
sudo startkde

Setup completed. Entering chroot...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.12.4
Release Date: 2012-08-27
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-4-amd64 i686 Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Aug 31 19:53:26 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=6ae23ae3-1182-fe4a-ae76-bfdf10007b8a/PARTNROFF=1 hashtree=PARTUUID=6ae23ae3-1182-fe4a-ae76-bfdf10007b8a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=38da5d8e079de303288a85e0420d1c7c60982e4f salt=112a1747e8b7f41d4e33d23397566bb755fb91abb8efd7da23a3130110a76a28" noinitrd vt.global_cursor_default=0 kern_guid=6ae23ae3-1182-fe4a-ae76-bfdf10007b8a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 09 February 2015  10:12:47AM
xorg-server 2:1.12.4-6+deb7u6 (Julien Cristau <jcristau@debian.org>) 
Current version of pixman: 0.26.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Sep 25 19:19:09 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150924014025~master:04ff0c11
release: wheezy
architecture: i386
xmethod: xiwi
targets: kde
host: version 7262.52.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Aug 31 19:53:26 PDT 2015 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/wheezy...

**Comment by dnschneid** [comment]
@mrkapqa, your issue is unrelated.

@cmason37: I haven't tried those Chromium OS builds, but the "intel(0): Failed to claim DRM device." is interesting.  Could you post the output of `sudo edit-chroot -al`?

**Comment by dussel0815** [comment]
I have the same problem. On both vivid and precise the X-Server fails to start. (Using http://arnoldthebat.co.uk/wordpress/2015/09/14/chromiumos-special-build-r47-7451/) 
From /var/log/Xorg.1.log:
```
[  1728.454] (EE) intel(0): [drm] failed to set drm interface version: Permission denied [13].
[  1728.454] (II) intel(0): [drm] Contents of '/sys/kernel/debug/dri/0/clients':
[  1728.454] (II) intel(0): [drm]              command   pid dev master a   uid      magic
[  1728.454] (II) intel(0): [drm]                    X  1905   0   y    y   231          0
[  1728.454] (II) intel(0): [drm]               chrome  3012   0   n    y  1000          1
[  1728.454] (II) intel(0): [drm]                 Xorg 23987   0   n    y     0          0
[  1728.454] (EE) intel(0): Failed to claim DRM device.
[  1728.454] (II) UnloadModule: "intel"
```

`edit-chroot -al` outputs
```
name: vivid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/vivid...
crouton: version 1-20150924014025~master:04ff0c11
release: vivid
architecture: i386
xmethod: xorg
targets: xfce
host: version 7451.0.2015_09_13_1749 (Developer Build - tonyd) developer-build x86-atb
kernel: Linux localhost 3.19.3 #1 SMP Mon Sep 7 20:26:18 BST 2015 i686 i686 i686 GNU/Linux
freon: no
Not unmounting /mnt/stateful_partition/crouton/chroots/vivid as another instance is using it.
```

**Comment by dnschneid** [comment]
What does `sudo enter-chroot -n vivid ls -l /usr/bin/X` tell you?

**Comment by dussel0815** [comment]
It outputs:
```
chronos@localhost ~ $ sudo enter-chroot -n vivid ls -l /usr/bin/X
Password: 
Entering /mnt/stateful_partition/crouton/chroots/vivid...
-rwsr-sr-x 1 root root 9532 Mar 16  2015 /usr/bin/X
Unmounting /mnt/stateful_partition/crouton/chroots/vivid...
```

**Comment by DennisLfromGA** [comment]
> [  2428.779] (EE) intel(0): [drm] failed to set drm interface version: Permission denied [13].
[  2428.779] (EE) intel(0): Failed to claim DRM device.

I'm getting the same error messages and my `/usr/bin/X` file has the same permissions as @dussel0815s.

This is on my Acer C710 (parrot) using a [Cloudready](http://www.neverware.com/free/#freedetails) version of Chromium. It's just an experiment so it's no biggie but I would still like to figure out the problem so I can run a chroot or two.

My croutonversion is:
```
name: trusty.r39
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty.r39...
crouton: version 1-20151016090355
release: trusty
architecture: i386
xmethod: xorg
targets: cli-extra,extension,keyboard,xiwi,xorg,lxde-desktop,chrome-beta
host: version 43.1.37
kernel: Linux localhost 4.0.5+ #1 SMP Wed Sep 30 02:05:19 UTC 2015 i686 i686 i686 GNU/Linux
freon: no
```

I'm using the following Chromium build (via Cloudready):
```
CHROMEOS_RELEASE_BOARD=dataart
CHROMEOS_RELEASE_BRANCH_NUMBER=86
CHROMEOS_RELEASE_BUILD_NUMBER=6946
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_CHROME_MILESTONE=43
CHROMEOS_RELEASE_DESCRIPTION=43.1.37
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_RELEASE_PATCH_NUMBER=2015_09_30_0319
CHROMEOS_RELEASE_TRACK=developer-build
CHROMEOS_RELEASE_VERSION=43.1.37
GOOGLE_RELEASE=43.1.37
CHROMEOS_AUSERVER=https://cloudready-free-update-server.neverware.com/update
CHROMEOS_DEVSERVER=https://cloudready-free-update-server.neverware.com/
```

Also, xmethod 'xiwi' connects and opens but all I get is a blank screen.
I may try to add a 'kde' target to see if it acts any differently.

------

When I first ran crouton, I kept getting the error message:
`Your version of Chromium OS is extraordinarily old.`

I had to change `build/wrapper.sh` to use the *'version'* number instead of the *'platform'* number ([Version Numbers](https://www.chromium.org/developers/version-numbers/#TOC-Chromium-OS)) and `installer/main.sh` to use '_CHROME_MILESTONE=' instead of '_RELEASE_VERSION='. This should work for both Chrome OS and Chromium.

**Comment by dnschneid** [comment]
_CHROME_MILESTONE is a bit coarse, but that really just impacts how quickly we can expire old hacks and put in new dependencies.  @drinkcat: do we have a strong need for the granularity, or can we drop back to simple MILESTONE comparisons?

**Comment by drinkcat** [comment]
dev channel can keep the same milestone but upgrade the build number. So MILESTONE won't work generally (using it for the `Your version of Chromium OS is extraordinarily old.` check would be fine though).

Could we use `CHROMEOS_RELEASE_BUILD_NUMBER` ?

**Comment by DennisLfromGA** [comment]
@dnschneid, @drinkcat - I should have noticed the build number was common to Chrome OS and Chromium but, in my haste, I overlooked it and chose the `CHROMEOS_RELEASE_CHROME_MILESTONE` which, like you mention, is a bit too course. 
I think the `CHROMEOS_RELEASE_BUILD_NUMBER` might be a good parameter to use since, in the Cloudready version of Chromium, it's currently using a build number of `6946` which is greater than `CROS_MIN_VERS=6310` in build/wrapper.sh so it should work for both OSes.

Thanx for looking at this.
[ It might even be a pie ;) ]
-DennisL

----
P.S. I've since done a full recovery on my Acer C7 that was running Cloudready and restored it back to Chrome OS since I couldn't get any gui desktops to work on the Cloudready platform. I'm not the most patient person around...
The good news is I've got my crispy CROUTON partion re-defined so I'm good to go again. ;)

**Comment by tedm** [comment]
I like pie!!

**Comment by DennisLfromGA** [comment]
> I like pie!!

Go for it!

**Comment by kgingeri** [comment]
Just my 2 cents worth here... Cloudready seems to be an up and coming thing.  Having Crouton run on it is also something very worthwhile for me!  @DennisLfromGA I'll go halfs on the the pie ;vP

**Comment by tedm** [comment]
So is the task here to replace CHROMEOS_RELEASE_CHROME_MILESTONE with
CHROMEOS_RELEASE_BUILD_NUMBER
? And if so, in which module (s) ? Should Cloudready be added to a list of
future targets, or is it something else? I've heard of it, but have not
installed or seen it  yet.

**Comment by kgingeri** [comment]
@tedm I would say yes, it should be added.  I personally have not tried to install Crouton on Cloudready, so I cannot answer your first question.  @DennisLfromGA is your guy for that question.

FWIW, Cloudready is basically a clone of ChromeOS for PC and Mac etc.  It can even be installed on existing machines.  It preformed very well for me on a Mac Air 11" (2008 era) and made it more usable again.  There does seem to be a good support 'team' behind it - tho I really have no idea how committed to the future they are.

**Comment by DennisLfromGA** [comment]
@ted,
> So is the task here to replace CHROMEOS_RELEASE_CHROME_MILESTONE with
CHROMEOS_RELEASE_BUILD_NUMBER ?
And if so, in which module (s) ?

I think the tentative proposal is to replace '_RELEASE_VERSION=' with '_RELEASE_BUILD_NUMBER' in `installer/main.sh`, this way, `build/wrapper.sh` would not have to change. You of course leave off the 'CHROMEOS' part.

> Should Cloudready be added to a list of
future targets, or is it something else?

That is a whole 'nother ballgame, it is definitely 'something else'. 
Cloudready is a full, chromium based OS, like Chrome OS so it's not in the 'target' category.

**Comment by dussel0815** [comment]
I think there is also another issue: I did not use the Cloudready build, but Arnoldthebats and the install had no "Your version is old" error. Instead I could not start the x server.
So there is one issue with the installer checking the wrong version but also another with the failing X server.

**Comment by DennisLfromGA** [comment]
@dussel0815 - You're right, I think we've gotten away from the original issue.

**Comment by tedm** [comment]
@DennisLfromGA  Dennis, I found your code here:

https://github.com/dnschneid/crouton/blob/488c9e21c39f5a6bd644aff49128e2f8a9016978/installer/main.sh

But it says I have to be on a branch to make changes (I can't fork here, I can on my make changes online).

**Comment by DennisLfromGA** [comment]
@tedm, 
That's totally unrelated, it was a PR for 'Removed $TARGETSDIR prefix' that has already been merged.
You need to make changes to the crouton *master* online ( [installer/main.sh](https://github.com/dnschneid/crouton/blob/master/installer/main.sh) ) by selecting the 'edit' icon to the right of History -
![screenshot 2015-10-30 at 4 31 02 pm](https://cloud.githubusercontent.com/assets/3418772/10857385/2f3144ee-7f24-11e5-983d-986c261fc82e.png)

or via 'git' in a crouton chroot - see [Set Up Git](https://help.github.com/articles/set-up-git/).

**Comment by tedm** [comment]
@DennisLfromGA I made the change, and initiated the pull request.

I know these commands with gitlab (which we use at work):

git push, pull, commit -a, origin, master, keygen-ssh, copy/paste keys, 

What am I missing?

**Comment by semog** [comment]
I was able to install Crouton (finally) onto CloudReady, but was unable to get the graphical interface to run (Xfc4). I don't know if it's the same problem that the Arnoldthebat is having.

**Comment by DennisLfromGA** [comment]
@tedm,
> What am I missing?

I looked at your [PR](https://github.com/tedm/crouton/commit/aebd7b44209e6461ee2c135a9361484edce4f0e4) and it doesn't look like your missing anything. 
It looks good to me, now we just have to see if it looks good to the developers.

**Comment by tedm** [comment]
OK, thanks @dennisl

**Comment by tedm** [comment]
@cmason37 @mrkapqa Does this fix your issues?

**Comment by wsherliker** [comment]
Hi,

The patch for this could be as outlined or with line 132 (on the latest crouton) as:
if ! awk -F= '/_CHROME_MILESTONE=/ { exit int($2) < '"${CROS_MIN_VERS:-0}"' }' \

In any case this allows crouton to install and be used. Only remaining issue is that on the latest cloudready (neverware) version 44 the startgnome etc. work but the Chrome extension using xiwi or extension do nothing. You just get the constant 'Connecting' and failing cycle. 

Any chance someone could look at that as it would be great to be able to run the couple of missing apps that you get in Linux but not Chrome OS. 

Overall Crouton is great, thanks to the team for that.

**Comment by tedm** [comment]
@DennisLfromGA Which patch do you think is better, the original one with PR submitted or @wsherliker 's one with awk ? I haven't used cloudready yet, so know nothing about that.

**Comment by DennisLfromGA** [comment]
@tedm - As if my opinion would count ;), I think your current [PR](https://github.com/tedm/crouton/commit/aebd7b44209e6461ee2c135a9361484edce4f0e4)'s solution is better because the RELEASE_BUILD_NUMBER is a 'finer' control, as opposed to the CHROME_MILESTONE number, which I originally proposed in my haste. :/
See @dnschneid's comment above - https://github.com/dnschneid/crouton/issues/2126#issuecomment-150357067

**Comment by dnschneid** [comment]
OK, @tedm's patch is merged.  Re-open if you still have issues.

**Comment by mrkapqa** [comment]
These days i am using HugeGreenBugs. iso on DualBoot for the Acer C720.
Should i buy another Chromebook (possibly Toshiba Chromebook 2) anytime soon, i will let you know, cause i prefer Debian over Ubuntu. thanks for the help.

**Comment by cmason37** [comment]
@dnschneid I'm on arnoldthebat's latest special build again, & this does not fix my issue at all.I'm still having the exact same problem, log & everything.

**Comment by gnidorah** [comment]
Same stuff here. But got success when built Chromium OS for PC by myself. Here is the howto: https://gist.github.com/gnidorah/8ca4f7db3af38b1622a8

**Comment by chaitan3** [comment]
@cmason37 Try removing the intel driver in the chroot using "sudo apt-get remove xserver-xorg-video-intel". The X server will use the fbdev driver and the chroot desktop should work.

From my limited knowledge of the linux graphics stack, I think the reason the intel driver fails is that it's not able to capture the display device through drm. If you take a look at the Xorg logs on the host you can see that "drmDropMaster" and "drmSetMaster" fail. This is because the xorg server is run as a non-root user (verified on CloudReady chromium os) and it's not able to call the DRM ioctls.

I'm trying out a few solutions and will maybe have the intel driver working this week.

**Comment by drinkcat** [comment]
@chaitan3 One needs a patch that looks like this to get drm dropping/setting to work correctly: https://chromium.googlesource.com/chromiumos/third_party/kernel-next/+/d53b6142c2b5c742d2c547568c9814597c41ede6 . Not sure what kernel arnoldthebat is using (maybe a 4.4 kernel?).

**Comment by drinkcat** [comment]
In any case, please file a new issue if this is still a problem.
