### ISSUE TITLE
Mouse is missing until a program is launched

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#2131]
XFCE Ubunutu 12.04
So I've been having this problem where my mouse cursor wasn't present but I could still use it. So I started a Libre Office odt file and once it started my mouse cursor reappeared however, Libre Office didnt show up in the taskbar on top and I couldn't move the window but I could still type in the program.

**Comment by dnschneid** [comment]
Could you post the output of `sudo edit-chroot -al`?

**Comment by FlyKoBo** [comment]
Sorry I had to use Libre Office urgently for school so I just powerwashed my chromebook and then just reinstalled xfce instead i reintsalled with -r trusty and everything is working fine

**Comment by nhennecke** [comment]
I am experiencing the same or a very similar issue.  The requested output from the last comment on my machine is:

name: minecraft
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/minecraft...
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8350.68.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:11:23 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/minecraft...
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
Changing audio GID from 220 to 600...
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8350.68.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:11:23 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

A little more background on my environment.  This is almost exclusively used by my kid to run minecraft.  We were trying to do some copy/paste for command blocks and the default net surf browser was insufficient for the task so I went to install firefox.  Found updates were needed so did an apt-get update and then installed firefox.  Firefox ran fine, went to copy/paste into minecraft and upon pasting in the text the whole chromebook crashed.  Upon reboot the problems began.  The xfce4 env starts fine and looks normal except the mouse cursor is missing.  You can still move the mouse and get it to interact w/ other windows though.  Once other windows open the mouse cursor appears and then is the default large X when outside of the window.  The window controls do not appear for min/max/close.  Minecraft will startup and stays in the state that it would be if you had pressed esc to access the options window.  Like the control of the interface isn't truly granted to the running program because xfce is still trying to load the mouse/window controls.  The work spaces do not startup correctly either.  They appear as one small widow in the upper right and do not break out into the default # of work spaces.

I've tried additional updates w/ apt-get with no change in the status.  Any help that can be provided would be extremely helpful.  Thanks!

**Comment by drinkcat** [comment]
@nhennecke Please file a new issue.
