### ISSUE TITLE
Unmounting removable disk-like devices from inside the chroot

### ISSUE THREAD

**Issue by SnarkBoojum** [dnschneid/crouton#2134]
Whenever I connect a removable disk-like device, the chroot shows a window telling I don't have the permission -- that's a little annoying but not a problem.

But when I want to unmount the device, I have to switch back to chromeos, open the file manager and click -- and I find that a problem, since that's the only thing I use chromeos for (apart from starting the chroot!)...

So is there a way to unmount those from inside the chroot ?

Thanks!

**Comment by tista500** [comment]
@SnarkBoojum,

Which way you've used to do mount/unmount with (i.e. mount, udiskctl, gvfs-mount, nautilus, thunar, and so much more...)? I think this issue depends on your desktop environments as well since your method might be based on some backends related to desktop framework. And one more thing, policykit also lies behind the frontend of mount actions strongly... So did you tweak such policykit rules to fit your usage of mount/unmount?

As my experiences, once we've unmount (something like `sudo umount ...`) the external storages at the early stage of kicking chroot, after all we could mount/unmount anytime we want via file-manager if we properly prepared for some policykit rules before we've done things.

Regards.

**Comment by SnarkBoojum** [comment]
I tried in PCManFM, and in a terminal with umount (no sudo), and I have no tweak anywhere : I innocently thought it could just-work(tm) :-P

**Comment by drinkcat** [comment]
Devices should be mounted/unmounted in Chromium OS.
