### ISSUE TITLE
[Wily][Target: Unity] sudo startunity only shows a background image

### ISSUE THREAD

**Issue by Alfriadox** [dnschneid/crouton#2144]
I wanted to install Wily Werewolf yea? Well I done installed it, but when I boot into it using that 
`sudo startunity -n test`
It begins, but only the background loads up. No launcher, No apps.

**Comment by Alfriadox** [comment]
I went back into chrome, and ran 
`sudo enter-chroot -n test`
and it worked.
In the chroot, I ran
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install software-center
```
This all worked.
When I ran 
`sofware-center`
expecting the software center to open in a window in the chroot, this happened:
```
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
2015-09-29 09:29:56,223 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/share/software-center/softwarecenter/netstatus.py', 122, '__init_network_state')'
2015-09-29 09:29:56,223 - root - WARNING - failed to init network state watcher 'org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files'
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(software-center:24382): Gtk-CRITICAL **: gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
```

**Comment by tista500** [comment]
@Alfriadox,

Thanks for your trial in development release. :)
I am a member of Ubuntu+1 team, and wily is still final-beta phase now. Unfortunately I'm not familiar with Unity desktop environment though, could you please let the title be more specific (i.e. *[Wily][Target: Unity] `sudo startunity` only shows a background image* ...etc)?

As I posted before, please see this issue: #1706 
That issue is in Vivid release cycle, but I suppose the issue was carried to Wily cycle unfortunately...

Regards.

**Comment by Alfriadox** [comment]
Thank you. Can you suggest a desktop environment?

**Comment by calinb7** [comment]
Thank you, Alfriadox.

I replied to this email on the Git bug report thread.

Best Regards,

-Cal

--------------------------------------------
On Fri, 10/2/15, Alfriadox <notifications@github.com> wrote:

 Subject: Re: [crouton] [Wily][Target: Unity] sudo startunity only shows a background image (#2144)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Date: Friday, October 2, 2015, 1:32 PM
 
 Thank you. Can you suggest a
 desktop environment?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by tista500** [comment]
@Alfriadox,

> Thank you. Can you suggest a desktop environment?

I'm not very sure what you want to do with Wily final-beta, so the answer might be a bit unclear... If you would need some later development codebases for your projects, Wily would be nice today. And you would also try to tweak some upstart/systemd jobs and unity7 libraries to put into chroot xinit sequence by yourself...

On the other hand, all you want was "just" working state on Wily, it would be better to employ some "legacy" desktop environments at first like XFce, LXDE, and so... However, Wily Gnome might work out of the box as well because it just can be launched from gnome-session with proper options, at least quite more simpler than Unity7's launching sequence if I remembered well.

Anyway I would also try installing Wily Gnome in a couple of days after.

Regards.

**Comment by drinkcat** [comment]
wily: Not supported, never supported. Sorry...
