### ISSUE TITLE
Allow backups to be saved to Google Drive directly

### ISSUE THREAD

**Issue by brmbrmcar** [dnschneid/crouton#2173]
I know it would be hard, but sometimes there is not enough room on the computer for a backup.

**Comment by mark-hahn** [comment]
I use objectivefs which provides a FUSE file system to the cloud.  It is
great for large storage since it is backed by AWS or other cloud storage.
There is no local directory like dropbox and many other cloud solutions.

The only drawback is that it costs money, $7/mount/month.  You could back
up crouton and everything else for $7/mo.

**Comment by dnschneid** [comment]
Well, you could sort of simulate it by using the split function (`-S`), but you'd have to be able to upload and then delete faster than the files are generated :)

The better approach is to just backup to external media.

**Comment by brmbrmcar** [comment]
Yes, but not everyone has external media large enough.
