### ISSUE TITLE
sid: no longer has /etc/X11/Xwrapper.config

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2185]
Looks like sid no longer has /etc/X11/Xwrapper.config.  crouton needs to not fail, although we should see whether we need to create this file or not.

**Comment by wymby** [comment]
It's a systemd issue. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801401 message 45 -- without systemd running you may need to install xserver-xorg-legacy and add "needs_root_rights=yes" to it. Affects stretch as well as sid.

**Comment by dnschneid** [comment]
Seems like skipping that step should be safe, since we run systemd-logind.

pie: make the Xwrapper modification never fail and confirm that X11 launches on Sid.

**Comment by aa0na** [comment]
i'm also experiencing this issue on my chromebook pixel 2
sudo sh ~/Downloads/crouton -r sid -t x11

note:  i can also either loose my mouse cursor or the ability to type on the console, if i can still type i just sudo reboot and then touch the missing file to continue with
sudo sh ~/Downloads/crouton -r sid -t x11 -u

**Comment by aurey2244** [comment]
Would I be able to do anything about this, because after solving that issue at the top then i get this one afterwards:E: Failed to fetch http://httpredir.debian.org/debian/pool/main/x/xscreensaver/xscreensaver-data_5.34-1_armhf.deb  Error reading from server. Remote end closed connection [IP: 2001:41c8:1000:21::21:35 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
I have already updated it 2 times

**Comment by voidplayer** [comment]
so whats the work around for this one?

install xserver-xorg-legacy and add "needs_root_rights=yes" to Xwrapper.config ?
