### ISSUE TITLE
Running from backups deliver very poor performance

### ISSUE THREAD

**Issue by brmbrmcar** [dnschneid/crouton#2201]
5 minutes startup, ANY game crashes, 15 minutes to log off.

**Comment by brmbrmcar** [comment]
Anyone?

**Comment by mark-hahn** [comment]
Do you mean that you backup, then restore, and then have problems?

**Comment by brmbrmcar** [comment]
Yes.

**Comment by DennisLfromGA** [comment]
Where are you rinning your 'backups', on your Chromebook or on an SD Card/USB stick ?
What is the output of - `sudo edit-chroot -al` ?

**Comment by DennisLfromGA** [comment]
It's possible that, since the backup was created, both 'crouton' and Chrome OS have had new versions so maybe all that's needed is a chroot update.

**Comment by brmbrmcar** [comment]
I did a powerwash and backed up from the Downloads folder. (I stored it in the cloud in the meantime).

**Comment by brmbrmcar** [comment]
It was one night.

**Comment by DennisLfromGA** [comment]
@brmbrmcar - The bits and pieces aren't helping, we'll need more info. to help you.

**Comment by tedm** [comment]
was it this night? : https://www.youtube.com/watch?v=RSX_y5hLt1k

**Comment by brmbrmcar** [comment]
No.

**Comment by DennisLfromGA** [comment]
@brmbrmcar - If this is a non-issue now, *please* close it. If not, *please* give us more details.

**Comment by brmbrmcar** [comment]
I reinstalled it in the end. But iti s an issue. What details do you want? I went from dev to beta Chrome OS.

**Comment by DennisLfromGA** [comment]
Okay -
- Where are/were you running your 'backups', on your Chromebook or on an SD Card/USB stick ?
- What is/was the output of - sudo edit-chroot -al ?
- It's possible that, since the backup was created, both 'crouton' and Chrome OS have had new versions so maybe all that's needed is a chroot update.
- Does it still run slow after you reinstalled it ?

**Comment by brmbrmcar** [comment]
I didn't run sudo edit-chroot -al; I deleted it before I opened the issue.
It doesn't run slow after I reinstalled.
I put it onto Downloads, then Google DRive.

**Comment by DennisLfromGA** [comment]
So it's hard to tell what the initial problem was at this point.
Since you've solved your issue, maybe this can now be closed.

**Comment by brmbrmcar** [comment]
No, it is an issue generally, but not for me.

**Comment by DennisLfromGA** [comment]
So I think you should close this issue since no further details can be obtained for now.
When if/it happens again, it can be addressed then.

**Comment by brmbrmcar** [comment]
I only did it once.
This is an issue, not a help thread.

**Comment by DennisLfromGA** [comment]
@brmbrmcar,
> Anyone?
>> No, it is an issue generally, but not for me.
>>>This is an issue, not a help thread.

You're the OP, you opened this issue but you didn't want help ?
What do you want then ?  I'd really like to understand...

**Comment by brmbrmcar** [comment]
The issue to be fixed for other people.

**Comment by tedm** [comment]
@brmbrmcar If you're saying that many people have issues with use and performance on removable media, and for some it works, and for some it fails, I'd agree with that. Different brands and qualities of removeable media have widely varying lifetimes. I've pretty much given up on removeable media to run an OS on, because of this, I had a good 2-3 years with Arch linux running off an SD card, then after 3-4 different cards, including same brand/model as original, I couldn't rely on them.

If it's something else, please clarify. Thanks.

**Comment by brmbrmcar** [comment]
I mean, once you have installed it.

**Comment by DennisLfromGA** [comment]
@brmbrmcar,
> The issue to be fixed for other people.

:confused: If you look around, you are the **only** one that has reported this issue 'Running from backups deliver very poor performance', no one else has had an *issue* with this to my knowledge.

**Comment by tedm** [comment]
@brmbrmcar It doesn't make sense that it would run slower after installing from a slower media. If it is running slower, I think you're still running it from media?? but you think you're running it on native chromebook media. Try this fix: unplug the external media, and see if it speeds  up? If it does, don't use that brand of media anymore, go to BestBuy and get a refund.

**Comment by brmbrmcar** [comment]
I think on setup the file is compressed again, and it should be set up normally.
