### ISSUE TITLE
wrong package name for kde install on kde wily/utopic

### ISSUE THREAD

**Issue by imakiro** [dnschneid/crouton#2260]
hello!
I've tried installing the kde-desktop target on Ubuntu Vivid release for my Dell CB 11 candy, 
the install fails with 

> Unable to locate package kde-plasma-desktop
> Failed to complete chroot setup.

The package name in wily is "plasma-desktop" not "kde-plasma-desktop"
I forked the project and tried to look for why the package name is wrong but I don't really get why because the process seems fully automated... 

Command run:

> sudo sh ~/Downloads/crouton -t xiwi,kde -r wily -e -P http://192.168.1.XXX:XXXX > ~/Downloads/installwilykde;log

(the  last 20 lines are coming, my log file doesn't seem to record what happened corectly and my bloody trackpad stops working each time the command crashes... mouse not recognised anymore too...)

**Comment by natbett** [comment]
I was able to get this working. My solution was to extract the tar.bz file at the end of the /tmp/crouton-install-cache/crouton file:
```bash
cd /tmp/crouton-installer-cache
mkdir crouton.unbundled
line=`awk '/^###/ { print FNR+1; exit 0; }' crouton`
tail -n "+$line" crouton | tar xjC crouton.unbundled
```
Then I modified crouton.unbundled/targets/kde and replace kde-plasma-desktop with plasma-desktop. Then I built the tar.bz again:
```bash
cd crouton.unbundled && tar cvfj ../crouton.tar.bz *
```
and appended it in place of the original tar, I used vim to delete all lines after `### end of script; tarball follows` then ran:
```bash
cat crouton.tar.bz >> crouton
```

**Comment by DennisLfromGA** [comment]
@natbett - Good job getting that working. :+1: 

----

@imakiro & @natbett,

Something similar to this cropped up when installing the vivid/gnome desktop, see https://github.com/dnschneid/crouton/issues/1706#issuecomment-104463165.

The problem is with the package specified in the desktop target files.
When it fails, you can enter the chroot as root and modify the `/prepare.sh` script to replace the correct package name and then re-run it. See the issue referenced above for more details.

For a more permanent fix, the '[kde target](https://github.com/dnschneid/crouton/blob/master/targets/kde)' would have to be modified via a pull request, similar to https://github.com/dnschneid/crouton/pull/1689 and using syntax similar to https://github.com/dnschneid/crouton/pull/1689#discussion_r29560691.

**Comment by DennisLfromGA** [comment]
@imakiro - Good job! It looks like a winner to me ( _but I don't count_ ;), ha, ha.

**Comment by imakiro** [comment]
lol, I don't use crouton anymore, but first of ll you count like everyone helping here, and secondly, I open an issue, I like it to be solved.
