### ISSUE TITLE
defined own packages dependences causes breakege in the long term

### ISSUE THREAD

**Issue by voidplayer** [dnschneid/crouton#2263]
Why not trust the distributions dependences? In my short time with crouton I hit 3 bugs related. Some upstream (debian in my case) need a new package to work but since crouton install its own list of packages instead of a generic one and let the distro pull their own dependences.

These issues seem to take a lot time to fix and by simplifying the packages list would help reduce bugs in crouton too.

Also, this kind of bugs prevents installations which is very unfortunate

example bugs:
#1983
#1996
Im not sure about #2185 but in not affected in debian by the bug linked on this one on my desktop

Im sure theres more around (basically every time upstream changes something)

Since this is not already done there must be some reasoning, but i fail to see why :s

Thanks for your consideration!

**Comment by dnschneid** [comment]
crouton tries to use metapackages and automatic dependencies as much as possible, but most of the dependencies for desktop environments are targeting large, multi-GB dedicated disk installs, and not the smaller X00MB installs that crouton needs.  The -desktop targets do use the full dependency chain if you don't care about your disk space, but crouton generally tries to be as remain as possible out of the box so you have enough space to do what you want.

Most crouton incompatibilities aren't actually due to the package selection, and rather due to quirks of being in a chroot environment with a kernel and init process out of the distro's control.

**Comment by voidplayer** [comment]
I see

At least debian strives for minimal metapackages as well, even in chroots. Ive seen multiple bugs on their bugtracker with people fighting to get the chance to get an extra package where you get as minimal as possible. Trying to get more minimal than that is going to be hard

Just install with --no-recomended (this way, if something fails, you can file a bug upstream about it! and its not your fault!). This is the reason recommended and dependences are a separated list

Maybe I just had bud luck, and hit a few of them myself and was unable (or had a really difficult time) to install crouton several times over a long period of time because of them

I understand there is a chance to shrink it further because the chroot environment w/o kernel and no init system dont "need" some extra stuff, but, imho, is not worth it to shave the 500mb you end up saving with your own customized package list. As minimal as chromebooks are, they are not embedded devices where every Mb counts

And this comes from a guy with a chromebook where if i install 2 -desktop packages i run out of space, so i know about lack of space :)

This sounds more work for you and more bugs for us, although I understand your motivation too, so thanks for your work and trying to keep up this list nonetheless!

happy 2016!
