### ISSUE TITLE
crouton update fails with trusty

### ISSUE THREAD

**Issue by seanmahrt** [dnschneid/crouton#2272]
I am trying to update trusty from crouton first before I go into the chroot to update it (seems like a good idea).  I deleted crouton and redownloaded a fresh version and it still won't update.

command:

sudo sh ./crouton -u -n trusty
 response: /usr/local/chroots/trusty already exists; updating it...
Unable to determine the release in /usr/local/chroots/trusty. Please specify it with -r.

name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150827155505~master:edbce112
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,lxde
host: version 7390.68.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Nov 5 10:53:38 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

Where to next?

**Comment by DennisLfromGA** [comment]
Your chroot may not be fully setup, or something has changed.
Maybe just try to get into it first via `sudo enter-chroot -n trusty`
and see if that succeeds. If it tells you the setup didn't finish and ask if you want to proceed, go for it.
Then, either update your chroot via `sudo apt-get update; sudo apt-get upgrade`
or exit the chroot and run your crouton update command again.

**Comment by seanmahrt** [comment]
I'll try that. I know the enter-Chroot works. Just was surprised the update crouton wasn't happy. I'm pretty sure the apt update will work too

Sean

**Comment by DennisLfromGA** [comment]
Yeah, the message:
`Unable to determine the release in /usr/local/chroots/trusty. Please specify it with -r.`
seems to indicate something is definitely wrong with the chroot...

**Comment by seanmahrt** [comment]
Somehow my update list was really hosed up (us.release.ubuntu.com) instead
of us.archive.ubuntu.com.  Wonder if that was from the original crouton
trusty install...

**Comment by DennisLfromGA** [comment]
Yeah, I don't know how '*us.release.ubuntu.com*' got in there.
Is the crouton update working for you now?

**Comment by seanmahrt** [comment]
Yes, after I corrected it, the crouton update worked great. Might be good to cough an error code or something for totally screwy repositories. 

Sean

**Comment by w-barath** [comment]
I have this same problem right now.  I've disabled all optional repos and I have archive.canonical.com for all the standard ones.

I've tried enter-chroot and done a manual update/upgrade without issue, I've verified that /etc/lsb-release, /etc/crouton/name, /etc/crouton/release all say trusty.

chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n trusty
/usr/local/chroots/trusty already exists; updating it...
Enter encryption passphrase for trusty: 
Unable to determine the release in /usr/local/chroots/trusty. Please specify it with -r.
chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n trusty -r trusty
/usr/local/chroots/trusty already exists; updating it...
Enter encryption passphrase for trusty: 
Release doesn't match! Please correct the -r option, or specify a second -u to
change the release, upgrading the chroot (dangerous).
chronos@localhost / $ sudo sh ~/Downloads/crouton -uu -n trusty -r trusty
/usr/local/chroots/trusty already exists; updating it...
Enter encryption passphrase for trusty: 
WARNING: Changing the chroot release to trusty.
Press Control-C to abort; upgrade will continue in 5 seconds.
chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n trusty -r trusty
/usr/local/chroots/trusty already exists; updating it...
Enter encryption passphrase for trusty: 
Release doesn't match! Please correct the -r option, or specify a second -u to
change the release, upgrading the chroot (dangerous).

So at the very least, the extra -u does not function correctly to set the release.

It would be nice if the script would report what information it disagrees with so that users could take corrective action instead of (probably) giving up and junking their chroot.  I'd really prefer not do that but soon it will be my only option.

**Comment by cyrildtm** [comment]
Running into the same situation. `apt-get` works. Changing repo to us.archive.ubuntu.com from archive.ubuntu.com does not help either.
