### ISSUE TITLE
Can only get into xfce once

### ISSUE THREAD

**Issue by thebirdman13** [dnschneid/crouton#2286]
I just set up xfce and the first time I used it with the "sudo startxfce4" command it worked perfectly. However, after using it for a little while then exiting it I was unable to start it. I enter the exact same line of code (sudo startxfce4) but instead of starting up like the previous time this came up:

Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Nov 5 13:33:59 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9712446f-4d3f-6341-9fd5-2cec04661aa9/PARTNROFF=1 hashtree=PARTUUID=9712446f-4d3f-6341-9fd5-2cec04661aa9/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5f15e8f23893e000bd430c46498a4ecc9ae57b8e salt=d1eb505a5be7500130725fe42d96845846194ba71d9f63f6fe5dba5e056643e2" noinitrd vt.global_cursor_default=0 kern_guid=9712446f-4d3f-6341-9fd5-2cec04661aa9 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Dec  8 16:39:34 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I've looked around on the internet but was unable to find someone with a similar issue. Thanks for any help you can give, I am new at this and trying my best to get a hang of it.

**Comment by DennisLfromGA** [comment]
@thebirdman13,
Let us see the output of: `sudo edit-chroot -al`

I don't know how long it's been since you first installed it and when you ran into trouble.
It could be Chrome OS has updated and the chroot needs to be updated also to keep in step.
You can follow this procedure to try and troublshoot it: '[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)'.

**Comment by thebirdman13** [comment]
I installed it earlier today, and within the same day it is having this issue so I don't think it has to do with an update, but I'll check out that page and see what I can do.

The output of "sudo edit-chroot -al" is:
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 7390.68.0 (Official Build) stable-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Thu Nov 5 13:33:59 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Thanks for the help

**Comment by DennisLfromGA** [comment]
@thebirdman13 - Okay, let us know if the troubleshooting steps fix it.  
In addition to or instead of updating it using 'crouton -u ...', you could get into the chroot command line via:  
`sudo enter-chroot -n precise`  
and then, to update the chroot's packages in case something has gone awry there, run:  
`sudo apt-get update; sudo apt-get upgrade`  

Then exit the chroot and try your 'startxfce4' command again.

----

Also, if you don't have too much time & effort in your 'precise' chroot yet, you could delete it and install a 'trusty' release (using `-r trusty`) which is more up-to-date and will usually work better.
