### ISSUE TITLE
Trusty won't switch to ChromeOS with Ctrl+Alt+F2 on Samsung XE500C12-K01US

### ISSUE THREAD

**Issue by HeckuvaTester** [dnschneid/crouton#2300]
Created a chroot based on Trusty by using the command: 'sudo sh ~/Downloads/crouton -r trusty -t unity.' Previously, I had a chroot with precise, which did switch back to ChromeOS with the key combination. The only way to get back to ChromeOS is to 'log out' of Unity. Any suggestions on how to fix this?

**Comment by DennisLfromGA** [comment]
Use <kbd>Ctrl+Alt+_Shift_+F2</kbd>
Or, from a chroot command line: `croutoncycle cros`

**Comment by HeckuvaTester** [comment]
Thank you! If I may ask, do you know why trusty requires the shift key but precise doesn't?

**Comment by DennisLfromGA** [comment]
'precise' and all chroots require the 'Shift' key in the combo to switch back & forth.
This has been in effect since at least _June 15 of 2013_, that's when the [README](https://github.com/dnschneid/crouton/commit/4b5b1ce16224adfdfca7c6e0b0f45875549bc9c1) was updated. 
It was _always_ required on ARM platforms.

**Comment by divx118** [comment]
@HeckuvaTester Please close the issue when it is solved. Thanks in advance
