### ISSUE TITLE
Xiwi and external monitors

### ISSUE THREAD

**Issue by drcmda** [dnschneid/crouton#2344]
I run Crouton on a 2015 Pixel, i use xiwi to run apps. On my laptop i have no problems but as soon i drag windows on my external monitor in an extended screen config the content appears twice as big. Is there anything i can do?

screen:

![screen 48](https://cloud.githubusercontent.com/assets/2223602/12078549/d4d18380-b216-11e5-9e5b-7c7110622894.jpeg)

monitor:

![monitor](https://cloud.githubusercontent.com/assets/2223602/12078550/d9df1220-b216-11e5-9d07-1fcac725b626.jpeg)

**Comment by tista500** [comment]
@drcmda,

As this https://github.com/dnschneid/crouton/issues/1966#issuecomment-126955136, I suppose Xiwi could not detect the external monitor resolution when sliding into it from internals. I'm not sure but seems very similar issue on #1966. So once you maximized and restored that window after moving it into externals, Xiwi could detect the resolution of external monitor and fit to correct scaling? Since Xiwi window is under control of ChromeOS's window manager...

Regards.

**Comment by drcmda** [comment]
@tista500 thanks for the reference. Maximizing unfortunately does nothing. Clicking HDPI in the Crouton extension also doesn't react. The only hack i've found is maximizing it on the screen and then dragging it up, it stays normal but doesn't fill the screen. As soon as i stretch it goes big again.

**Comment by drinkcat** [comment]
Very similar to #1966, but possibly even trickier...
