### ISSUE TITLE
sudo error...

### ISSUE THREAD

**Issue by snowcat-Jung** [dnschneid/crouton#2369]
(trusty)snowcat@localhost:~$ sudo apt-get update
    sudo: error in /etc/sudo.conf, line 0 while loading plugin `sudoers_policy'
    sudo: /usr/lib/sudo/sudoers.so must be only be writable by owner
    sudo: fatal error, unable to load plugins

How can I fix it??

Chromebook Pixel 2015 LS
ubuntu 14.04 unity

**Comment by DennisLfromGA** [comment]
I think I would first try to do a crouton update using the '-u' option since it looks like something is 'broken' in the chroot.:

`sudo sh ~/Downloads/crouton -u -n trusty`

If that doesn't fix it, you might try entering your chroot as 'root' using:

`sudo enter-chroot -n trusty -u root`

Then do your `apt-get update; apt-get upgrade`

**Comment by snowcat-Jung** [comment]
@DennisLfromGA I just reinstall my crouton...

**Comment by DennisLfromGA** [comment]
...and that's another way... ;)
