### ISSUE TITLE
Command "xiwi xinit" will execute xinit twice.

### ISSUE THREAD

**Issue by divx118** [dnschneid/crouton#2381]
Like the title says, when running for example `xiwi xinit /usr/bin/i3`, we don't check for xinit in the xiwi script when executing `/usr/local/bin/xinit`. So two windows will open see [Line 124 in xiwi script](https://github.com/dnschneid/crouton/blob/master/chroot-bin/xiwi#L124) and https://github.com/dnschneid/crouton/issues/1576#issuecomment-170690803 for why this should be considered a bug.
Thanks @ipstone for noticing.

**Comment by ipstone** [comment]
Thank you for opening this issue. Though the duplicated window can be suppressed by/when running:
(After enter-chroot )
> $ XMETHOD=xiwi xinit /usr/bin/i3

I am just curious (as someone not knowing bash): when setting XMETHOD=xiwi on the same line of xinit /usr/bin/i3: does it mean add an environmental variable to the command 'xinit /usr/bin/i3' ?

if so, might there some way we can modify it to create an alias to easily lauch i3 under xiwi?

Update 1: I used the startxfce4 as template to create starti3 ( see the last section here: https://github.com/dnschneid/crouton/wiki/i3 ); then we can do sudo sh starti3 -X xorg; or sudo sh starti3 -X xiwi to run i3 either under xorg or xiwi

Update 2: One unsolved obstacle in using i3 under xiwi now, is that chromebook default shortcut keys would intercept mod+1, 2, 3 etc, so that the i3 switch workspace keybindings would not work.  This somehow limited the usage of i3 under xiwi. Not sure if it's a bug, but if there's way to circumference the defaul keybinding for i3 under wiki, that would be great.

**Comment by fuzetsu** [comment]
@ipstone 
Not really on topic for this issue, but you should be able to solve the issue you mention in "update 2" by switching the mod key to something else in the config. 
I use the Alt key by adding `set $mod Mod1` in the `~/.i3/config` file.
