### ISSUE TITLE
Installing openscad in ARM chroot

### ISSUE THREAD

**Issue by raygeeknyc** [dnschneid/crouton#2401]
Most of the support and underlying library packages are available but it looks like apt-get cannot find any installation candidate for the openscad package on my (arm) Asus Flip.

Does anyone here know of a suitable installation package or had experience building this from source?
TIA

**Comment by tista500** [comment]
@raygeeknyc,

Just googling now, it seems launchpad failed to build on armhf:
https://launchpad.net/ubuntu/+source/openscad

I'm not a user of openSCAD though, it needs openGL/EGL implementation with Qt? If so, our Rockchip rk-3288 might not accept for required components to run properly because we usually launch X11 window system with modesetting or fbdev user-space driver without any openGL/EGL implementations handled by DRI2, those drivers surely will take us to "fallback" Software-Rasterizer rendering mode instead of glamorEGL stack. It means GL/EGL performance got really unacceptable in any cases...

However, we might be able to build from srouce on our rk-3288 with some libgl1-mesa-* packages. But after reading above launchpad log, we, at least on my Xenial, need to write some patches to fix up build with onepGL/EGL on armhf architectures.

As known well, Mali closed-source GLES libraries could run 3D-acceleration on rk-3288 (Mali T-764 Graphics). But it only provided GLES runtime, not GL/EGL. Indeed, it still lacks DDX today...

Although I've never tried to build it from source, it sounds too hard to succeed building for me, additionally, it seems too difficult to run openSCAD normally on my Flip as well. I'm sorry I could not answer your issue clearly.

Regards.
