### ISSUE TITLE
Cinnamon Support for Debian?

### ISSUE THREAD

**Issue by Tenn1518** [dnschneid/crouton#2407]
I've searched about Cinnamon support on crouton, and it seems like cinnamon will only be added if an official PPA for Ubuntu is created. However, cinnamon is now available in the main repositories for Debian 8 Jessie, which is supported. It also is in the Ubuntu 16.04 repositories. So can we have Cinnamon support for Debian users? I know the majority of crouton users use Ubuntu, but I really want Cinnamon and use Debian.

I could wait for Ubuntu 16.04 for better support, since cinnamon is in the xenial repos, but I wanted to see if I could get it earlier.

**Comment by tista500** [comment]
@Tenn1518,

I'm afraid that you have started discussion only for Intel architectures... I don't know Cinnamon well but, it should have been stolen the Mutter compositor codebase, right? Mutter is the clutter-based 3D accelerated compositor what needs openGL/Mesa, instead of X11-based compositor like xfwm4 and metacity. It means "If Cinnamon did not have any fallback compositor, it surely fails to launch it on ARM architectures (Exynos, Rockchip and Tegra)". Today some Chromebooks which employed ARM could not implement openGL/Mesa in Crouton yet. The situation seems similar to Unity7(Compiz) on ARM architectures. In Precise release cycle, the legacy Unity-2D (Qt/X11 based compositor) could run on our ARM properly, but now, it's completely outdated... By the way, did you know Cinnamon had some fallback/flashback compositors?

It may be quite easy to revive cinnamon target though, however, at least, it needs some "fool-proof" blocker to stop adding its target into armhf crouton, or somehow to launch X11. But I'm not a maintainer/developer of crouton, so I hope devs would answer your feature-request...

Regards.

**Comment by Tenn1518** [comment]
Ah, I see. Well, it wasn't too much work to get cinnamon working anyways, I just had to create a core Debian chroot and use the xorg target to install xorg, install Cinnamon, and create a startcinnamon file for Chrome OS and a .xinitrc file for Debian.
