### ISSUE TITLE
Sana appears to require the crouton extension to be installed

### ISSUE THREAD

**Issue by szbergeron** [dnschneid/crouton#2418]
Even though it probably isn't in line with the consensus of most users I find using a windowed interface a little disjointed/disorienting so I prefer to use Crouton as a separate desktop and switch between them with CTRL+ALT+SHIFT+forward/backward. What I'm finding is that a Sana Chroot seems to require the use of the crouton extension, and running it as a separate desktop is impossible. I tried installing it a few times, with the only targets being kde-desktop+audio+keyboard+chrome, but upon running `sudo startkde -n sana` I run into a problem where it keeps trying to connect to the extension which just isn't there. I didn't see on any of those targets an extension requirement so I really don't know what's going on. Any help is greatly appreciated.

**Comment by DennisLfromGA** [comment]
@dreamwavedev,

There is a crouton `extension` target that provides:

-  *Clipboard synchronization and URL handling with Chromium OS.*

You specify it as a target when you install or update a chroot.
If you install the `xiwi` target/xmethod, then the `extension` target is automatically installed along with it.

There is also the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension for use with the `xiwi` target/xmethod that needs to be installed from the 'Chrome Web Store'. This app states that it is:

-  *Required to support the "xiwi" target, which puts X11 in a native window.*

So, if you install the `xiwi` target/xmethod, you'll need the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' web app too.

If you have both installed, you're `xiwi` session should connect and work just fine.

**Comment by dreamwavedev** [comment]
Sorry, I guess I meant Xiwi. I know it's useful to a great many people but I would vastly prefer to be able to use my chroot without crouton integration/xiwi and just with the CTRL+ALT+SHIFT+forward/backward keys. I didn't specify the Xiwi target but it appears it was installed anyway.

**Comment by DennisLfromGA** [comment]
> I run into a problem where it keeps trying to connect to the extension which just isn't there.

Installing the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension for use with the xiwi target/xmethod from the 'Chrome Web Store' will take care of your problem with the failed connection attempts I believe. 

-----
However, if you just have 'xiwi' installed, you can add/install 'xorg' with a crouton update:

  `sudo sh ~/Downloads/crouton -n sana -t xorg -u`

That will also make 'xorg' the default xmethod.
And, if 'xorg' was previously installed along with 'xiwi' and 'xiwi' was the default, the update will make 'xorg' the default.

If you have both 'xorg' and 'xiwi' installed and want to switch xmethods for a session, just use the '-X' option when invoking your start script, similar to:

  `sudo startkde -n sana -X xorg`

**Comment by heloword** [comment]
It seems that crouton regards xiwi as the default target when we install sana with the target xfce, kde, x11 or others.My xiwi works fine, but i also want a  separate desktop.
when i run `sudo sh ~/Downloads/tools/crouton -u -n sana -t xorg` , there is something wrong:

> Package 'xserver-xorg-video-all' is not installed, so not removed
xorg is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 xserver-xorg-core : Conflicts: xserver-xorg-video-modesetting
 xserver-xorg-video-modesetting : Depends: xorg-video-abi-18 but it is not installable
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Failed to complete chroot setup.

Is this a bug or something else?

**Comment by DennisLfromGA** [comment]
@heloword - Please show us what's displayed when you enter: `sudo edit-chroot -all`

**Comment by heloword** [comment]
@DennisLfromGA 
> 
name: sana
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sana...
crouton: version 1-20160206234800~master:daa872a0
release: sana
architecture: amd64
targets: xorg,cli-extra
host: version 7834.60.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Mar 10 03:33:26 PST 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sana...

**Comment by DennisLfromGA** [comment]
@heloword,

It seems since no X-windowed desktop target was specified in your installation, the 'xorg' xmethod was not set. If you're not going to use any graphics desktop, this shouldn't pose a problem.

>xserver-xorg-core : Conflicts: xserver-xorg-video-modesetting
xserver-xorg-video-modesetting : Depends: xorg-video-abi-18 but it is not installable
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

I'm not sure why you're getting those errors and I'm afraid I'm not very good at solving package discrepancies. :(
I like to install 'aptitude' since it seems to do a better job with broken installations and packages in general.
With it installed, you could do: `sudo aptitude -f install` and see what it recommends.

You *may* be able to install the 'xfce' target, even though you don't plan to use it and see if that 'fixes' those  'xserver-xorg*' errors.

Sorry I couldn't give you more expert advice,
-**DennisL**

**Comment by heloword** [comment]
@DennisLfromGA Thank you all the same!
By the way, i find the source code with x11 target

> 
https://github.com/dnschneid/crouton/blob/master/targets/x11

It seems that sana can only choose xiwi when i install the x11 target.
