### ISSUE TITLE
Error during install now need to delete files

### ISSUE THREAD

**Issue by Githubbly** [dnschneid/crouton#2419]
I ran into a problem during installation and closed out of the terminal. When I went back in I tried reentering the command install Crouton, but it told me there are already files present. How can I go about deleting them?

![screenshot 2016-02-04 at 1 33 18 am](https://cloud.githubusercontent.com/assets/17049618/12789032/7b08b756-cadf-11e5-92ca-09feddf9978a.png)

**Comment by DennisLfromGA** [comment]
You can delete your chroot(s) using the `delete-chroot` command, like:

`sudo delete-chroot precise`

If you want to try and 'fix' it, you can try to do a crouton update on it, like:

`sudo sh ~/Downloads/crouton -n precis -u`

If you don't specify a 'release' name with the '-r' option, then you will get the default 'precise' release.
I prefer to use 'trusty' since it's a *lot* more up-to-date and works much better for me.

**Comment by divx118** [comment]
@DennisLfromGA s/precis/precise ;)

**Comment by DennisLfromGA** [comment]
Oops - thanx @divx118 :+1:
