### ISSUE TITLE
Why does crouton want me to do a recovery.

### ISSUE THREAD

**Issue by ealgase** [dnschneid/crouton#2428]
Whenever I make or update a chroot, I get this message:

    WARNING: Your rootfs is writable. Signed boot verification cannot be enabled.
    If this is a surprise to you, you should do a full system recovery via USB.
Why do you have this message?

**Comment by DennisLfromGA** [comment]
Most likely because rootfs verification was removed making the root file system read-writable by one of a few different methods.

- '[Debugging Features](http://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features)' was selected when the account was setup.
- The script `/usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification...` may have been triggered by running it directly or using another script that invokes it.

The simplest way to reset it is to do a [Chrome OS Recovery](https://support.google.com/chromebook/answer/1080595?hl=en&source=genius-rts) but that, unfortunately, will wipe out all user data including any chroot(s) you have installed and reformat all the partitions on your Chromebook - a pretty drastic step. 
If you decide to recover your Chromebook, make sure you backup your chroot(s) and anything important in your ~/Downloads folder.

You can still run your chroot(s) with rootfs verificaiton removed, it's just more dangerous having your Chromebook in this state since anything can now be altered.

**Comment by ealgase** [comment]
I ran the `make_dev_ssd.sh` script, I'm just wondering why crouton warns me.

**Comment by DennisLfromGA** [comment]
> If this is a surprise to you, you should do a full system recovery via USB.

So if it's not a surprise to you, you don't *need* to take any action.

'crouton' checks if it's safe to enable boot signing verification. If it's not safe, it's been known to brick the system so 'crouton' will warn you about this. If it is safe, then 'crouton' will also turn off usb & legacy booting.
