### ISSUE TITLE
How do you restore a chroot backup to an external location?

### ISSUE THREAD

**Issue by Asuza** [dnschneid/crouton#2456]
After reading the help docs and the `edit-chroot` options I believe I could restore a chroot to an external location, away from `/mnt/stateful_partition/crouton/chroots` to anywhere else.

This is the command I used to try it, but it ended up restoring to `/mnt/stateful_partition/crouton/chroots` anyway (where I ran out of space):
```
sudo sh crouton -r jessie -f /media/removable/USB\ Drive/chromebook-backup/jessie-20160217-1446.tar.gz -m /media/removable/SD\ Card/chroots/
```
Can `-m` not be used during a restore?

**Comment by nmilosev** [comment]
```-m``` is for mirror setting? I think you want ```-p [path]```

**Comment by Asuza** [comment]
I think `-m` is a mirror for `crouton`, while this is the help description for `-m` for `edit-chroot`:
```
   -m DEST     Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.
```
Thanks for the suggestion, though!

**Comment by nmilosev** [comment]
Ah I see my bad, but why are you trying to move your chroot with ```edit-chroot```? I would try to do it with the crouton installer, since you are installing it (technically) again. So maybe:

```sudo sh ~/Downloads/crouton -f [tarball path] -p [destination path]```

I'm presuming you did your backup with ```-b```

And there is definitely some confusion here, you wrote in your question that you are using ```crouton``` but you are looking at ```edit-chroot``` parameters.

**Comment by Asuza** [comment]
Ah, I'm sorry. I've clearly mixed up my scripts. I believe I did do my backup with `-b`, but I guess I need to go over it again (and try using `-p` to restore to a specific path next time).

**Comment by DennisLfromGA** [comment]
@Asuza,

> After reading the help docs and the edit-chroot options I believe I could *__restore a chroot to an external location__*, away from /mnt/stateful_partition/crouton/chroots to anywhere else.

I think we need to clarify what you are trying to do, you mentioned '*__restore__*' but I think you may ultimately want to '*__move__*' it from internal storage to your external media.

You can do that in (at least) two ways - One using your backup tarball or two moving it from the internal drive.

**1:**
`sudo sh ~/Downloads/crouton -f /media/removable/USB\ Drive/chromebook-backup/jessie-20160217-1446.tar.gz -p /media/removable/SD\ Card`

Once that is restored and working, then remove it from the internal drive with:
`sudo delete-chroot jessie`

**2.:** 
`sudo edit-chroot jessie -m /media/removable/SD\ Card/chroots/`

> Ah, I'm sorry. I've clearly mixed up my scripts.

Actually, the `crouton` command uses `edit-chroot` to do the work so that's a third way.

*Hope this helps,*
-**DennisL**
