### ISSUE TITLE
Back/forward should work while holding Ctrl+Alt+Shift.

### ISSUE THREAD

**Issue by JoshMcCullough** [dnschneid/crouton#2480]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
xmethod: xorg
targets: kde,audio,xorg,extension,x11,touch,keyboard,cli-extra
host: version 7834.60.0 (Official Build) beta-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Thu Mar 10 03:29:27 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

When switching between ChomeOS and running chroots, I'd like to be able to "quick switch" by holding Ctrl+Alt+Shift and using the forward/back buttons without releasing Ctrl+Alt+Shift to move back and forth quickly. Currently I need to release Ctrl+Alt+Shift in order to "switch back".

**Comment by dnschneid** [comment]
crouton required the keys to be released because otherwise, each session (Chromium, X) would think those keys are still held down.  For X, the release of those keys could be spoofed via xte.  For Chromium, I believe the keys will automatically be released thanks to [this bug](https://crbug.com/457077), but I haven't confirmed that yet.

Once we confirm Chromium behaves properly, we can add the xte spoofing on the X11 side and get rid of the key release requirement.

**Comment by JoshMcCullough** [comment]
Ah, thanks for the explanation!
