### ISSUE TITLE
Possible to keep same LaTeX install with distro updates? (Also best distro for LaTeX?)

### ISSUE THREAD

**Issue by mangobait** [dnschneid/crouton#2510]
I want to run LaTex on my Chromebook (Dell 11) and prefer Crouton.

Question 1: can I maintain a LaTeX install if I update Ubuntu from 12.04 to 14.04 (or soon 16.04)? Or would I have to reinstall LaTeX? (14.04 or newer preferred.)

Question 2: Which distro (Ubuntu preferred) is best to run LaTeX? Or am I best to not use Crouton?

I'm new to Crouton (and fairly new to Linux) but old to LaTeX (used it on OSX for a decade). 

(I realize this isn't an "issue" per se but don't know what other forums are as specific to this.)

**Comment by davidlowryduda** [comment]
You can use any distribution you want. Since you have an Ubuntu preference, you can have latex on any Ubuntu version. It does happen to be that there are LaTeX changes in the standard texlive libraries associated to 12.04 and 14.04. Depending on what you're doing, you may encounter version difficulties if you continue to use texlive-full from 12.04.

If LaTeX is your main concern, the easiest thing to do would be to sudo apt-get install texlive-full after updating to 14.04. This is a very very very large installation. But it should have what you need.

There are ways to have better control over what latex packages you do or don't install on your machine, but this issue list does not seem to be a good place to discuss it. But some googling will lead you to lots of reputable posts, such as on StackOverflow, concerning putting latex on ubuntu machines while being able to use modern, updatex latex packages. I use LaTeX on my Chromebook via Crouton all the time.
