### ISSUE TITLE
Chrome in chroot doesn't respect australian scrolling

### ISSUE THREAD

**Issue by tabatkins** [dnschneid/crouton#2511]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160330180425~master:43e2fca0
release: precise
architecture: amd64
xmethod: xorg
targets: audio,cli-extra,extension,keyboard,touch,xfce
host: version 7834.66.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 29 05:09:41 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
#### Please describe your issue:

I use "Australian scrolling" on my Chromebook.  Everything worked out nicely across ChromeOS and my chroot.

I realized the Chrome in my chroot was out-of-date (Chrome 42!) so I updated it to Chrome 49. When I did so, the chroot Chrome switched itself to "normal" scrolling.  Toggling the Ubuntu "inverted scrolling" preference didn't seem to do anything to it (tho it definitely does have an effect on the rest of Ubuntu!).

Just in case it was relevant, I updated Crouton too; no dice. Chrome in the chroot continues to use "normal" scrolling no matter what I do.

I also tried switching ChromeOS to "normal" scrolling, just to see if it was inverting somehow; nope, Chrome in the chroot stays "normal".

**Comment by makingmark** [comment]
I just now experienced this issue with both Xenial and Trusty chroots and in both KDE and XFCE environments. Very frustrating as the natural aka Australian scrolling defaults selected in all of those work fine for other browsers & system apps - it seems like only Chrome isn't behaving...

...and indeed I turned up similar complaints here: https://bugs.chromium.org/p/chromium/issues/detail?id=582547

I was able to fix this following instructions here: http://askubuntu.com/a/519859 

Tweaks I had to make:
1. I deleted the Option "DialDelta", as my Synaptics aka Elan Touchpad on my Toshiba Chromebook 2 Swanky (2014 model) only had two options, not 3 (both of which, by the way, had the value of 74, not 1 as in the example given - and so I used -74 -74)

2. Instead of sudo nano /usr/share/X11/xorg.conf.d/20-natural-scrolling.conf, I ran gksu mousepad with same path (nano is not on my installation).
