### ISSUE TITLE
Will there ever be a mate target?

### ISSUE THREAD

**Issue by JaxonWright** [dnschneid/crouton#2520]
I would love to have mate on my chromebook, as it is what I am most used to.

**Comment by Polygon-6789** [comment]
You can install MATE by using the x11 target and then installing the MATE desktop packages yourself.

**Comment by zxvv** [comment]
I can take a stab at it.

Based on what I see recommended, the gist of it would be:

sudo apt-get install --no-install-recommends ubuntu-mate-core ubuntu-mate-desktop

**Comment by zxvv** [comment]
The pull request supports mate on most ubuntu, and a few recent debian releases.

There is one caveat when running mate in a window using xiwi. Xiwi runs the i3 window manager.  Due to differences betwen mate's 'marco' window manager and i3, some desktop items display error dialogs. This is not an issue when it is started using the xorg target.

**Comment by gardwired** [comment]
working for me -- sourced from various threads here:
crouton -r jessie -t audio,x11,xorg  (not actually sure you need targets at all)
then in chroot:  apt-get  install task-mate-desktop

create .xinitrc
exec mate-session

to start x (inside chroot): xinit  
startx doesn't work
