### ISSUE TITLE
having multiple chroots on one computer

### ISSUE THREAD

**Issue by Anklebitter** [dnschneid/crouton#2533]
issue:
Ok so here is the problem I'm wondering if I can install two chroots at the same time, putting kali linux on  a flash drive and ubuntu on the internal SSD of my acer c710 chromebook is that even possible? and if so is there any extra steps that I need to follow or cautions I need to worry about?

**Comment by DennisLfromGA** [comment]
@Anklebitter,

Yes, you can install and run multiple chroots on the internal SSD or on external media.
The only thing you need to keep in mind is that you have to specify the path to your chroot(s) on external media since 'crouton' is expecting them to be in `/usr/local/chroots` by default.

You can do this by using the '-c' option when launching your 'start*' script(s), see below:
`    -c CHROOTS  Directory the chroots are in. Default: /usr/local/chroots`

Hope this helps,
-**DennisL**
