### ISSUE TITLE
[QUESTION] Do you think it is possible to invoke crouton from a Chrome OS App?

### ISSUE THREAD

**Issue by Kaegell** [dnschneid/crouton#2555]
Hello everyone,

I know this is not really a crouton-specific problem, but I still posted it here.

I'm not sure, but Chrome OS Apps can be written either in javascript, Dart or GoLang, right?
Do you think it would be possible to make Apps that invoke directly crouton to launch graphical apps instead of creating a window of sorts? That would be a really sweet! :)

**Comment by nmilosev** [comment]
Launching directly from ChromeOS will be difficult because of security issues. 

I am to lazy to type '''sudo enter-chroot''' so I added the following line to my '''.bashrc''' file in ChromeOS:

'''alias e='clear && sudo enter-chroot''''

So I can only type '''e'''

As for launching apps in ChromeOS window, it is already possible with the xiwi target, you can look into it.

**Comment by idvoretskyi** [comment]
@Kaegell duplicates https://github.com/dnschneid/crouton/issues/2475
