### ISSUE TITLE
How to keep Linux running after closing the crosh shell?

### ISSUE THREAD

**Issue by danielpyon** [dnschneid/crouton#2574]
```
Please paste the output of the following command here: n/a
```

**Comment by raidzero** [comment]
Try ctrl+shift+alt+f1, also I am not sure you can close the shell that launched the xorg environment, doing so would probably terminate the shell and X session

**Comment by DennisLfromGA** [comment]
@danielpyon,

What @raidzero said is all true, here is a bit more explanation.

---
I noticed you wrote '*n/a*' instead of providing us with the output of:
 `sudo edit-chroot -all`  (`croutonversion`)
We ask for those details in order to see exactly what you've installed (targets, xmethods, etc.) and what hardware you're using. Those are often important details and help us troubleshoot issues.

The key-combo <kbd>ALT+CTRL+F1</kbd> is depricated and has been for a couple of *years* now.
To switch between 'Chrome OS' and your 'chroot' please use <kbd>CTRL+ALT+SHIFT+F1/F2</kbd>

In order to close the crosh window and keep the crouton chroot running, you can use the '-b' option, something like this:

`sudo startxfce4 -b`

The '`start*`' scripts use `edit-chroot's` options, the '-b' option is explained below:
```
    -b          Fork and run the specified command silently in the background.
```

*Hope this helps,*
-**DennisL**
