### ISSUE TITLE
Minimal Crouton Install Needed for Restore?

### ISSUE THREAD

**Issue by darethehair** [dnschneid/crouton#2605]
[Forgive me if this has been answered somewhere already]

In a situation where I would want to wipe a Chromebook clean, and then quickly/easily restore a previously working Crouton installation from a backup -- what is the proper technique to use?  My impression is that a Crouton installation already needs to be present in order to restore from a backup.  Is there a shortcut -- or a minimal install -- that would shorten this effort?

**Comment by DennisLfromGA** [comment]
> My impression is that a Crouton installation already needs to be present in order to restore from a backup.

That's not quite right.
In order to use `edit-chroot`, you *do* need to have a crouton installation present.
But, on a Chromebook where you've wiped it clean, you can download a fresh copy of [crouton](https://goo.gl/fd3zc) and then use it's '-f' and then '-b' option to restore your chroot(s) and scripts.
This of course assumes you've successfully backed up your chroot(s) using `edit-chroot's` '-b' and optionally '-f' options.

First, to restore your chroot, use something like: 
`sudo ~/Downloads/crouton -f trusty-20160224-1209.tar.gz`
( I used my 'trusty' chroot in the example )

Then, to restore the crouton scripts needed for your chroot, use something like:
`sudo ~/Downloads/crouton -b`

-*DennisL*

**Comment by darethehair** [comment]
Thanks, DennisL, for pointing me in the right direction!  Looking more closely, the main crouton page mentions this 'alternate' way of doing a recovery/restore -- it is the 'Crouton-Command-Cheat-Sheet' page that only mentions the 'edit-chroot' method.

**Comment by DennisLfromGA** [comment]
Cool! 
You can close this issue if you're satisfied with the answer.
