### ISSUE TITLE
Intermittent - Can't open /media/removable/Crouton/bin/enter-chroot

### ISSUE THREAD

**Issue by blackbulldog** [dnschneid/crouton#2606]
MY Crouton has been working just fine for a week or so - on a 32gb sandisk flash drive. Then, when trying to fire it up this morning, I get and error as below:
chronos@localhost / $ sudo sh /media/removable/Crouton/bin/enter-chroot
sh: Can't open /media/removable/Crouton/bin/enter-chroot
So I work my way donw thru the directory structure to see what's there and it looks like all the necesseray directories are there but they don't seem to be recognised.
Anyone help?
chronos@localhost / $ ls bin debugd dev etc home lib lib64 lost+found media mnt opt postinst proc root run sbin sys tmp usr var
chronos@localhost / $ cd /media
chronos@localhost /media $ cd removable
chronos@localhost /media/removable $ ls
Crouton SD Card chronos@localhost /media/removable $ cd Crouton
chronos@localhost /media/removable/Crouton $ ls
bin chroots cron Crouton - Downloads lost+found vnc.txt web
chronos@localhost /media/removable/Crouton $ cd bin
chronos@localhost /media/removable/Crouton/bin $ ls
crash_reporter_wrapper delete-chroot edit-chroot enter-chroot mount-chroot startunity unmount-chroot
chronos@localhost /media/removable/Crouton/bin $ cd enter-chroot
bash: cd: enter-chroot: Not a directory

Can't duplicate at will, seems to be intermittent.

However, tried this afterwards:

Tried this:
chronos@localhost / $ sudo edit-chroot -a

sudo: edit-chroot: command not found

chronos@localhost / $ sudo sh ~/Downloads/crouton -n Crouton -u

Downloading latest crouton installer...
######################################################################## 100.0%

/mnt/stateful_partition/crouton/chroots not found.
/usr/local/chroots/Crouton does not exist; cannot update.
Valid chroots:

chronos@localhost / $ sudo sh /media/removable/Crouton/bin

chronos@localhost / $ sudo sh ~/Downloads/crouton -n Crouton -u

/mnt/stateful_partition/crouton/chroots not found.

/usr/local/chroots/Crouton does not exist; cannot update.

So that seemed not to work but ... then when I retried 

sudo sh /media/removable/Crouton/bin/enter-chroot

I got the trusty prompt.

I typed startunity and, lo and behold, it worked and my ubunutu install was there again ...

will report it

**Comment by DennisLfromGA** [comment]
I noted a few possible problems with the above.

You `cd'd` to `/media/removable/Crouton` and listed the following:
 `bin chroots cron Crouton - Downloads lost+found vnc.txt web`

That looks okay, you have a `bin` and `chroots` folder, I'm not sure why you have another `Crouton` and `Downloads` folder in there though.

You then `cd'd` to `bin` and listed the following:
`crash_reporter_wrapper delete-chroot edit-chroot enter-chroot mount-chroot startunity unmount-chroot`

That looks okay too.
Next you tried to `cd` into `enter-chroot` but that won't work because it's a *script* not a *folder*.

You next tried: `sudo edit-chroot -a`
That failed because you didn't specify the PATH to enter-chroot.
Also, the '-a' option won't do anything without other options like '-l', etc.

Since you were in the `bin` folder, you could have entered: `sudo ./enter-chroot -al` to list your chroot(s) or even specified `sudo ./startunity` to start your Unity desktop. The './' prefix in those commands tells the shell to look in the current directory.

To update your chroot from anywhere, you could use: 
`sudo ~/Downloads/crouton -p /media/removable/Crouton -n Crouton -u`
assuming your chroot is named 'Crouton'

You can start your Unity desktop from anywhere using:
`sudo /media/removable/Crouton/bin/startunity`

If you have the scripts in your `/usr/local/bin` folder, you can also use:
`sudo startunity -c /media/removable/Crouton/chroots`

In the above examples, note the use of the full path and the use of `crouton's` '-p' and `edit-chroot's` '-c' options for specifying the location of you external media. 

Hope this helps,
-*DennisL*

**Comment by DennisLfromGA** [comment]
Please close this issue if the response above resolved your issue, if not, please give us more details. Thanx
