### ISSUE TITLE
This happens when ever I try to install crouton on my chromebook....

### ISSUE THREAD

**Issue by couln016** [dnschneid/crouton#2611]
I recently got a chromebook and I am currently trying to convert it to running ubuntu, I have followed the correct instructions but it always comes up with this:
crosh> shell
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -t unity
Downloading latest crouton installer...
###### ################################################################## 100.0%

/usr/local/chroots/precise already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.

Please help!

**Comment by DennisLfromGA** [comment]
@couln016,

You didn't show us the output of `sudo edit-chroot -all` so we don't know what you have installed or attempted to install or the device you have so it's hard to give you advice specific to your hardware.

The installation must have failed a time or two since it's telling you:
> **/usr/local/chroots/precise already has stuff in it!**
Either delete it, specify a different name (-n), or specify -u to update it.

It would probably be best to just delete the existing one with: `sudo edit-chroot -d precise`

Then, start the install over again with something like:

`sudo sh ~/Downloads/crouton -r trusty -t unity,extension`

Note: I prefer to use the 'trusty' release since it's an LTS and usually gives less trouble. Also, I didn't specify targets 'xorg' nor 'xiwi' since we don't know what device you're using.
I usually specify both so I can have a choice when running my desktop(s).

Hope this helps,
-**DennisL**

**Comment by niharxavier** [comment]
Try to powerwash your computer,(Back up your data!)

Then, redownload it

Hope this helps,
Nihar

**Comment by DennisLfromGA** [comment]
@niharxavier, 

A 'powerwash' is unnecessary and a waste of time, `delete-chroot` will be sufficient in this case.

-**DennisL**

**Comment by niharxavier** [comment]
Oh,
I did not know that.
Im just a small 10 year old boy.

Thanks anyway!

**Comment by chromeuser1** [comment]
Dennis, that was nice help thx!

**Comment by sweettttttt66666** [comment]
can someone help when i enter in Delete-chroot it just brings up options and idk what to do

**Comment by DennisLfromGA** [comment]
@sweettttttt66666,

Linux is case sensitive so 'Delete-chroot' will never work.
You can find the name(s) of your chroot(s) by running:
- `sudo edit-chroot -al`

Then once you know the name(s) of the chroot(s) you want to delete use this command:
- `sudo delete-chroot [chrootname(s)]`

Substitute 'chrootname(s)' above with your actual chroot name(s) and leave out the brackets.

-**DennisLfromGA**
