### ISSUE TITLE
Network hostnames cannot be resolved from inside crouton

### ISSUE THREAD

**Issue by wallace11** [dnschneid/crouton#2626]
```
name: freya
encrypted: no
Entering /media/removable/elementary/chroots/freya...
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,extension
host: version 8172.47.0 (Official Build) beta-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jun 1 23:05:52 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

Simply by pinging a network device by its hostname from chros you get a ping, but with the same command inside crouton you get "ping: unknown host" error.
Doing the same with IP addresses works on both ends. 

Various edits to the `resolv.conf`, `nsswitch.conf` or `avahi-daemon.conf` confirmed that the problem is not at this level. 

Using `mdns-scan` I could find _some_ devices on the network, but not others (and yes, they're all mDNS aka .local domains).

Following pages/discussions were reviewed and might help with the solution:
https://github.com/dnschneid/crouton/issues/2331
https://github.com/dnschneid/crouton/wiki/How-to-mount-network-shares-on-Chromebook-(sshfs,-cifs,-nfs-etc)
https://github.com/dnschneid/crouton/issues/393
https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton

**Comment by devanlai** [comment]
I ran into this issue recently and was similarly frustrated that all of the prior discussion I could find was focused on the case of spawning an avahi-daemon inside of the chroot to advertise a custom hostname or services. While that'd be great if I were planning to keep my chroot running all the time to host a server, I'm trying to use my Chromebook as a thin client, not as a development server, so that approach doesn't feel like the right fit to me.

Inspired by this [blog post](https://zwischenzugs.com/2018/06/08/anatomy-of-a-linux-dns-lookup-part-i/) on how Linux performs name resolution, I decided to run an strace and I notice that it was attempting to connect to the avahi-daemon socket, which is of course not running inside my chroot:
```
(buster)devan@localhost:~$ sudo strace -e trace=connect -f ping avernus.local
connect(5, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(5, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
connect(5, {sa_family=AF_UNIX, sun_path="/var/run/avahi-daemon/socket"}, 110) = -1 ENOENT (No such file or directory)
connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
ping: avernus.local: Name or service not known
+++ exited with 2 +++
```

Digging into `enter-chroot`, I added an extra binding for the avahi daemon socket modeled on the existing code for CRAS:
```bash
if [ -d /var/run/avahi-daemon ]; then
    bindmount /var/run/avahi-daemon /var/host/avahi-daemon
    # Add a /var/run/avahi-daemon symlink for mdns clients
    ln -sfT /var/host/avahi-daemon "$(fixabslinks '/var/run')/avahi-daemon"
fi
```

This seems to resolve the issue for me, allowing processes inside the chroot to connect to the host Chrome OS avahi-daemon for mdns name resolution. While I'm not sure about the security implications of doing it this particular way, it feels a lot less hacky than having to spawn and manage a second copy of avahi-daemon just to get mdns working.

For those that want to run their own avahi-daemon and operate as a server, the symlink from `/var/host/avahi-daemon` to `/var/run/avahi-daemon` could be removed from inside the chroot, allowing their own daemon to handle requests.
