### ISSUE TITLE
sudo command broken, message "sudo: must be setuid root"

### ISSUE THREAD

**Issue by calvinzhe** [dnschneid/crouton#2648]
```
sudo
```

#### Please describe your issue:
Whenever I try to use the sudo command, I get the message "sudo: must be setuid root"
I've found that it has to do with the fact that root is no longer owned by sudo, and the way to fix it (on normal Linux distributions) is to go into recovery mode and set the ownership of root to sudo.  However, how can I do this in crouton?

I am using ChromeOS on a Chromebook and it has xubuntu xfce4 installed.

#### If known, describe the steps to reproduce the issue:
I'm not exactly sure what caused this issue, but prior to getting the problem I was messing around with my environment variables, and testing to see if it worked by restarting a few times.  I believe the problem occurred right after I added JAVA_HOME variable to the bottom of the file ~/.bashrc and restarting.  I then could no longer see any of the mounted drives on my desktop like I normally would.  The Synaptic Package Manager would also not work.

I was also trying to use an ez_install.py file prior to the problem arising.

**Comment by tcagle** [comment]
Can't you use enter-chroot and remove your .bashrc file changes? Also what exactly was ez_install.py installing? I never run install scripts from unknown parties without making an effort to determine what they are going to try to do to my system so I can be prepared if something goes south. If you are uncomfortable with vi you can still install nano from an enter-chroot prompt:
sudo apt-get install nano
Also I think you meant to say "sudo is no longer own by root" instead of the inverse. Here is my working system...

(precise.pws)tim@localhost:~$ ls -ld /usr/bin/sudo
-rwsr-xr-x 2 root root 71280 Mar 12  2015 /usr/bin/sudo

The fourth character (the 's') is the sticky bit referred to in that error message. If yours is toasted I am not sure how to fix that short of reinstalling the chroot.
A wise man once told me: Blessed are the pessimists for they hath made backups. This is not really a crouton issue per se.... You have a crouton install that is now damaged somehow. You should probably close this issue and seek help here: https://plus.google.com/communities/109120069102230291151
Good luck,

**Comment by calvinzhe** [comment]
Sorry, I didn't exactly know where to go to get help so I came here.  Thanks.

**Comment by DennisLfromGA** [comment]
@calvinzhe,

You *can* access your chroot(s) directory structure from crosh; no need to use `enter-chroot` or a `start*` script. If your chroot is in the default location: `/usr/local/chroots`, then, for instance,  you could 'cd' into it using something like this -

`cd /usr/local/chroots/precise/usr/bin`

Then do: `ls -l sudo` and see if it's owned by root and the setuid bit is set, if not, try this:

`sudo chown root:root sudo; sudo chmod 4755 sudo`

It should look something like this when you're done:

`-rwsr-xr-x 1 root root 152K Aug 27  2015 sudo`

If your chroot is not 'precise' then adjust accordingly.

*Hope this helps,*
-**DennisL**

**Comment by calvinzhe** [comment]
Sweet, thanks DennisL, I fixed it.  I didn't know there was another sudo file within /usr/local/chroots/precise/usr/bin/, and that was the one that needed to be changed to root ownership.

I also had to change the ownership of the file sudoers.so in the folder
/usr/local/chroots/precise/usr/lib/sudo/
to root, as well as its write privileges to owner only using
`sudo chmod go-w /usr/lib/sudo/sudoers.so`
