### ISSUE TITLE
[Suggestion] Have a edit-chroot flag which can estimate the file size of a chroot backup

### ISSUE THREAD

**Issue by braeden** [dnschneid/crouton#2685]
For example when I backup my chroot I would love to be able to see the capacity of the .tar.gz file so that I can choose backup media appropriately. In the future I might write some code and submit a pull request for it... but for now, maybe someone has an easy solution. Thanks!

**Comment by kaymmm** [comment]
While I agree that this is potentially useful, it's not really practical because to know the size of the compressed archive requires actually processing the archive, which is slow and painful. It could be done with something like:
```
sudo tar -cz /mnt/stateful_partition/crouton/chroots/[name] | wc -c
```
but that takes forever unless someone knows of a better way of estimating compressed size without having to process the compression.

Perhaps a better option would be to print out the *maximum* size of the uncompressed archive, which is essentially just the size of the chroot directory: 
```
sudo du -h --max-depth=0 /mnt/stateful_partition/crouton/chroots/[name]
```
When I just ran these two commands, I got ~1.5gb for the tar vs. 2.4gb for the actual size of the chroot on disk. Adding shortcuts for either or both of these commands would be pretty trivial, but is it worthwhile and informative without being overly confusing for novices?

**Comment by DennisLfromGA** [comment]
@kaymmm - I agree that determining the size beforehand would not be practical.

I ran both commands on one of my chroots and got similar results, I also timed them -
> time sudo du -h --max-depth=0 /var/crouton/chroots/xenial-mate/
>> 6.0G    /var/crouton/chroots/xenial-mate/ 
>> real    0m0.687s (just milliseconds)

> time sudo tar -cz /var/crouton/chroots/xenial-mate/ | wc -c
>> 3600245987 (or 3.6GB)
>> real    4m51.038s (almost 5 minutes)

As you can see, it's quick and easy to get the chroot's size before compression but painfully slow to get the compressed size, so slow as to not be worth it in my opinion.

I was thinking it might be nice if `croutonversion` would report the chroot's size too.
You might be able to get it with something like: `sudo du -hx --max-depth=0 --exclude /Downloads /`
Failing that, maybe `edit-chroot` could have a '`-S`' option or something similar to show the chroot's size.

-**DennisL**

**Comment by DennisLfromGA** [comment]
Not relevant to this issue but crouton's author has suggested to: Add destination size test #2108

**Comment by DennisLfromGA** [comment]
Also, this won't help determine if you have enough space *beforehand* but there is a proposal to add backup and restore progress via pipeview, I'm afraid I started it over a year ago and kind of abandoned it - for a while... See https://github.com/dnschneid/crouton/commit/af4fa5807faaad5a90f957b5a7dc688582429796 for some of the development notes and such.

There is also another similar issue that shows the `pv` ('pipeview') command in use here https://github.com/dnschneid/crouton/issues/1655

Hope this helps,
-**DennisL**

**Comment by braeden123** [comment]
I wonder if we could approximate a worst case compression ratio (for a chroot) and multiply it by the chroot size to guess a final size?

**Comment by DennisLfromGA** [comment]
@braeden123 - We can, but I don't know if the crouton developers will want to.
I've kludged together something for my own use here - [chrootbu](https://goo.gl/VCNxZn)
It's very rudimentary and could use some cleanup but it seems to work for me.
