### ISSUE TITLE
c++ refrence

### ISSUE THREAD

**Issue by bellsk** [dnschneid/crouton#2687]
Hi :) 
I've written a function that writes  the time typed by a user in a .txt file using the    operator "<<" 
When I declare it this way :
 
// clockk is the name of the class 
void clockk::output(std::ofstream& b)
{
    b << m_hours << ":" << m_minutes <<":" << m_secondes <<"\n" ;
}
ofstream&  operator<<(ofstream& b,clockk time )
{
    time.output(b);
    return b;
}
 

When I try to compile it shows 
![sans titreim](https://cloud.githubusercontent.com/assets/20488461/16894029/1fe3ab7e-4b4a-11e6-864f-429b59ebb2de.png)

but when I use a refrence to the clockk object, things work 
// the same output method 
ofstream&  operator<<(ofstream& b,clockk& time )
{
    time.output(b);
    return b;
}

Why ?

**Comment by braeden123** [comment]
This issue is seemingly not related to crouton - see [this](https://www.google.com/search?q=iso+c%2B%2B+says+that+these+are+ambiguous&oq=iso+c%2B%2B+says&aqs=chrome.0.0j69i57j0l3.3516j0j4&client=ubuntu&sourceid=chrome&ie=UTF-8#safe=strict&q=iso%20c%2B%2B%20says%20that%20these%20are%20ambiguous%20even%20though%20the%20worst%20conversion%20for%20the%20first)

**Comment by drinkcat** [comment]
See #262.
