### ISSUE TITLE
Updating ubuntu on crouton so Kodi addons can work again.

### ISSUE THREAD

**Issue by hormosapiens** [dnschneid/crouton#2809]
```
Please paste the output of the following command here: sudo edit-chroot -all
localhost / # sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160518095657~master:fd37bb79
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8743.57.0 (Official Build) beta-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Oct 5 23:18:36 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue:
There is a need to update the ubuntu version from 12.04.5 (Precise) to newer versions. Kodi version of Precise is not supported anymore, hance the addons for kodi 14.2 are not working. Also, I cant delete crouton and install a new one. the only thing to do is a powerwash as I cant uninstall crouton. all commands in shell are not working or I am doing them wrong. Is there a "sudo" in front of every command?

Anyway, would be great to have a crouton with default install latest LTS with xfce.
Thanks for your work.

#### If known, describe the steps to reproduce the issue:

localhost / # croutonversion -u -d -c
bash: croutonversion: command not found

localhost / # sudo delete-chroot evilchroot
/mnt/stateful_partition/crouton/chroots/evilchroot not found.

or this:

localhost / # sudo edit-chroot -d evilchroot
/mnt/stateful_partition/crouton/chroots/evilchroot not found.

**Comment by DennisLfromGA** [comment]
@hormosapiens,

The `sudo edit-chroot -all` command you ran shows you have a chroot with the precise release and it is named precise. The evilchroot name shown in the README was just an example.

Use this to delete it: 

`sudo delete-chroot precise`

Also, the `croutonversion` command you show above needs to be run from within the chroot.

There are a number of releases that crouton can install -

```
Recognized debian releases:
    potato* woody* sarge* etch* lenny* squeeze* wheezy jessie stretch sid
Recognized kali releases:
    kali* sana* kali-rolling
Recognized ubuntu releases:
    warty* hoary* breezy* dapper* edgy* feisty* gutsy* hardy* intrepid* jaunty*
    karmic* lucid* maverick* natty* oneiric* precise quantal* raring* saucy*
    trusty utopic* vivid* wily* xenial* yakkety*
Releases marked with * are unsupported, but may work with some effort.
```

Note above that not all releases are supported yet.
The ubuntu xenial release is the latest LTS release but it still has some problems and is not fully supported in crouton as yet. I would recommend you install an ubuntu trusty chroot since it works well on most devices and is supported.

You can install a trusty chroot with the xfce4 desktop using: 

`sudo sh ~/Downloads/crouton -r trusty -t xfce,extension`

That command will also name your chroot trusty

*Hope this helps,*
-**DennisL**

**Comment by hormosapiens** [comment]
Best answer I've ever had.
Thank you for your answer and your work.

**Comment by DennisLfromGA** [comment]
Glad to help.

-**DennisL**
