### ISSUE TITLE
Can't open /home/chronos/user/Downloads/crouton

### ISSUE THREAD

**Issue by RioTheNinja** [dnschneid/crouton#2844]
```
Please paste the output of the following command here: sudo edit-chroot -all
sudo: edit-chroot: command not found
```

I'm trying to download Linux via Crouton (http://www.makeuseof.com/tag/install-linux-chromebook/), and after typing shell, I get this error:
![screenshot 2016-10-20 at 3 27 06 pm](https://cloud.githubusercontent.com/assets/22966495/19574774/b6d09bc0-96d9-11e6-89b4-f34e755b78e4.png)

**Comment by DennisLfromGA** [comment]
@RioTheNinja,

Step. 1 under the heading *'How to Install Linux as a Chroot Using Crouton'* was -
- Download Crouton to your device’s local hard-drive.

That's an important first step but they didn't mention where to get it.
Click on this link: https://goo.gl/fd3zc
That should open the 'Files' app and prompt you to save 'crouton' in your ~/Downloads folder.

That article is from 2014, a lot has changed since then in both Chrome OS and 'crouton'
I would recommend using the 'trusty' release now so instead of the command above use this instead:

`sudo sh ~/Downloads/crouton -r trusty -t xfce,extension`

*Hope this helps,*
-**DennisL**

**Comment by jywarren** [comment]
I was able to get it with `wget https://goo.gl/fd3zc` and then renamed `fd3zc` to `crouton`. Thanks!

**Comment by jywarren** [comment]
Took some moving of `crouton` around a bit since there's no linked directories, but I copied it onto an SD card and then ran it from outside the chroot. Worked!

**Comment by Cesandri89** [comment]
Thank you for your help
