### ISSUE TITLE
cursor issue after switch

### ISSUE THREAD

**Issue by giliammc** [dnschneid/crouton#2878]
i have an acer c910 core i3 4gb of ram and a 128gb ssd the output for sudo edit-chroot -all is
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161028111244~master:948ee6dc
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,xfce,extension,audio
host: version 8743.76.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 25 23:34:16 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

after switching back into my chroot my cursor turns into this 
![image](https://cloud.githubusercontent.com/assets/10850574/20224073/4ae703c4-a802-11e6-924f-704430a4530e.png) (sorry for the picture quality if i took a screenshot the cursor shows up as normal) if i change the resolution from 1920x1080 to something else and then back again this resets the cursor but if i switch to chrome and back again it reapers. thanks in advance for any help crouton is really great and the support community is one of the best.

**Comment by sunnyps** [comment]
I was able to reproduce this on my Dell Chromebook 13 (i3/8G) on trusty with unity and sid with gnome. I use a scaled resolution for ChromeOS (1536 x 864) and the chroot uses the default resolution (1920 x 1080). I thought it was related to GL accelerated desktops but @giliammc was able to reproduce this on XFCE which is not hardware accelerated by default.

**Comment by drinkcat** [comment]
Just to clarify, are you running crouton in a window (method `xiwi`?), or natively using method `xorg`?

**Comment by drinkcat** [comment]
@sunnyps : Can I have your output of `edit-chroot -all` as well?

**Comment by giliammc** [comment]
i was using xorg

**Comment by dnschneid** [comment]
This is crbug.com/482801 ...I thought there was a corresponding bug on the crouton tracker as well, but I can't find it at the moment.

**Comment by dnschneid** [comment]
Okay, sounds like this is going to need a fix on the crouton side.  Having chatted with the kernel graphics people, it sounds like the issue is that Chromium OS uses planes to render the cursor, while X11 uses the old cursor interface.

Whenever frecon grabs the display, the first thing it does is disable all of the planes on all of the crtcs.  See [drm_setmode](https://chromium.googlesource.com/chromiumos/platform/frecon/+/master/drm.c#503) in frecon (which calls drm_disable_non_main_crtcs -> drm_disable_crtc -> drmModeSetCrtc).  When Chromium OS regains master, it re-enables the relevant planes, so this is safe to do.

crouton can do the same thing in the [VT_ACTIVATE handler of freon.c](https://github.com/dnschneid/crouton/blob/master/src/freon.c#L130).  Right after the dbus method completes, nobody owns the DRM master, so freon.c could grab DRM master, disable all planes, and release DRM master before X11 picks it up.

The freon implementation, as well as [this overview](https://dvdhrm.wordpress.com/2012/09/13/linux-drm-mode-setting-api/) are probably good references.

**Comment by dnschneid** [comment]
Alternatively, as OP reports, changing the resolution seems to reset the planes, so maybe some other less-invasive xrandr command would have a similar effect.

**Comment by drinkcat** [comment]
Strange, I could not reproduce on chell (R56-8951.0.0).

**Comment by drinkcat** [comment]
But I could reproduce on samus R54-8743.85.0 (xenial xorg).

**Comment by drinkcat** [comment]
And on samus R56-8951.0.0, there is something special on chell (kernel 3.18?) that makes the problem disappear.

**Comment by dnschneid** [comment]
Try the latest version of crouton and see if it fixes things for you.

**Comment by bengolds** [comment]
I just upgraded my xenial chroot to the latest crouton and am still having this issue. This is on samus r54 though -- drinkcat, is your fix only available on r56? 
croutonversion shows: 1-20161129162558~master:5f2f11f9
