### ISSUE TITLE
Cycling between OS and chroots (Acer C730)

### ISSUE THREAD

**Issue by octopusnz** [dnschneid/crouton#2880]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161028111244~master:948ee6dc
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,unity
host: version 8743.83.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Wed Nov 2 23:41:41 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

The hardware is an Acer Chromebook 11 (C730).

I'm unable to cycle between my chroot and Chrome OS using Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward. 

#### Some things I have tried

chroot with and without keyboard targets
chroot with keyboard and extension targets (plus installing crouton extension in Chrome OS)
upgrading Chrome OS
upgrading crouton

#### If known, describe the steps to reproduce the issue:

I'm using sudo startunity from <del>crosh</del> bash
ubuntu loads happily
Then attempting the keyboard combination Ctrl+Alt+Shift+Back and then just in case Ctrl+Alt+Shift+Forward
Nothing happens

**Comment by DennisLfromGA** [comment]
@octopusnz,

Not sure what might be going on but <kbd>Ctrl+Alt+Shift+Forward</kbd> is the correct key combo.
You're using the latest version of both crouton and CrOS so that's not the problem.

This is not an elegant solution but you might be able to switch back to CrOS using: `croutoncycle cros`

Also, pressing the 'switch window key/F5' may present the CrOS window for selection.

I use the 'Autohide shelf' feature that pins the 'crouton integration' extension to the shelf and switch back & forth that way sometimes.

Please let us know if any of the above works or if you find a solution please share it.

*Hope this helps,*
-**DennisL**

**Comment by octopusnz** [comment]
@DennisLfromGA Thanks for taking a look!

I can report: 

croutoncycle cros does switch back to Chrome OS
Switch window/F5 key does not bring up any windows

I also tried the below in case it makes a difference as to whether I'm starting the desktop environment as root:
sudo enter-chroot
startunity

No change in behaviour.

Do let me know if there is any useful log file somewhere or anything I can enable to capture what happens when I press Ctrl+Alt+Shift+Forward inside the chroot?

**Comment by DennisLfromGA** [comment]
@octopusnz,

Okay, thanx for your results, maybe the devs will catch something not so apparent to us in the meantime.

*Hope this helps,*
-**DennisL**

**Comment by octopusnz** [comment]
Well after a bit more testing - this is actually a case of user error.
I've been switching successfully between OS and chroot for most of the day, so can safely say it is working as intended. No need for further investigation.

**Comment by DennisLfromGA** [comment]
Thanx for the feedback.
