### ISSUE TITLE
emacs commands for copying and pasting not working

### ISSUE THREAD

**Issue by qAp** [dnschneid/crouton#2907]
```
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: trusty1
encrypted: yes, unlocked
Enter encryption passphrase for trusty1: 
Entering /mnt/stateful_partition/crouton/chroots/trusty1...
crouton: version 1-20150519153807~master:30cf02c9
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,keyboard,chrome,core,unity
host: version 8743.85.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Nov 15 18:22:58 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty1...
```

So, normally in emacs, to copy a region and paste it somewhere else, the following are done:

1. Move cursor to the start of the region to be copied.
2. `ctrl-space` returns "Mark set"
3. Move cursor to the end of the region to be copied.
4. `alt-w`.  This copies the region
5. Move the cursor to where to paste the copied region.
6. `ctrl-y`. Pastes the text, and returns "Mark set".

However, in emacs in crouton, the above does not work:

1. Move cursor to the start of the region to be copied.
2. `ctrl-space` does not return "Mark set"
3. Move cursor to the end of the region to be copied.
4. `alt-w` returns "The mark is not set now, so there is no region"
5. Move the cursor to where to paste the copied region.
6. `ctrl-y` returns "Kill ring is empty"

Is there something in emacs or in crouton that can make this work?

**Comment by massma** [comment]
```
crouton: version 1-20161129162558~master:5f2f11f9
release: jessie
architecture: amd64
xmethod: xiwi
targets: extension,core,xiwi
host: version 8872.73.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:06:42 PST 2016 x86_64 GNU/Linux
freon: yes

```

I am having the same issue. For me it appears to be a problem with ```ctrl-space```. This behavior started for me either after upgrading to the newest crouton version version ```1-20161129162558~master:5f2f11f9``` or with an automatic Chrome OS upgrade. About a month ago I wasn't having the issue.

 ```ctrl-space``` works as it should if I ```alt-tab```  to switch to another window other than crouton-extension and then return to crouton-extension. However, after an indeterminate amount of time ```ctrl-space``` stops working. I haven't been able to identify a trigger that causes ```ctrl-space``` to stop working. At first I thought it was an issue with X-Term or Debian, but because it is temporarily fixed by switching to anther Chrome window and then back to crouton-extension it might be an issue with crouton or crouton-extension.

**Comment by mdwy62** [comment]
I am finding the same issue. For xubuntu with xorg, ctl-spc worked to set-mark-command in emacs (gui); while with xiwi, I think ctl-spc is being captured by ChromeOS (because it no longer works, in fact it starts to insert ever longer strings of spaces); Similarly, if I am in LibreOffice Calc, alt-s "should" open the Sheets drop down menu, but instead is being captured by a deprecated Signal extension I have on Chrome. Both of these occur in full screen mode under xiwi. I can switch back to xorg I guess. Is there a way to edit which key combinations ChromeOS keeps for itself rather than passing through to the chroot?
