### ISSUE TITLE
Linux Mint Support please!

### ISSUE THREAD

**Issue by monghimng** [dnschneid/crouton#2914]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Hi, please make linux mint support! My couple of friends and I all love Linux Mint, and it is such a common distro. Can crouton please be made to support it? Thanks in advance.

**Comment by DennisLfromGA** [comment]
It's been discussed a bit, see https://github.com/dnschneid/crouton/issues/2865.

There was a `cinnamon` target at one time but I believe it wasn't available on all hardware so it was dropped. There's talk of reviving it since it's now offered again on more platforms.

Maybe someday it will happen, who knows...
-**DennisL**

**Comment by darethehair** [comment]
I also would really appreciate a Linux Mint option -- for me specifically the LMDE (Linux Mint Debian Edition) version.  I was inspired by Tenn1518's github page on installing Cinnamon into crouton:

[https://github.com/Tenn1518/crouton-cinnamon](url)

Rather than the Ubuntu-flavored approach that he took, I opted for the pure Debian approach, and eventually created my own webpage (mostly for my own benefit):

[(http://darethehair.duckdns.org/dmenns/chromeos.html)]

With a few Mint touches, I have something that begins to look like the LMDE that I really want -- but I lack the information to go all the way.  Yes, it would sure save a lot of time in my multiple installs if I could do this all on the command line while installing crouton itself, but I am pleased with what I can make on my own with a bit of effort :)
