### ISSUE TITLE
unity xenial locale issue

### ISSUE THREAD

**Issue by jaimejimbo** [dnschneid/crouton#2921]
when installing xenial, gnome locales aren't installed by the script. It makes gnome-terminal not to work. It is fixed when installing language-pack-gnome-en language-pack-en packages.

**Comment by DennisLfromGA** [comment]
@jaimejimbo,

Do you know if this only pertains to the 'xenial' release?

-**DennisL**

**Comment by jaimejimbo** [comment]
I didn't have that issue with trusty, but I haven't tested the rest of releases.

**Comment by xxcriticxx** [comment]
i installed `language-pack-gnome-en` terminal still wont open i am forced to use `xterm` since day one

**Comment by jaimejimbo** [comment]
if you install all packages I listed before, it should work. you can try sudo dpkg-reconfigure gnome-terminal or something like that.

**Comment by xxcriticxx** [comment]
my terminal opens icon blinks gray purple gray purple and application auto close

i got few application that just blink and close by them self

**Comment by jaimejimbo** [comment]
oh, my terminal didn't even open. So perhaps is a video driver issue.

**Comment by xxcriticxx** [comment]
@jaimejimbo what chromebook you on? i will try installing drivers later?

**Comment by alexluecke** [comment]
@jaimejimbo I think this is purely a locale issue. I am almost certain I fixed the problem by making locales were installed:

    sudo apt-get install locales
    sudo dpkg-reconfigure locales

**Comment by jaimejimbo** [comment]
@xxcriticxx , @alexluecke i had to reinstall and now it doesn't work. I'm trying to fix it...

**Comment by jaimejimbo** [comment]
localectl set-locale LANG="en_US.UTF-8"

That fixed it

**Comment by xxcriticxx** [comment]
@jaimejimbo my still does the same blinks and auto close after language selection

**Comment by jaimejimbo** [comment]
have you tried running it from xterm? you can search for error message on google, that's how i fixed my issue.

**Comment by octopusnz** [comment]
I have the same issue after installing the xenial release.
You need to manually configure a default locale else gnome-terminal won't work.

I actually think it may be an issue with the default locale not being set by the installer in the xenial release (not just the gnome locale).
And my hypothesis is this is because the default locale set in the crouton script is not available when the script tries to complete this step.

My steps:

Install using something like: -r xenial -t unity
Run locale 
All default locale values appear empty
Run locale-gen - I can't be 100% sure unfortunately but I think US.UTF-8 was not installed at this stage.

To fix:

In my case I want another EN locale so I:

```
apt-get install language-pack-en
locale-gen
dpkg-reconfigure locale
choose my default locale
log out / restart unity
```

Then gnome-terminal will launch.

I can see this exciting looking piece of code in crouton/core.

```
# Generate and set default locale
if [ ! -f '/etc/default/locale' ] && hash locale-gen 2>/dev/null; then
    echo 'LANG=en_US.UTF-8' > '/etc/default/locale'
    locale-gen --lang en_US.UTF-8
    if [ "${DISTROAKA:-"$DISTRO"}" = 'debian' ]; then
        dpkg-reconfigure locales
    fi
fi

```

My thoughts: 

1. If the EN languages/locales are not being setup correctly with the xenial release do we need to install the en language pack before this step in the script? (might explain why this is failing if it is triggered).

2. Unsure how the script defines the $DISTRO variable but does debian include the xenial release? If not this might need a tweak to trigger something like dpkg-reconfigure locales for xenial too.

**Comment by xxcriticxx** [comment]
@jaimejimbo i run all from xterm since terminal wont open

**Comment by xxcriticxx** [comment]
@jaimejimbo all working had to restart

**Comment by asabatelli** [comment]
I'm having this issue running Gnome via crouton.  The problem is that I can't even get UXTerm to open, so have no way within Gnome to address the issue.  Is there something I can do from the crosh/shell in Chrome OS to address this?  (I'm not super tech savvy, sorry...)

**Comment by asabatelli** [comment]
Figured it out after more searching.  for anyone else as new to this as me, from chrome os do the following.  Ctrl-alt-t, then type shell, then "sudo enter-chroot"... From here, you are basically in a terminal for gnome (or whichever distro you're using).
