### ISSUE TITLE
Faulty regex used for release detection

### ISSUE THREAD

**Issue by keidax** [dnschneid/crouton#2922]
The `sed` command on line 23 of [`getrelease.sh`](https://github.com/dnschneid/crouton/blob/master/installer/ubuntu/getrelease.sh) assumes that `main` will always be first in the list of distribution components. However, when using Ubuntu (particularly Synaptic) the order of components in `/etc/apt/sources.list` sometimes change, and `main` is no longer the first component. This may very well be an Ubuntu bug, but I think it would make sense for crouton to adopt more lenient behavior here.

This handling of the release detection has contributed to other users' issues in the past (e.g. #1293, #2521, #2272).

**Comment by w-barath** [comment]
Since the regex is incapable of parsing the sources.list [specification](http://manpages.ubuntu.com/manpages/yakkety/man5/sources.list.5.html), the script should either be rewritten to be able to parse the spec or it should simply not make the attempt to read sources.list in the first place.

Nowhere in the spec does it begin to suggest that "main" should even exist so using it as an anchor for a field is bogus.

This works better:
```
sed -n 's|^deb .*://[^ ]* \([^ -]*\).*$|\1|p' /etc/apt/sources.list
xenial
xenial
xenial
xenial
xenial
xenial
xenial
xenial
xenial
xenial

```

There's also other, easier, ways to get the release:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

```
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```
