### ISSUE TITLE
after enabling "debugging" and setting root password i am unable to access root in developer mode

### ISSUE THREAD

**Issue by Sapper-1cd** [dnschneid/crouton#2927]
```
acer chromebook 11 cb3-111 in developer mode
```

#### Please describe your issue:
I power washed and enabled debugging features.  Now i can't access root in developer mode.
No previous password I have set will work to access root.  The password i set when i enabled debugging doesn't work.  Nothing seems to work including test0000, enter, chronos...and all previous passwords.

Sorry, i am a linux noob and have attempted to research the issue but continue to fail.
Thank you for any help.

**Comment by Sapper-1cd** [comment]
After changing from stable to developer and then finally to beta channel...it appears to have fixed the issue.  Can access root immediately now without even a prompt for password with sudo bash.

**Comment by DennisLfromGA** [comment]
@Sapper-1cd,

Wow, glad you got it going.
Moving from the 'dev channel' (less stable) to the 'beta channel' (more stable) will force a powerwash so that's what fixed it.

That has happened to me also, I *did* set a password but it didn't take.
I think the ['Debugging features'](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features) option needs some debugging. :-)

I don't know if you were just experimenting with it or you needed to remove rootfs verification, etc.
If you just need to set a password you can use: `sudo chromeos-setdevpasswd`
If you need to remove rootfs verification, see ['Making changes to the filesystem'](https://www.chromium.org/chromium-os/poking-around-your-chrome-os-device/#TOC-Making-changes-to-the-filesystem). I also have a [script](https://gist.github.com/DennisLfromGA/6690677) that does it too.

*Hope this helps,*
-**DennisL**

**Comment by Sapper-1cd** [comment]
Thanks Dennis.  After i changed channels I ran across a video.  The maker of the video discusses how to go into vt2 and modify your password after enabling debugging features.  This is several minutes in.  https://youtu.be/vjwPuYRKEOE...approximately 7:30-9:00 min mark.  Evidently you can use the root password you set when you enabled debugging in vt2 and then modify it.

**Comment by OneEye237171** [comment]
Having same problem , this HP Chromebook has an issue it never asks to set a passwd when I turn on debugging but also my passwd when I do set one in the terminal set-devpasswd itll work for a couple logins but it never holds , I go to log in to a terminal later that day or next and the passwd is just not working , its been doing this since I bought it , Its getting a litttle old power washing my work away . Im actually locked out right now and its annoying me because I lost my awesome idea I was going to add to this chromebook build Im working on . Thanks for any advise anyone can give .
