### ISSUE TITLE
Crouton wont make visable files and directory when installing to sd card  

### ISSUE THREAD

**Issue by Jumpshawt** [dnschneid/crouton#2947]
```
Please paste the output of the following command here: sudo edit-chroot -all
sudo: edit-chroot: command not found
```
it says this because the command is on the sd card, i might need to install crouton on the ssd
#### Please describe your issue:
i have a 64 bit procecer btw
my sd card is in the ext4 format and i got crouton on it but it didn't make any directory so when i do
`sudo sh '/media/removable/unity/bin/unity'`
it pops up with `sh: Can't open /media/removable/unity/bin/unity`

if i cd to `/media/removable/unity` and press tab it can't find any other directory's 
and nothing shows up in the file browser 
I also have tried
```
cd "/media/removable/SD Card/"
sudo ./bin/startxfce4 -n trusty
```

`ls -l /media/removable/`
after it install it does take up room on the sd card even though there is no directorys or files that are visible

i dont have any chroots on the chromebook because i did a power wash recently 
#### If known, describe the steps to reproduce the issue:
I did
`sudo sh -e ~/Downloads/crouton -r trusty -t xiwi,unity -p '/media/removable/unity'`
then 
`sudo sh '/media/removable/unity/bin/unity'`
and it says 
`sh: Can't open /media/removable/unity/bin/unity`

**Comment by DennisLfromGA** [comment]
@BluesparkYT,

> sudo sh -e ~/Downloads/crouton -r trusty -t xiwi,unity -p '/media/removable/unity'

crouton makes a `chroots` folder under the path you give it so, in all likely hood, the path to your chroot is:

`/media/removable/unity/chroots/unity`

And to launch your desktop enter: `sudo sh /media/removable/unity/bin/startunity`

*Hope this helps,*
-**DennisL**

**Comment by BluesparkYT** [comment]
@DennisLfromGA like i said before there isn't folders or files visible at all, so i guess i will try formating my sd card again then trying to reinstall and getting a new installer :/

**Comment by DennisLfromGA** [comment]
@BluesparkYT,

> my sd card is in the ext4 format and i got crouton on it but it didn't make any directory so...

> after it install it does take up room on the sd card even though there is no directorys or files that are visible

Since both of those statements include some pretty conflicting info. I thought I'd make the suggestions I did.
I would just double-check to be sure that *nothing* was installed on your Chromebook under `/usr/local`.

At this point, I think I would re-format the SD Card (as ext4) and then start over -
- plug-in your SD Card
- Look under `/media/removable` to see what name/mountpoint it's using
- Use crouton's '-p' option to specify where you want to install it:
```
-p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
```

I've done this before and haven't had any such problems, it works.
Also, when launching your desktop(s) or using `enter-chroot` be sure to use the '-c' option to specify the location of your *chroots*:
`  -c CHROOTS  Directory the chroots are in.`

*Hope this helps,*
-**DennisL**
