### ISSUE TITLE
Cannot enter chroot (no gui) running on HP Chromebook 11-1101

### ISSUE THREAD

**Issue by drrobotnic** [dnschneid/crouton#2959]
Output of `sudo edit-chroot -all`
```
name: precise
encrypted: yes, unlocked
```
OS was running fine until today. Instead of getting booted into gui, i get a terminal prompt. I put down the usual
```
$ sudo enter-chroot
Mounting /mnt/stateful_partition/crouton/chroots/precise
/mnt/stateful_partition/crouton/chroots/precise does not appear to be a valid chroot
Unmounting /mnt/stateful_partition/crouton/chroots/precise
```

changed directory into the chroot found a bunch of encrypted files instead of usual files
Any help would be appreciated

EDIT: in case this is useful. `/mnt/stateful_partition/crouton/chroots/precise` shows a bunch of
`ECRYPTFS_ENCRYPTED_FNEK` files. Had no idea where this came from, but takes up a ton of space

**Comment by DennisLfromGA** [comment]
@drrobotnic,

> name: precise
encrypted: yes, unlocked

Your chroot *is* encrypted, you may have done this inadvertently by specifying crouton's '-e' option when installing or updating. You should have been prompted for a password, if so that's the one you need to open it each time. If you don't know the password you won't be able to get into your chroot and you may have to delete it and install a new one.

*Hope this helps,*
-**DennisL**

**Comment by drrobotnic** [comment]
It is encrypted. There is no password though.

**Comment by DennisLfromGA** [comment]
@drrobotnic,

> It is encrypted. There is no password though

Do you mean there is no **_known_** password?

> /mnt/stateful_partition/crouton/chroots/precise does not appear to be a valid chroot

It looks like something has corrupted your chroot so you may have to delete it and install a new one.

*Hope this helps,*
-**DennisL**

**Comment by drrobotnic** [comment]
Just going to try to delete the chroot and install a new one
