### ISSUE TITLE
Crouton booting from USB is newly broken (suspend/resume triggers fatal filesystem unavailability)

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#2980]
```
Cannot run edit-chroot, it hangs
```

#### Please describe your issue:

A recent update to ChromeOS broke suspend-resume for Crouton-on-USB build which was working for more than a year. 

On a Toshiba Chromebook CB30-B-104 I have been successfully running a build of crouton running from a low profile USB key for what must be a lot more than 12 months. An X session could survive a suspend/resume cycle and filesystem remained available.

However, a recent update to ChromeOS seems to have caused USB keys to be detached and file handles to be corrupted during a suspend resume cycle, in such a way that the filesystem cannot be unmounted using...

```sudo unmount /media/removable/crouton```

...which declares the filesystem is not mounted, even though the path /media/removable/crouton remains in the system after the suspend/resume cycle.

BTW if Google is reading this, it is really broken even for regular users as all folders on the mounted key disappear and it is impossible to unmount or remount the folder. Unplugging it forcibly and replugging it makes it appear as ```/media/removable/crouton\ 1``` and from then on all operations relating to the chroots hang, even when the ```-c``` flag is passed with the new chroot path, suggesting something is very wrong with mounted filesystems.

#### If known, describe the steps to reproduce the issue:

Accept an upgrade from Google, yet again have stability and features removed! The issue has survived a full powerwash and reinstallation of Crouton.

**Comment by FrobozzElectric** [comment]
I'm also seeing this issue on the same model Chromebook when running chroot from USB.

**Comment by Goldshot21** [comment]
Same here

**Comment by sebrobin** [comment]
Same here, it surely happens on all models, I have a Pixel 2. Very annoying.

**Comment by DanPete** [comment]
I believe I am having a similar problem since the ChromeOS 55 update. ChromeOS also crashes when suspend/resume cycle fails in crouton.

**Comment by dConall** [comment]
Same problem on my toshiba cb30-b-104

> name: trusty
encrypted: no
Entering /media/removable/USB/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.50.0 (Official Build) beta-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jan 4 21:54:43 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB/chroots/trusty...

**Comment by DennisLfromGA** [comment]
Not a perfect solution but, as a workaround, you might try the ['Keep Awake'](https://chrome.google.com/webstore/detail/keep-awake/bijihlabcfdnabacffofojgmehjdielb) extension using it in the 'sun' or 'sunset' mode.

**Comment by FrobozzElectric** [comment]
Any update on Google fixing this?

**Comment by DennisLfromGA** [comment]
@FrobozzElectric,

> Any update on Google fixing this?

Yup, this'll be rolling out in a future release:

- ['New Power Saving Options Coming To Chromebooks'](https://chromeunboxed.com/new-power-saving-options-coming-to-chromebooks/)

*Hope this helps,*
-**DennisL**

**Comment by DanPete** [comment]
Possible solution to this problem also https://github.com/dnschneid/crouton/issues/288

I got it to work by using umount and mount on my USB drive.

**Comment by Jackhford** [comment]
DennisLfromGA--
I haven't bothered you in a while. I'll bet you missed me. :} 

I have a San Disk Ultra Fit 128 GB USB drive with 2 partitions of about equal size: Ext4 and Fat32, and I moved my chroot to the Ext4 partition. The problem is that when I reboot a screen appears that says the USB drives (it shows 2 drive images as if it knows there are 2 partitions) do not contain an OS. My OS has actually been wiped. My only option is to insert my other 4 GB USB recovery drive and do a restore. What am I missing here, Dennis?
Thanks again for your help. I hope all is well with you and yours in GA.

**Comment by DennisLfromGA** [comment]
@Jackhford,

What are you trying to do, restore your Chromebook or just use the external media for your chroots?
I may be missing something but I'm not sure what's going on.

> The problem is that when I reboot a screen appears that says the USB drives (it shows 2 drive images as if it knows there are 2 partitions) do not contain an OS. My OS has actually been wiped.

Are you pressing <kbd>ctrl</kbd>+<kbd>U</kbd> or <kbd>ctrl</kbd>+<kbd>L</kbd> when you get the 'scary' screen or do you just press <kbd>ctrl</kbd>+<kbd>D</kbd> to get the sign-in screen?

If your Chromebook can boot before you insert the USB drive then booting up with it inserted shouldn't wipe out Chrome OS on your device. Once you login it should show you the partitions mounted when you open the Files app.
I would recommend you only insert the USB drive after you sign-in if you're using it for your chroots.

I'm pretty sure most if not all San Disk drives have a hidden partition.
In Chromebook Central, we *always* tell users to erase the media before attempting to use it for a recovery image or anything else. Whatever's on that hidden partition may be what's causing the OS to get wiped or confused.

*Hope this helps,*
-**DennisL**

P.S. All is well, thanx for asking.

**Comment by Jackhford** [comment]
Just use the external media for my chroots.
I press ctrl+D to get past sign-in screen.
I can boot before inserting the USB drive, but booting with the USB drive inserted destroys the OS.

I can boot and then insert the USB drive, but I really wanted to keep the USB drive installed. Any ideas on how to do this without destroying the OS?


thanks

**Comment by DennisLfromGA** [comment]
@Jackhford,

> Launching xfce located on external media requires the -c parameter, as I understand, but it's a pain in the butt.  Any ideas on how to do this without destroying the OS?

Yes, I think there is something on the San Disk drive causing it, probably in a hidden partition.
I'd backup everything on it and then erase it entirely, add a new partition table and reformat it again.

----
> Is there a way to simplify this using an alias, a link, a shortcut, editing a script, etc.

Yes, using one or more of the above would work.
I like to use aliases, I put them in a `.cros_aliases` file and invoke them in my `.bashrc` file like this:
```
# Alias definitions for Cr-48 and others
[ -f ~/.cros_aliases ] && . ~/.cros_aliases
```

And my `.cros_aliases` file contains the following entries & more:
```
alias edchroot='sudo edit-chroot -c /var/crouton/chroots'
alias enchroot='sudo enter-chroot -c /var/crouton/chroots'
alias unchroot='sudo unmount-chroot -c /var/crouton/chroots'
alias stlxde='sudo startlxde -c /var/crouton/chroots'
alias stunity='sudo startunity -c /var/crouton/chroots'
alias stxbmc='sudo startkodi -c /var/crouton/chroots'
alias stxfce4='sudo startxfce4 -c /var/crouton/chroots'
alias stxiwi='sudo startxiwi -c /var/crouton/chroots'
```

I have a custom partition on my Chromebook to store all of my chroots, backups, etc. so mine, above, will look different than yours.  Yours would probably look something like this:

`alias stxfce4='startxfce4 -c /media/removable/USB128EXT4/chroots'`

*Hope this helps,*
-**DennisL**  

**P.S.** This is a little off topic from the OP's issue but it may be of some benefit still.

**Comment by Jackhford** [comment]
-Dennis L
First, what editor is usable in crosh? I know about Vim and Qemacs and hate both of them. I'm a Nano person.
Second, I want to take your suggestion and create a .cros_aliases file (again, I don't know what editor to use) and

**Comment by DennisLfromGA** [comment]
@Jackhford,

First:
I use the built-in 'vi' editor but it's not for everybody.
According to '[this reply](https://groups.google.com/a/chromium.org/d/msg/chromium-os-discuss/VW7KxnMVWs4/X1f4FZM9d-cJ)' you can get 'nano' by running the `dev_install` command.
Please be forewarned, in my experience `dev_install` will wipeout anything in/under `/usr/local` so **backup** first.
 
Second:
You could use your preferred editor in a chroot and copy things to ~/Downloads then exit your chroot and move your `.bash_aliases` file into ~/ 

*Hope this helps,*
-**Dennis**

**Comment by Jackhford** [comment]
@Dennis L
I followed your instructions and reformatted my SanDisk Ultra Fit 64 GB USB thumb drive. I created to relatively equally sized partitions, "crouton" [Ext4], which is apparently /sda/sda1 and "Storage [Fat 32], which is /sda/sda2. I also created a "chroots" directory in "crouton."
chronos@localhost /media/removable/crouton/chroots $ lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda             8:0    1 115.7G  0 disk 
├─sda1          8:1    1  64.2G  0 part 
└─sda2          8:2    1  51.6G  0 part 
loop0           7:0    0   7.3G  0 loop 
└─encstateful 253:1    0   7.3G  0 dm   /mnt/stateful_partition/encrypted
loop1           7:1    0 396.9M  1 loop /run/containers/android_rWdyyx/root
loop2           7:2    0  49.2M  1 loop /run/containers/android_rWdyyx/root/vend
loop3           7:3    0     4K  1 loop /opt/google/containers/arc-removable-med
loop4           7:4    0     4K  1 loop /opt/google/containers/arc-sdcard/mountp
loop5           7:5    0     4K  1 loop /opt/google/containers/arc-obb-mounter/m
zram0         252:0    0   5.6G  0 disk [SWAP]
mmcblk0rpmb   179:48   0     4M  0 disk 
mmcblk0boot0  179:16   0     4M  1 disk 
mmcblk0boot1  179:32   0     4M  1 disk 
mmcblk0       179:0    0  29.1G  0 disk 
├─mmcblk0p1   179:1    0    25G  0 part /mnt/stateful_partition
├─mmcblk0p2   179:2    0    16M  0 part 
├─mmcblk0p3   179:3    0     2G  0 part 
├─mmcblk0p4   179:4         16M  0 part 
├─mmcblk0p5   179:5          2G  0 part 
├─mmcblk0p6   179:6        512B  0 part 
├─mmcblk0p7   179:7        512B  0 part 
├─mmcblk0p8   179:8         16M  0 part /usr/share/oem
├─mmcblk0p9   179:9        512B  0 part 
├─mmcblk0p10  179:10       512B  0 part 
├─mmcblk0p11  179:11         8M  0 part 
└─mmcblk0p12  179:12        32M  0 part 
mmcblk1       179:80   0  59.5G  0 disk 

I decided to create the symbolic link from /media/removable/crouton/chroots to /usr/local/chroots next, but can't seem to get the syntax right.

chronos@localhost /mnt/stateful_partition/crouton/chroots $ sudo edit-chroot trusty -l /media/removable/crouton/chroots chroots
Invalid chroot name '/media/removable/crouton/chroots'.

Should I have moved the chroot "trusty" to /media/removable/crouton/chroots before creating the link? Or can the link be created either before or after doing so?

And now I can't even launch "trusty." Sorry.
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-16037-gf59ef0b48a68 #1 SMP PREEMPT Mon Nov 13 16:34:36 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=2d0ca73d-d3bc-c34e-b19b-1afae8504f11/PARTNROFF=1 hashtree=PARTUUID=2d0ca73d-d3bc-c34e-b19b-1afae8504f11/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=a6a501cdb3158ff186d009b8a63e8fba56a47344 salt=6d5e898897dd649af64eea278004bfd4bda5022c225754c5bb69e71d177b3747" noinitrd vt.global_cursor_default=0 kern_guid=2d0ca73d-d3bc-c34e-b19b-1afae8504f11 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 13 October 2017  01:59:06PM
xorg-server 2:1.15.1-0ubuntu2.11 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Dec 27 16:18:35 2017
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20171122220410~master:99877eaf
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,core,audio,xorg,x11,gtk-extra,extension,chrome-beta,xfce,keyboard
host: version 9901.77.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-16037-gf59ef0b48a68 #1 SMP PREEMPT Mon Nov 13 16:34:36 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Cannot open /sys/class/tty/tty0/active: No such file or directory
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from https://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/trusty...
