### ISSUE TITLE
Kernel Version Not Supported

### ISSUE THREAD

**Issue by dio1911** [dnschneid/crouton#3008]
Following error produced on a Samsung Chromebook 3.  Trying to install kernel headers on chroot (trusty) to support installation of virtualbox.
```
sudo sh setup-headers.sh

Your kernel version 3.18.0-13436-g8b496ef with architecture amd64 is not supported
```

How can I obtain support for kernel version 3.18.0-13436-g8b496ef?

**Comment by divx118** [comment]
First, vitualbox modules are currently broken on chromebooks see https://github.com/divx118/crouton-packages/issues/45 Also if that is fixed it will be a pain to keep support for the newer 3.18.0 kernels since they use a subversion now which with each chrome update is changed. I would suggest enabling USB boot and install a legacy linux version on a fast USB stick or SD-card to dual boot into. Then you can have your own kernel.
