### ISSUE TITLE
sudo starte17: e17 black screen issues

### ISSUE THREAD

**Issue by tastyminerals** [dnschneid/crouton#3055]
I decided to install **e17** because it is the smallest UI supported.
`sudo sh crouton -t e17 -r trusty`
After setting UNIX password the installation is complete and I `sudo starte17`.
The desktop flashes and I can see Enlightenment setup screen. I click "Next" the screen goes black and I can only hard reset from here. I start **crosh** again, enter shell, `sudo starte17`, switching to Enlightenment DE again, I can now proceed with setup further. Once I click the last "Next", the screen goes black and I have to `ctrl+shift+alt+f1`.
Sign, I had the same issue a year ago and hoped that it was resolved, actually this happened to all targets except **xfce**. Only **xfce** worked and works for me without black screens. No other DE are working reliable enough to install them.

So, I have a question, is it something that caused by my particular chormebook model (Toshiba Chromebook 2) or just a normal **crouton** behavior that everyone is aware of but just accepts?
The issue is hiding somewhere here however:
```
ESTART: 1.62602 [0.00008] - SLEEP
conf->card in mixer sys setup is NULL
ESTART: 1.62731 [0.00129] - SLEEP
ESTART: 1.62942 [0.00211] - SLEEP
ESTART: 1.63018 [0.00076] - SLEEP
ESTART: 1.66693 [0.03675] - SLEEP
ESTART: 1.67298 [0.00606] - SLEEP
ESTART: 1.67492 [0.00194] - SLEEP
ESTART: 1.68747 [0.01255] - SLEEP
INF<e>e_xkb.c:22 Setting keyboard layout: us|default|basic
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
```

**Comment by DennisLfromGA** [comment]
@tastyminerals,

Good questions, I don't have good answers.

I would suggest you try the 'xiwi' xmethod to see if your issue is just an 'xorg' problem.
You can add 'xiwi' to your existing chroot using this:

`sudo sh ~/Downloads/crouton -n trusty -t xiwi -u`

You'll also need to install the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension from the Chrome Webstore.

Then start it the usual way with: `sudo starte17`
That will launch it in a 'xiwi' window by default.

To use 'xorg' again, launch it with: `sudo starte17 -X xorg`

*Hope this helps,*
-**DennisL**

**Comment by tastyminerals** [comment]
Yeah, I thought about that. Unfortunately xiwi is pretty sluggish even on not very weak Celeron based chromebook. Will definitely try it later. I think crouton is not the reason after all but **e17** is. I managed to install **lxde**, it works now. Closing.
