### ISSUE TITLE
Ubuntu 12.04 LTS goes EOL soon

### ISSUE THREAD

**Issue by tsimonq2** [dnschneid/crouton#3108]
Ubuntu 12.04 LTS will reach EOL soon (around 2 months) and be unsupported by Ubuntu/Canonical. We really need to stop using that as the default crouton instance and use either 14.04 or 16.04 instead.

What needs to happen for this change to be made?

Pinging @dnschneid as this an issue essential to the project.

**Comment by dnschneid** [comment]
Yeah, the plan is to migrate to 16.04 sometime in March.  It's looking like Unity on ARM is a lost cause.

We should also spit out help text when entering a chroot that their distro is EOLing and they need to run [X, Y, and Z](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release).  That page should probably be improved, since we'll likely be grabbing the process from there.

**Comment by dnschneid** [comment]
16.04 is now the default release...on April 1st I'll mark precise as EOL'd.
