### ISSUE TITLE
tablet mode: minimizing xiwi window leads to keyboard always up in chroot.

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3147]
I have a very annoying issue when using crouton while in tablet mode. When tapping anywhere inside the chroot the on screen keyboard pops up and remains up. I can dismiss it but once I tap anywhere inside the chroot again the problem repeats itself.
I have played around to further try to understand what's happening. Some of what I noticed:
only happens in xiwi not xorg
the issue doesn't happen right away when I log into a chroot, but after a period of time
not sure about this, but there might be an error in crosh that corresponds to when this issue starts happening.

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170309181220~master:a72a0cb5
release: xenial
architecture: arm64
xmethod: xiwi
targets: keyboard,xiwi,xorg,touch,xfce-desktop,chrome
host: version 9334.5.0 (Official Build) dev-channel elm
kernel: Linux localhost 3.18.0-13933-gc7d2791 #1 SMP PREEMPT Thu Mar 9 21:16:05 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes

**Comment by ricprata** [comment]
Seriously am I the only one who has this issue on a touchscreen chromebook? It's been really irritating using my chroot as xiwi because the onscreen keyboard takes up half the screen space when I flip the keyboard back. Plus it covers up the task bar, making it difficult to navigate.
How is the keyboard supposed to work in a xiwi chroot then? Willing to hear from anyone who has a touchscreen chromebook or the R13.
Additionally if I don't install the keyboard target the issue starts right away. With the target it takes a little time before it starts.

**Comment by ricprata** [comment]
I should add that this happens in multiple crouton configurations, no matter the desktop.
I've identified when my issue happens: when the chroot window is collapsed then brought back up again. So this must be a bug with the keyboard or the extension. Any comments on this?

**Comment by DennisLfromGA** [comment]
@ricprata,

I don't have an R13 so I can't test it myself. I guess it's falsely triggering tablet mode or something.

What happens if you just close the window/tab altogether then re-open it using the crouton integration extension?

*Hope this helps,*
-**DennisL**

**Comment by drinkcat** [comment]
Well, we haven't spend a lot (any) time looking at crouton in tablet mode, so, yeah, it's probably quite broken. I'm not sure why the keyboard pops up, and I'm sure it'd be quite tricky to make it appear at the right time (i.e. when you really want to use it).

Somebody will need to investigate...

**Comment by ricprata** [comment]
> What happens if you just close the window/tab altogether then re-open it using the crouton integration extension?

When I do that the problem goes away until the xiwi window is collapsed again.

> Well, we haven't spend a lot (any) time looking at crouton in tablet mode, so, yeah, it's probably quite broken.

I'd assumed, with many of the latest chromebooks being convertibles, having crouton work well with tablet mode would've been worked on. But I understand fixes can take time so I can/am willing to wait if that's the case.

> I'm not sure why the keyboard pops up, and I'm sure it'd be quite tricky to make it appear at the right time (i.e. when you really want to use it).

Which is why I wouldn't mind if the keyboard never appeared inside the chroot at all. I wouldn't mind downloading Onboard and using that instead.

@dnschneid not sure if it's related. I went into XFCE's settings and set the keyboard model to chromebook. I'm using English so I thought that's all I needed to set up the bindings?

**Comment by ricprata** [comment]
I found some info that may give more background on this issue. When I'm inside the chroot and flip the keyboard back it still works. (I'd thought the keyboard disable itself was hardware-based not software.) This seems to explain the problems in Xiwi (chromium is trying to turn off the keyboard while Linux is trying to use it).
I found the following script which seems to address this specific issue: https://gist.github.com/ninlith/d0b56676c09b9d3142266c20c833d3da
However I'm thinking it was designed solely for the R11 because I get `unable to find device AT Translated Set 2 keyboard` when trying to run it. This keyboard name doesn't appear under `xinput list`.
I don't know enough about coding to know how to fix this.

**Comment by DennisLfromGA** [comment]
@ricprata,

That script is a good find and may be what is needed.

I think you may just need to change one line ([L187](https://gist.github.com/ninlith/d0b56676c09b9d3142266c20c833d3da#file-tablet_mode-py-L187)) in the script to the value reported for your keyboard to make it work. The script has defined the *'base_input_devices'* as *"AT Translated Set 2 keyboard"* so you would change that line to what `xinput list` shows for your keyboard, I'm thinking.

My Dell CB without a touchscreen shows the following for `xinput list`:
```
(trusty)denny@localhost:~$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ <default pointer>                       	id=6	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
```
So it's identified as `"Virtual core XTEST keyboard"` in my case.

*Hope this helps,*
-**DennisL**

**Comment by ricprata** [comment]
I have that listed as well. When I run the script after using your suggestion the result is `INFO __main__ - Enabling input from base...`. However it stays stuck on that.
There were two others listed (gpio-keys and cros_ec). Same results.
Initially when I tried the script it asked for a module named `numpy`. I thought I'd installed it but honestly all the stuff about python is confusing. I could've done something wrong for all I know.

**Comment by DennisLfromGA** [comment]
@ricprata,

Thanx for that info.
The more details like that the better & quicker things will get fixed.

Since convertibles are getting more popular, these kinds of issues will probably pop up more often.
I've seen problems with the touchpads & touchscreens on these devices upstream so some of them aren't 'crouton' problems as such.

Hopefully both the 'crouton' & 'CrOS' devs will get some time to try & reproduce these issues and figure out what to do about them. 

-**DennisL**

**Comment by ricprata** [comment]
Interesting that you mention the touchscreen. Its feedback response is weird. When using Onboard, for instance, each press on a key types the letter twice. It works perfectly however when I switch the input event source from xinput to gtk. Since the touchscreen and touchpad are both xinput devices, I suspect the problem lies there.

**Comment by rdft4e** [comment]
Hi,
I confirm exactly the same behavior. It is a asus flip c100. Meanwhile in chrome os the virtualkeyboard appears correctly when needed, inside the crouton xiwi window, it is constantly appearing. Furthermore, this virtual keyboard is useless for this debian croutonized and i use an installed via apt virtual keyboard. Please, if you need more info of my system let me know what command I havet to type.

Finally, I guess that the ninlith python script has to be run in a chrome os shell? or inside crouton?

**Comment by AsixJin** [comment]
Has anyone found a solution to this yet? I am experiencing this on my Pixelbook.

**Comment by rdft4e** [comment]
Now this problem has made the Asus flip C100 unusable in tablet mode. 

Previously, @DennisLfromGA 's trick of closing the crouton window and reopening from the extension link had worked. Now this trick doesn't work anymore. By the time the chrome screen keyboard appears in the chroot, the applications inside the chroot become unresponsive.  

Please, I would need help to be able to install the ninlith/tablet_mode.py script if it is useful for the asus flip. 

My system (chroot encrypted)
crouton: version 1-20190120145639~master:5bf96711
release: jessie
architecture: arm64
xmethod: xiwi
targets: keyboard,xiwi,xorg,extension,lxde
host: version 11316.165.0 (Official Build) stable-channel bob 
kernel: Linux localhost 4.4.164-15546-gd8c7defc947f #1 SMP PREEMPT Sun Mar 3 22:53:43 PST 2019 aarch64 GNU/Linux
freon: yes
