### ISSUE TITLE
With xiwi,cli-extra,xfce(-desktop) targets, the only xmethod available is xiwi

### ISSUE THREAD

**Issue by Wizardcrying** [dnschneid/crouton#3200]
```
name: doublex
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/doublex...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xiwi 
targets: xiwi,cli-extra,xfce-desktop
host: version 9334.33.0 (Official Build) beta-channel sentry 
kernel: Linux localhost 3.18.0-13958-g2014267 #1 SMP PREEMPT Mon Apr 3 21:58:15 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/doublex...
```
The title explains the basics. Attempting to use `sudo startxfce4 -X xorg` throws this,
 of course (http://i.imgur.com/i2sX9uA.png):
```
chronos@localhost ~/Downloads $ sudo startxfce4 -X xorg
/mnt/stateful_partition/crouton/chroots/doublex does not contain XMETHOD 'xorg'
``` 
This chroot was just made with a very recent xenial bootstrap.

**Comment by DennisLfromGA** [comment]
@Wizardcrying,

That's because you specified the `xiwi` target/xmethod exclusively in the installation command.
You could have installed both xmethods and made the first one specified the default, something like:

`sudo sh ~/Downloads/crouton -r xenial -n doublex -t xorg,xiwi,cli-extra,xfce-desktop`

You can add the `xorg` target/xmethod by updating your chroot and make it the default using: 

`sudo sh ~/Downloads/crouton -n doublex -t xorg -u`

*Hope this helps,*
-**DennisL**

**Comment by Wizardcrying** [comment]
Thanks, @DennisLfromGA.
