### ISSUE TITLE
Potential misreporting of xmethod

### ISSUE THREAD

**Issue by Wizardcrying** [dnschneid/crouton#3201]
I started a Unity chroot using `-X xorg` with both targets installed. I checked back in the terminal on CrOS and this is what showed. 
```
[X.org X server inital output]
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Apr 12 20:17:45 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
(!!!) xmethod: xiwi (!!!)
targets: xiwi,xorg,cli-extra,unity
host: version 9334.33.0 (Official Build) beta-channel sentry 
kernel: Linux localhost 3.18.0-13958-g2014267 #1 SMP PREEMPT Mon Apr 3 21:58:15 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
[other warnings]
```
I'm not quite sure of whether or not it's time to panic. 
I have the crouton extension in the host and connected, which might matter.

**Comment by DennisLfromGA** [comment]
@Wizardcrying,

> targets: xiwi,xorg,cli-extra,unity

`croutonversion` reports what 'targets' you specify on the installation command line (-t ...).
Since you explicitly specified `xiwi` as the **_first_** target it becomes the **_default_** xmethod, hence -

> (!!!) **xmethod: xiwi** (!!!)

> I'm not quite sure of whether or not it's time to panic.

Please don't panic, it's WAI (works as intended) behavior. ;-)

> I have the crouton extension in the host and connected, which might matter.

When using `xiwi` you *need* the ['crouton integration'](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension connected, that's a good thing.

----
Since you have both xmethods, you can launch your desktop using either in a number of ways with something like:

- `sudo startunity` (that will launch in a window via 'xiwi', the default)

- `sudo startunity -X xiwi-fullscreen` (that will launch fullscreen via 'xiwi')

- `sudo startunity -X xiwi-tab` (that will launch in a browser tab via 'xiwi' - *my favorite*)

- `sudo startunity -X xorg` (that will launch in a separate screen via 'xorg')

*Hope this helps,*
-**DennisL**

**Comment by Wizardcrying** [comment]
Thanks, @DennisLfromGA.
If the default xmethod is to be displayed and is known to be displayed in that case, then I assume there is no problem.
