### ISSUE TITLE
Module snd-aloop not in Crouton?

### ISSUE THREAD

**Issue by MeneerJansen** [dnschneid/crouton#3220]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
```
﻿name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160715134041~master:0dc76a22
release: trusty
architecture: amd64
xmethod: xorg
targets: gnome
host: version 8172.62.0 (Official Build) stable-channel leon 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jul 6 18:13:49 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
```

#### Please describe your issue:
Cannot load Alsa's loop device so that I can record audio from Wine Windows applications. This works perfecly fine on my other Linux box. I want to load the kernel module `snd-aloop` but I get the followin error message:
```
$ sudo modprobe snd-aloop
modprobe: FATAL: Module snd-aloop not found.
```
Why is the module `snd-aloop` not part of the package `alsa-utils` in Crouton?

 
#### If known, describe the steps to reproduce the issue:
Install the package `alsa-utils` and try to insert the kernel module `snd-aloop` in the kernel. Works on all Linux versions but not in Crouton....

**Comment by divx118** [comment]
Modules for crouton need to be build against the chromeos kernel. Since there are no kernel headers available for the kernel you need to build your own headers and install them to build the module or  just build the module you need with the chromeos source. See https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules and https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)
Also note that you will need to disable the module_locking before you can load any external modules. This is also explained in the guides.

**Comment by MeneerJansen** [comment]
But why is it not there already like all other ALSA related thins like Jack end other drivers/kernel modules?

**Comment by divx118** [comment]
You only have modules available that ship with chromeos. snd-aloop module is not one of them, because chromeos will not need it.

**Comment by DennisLfromGA** [comment]
Sometimes the devs on [chromium os discuss](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-os-discuss) will listen and respond to reasonable requests, couldn't hurt to [ask there](https://groups.google.com/a/chromium.org/forum/#!newtopic/chromium-os-discuss).

**Comment by MeneerJansen** [comment]
Thanks for the clear clarifications everybody. :)
