### ISSUE TITLE
ChromeOS wiped my user, now enter-chroot fails trying to mount something

### ISSUE THREAD

**Issue by ChrisHodgesUK** [dnschneid/crouton#3227]
```
name: jessie
encrypted: yes, locked
Unmounting /media/removable/SD Card/jessie...
name: lost+found
encrypted: no
Entering /media/removable/SD Card/lost+found...
/usr/local/bin/enter-chroot: 511: cannot create /run/crouton/media/removable/SD Card/lost+found/etc/crouton/name: Directory nonexistent
Unmounting /media/removable/SD Card/lost+found...
```

I'm on an Asus C201, with my jessie chroot on the SD card.  ChromeOS was playing up (never getting a prompt in crosh) and there were updates pending so I allowed it to "restart to install updates".  It installed an update to allow me to run Android apps (which I already do) then told me the update had failed and I'd need to link my account again.  

When I relinked my account and tried `enter-chroot` (initially via a script I've got because of a known issue with `/dev/dri/card0` and `/dev/dri/card1`) I got the message `mount: mount(2) failed: No such file or directory`.  I suspect it's trying to mount my old downloads folder (which ChromeOS appears to have wiped) but the errors relating to `lost+found` in the output of `edit-chroot` seem strange.

**Comment by DennisLfromGA** [comment]
@ChrisHodgesUK,

When you install a chroot on external media, crouton's '-p' option is used to specify the 'parent' directory of where the `/bin` & `/chroots` directories will be created. It looks like your 'jessie' chroot might not be in a `/chroots` directory but rather in the 'root' directory so that could be at least part of the problem.

When you use `edit-chroot` or any of the `start*` scripts you'll need to use the '-c' option to enter the directory of where the chroot is actually located , not the parent directory.

Your script to launch may need to be tweaked or not used at all.
The '/dev/dri/card0 and /dev/dri/card1' issues has been fixed and merged so as long as your chroot has been updated since then you shouldn't need the script.

*Hope this helps,*
-**DennisL**

**Comment by ChrisHodgesUK** [comment]
My bash debugging isn't up to much but I've narrowed it down a bit. The problem seems to appear in `/usr/local/bin/mount-chroot` around/just after line 500.  It appears to be able to decrypt the chroot OK (I don't get "Failed to decrypt $NAME" unless my passphrase is wrong). But I do get "Failed to mount $NAME" a few lines later.

If I use `echo_tty` to output som of the variables just before the attempt to mount, I get:

`$CHROOTSRC` = `/media/removable/SD Card/jessie` which looks right

and

`$CHROOT` = `/run/crouton/media/removable/SD Card/jessie` which exists and appears empty -- as I'd expect from a mount point at which nothing is mounted.

**Comment by ChrisHodgesUK** [comment]
**@DennisLfromGA** for some reason your comment didn't show up until I submitted mine but I can't figure out what has changed since it was working before chromeos broke my user.  For testing I've stopped using my script, but apart from the card0/card1 thing it was just doing:

```
sudo enter-chroot -c /media/removable/SD\ Card
startxfce4
```
I think the reason it's not in a `chroots` folder was that I created it on the internal storage then moved it.  It's been running fine for a couple of months though.  I do recall some fiddling with the parent directory when I wanted to add xiwi to get the chrome extension working.

**Comment by DennisLfromGA** [comment]
@ChrisHodgesUK,

That explains it then, thanx.

Not sure you know, and disregard this if you do, but the `edit-chroot` script has built-in mechanisms to copy or move a chroot so that everything is put in the right place. Check out the options for that below -
```
    -m DEST     Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.

    -C DEST     Like -m, but copies instead of moves.
```
So you could move your internal chroot to your external media using something like:

`sudo edit-chroot -m /media/removable/SD\ Card jessie`

*Hope this helps,*
-**DennisL**

**Comment by ChrisHodgesUK** [comment]
@DennisLfromGA 
if I reinstall crouton I'll either move it properly or start on the SD card in the first place.  I say *if* because however good crouton is, if chromeos can break it so comprehensively I don't think I can trust the combination.  I'm also still hoping to recover this system. (On ARM my options are rather limited but I may be able to dual boot Arch Linux)

I've been poking around and think that mount is failing on the decryption after all, despite the error message being "no such file or directory".  I can't find a `wrapped-passphrase`  file anywhere (with  `sudo find / -name 'wrapped passphrase'`); I'm new to ecryptfs but from what I've read expect to find such a file.
