### ISSUE TITLE
Chroot Not Starting

### ISSUE THREAD

**Issue by jakegee** [dnschneid/crouton#3244]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160902144033~master:9f8e9a22
release: precise
architecture: amd64
xmethod: xorg
targets: xfce,keyboard,extension
host: version 9334.72.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 4.4.44-07366-g24ac249 #1 SMP PREEMPT Wed May 17 18:06:46 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```
Each time I try to start my chroot, 'startelementary' it tries to open, but hangs on a black screen before hangup.

This began I believe after installing the latest update of ChromeOS:
Version 58.0.3029.140 (64-bit)
Platform 9334.72.0 (Official Build) stable-channel quawks
ARC Version 4017628
Firmware Google_Quawks.5216.204.61

When I type sudo enter-chroot this is the error message I'm getting:
Entering /mnt/stateful_partition/crouton/chroots/precise...
Unknown username "dnsmasq" in message bus configuration file
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1

Which I'm guessing is the reason why it will no longer load. I've updated crouton to the latest release and also tried restoring a backup. Another notable thing is the crouton integration extension on chrome isn't able to connect either. I'm guessing that's because of the issue with my chroot.

Can anybody please provide any help regarding this? Thank you!

Jake

**Comment by DennisLfromGA** [comment]
@jakegee,

The 'precise' release has reached end-of-life and is no longer supported.
You could try upgrading your chroot to the 'xenial' release following the wiki guide: [Upgrade chroot release](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release).
I want to warn you though to be sure to first back up your chroot before attempting the upgrade since it has been troublesome, for me at least, when going from 'precise' to anything newer.
In fact, you may be better off installing a fresh new 'xenial' chroot.

There is a current PR (pull request) for the 'elementary' target, it's not been reviewed and merged yet but I've gotten it to work, see [this comment](https://github.com/dnschneid/crouton/pull/2973#issuecomment-274998342) for details.

*Hope this helps,*
-**DennisL**

**Comment by jakegee** [comment]
Thanks for your kind reply, Dennis. I'll try that release out when I got some free time next week.
