### ISSUE TITLE
How to remove the xiwi target from a chroot 

### ISSUE THREAD

**Issue by 9291Sam** [dnschneid/crouton#3249]
I tried xiwi for my chroot but most of the programs I use do not work with xiwi so I need to know how to remove the target from my chroot. Also I would also like the ability to do 'sudo startxfce4' again rather than 'sudo startxfce4 -X xorg'.

**Comment by DennisLfromGA** [comment]
@9291Sam,

I would just reinstall the 'xorg' xmethod using: `sudo sh ~/Downloads/crouton -t xorg -u`
That will change your default xmethod to 'xorg' so you don't have to enter '`-X xorg`' on the command line.

I don't think it would be wise to try and remove the 'xiwi' xmethod at this point since you could end up breaking things. If you want to *'hide'* it from crouton you could edit both `/.crouton-targets` and `/etc/crouton/targets` files inside the chroot and remove 'xiwi' from the lists. Then do a crouton update.

*Hope this helps,*
-**DennisL**

**Comment by cainy-a** [comment]
> @9291Sam,
> 
> I don't think it would be wise to try and remove the 'xiwi' xmethod at this point since you could end up breaking things. Here's what I would suggest -
> 
> **Option 1:**
> 
> * Reinstall the 'xorg' xmethod using: `sudo sh ~/Downloads/crouton -t xorg -u`
>   That will change your default xmethod to 'xorg' so you don't have to enter '`-X xorg`' on the command line.
> 
> **Option 2:**
> 
> * _Hide_ the installed 'xiwi' target from crouton by editing both `/.crouton-targets` and `/etc/crouton/targets` files inside the chroot and remove `xiwi` from the lists. Then do a crouton update.
> 
> _Hope this helps,_
> -**DennisL**

That totally worked for me! Thanks for the useful answer.
