### ISSUE TITLE
chroot commands dont exist after attempting to install crouton

### ISSUE THREAD

**Issue by MerpDerpster** [dnschneid/crouton#3251]
```
chronos@localhost / $ sudo edit-chroot -all
sudo: edit-chroot: command not found
```

Ok so I've got a Samsung Series 3 ARM Chromebook that I recently bought off eBay and I did a fresh install of ChromeOS before attempting to install crouton. So I find the tutorial on installing it [here](https://chromebook.guide/crouton/).
so I type in the install command after putting my chrome book into dev mode:

`sudo sh -e ~/Downloads/crouton -r trusty -t unity-desktop,gtk-extra,cli-extra,extension,keyboard,xbmc,chrome -e`

and everything went fine untill the last part.

> : Extracting upstart...
I: Extracting util-linux...
I: Extracting zlib1g...
Moving bootstrap files into the chroot...
Preparing chroot environment...
unity is unsupported on ARM for releases after precise

ok, so I've made a mistake.

so I try this first:
`chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r trusty -t xfce,gtk-extra,cli-extra,extension,keyboard,xbmc,chrome -e
Google Chrome does not yet have an ARM build. Installing Chromium instead.
/usr/local/chroots/trusty already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -u trusty -t xfce,gtk-extra,cli-extra,extension,keyboard,xbmc,chrome -e`

and that last line just spat out the "help" of the crouton program.

so Try to delete and start over:
`chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r trusty -t xfce,gtk-extra,cli-extra,extension,keyboard,xbmc,chrome -e^C
chronos@localhost / $ sudo edit-chroot -d trusty
sudo: edit-chroot: command not found
chronos@localhost / $ sudo edit-chroot -d trusty
sudo: edit-chroot: command not found
chronos@localhost / $ sudo sh edit-chroot -d trusty
sh: Can't open edit-chroot
chronos@localhost / $ sudo delete-chroot trusty
sudo: delete-chroot: command not found
chronos@localhost / $ ^C
chronos@localhost / $ sudo sh delete-chroot trusty
sh: Can't open delete-chroot
chronos@localhost / $ sudo delete-chroot trusty
sudo: delete-chroot: command not found
chronos@localhost / $ sudo edit-chroot -all
sudo: edit-chroot: command not found`

so that's my main issue, none of the commands do things. 
I'm sorry if this isn't the right place to post this, I'm new to this whole thing, and Chromebooks are so overly complicated, at least mine is, cause the whole ARM thing and it just so happening to be a model where neither John Lewis' nor Mr. Chromebox's bios mods work, my luck.
any help is appreciated and thanks in advance.

**Comment by DennisLfromGA** [comment]
@MerpDerpster,

> /usr/local/chroots/trusty already has stuff in it! Either delete it, specify a different name (-n), or specify -u to update it.

That's the problem, you tried to remove the failed chroot first with: `sudo delete-chroot trusty`
But since the install failed it didn't install `delete-chroot` nor any of the other `host-bin/` files.

Try doing this next: `sudo sh ~/Downloads/crouton -b`
Then try this again: `sudo delete-chroot trusty`

Once that's done, then you can start over with your new installation using:

`sudo sh ~/Downloads/crouton -r trusty -t xfce,cli-extra,extension,keyboard,xbmc,chrome`

You don't need `gtk-extra` since it's installed with `xfce` and I would leave off the `-e` option at the end as I show above. Once everything is installed successfully and you've tweaked it to your liking you can 'encrypt' it if you like with a crouton update. I've found that works best for me anyway.

*Hope this helps,*
-**DennisL**

**Comment by MerpDerpster** [comment]
@DennisLfromGA Thanks, my dude! It worked.

**Comment by DennisLfromGA** [comment]
@MerpDerpster,

So glad I could help, *dude!* :+1: 

-**DennisL**
