### ISSUE TITLE
enter-chroot asks for a password other than Chrome/chroot sudo password for chroot on external device after reboot

### ISSUE THREAD

**Issue by sebastian-fredriksson-bernholtz** [dnschneid/crouton#3259]
Hi, I'm a newbie at crouton and linux so I hope I've posted what I know. I've posted all the information I could think of that could be relevant.

#### sudo edit-chroot -all
```
name: xenial
Enter encryption passphrase for xenial: 
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce
host: version 9334.72.0 (Official Build) stable-channel clapper 
kernel: Linux localhost 4.4.44-07366-g24ac249 #1 SMP PREEMPT Wed May 17 17:46:51 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
#### sudo edit-chroot -p /media/removable/ChrootDevice -all
```
name: homexenial
encrypted: no
Entering /media/removable/ChrootDevice/chroots/homeqxenial...
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: lxde
host: version 9334.72.0 (Official Build) stable-channel clapper 
kernel: Linux localhost 4.4.44-07366-g24ac249 #1 SMP PREEMPT Wed May 17 17:46:51 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/ChrootDevice/chroots/homeqxenial...
```

#### Please describe your issue:
I have installed an Ubuntu Xenial LXDE chroot on an external USB. After installation it worked fine and I started and exited the chroot a number of times without being prompted for any password except the Chrome sudo password. The chroot is not encrypted and I use my Chrome OS sudo password to enter the chroot and while in the chroot I have definitely used sudo in the terminal and, although I'm not 100 percent certain, I'm quite confident I must have had to enter the chroot sudo password there. I'm very certain that I've got the passwords correct.

However, after having rebooted my laptop I am prompted for a password when trying to enter the chroot. I've tried with my chrome and chroot passwords, and also leaving it blank but get `su: Autentication failure`, see below. I don't know if it' related to this issue: [2737](https://github.com/dnschneid/crouton/issues/2737).

```
$ sudo sh /media/removable/ChrootDevice/bin/enter-chroot 
Password: 
Entering /media/removable/ChrootDevice/chroots/homexenial...
Password: 
su: Authentication failure
WARNING: starting chroot system dbus daemon failed with code 1
Password: 
su: Authentication failure
Unmounting /media/removable/ChrootDevice/chroots/homeqxenial...
```

#### If known, describe the steps to reproduce the issue:
1. Install chroot on external device using `sudo sh ~/Downloads/crouton -r DISTRO -t ENVIRONMENT -p '/media/removable/NAME OF DRIVE'`
2. Reboot computer
3. Try to enter chroot

#### Additional information

After not being able to enter the chroot I tried to update it using `sudo sh ~/Downloads/crouton -u -n homexenial -p  /media/removable/ChrootDevice`. It started installing things and then asked for the same password. After not being able to input correct password I used Ctrl-c and Ctrl-d to abort. After that I tried to reenter and was told that the chroot was in the middle of an update script. I responden y to a prompt about continuing the update, after which I got a message saying that it was removing the update script or something along those lines. The script didn't finish and got stuck for a long time and I used Ctrl-c or Ctrl-d to stop it. I don't know if this could have messed with the `edit-chroot` output I got above. The chroot on the external device is a newer install than the old.

**Comment by DennisLfromGA** [comment]
@BamseSBG,

When you encrypt one or more chroots, `crouton`, or actually `mount-chroot` will tell you -

> 'You must have a root password in Chromium OS to mount encrypted chroots.'

Then it will invoke `chromeos-setdevpasswd` to setup a password when entering a shell.
This password can be different than the one you provided to encrypt the chroot.
It can also be different than the password you provide for the user in the chroot.
So you could be prpmpted for three different passwords in order to enter an encrypted chroot.

Even though your 'homexenial' chroot is not encrypted, you'll still be prompted for the password requested by `chromeos-setdevpasswd`. That would be the 'Chrome OS sudo password' that you mentioned above I believe.  

I guess it's possible that that password has either gotten corrupt or is missing.
Maybe you could try invoking `chromeos-setdevpasswd` again and entering the same or a new password. I don't know if that will resolve your issue but it might be a first step.

*Hope this helps,*
-**DennisL**

**Comment by BamseSBG** [comment]
Hi DennisL!

Thanks for your help! I tried running `chromeos-setdevpasswd` in both shell and crosh and got:
```
chronos@localhost / $ chromeos-setdevpasswd
bash: chromeos-setdevpasswd: command not found

crosh> chromeos-setdevpasswd
ERROR: unknown command: chromeos-setdevpasswd
```
However, I managed to enter the chroot today without it asking me for a password. I'm really confused as to why it asks me for password sometimes and not other times. Just to clarify, I'm always prompted for a password before entering the chroot. This is the password I refer to as the chrome sudo password. And this password always works. The password that doesn't work comes after I try entering the chroot. 

Without knowing what I'm really talking about, I think the password I'm prompted for but don't know is the chroot root user password. This is based on the fact that I get `su: Authentication failure` and it doesn't work with my own user password. I reckon it's trying to switch to the root user. Could that be the case? I've tried leaving the password blank as the root user by default has a blank password (?). I'm gonna try setting the root user password to my own user password now that I managed to enter the chroot again.

**Comment by DennisLfromGA** [comment]
@BamseSBG,

Okay, thanx for the info., I think we've got a handle on it now.

I said:
> Maybe you could try invoking chromeos-setdevpasswd again and entering the same or a new password. 

Sorry, but I should've have said above to do that as root or via `sudo` like: 

`sudo chromeos-setdevpasswd`

> This is the password I refer to as the chrome sudo password. And this password always works. The password that doesn't work comes after I try entering the chroot.

After your above explanation, I think the problem is with the 'username' password in the chroot. That's an easy fix luckily by just entering your chroot as 'root' and resetting the 'username' password.  Here's how -

1. Enter the chroot as root: 
`sudo enter-chroot -n homexenial -c /media/removable/ChrootDevice/chroots -u root`

2. Change the 'username' password: `passwd [username]` 
Substitute [username] with the one you originally created, 
you'll be prompted to enter the password twice for verification.

3. Exit the chroot.

Now when you run any `sudo` commands in the chroot it will prompt for the 'username' password you just set.

*Hope this helps,*
-**DennisL**
