### ISSUE TITLE
Encryption is not working

### ISSUE THREAD

**Issue by maddin200** [dnschneid/crouton#3262]
Encryption will not work after Chrome OS update Version 59.0.3071.91 (Official Build) (64-bit)

tried xenial and precise on a Asus C300 either previous installation and new

**Comment by DennisLfromGA** [comment]
@maddin200,

Please provide more details, anything else that might help narrow it down, like -

- [ ] What command string  are you using
- [ ] Does it only fail on initial install or when trying to encrypt a non-encrypted chroot?
- [ ] When/where does it fail?
- [ ] What are the error messages displayed?

-**DennisL**

**Comment by maddin200** [comment]
tried:
sudo sh ~/Downloads/crouton -e -n xenial -t unity
sudo sh ~/Downloads/crouton -e -n precise -t unity

as well it failed on a previous installation
encryption password was not accepted on enter-chroot

**Comment by DennisLfromGA** [comment]
@maddin200,

- [ ] Are you prompted for a password when entering 'shell' ?
- [ ] Does it only fail on initial install or when trying to encrypt a non-encrypted chroot?

-**DennisL**

**Comment by kinggrowler** [comment]
This is failing for me as well. Same build as @maddin200: 59.0.3071.91  (Official Build) (64-bit). I have an Acer Chromebook 14.

I can create and enter chroots that do NOT have a password set, however when I try to create a NEW chroot using '-e' option, I am prompted for the password, but the build fails with error 'mount failed no such file or directory' .

`$ sudo sh ~/Downloads/crouton -t core -n blort -e
Choose an encryption passphrase for blort: 
Please confirm your passphrase: 
Generating keys (move the mouse to generate entropy)...
done
mount: mount(2) failed: No such file or directory
Failed to mount blort.`

I get the same error message when trying to mount a previously encrypted chroot as well. At the moment I can no longer open any of my encrypted chroots.

**Comment by kinggrowler** [comment]
Some additional info to the above: I tried to manually create a new encrypted mount using ecryptfs, and get the following error:

Attempting to mount with the following options:
  ecryptfs_unlink_sigs
  ecryptfs_key_bytes=16
  ecryptfs_cipher=aes
  ecryptfs_sig=cc591c60858cca15
Can't change ownership of sig file; errno = [2]; [No such file or directory]
WARNING: Based on the contents of [/root/.ecryptfs/sig-cache.txt],
it looks like you have never mounted with this key 
before. This could mean that you have typed your 
passphrase wrong.

Would you like to proceed with the mount (yes/no)? : yes
Would you like to append sig [cc591c60858cca15] to
[/root/.ecryptfs/sig-cache.txt] 
in order to avoid this warning in the future (yes/no)? : yes
Error appending to [/root/.ecryptfs/sig-cache.txt]; rc = [-5]. Aborting mount.
Error processing sig; rc = [-5]
Error mounting eCryptfs: [-5] Input/output error
Check your system logs; visit <http://ecryptfs.org/support.html>
chronos@localhost ~/Downloads $ sudo mkdir ~root/.ecryptfs
mkdir: cannot create directory ‘/root/.ecryptfs’: Read-only file system


Perhaps the mount command above is barfing on "Error appending to [/root/.ecryptfs/sig-cache.txt]; rc = [-5]. Aborting mount." because "mkdir: cannot create directory ‘/root/.ecryptfs’: Read-only file system" ??

**Comment by maddin200** [comment]
fails on initial install; password works

I will not to reproduce with my encrypted Acer Chromebook :-).

**Comment by smerrill** [comment]
I was having a similar issue where an encrypted chroot would not mount after a ChromeOS update. Can you see if https://github.com/dnschneid/crouton/pull/3278 solves it for you?

**Comment by kinggrowler** [comment]
@smerrill , yes this works for me. Thanks!

**Comment by dnschneid** [comment]
Patch is merged and released, so this should be fixed. Just update your chroot!
