### ISSUE TITLE
Can I Install Multiple Chroots?

### ISSUE THREAD

**Issue by Astrades** [dnschneid/crouton#3280]
Is it possible to install multiple chroots? I have Ubuntu 16.04 with Gnome installed on a flash drive and I want to install another copy of Ubuntu 16.04 with XFCE entirely separately. Is this possible? How EXACTLY would I go about doing so? Thanks in advance.

**Comment by zguithues** [comment]
you certainly can, though you'll have to specify a chroot name if you plan to use the same release.

All you have to do is add "-n CHROOTNAME" to the end of your crouton command.

example...
## Ubuntu 16.04 xenial with Gnome
sudo sh ~/Downloads/crouton -t gnome-desktop -n gnome

## Ubuntu 16.04 xenial with XFCE
sudo sh ~/Downloads/crouton -t xfce-desktop -n xfce


**I didn't specify "-r xenial" because 16.04 xenial is the default chroot.**

**Comment by Astrades** [comment]
How would I go about booting them? Would it just be "sudo start(chrootname" ?

**Comment by DennisLfromGA** [comment]
@Astrades,

To add, @zguithues is correct, you'll need to specify unique chroot names.

But actually, 'crouton' will look for the desktop target and launch the first one that matches.
So, in your case, to launch *gnome* just use:

`sudo startgnome -c /path/to/external/media/chroots`

And to launch to launch *xfce* just use:

`sudo startxfce4 -c /path/to/external/media/chroots`

You can of course also specify the name of the chroot using the '`-n [chrootname]`' option to your '`start*`' command but it's not strictly necessary if you have different desktop targets in each chroot.

-----
Also, if you'd like to rename your existing chroot to be more friendly use something like this:

`sudo edit-chroot -c /path/to/external/media/chroots xenial -m xenial-gnome`

*Hope this helps,*
-**DennisL**

**Comment by zguithues** [comment]
Thanks for the additional info @DennisLfromGA !

I had not realized that i could specify the chroot in the "sudo startxfce4" command.  I could have used that yesterday, as i was testing things with my kodi pull request.
