### ISSUE TITLE
Ability to use the same home folder as Chrome OS.

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#3313]
Hello, I'd like to have one home folder. Is it possible to configure Crouton to use Chrome OS' home folder, and not have a separate one inside the chroot? That way I can update dotfiles, etc, easily, in one place, and share files easily regardless if I am in chroot or ChromeOS.

**Comment by trusktr** [comment]
On previous setups, I had dual boot with Window + Linux, or MacOS + Linux, and I would have one home folder for both OSes regardless which one I booted into, which was convenient; the same files are available no matter which OS is booted.

**Comment by darethehair** [comment]
Never tried it myself, but does this help?

[https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders](url)

**Comment by trusktr** [comment]
@darethehair That might be it. What would a command line example look like? So that if I `touch ~/foobar` while in crosh, then log into the chroot, I will be able to `ls -l ~/foobar` which would be the same file.

**Comment by darethehair** [comment]
@trusktr, I have not tried this myself, but 'yes', that is the way I would expect that it would work i.e. shared directory between two systems.  I do something similar between Linux and Windows -- this should be even more straight-forward since crouton is just a 'chroot' of the real running ChromeOS.  Try it and let the rest of us know how it works out :)
