### ISSUE TITLE
Touchpad requires high pressure to work

### ISSUE THREAD

**Issue by LufyCZ** [dnschneid/crouton#3325]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
######  chronos@localhost ~/Downloads $ sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170619181610~master:980f090f
release: stretch
architecture: amd64
xmethod: xorg
targets: xorg,keyboard,xiwi,gnome-desktop
host: version 9592.37.0 (Official Build) beta-channel lars
kernel: Linux localhost 3.18.0-14861-g70c266fc4519 #1 SMP PREEMPT Tue Jun 27 23:29:17 PDT 2017 x86_64 GNU/Linux
freon: yes
# #### Please describe your issue:
You need to make a lot of pressure on the touchpad to work

# #### If known, describe the steps to reproduce the issue:
This happened after updating my chroot. Steps to reproduce:
sudo bash crouton -r kali-rolling -t gnome-desktop,keyboard . It happened in my chroot, so I decided to make a clean one, which had the same issue.

**Comment by libjared** [comment]
Is xserver-xorg-input-synaptics installed?

**Comment by LufyCZ** [comment]
No, but when I install it, I loose all functionality except moving the mouse (double-tap to right click doesnt work, tap to click doesnt work, two-finger scrolling doesnt work)

**Comment by MrQuiX** [comment]
I have the same issue with my Acer R13, it looks like Kali dropped the xserver-xorg-input-synaptics (and thus the synclient FingerLow=1 FingerHigh=5 fix) in favor of libinput.  I can view the device settings via sudo udevadm test /sys/class/input/event2 but I am lost on how to adjust the min and max values.

According to https://wiki.archlinux.org/index.php/Libinput the issue may be that in order to use libinput with Xorg, you must install xf86-input-libinput package, which is "a thin wrapper around libinput and allows for libinput to be used for input devices in X. This driver can be used as as drop-in replacement for evdev and synaptics."  Since I am on arm architecture it looks like I don't have a wrapper option.  Running kali-rolling via Wayland presumably would fix this issue.

**Comment by cobalt2727** [comment]
Hate to be that guy commenting on a 3-year-old post, but I just set up Ubuntu Bionic and I'm having the exact same issue on an HP Chromebook x360 14. Any advice?

**Comment by ImpeccablePenguin** [comment]
Had the same issue on bionic with xfce recently. Installing xserver-xorg-input-synaptics and restarting fixed it.
