### ISSUE TITLE
Changed CPU Governor with cpufrequtils. Chromebook Resetting Randomly in Linux Environment

### ISSUE THREAD

**Issue by naunuk2424** [dnschneid/crouton#3348]
```
chronos@localhost / $ sudo edit-chroot -all
name: Terminal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/Terminal...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9460.60.0 (Official Build) stable-channel banjo 
kernel: Linux localhost 4.4.52-08254-ge4cd28825ca4 #1 SMP PREEMPT Mon Jun 5 17:04:00 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/Terminal...
```

I've set up a .sh script to set my cpu governors to performance to help me run some games on my chromebook and I've seen a huge performance boost but there also seems to be some huge instability leading to the actual chromebook restarting randomly while in the linux environment.

Here is the command being used by the shell script

    'sudo /etc/init.d/cpufrequtils restart'    

 (the defaults file for CPUfrequtils looks like this)

    'GOVERNOR="performance"'    

The combination of these commands/lines is successful in changing the CPU governor however the instability far outpaces the performance boost. Every 10-40 min the chromebook suddenly goes to the "OS VERIFICATION IS OFF" screen.

Any ideas on what to do?

My first thought was overheating. However the chromebook dosen't get hotter than it usually does. This model also features a fan.

I haven't changed the actual frequencies of the cpu, just which governor is used.

The driver for CPU scaling was listed as Intel_Pstate if that helps.

I can post any logs you can think of

[Dmesg Output (Pastebin)](https://pastebin.com/Kw9wZZZf))

**Comment by dnschneid** [comment]
This is probably an issue more suited to chromium-os-discuss, but from the [intel_pstate bug](https://bugs.chromium.org/p/chromium/issues/detail?id=397688), it looks like pstate governor [directly pokes at the CPU voltage](https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel-next/+/210106).  It's worth looking into whether the interactive governor is able to undo whatever it is the pstate governor does and set the voltage appropriately -- otherwise, it's possible you're running at too low a voltage (whatever was set last by the pstate governor) and the CPU is crapping out when it starts to warm up.

One hacky test you could try is to run a bunch of heavy processes (maybe several `md5sum /dev/zero` or something) to get the pstate governor to max out, then switch the governor to performance before killing the md5sums.  You could also look into sysfs to see if there's any parameters you can poke to force the pstate governor to the max state.  If the system is stable after doing that, then the voltage config is the most likely suspect.
