### ISSUE TITLE
Crouton is very buggy in dev build of chrome os 

### ISSUE THREAD

**Issue by Jumpshawt** [dnschneid/crouton#3353]
I forgot to record the bugness  because im really smart :/ 
im pretty sure it starts when you are in fullscreen or close and open the chrome book 
the bugness  affects chrome os and crouton 

The few direction i can point in is that existing chroots that were made before some dev update are less glitchy then ones that were made in the dev build, switching between chrome os and the chroot seems to glitch it out more, same with closing the screen. most of the time it starts when the chroot has been open for a bit. (about 30 mins i think) this was stuff in the old chroot. 

Newly made chroots seem to glitch out instantly when it goes in fullscreen mode, but like i mentioned earlier i am on a old version now so i cant really help :/

**Comment by DennisLfromGA** [comment]
@BluesparkYT,

Yup, the dev channel is unstable.
For more stability move to the beta or stable channel.

Please show us the output of: `sudo edit-chroot -all`
Apart from that, if you can provide more details about what's happening when, we might be able to troubleshoot it.

*Hope this helps,*
-**DennisL**

**Comment by BluesparkYT** [comment]
@DennisLfromGA 

i switched to beta before i posted this so it wouldn't really help. also its visual glitching out so it even if i had it, idk if it would help much.  

i can kinda explain it but not show it since I lost my recordings of it when i deleted my chroot. how ever I do have some footage of tf2 glitching out.

the main 2 things that happen is a lot of warping of images, mostly menu bars and colors sometimes aren't in the right place, a bit like a rgb projector but one of the lights isn't in sync properly for a lot of images.

 its really hard to explain since so much stuff is happening at once.  this mostly apply to chroots made before a dev update (dunno what one). 

the ones made after the some dev update is hard to explain other then 3d things in open gl glitch out like crazy. 

I don't have much to say about it because it was so unusable in that state I only used it for about 30ish minutes before switching channels.

**Comment by DennisLfromGA** [comment]
@BluesparkYT,

> i switched to beta before i posted this so sudo edit-chroot -all it wouldn't really help.

It can't hurt. 

-**DennisL**

**Comment by BluesparkYT** [comment]
@DennisLfromGA 
sorta late but here is it anyways 
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: unity,chrome
host: version 9765.48.0 (Official Build) beta-channel kip 
kernel: Linux localhost 4.4.70-11324-g2bac8d6a9eb1 #1 SMP PREEMPT Mon Aug 28 22:03:17 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@BluesparkYT,

> im pretty sure it starts when you are in fullscreen or close and open the chrome book
the bugness affects chrome os and crouton

Since you're using the dev channel you should have the newer 'power' features that allow more control over sleep mode and lid closing, see below -

![screenshot 2017-09-01 at 2 51 46 pm](https://user-images.githubusercontent.com/3418772/29996963-54f8694a-8fd6-11e7-9b39-ebf45c6068f3.png)

![screenshot 2017-09-01 at 2 46 18 pm](https://user-images.githubusercontent.com/3418772/29996966-5ff67526-8fd6-11e7-8dba-168bc27f86a6.png)

You could experiment with those controls and see if it improves your experience.

You could also try installing the 'xiwi' xmethod and experimenting with it.

*Hope this helps,*
-**DennisL**
