### ISSUE TITLE
Calling Chrome Browser in ChromeOS from  crouton install 

### ISSUE THREAD

**Issue by aarwdc** [dnschneid/crouton#3357]
```
Please paste the output of the following command here: sudo edit-chroot -all
ame: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170619181610~master:980f090f
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,chrome
host: version 9592.71.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Wed Jul 26 23:33:35 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

#### Please describe your issue:
I am noob to the whole Linux world, trying to wean myself off of Windows at that ripe age of 62, so excuse the ignorance.

The following instructions were given to another user, to call the chrome browser in ChromOS with URL links:  

> > You could try using update-alternatives to make sure x-www-browser, gnome-www-browser, and www-browser point to the croutonurlhandler. You may also want to look at your gnome settings for default applications.


What is specific code I would use, and where would I place it?

**Comment by brownieboy** [comment]
Belated answer, since your post actually pointed _me_ in the right direction!

Simply type` croutonurlhandler ` into any Linux terminal and it calls the Chromebook's Chrome browser.

To make it default, assuming that you've installed the XFCE version of the crouton, which you appear to have done:

1. Go to Applications->Settings->Preferred Applications, from the main XFCE menu
1. On the Web Browser drop-down list, click the down arrow to the right, then pick "Other"
1. From the resulting **Choose a custom Web Browser** dialog, paste in `croutonurlhandler "%s"`, then click on the Ok and Close buttons.

The main Chromebook's Chrome browser should now be the default for your crouton Linux!

I was then able to delete my crouton installed version of Chromium, saving 200 Meg of precious drive space.  I also deleted Netsurf, although I don't think that took up much space.

**Comment by aarwdc** [comment]
Thank you so much !works perfectly -worth the wait !

**Comment by cobalt2727** [comment]
Any idea how I'd set it as the default browser in GNOME?

**Comment by DennisLfromGA** [comment]
@cobalt2727,

This is a *closed* issue but I googled it for you: 
- https://help.gnome.org/users/gnome-help/stable/net-default-browser.html

*Hope this helps,*
-**DennisLfromGA**

**Comment by cobalt2727** [comment]
> @cobalt2727,
> 
> This is a *closed* issue but I googled it for you: 
> - https://help.gnome.org/users/gnome-help/stable/net-default-browser.html
> 
> *Hope this helps,*
> -**DennisLfromGA**

I don't see an option for the chrome OS browser though...
