### ISSUE TITLE
Croutoncycle not doing anything

### ISSUE THREAD

**Issue by ecollins** [dnschneid/crouton#3358]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170619181610~master:980f090f
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,lxde
host: version 9592.71.0 (Official Build) stable-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jul 26 23:35:00 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### I'm unable to switch back to ChromeOS from my Ubuntu Chroot. 

At first I thought that the issue was my external keyboard (no forwards/backwards keys), but on further inspection, running "croutoncycle next/prev/cros" doesn't do anything either. "croutoncycle list" works as expected. I can only get back to ChromeOS by logging out.

**Comment by thoellrich** [comment]
I have the same issue. For some reason `croutoncycle` thinks it's stuck on ChromeOS and `crountoncycle cros` is a no-op, because it thinks that nothing has to be done. Additionally the keyboard short-cuts also no longer switch for me.

Looking at the script, I can see that `force` can be used to force an update. So `crountoncycle force cros` works for me.
