### ISSUE TITLE
Help! I´m just a newbie trying to install Linux on my ARM Chromebook..and STUCK!

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3359]
I tried to install Linux and run it but this came up. Frommy own view, i think it didnt install or something. Please how can i fix this? 

chronos@localhost / $ sudo startxfce4
Password: 
Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-87-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Jul 26 23:30:23 PDT 2017 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=81dd2b18-105b-e849-920f-d33a57906687/PARTNROFF=1 hashtree=PARTUUID=81dd2b18-105b-e849-920f-d33a57906687/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=21eec100273da0cc3e07da8cf506ee56bd81a20c salt=56571da8d97c2887352f75d8445fc3ce770eced29d006d22a267fdaa010b6e61" noinitrd vt.global_cursor_default=0 kern_guid=81dd2b18-105b-e849-920f-d33a57906687  
Build Date: 25 July 2017  01:30:24PM
xorg-server 2:1.19.3-1ubuntu1~16.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Aug 21 01:19:14 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1503274754.505562 sender=:1.11 -> destination=:1.49 serial=1281 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
method return time=1503274755.763128 sender=:1.11 -> destination=:1.50 serial=1282 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by Titousensei** [comment]
Same for me. Samsung xe303c12, installed with non-encrypted chroot.

**Comment by devman0903** [comment]
Same, Samsung XE303C12-A01US, non encrypted, use GNOME and KALI-ROLLING
![crouton_ss](https://user-images.githubusercontent.com/17048104/29992455-2be1d2a0-8f61-11e7-97c1-f48c4466e031.png)

**Comment by zguithues** [comment]
I think this issue is related to mesa drivers for arm.  I saw the same/similar error in #3395.
`MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.`

I might be way off track here, but it's all that jumps out at me.  I asked the dev about it in the other issue, I hope he can help shed some light on the underlying cause.

@devman0903 your error is different.  I think this might be the issue with `xserver-xorg-legacy`.
Try to enter the chroot and uninstall `xserver-xorg-legacy`

1. enter chroot with: `sudo enter-chroot -n kali-rolling`
2. uninstall `xserver-xorg-legacy` with: `sudo apt remove xserver-xorg-legacy`
3. start gnome with: `sudo startgnome`

Please report back if this fixes it.

If that doesn't work, try installing the same targets on a Ubuntu Xenial/16.04 (`-r xenial`) chroot to determine if this is a chromebook issue, or a kali-rolling issue.

I've got a patch in review that will fix this issue with `xserver-xorg-legacy` moving forward.
