### ISSUE TITLE
Inverted XTerm through XIWI

### ISSUE THREAD

**Issue by superloach** [dnschneid/crouton#3360]
```
chronos@localhost / $ sudo edit-chroot -all
name: xiwi
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xiwi...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi
host: version 9765.31.0 (Official Build) dev-channel cyan 
kernel: Linux localhost 3.18.0-15945-g3e5ac8a02327 #1 SMP PREEMPT Wed Aug 16 22:09:39 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xiwi...
```

#### Please describe your issue:
 when I start `xterm` through xiwi, the colors are inverted. anyone know why? it just upsets the whole "terminal" feel for me. ^_^

#### If known, describe the steps to reproduce the issue:
`sudo startxiwi -n xiwi xterm`

**Comment by superloach** [comment]
#3257 may be related...

**Comment by icecream95** [comment]
You mean you get black text on a white background?
That is the default behaviour for xterm.

You can change the colour either from the command line with something like this:

`sudo startxiwi -n xiwi xterm -bg black -fg white`

To permanently change the colour, run these commands from xterm:

    echo XTerm*Background: black >> .Xdefaults
    echo XTerm*Foreground: white >> .Xdefaults

Restart xterm and the colours should be how you want them.
Obviously, if your problem is the opposite (you want black on white), just swap the black and white.

**Comment by fulv** [comment]
Even quicker:

```
sudo startxiwi -b xterm -rv
```

**Comment by superloach** [comment]
Oh wow, this is so old! I've since migrated from Crouton to Chromebrew, and figured out on my own how to fix that when using xterm through Sommelier.
Thanks anyways! 😆
