### ISSUE TITLE
Question: Best way to access chroot home directory from ChromeOS?

### ISSUE THREAD

**Issue by pierslawrence** [dnschneid/crouton#3362]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xubuntu-xenial-piers
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xubuntu-xenial-piers...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,xfce-desktop,extension
host: version 9592.71.0 (Official Build) stable-channel peppy
kernel: Linux localhost 3.8.11 #1 SMP Thu Jul 27 00:04:59 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:
After reading the Wiki page:
[https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders](https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders)

I am wholly confused about how to do the sharing correctly. Perhaps especially through reading issue #620

I would like to access the crouton home directory from ChromeOS. Specifically from the file manager app. My question is how is it best to achieve this?

I understand that creating a symlink pointing to the target directory in the chroot does not work for the file manager, but oddly (?) does work for file:///home/chronos/u-long-number/Downloads/symlink type links in the url bar.

What I would like to know is if doing the following is a good, bad, or terrible idea (based on following #620):

1) modify /etc/crouton/shares (in the chroot) to include the line: 

encrypted/home ~/Downloads/home

at the end after already mounting the downloads folder

2) moving the contents of the home folder of the chroot to ~/Downloads/home

3) Being happy and getting on with life being able to access files through the Downloads directory.

4) Perhaps this is a terrible idea, and I will lose all of my files in the chroot.

Is there an alternative/better way of sharing files back and forth between the chroot and ChromeOS?

**Comment by DennisLfromGA** [comment]
@pierslawrence,

> After reading the Wiki page:
https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders

> I am wholly confused about how to do the sharing correctly. Perhaps especially through reading issue #620

The 'shares' wiki page says: 
> `The /etc/crouton/shares file in your chroot defines directories to map into the chroot from the host.`

So that's the opposite of what you're trying to do I think.

> I would like to access the crouton home directory from ChromeOS. Specifically from the file manager app. My question is how is it best to achieve this?

I believe the best way to do that is to add a ssh server in your chroot (see [OpenSSH Server](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton#openssh-server)) and then use the Files app 'SFTP File System' service, you can add it from the Web store if you don't have it, see below -

![sftp-svc](https://user-images.githubusercontent.com/3418772/29573435-f51e5630-872c-11e7-832c-1b245516bd61.png)

That's the way I do it when needed.

*Hope this helps,*
-**DennisL**

**Comment by dnschneid** [comment]
You should be able to modify /etc/crouton/shares to have
```
downloads/home ~
```
...but you may want to move the contents of your home directory elsewhere before doing so, since it'll be difficult (but not impossible) to access them when you start the chroot with the updated shares.  Keep in mind that if you log into your chroot using `-u root`, this will cause crouton to mount your shared home directory over /root as well.  You might be better off with:
```
downloads/home ~username
```
where username should be your normal chroot username.  That way, no matter what username you use to enter the chroot, your home directory will end up in the right place.

Anyway, this works because the left side is where the directory is stored in Chromium OS, and the right side is the path it appears as inside the chroot.  As such, the folder will be stored in your downloads folder on Chromium OS' side, and thus accessible in Files.app.

Two caveats:

1) Your home directory may be susceptible to auto-cleanup, so if you start to run out of space, Chromium OS may delete random files from your home directory.  Not certain about this (maybe this has been proved false in the past...)

2) crouton backups (`edit-chroot -b`) will not capture your home directory when making chroot backups.  You'll be responsible for backing it up yourself.  This is because your home directory is no longer stored in the chroot.

**Comment by DennisLfromGA** [comment]
I'm probably doing something wrong but after adding the following entries -

`downloads/home ~` or `downloads/home ~denny`

To `/etc/crouton/shares` didn't work for me.

I launched `enter-chroot` and couldn't get into my home directory.
Here are the results -

> chronos@localhost ~ $ enter-chroot -n trusty
Entering /var/crouton/chroots/trusty...
No directory, logging in with HOME=/
mkdir: cannot create directory ‘//.config’: Permission denied
ln: failed to create symbolic link ‘//.config/pulse/default.pa’: No such file or directory

> (trusty)denny@localhost:/$ pwd
/
(trusty)denny@localhost:/$ cd
(trusty)denny@localhost:/$ pwd
/
(trusty)denny@localhost:/$ cd ~denny
-su: cd: /home/denny: Permission denied

I'm also pretty confused now since I thought the `shares` file only mapped from CrOS into the chroot.

-**DennisL**

**Comment by dnschneid** [comment]
Looks like it kinda worked?  What's the uid of denny vs. the result of `ls -ld ~denny`?

**Comment by dnschneid** [comment]
And yes, the shares file is still mapping from CrOS into the chroot.  It just so happens you're mapping the directory outside the chroot (~/Downloads/home in this case) over the home directory in the chroot (what should be /home/denny).
