### ISSUE TITLE
Libreoffice corrupted

### ISSUE THREAD

**Issue by ssyyddii** [dnschneid/crouton#3391]
```
chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20170830174419~master:0b3ec2c2
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,xfce
host: version 9592.71.0 (Official Build) beta-channel panther 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jul 26 23:31:20 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $ 
```

Libreoffice is corrupted.  I've uninstalled Libreoffice and installed it again. I've updated crouton. I powerwashed my chromebox. I reinstalled a backup where it was working ok.  It was still corrupted after doing all that.   I updated again.  Can't fix problem. When you open a document, the same corrupted 0's appear in the menus. 

![screenshot 2017-09-04 at 11 25 06](https://user-images.githubusercontent.com/12481134/30020367-d66f4776-9163-11e7-94d6-cec92d7af0e8.png)

**Comment by tcagle** [comment]
I have the same kernel as you and I see that unoconv package is showing as broken in synaptic package manager. This puzzles me as is shows several libre office related things that my ubuntu thinks are still on ubuntu5 when if you look in the repo they are actually on ubuntu5.1 version now.....

W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libr/libreoffice/libreoffice-style-galaxy_4.2.8-0ubuntu5_all.deb
  404  Not Found [IP: 91.189.91.26 80]


W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libr/libreoffice/uno-libs3_4.2.8-0ubuntu5_amd64.deb
  404  Not Found [IP: 91.189.91.26 80]


W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libr/libreoffice/ure_4.2.8-0ubuntu5_amd64.deb
  404  Not Found [IP: 91.189.91.26 80]

**Comment by tcagle** [comment]
I manually downloaded all six of these to my chroot and installed each with 

sudo dpkg -i <filename>

here are the correct URL's for the six packages...

 http://archive.ubuntu.com/ubuntu/pool/universe/libr/libreoffice/libreoffice-style-galaxy_4.2.8-0ubuntu5.1_all.deb
 http://archive.ubuntu.com/ubuntu/pool/main/libr/libreoffice/uno-libs3_4.2.8-0ubuntu5.1_amd64.deb
 http://archive.ubuntu.com/ubuntu/pool/main/libr/libreoffice/ure_4.2.8-0ubuntu5.1_amd64.deb
 http://archive.ubuntu.com/ubuntu/pool/main/libr/libreoffice/libreoffice-common_4.2.8-0ubuntu5.1_all.deb
 http://archive.ubuntu.com/ubuntu/pool/main/libr/libreoffice/libreoffice-core_4.2.8-0ubuntu5.1_amd64.deb
 http://archive.ubuntu.com/ubuntu/pool/main/libr/libreoffice/python3-uno_4.2.8-0ubuntu5.1_amd64.deb
 
Now my precise chroot updates correctly again and libreoffice works and is on the menu as it should be.
My updates had been acting up since I first tried to install libreoffice back in May or so.

**Comment by ssyyddii** [comment]
Followed your instructions. Libreoffice stopped working all together and then was unable to update chroot, got an error. So completely at a loss.  I'm getting a windows computer, fed up with crouton.

**Comment by ssyyddii** [comment]
When I ran the scripts I got errors.  I ran them in the order you listed them.  I don't know what else to do.

**Comment by eyqs** [comment]
I don't have a solution to your problem, but have you considered using Google Docs/Sheets/Slides to open and edit your office files instead, since you're on a Chromebook anyway?

**Comment by zguithues** [comment]
have you tried on a more recent release?  precise is 5 years old...
I'm fairly sure it works in xenial.

**Comment by ssyyddii** [comment]
I think updating to Xenial is what caused the problem in the first place. I am using Zoho writter now. Have to edit a Word text heavily formatted with headers, footers, alignments, boxes so LibreOffice was the go to text processor program.  It still works but  the corrupted "0's" appear in the menus so you don't know what menu options are half the time.  Zoho writter seems to do the trick although some of the Word formatting isn't shown but seems to save it after. Google Docs can't handle a complex Word text; formatting goes crazy.  Which is very unfortunate.

**Comment by tcagle** [comment]
Updating my precise back in may is what apparently broke my copy as well. I suspect my "fix" was not correct for the xenial upgrade you have. But with the proper numeric version numbers it might well have worked for you.

**Comment by zguithues** [comment]
I tend to avoid updating linux versions because i always tend to have stupid issues that are difficult to track...  I always keep all my important files online, so i can always just blow away an install and start over.
