### ISSUE TITLE
Changing Kernel Version

### ISSUE THREAD

**Issue by Karthik99999** [dnschneid/crouton#3414]
I want to change my kernel to 3.10.18 so i can run virtualbox. Does anyone know how to do that? I'm running a 64bit ubuntu 16.04 with kernel 4.4 (if that matters). All the tutorials i've seen require a reboot to access grub to change the kernel which chroots can't do.

**Comment by icecream95** [comment]
You don't need to change the kernel version to run virtualbox.

See [the virtualbox](https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)) page in the crouton wiki, which should give you instructions on how to install virtualbox.

The other pages on virtualbox in the wiki ([this](https://github.com/dnschneid/crouton/wiki/Enable-kernel-VT_x-for-Virtualbox), [this](https://github.com/dnschneid/crouton/wiki/Scripts-to-recover-VirtualBox-environment-after-CrOS-updates-(tarball)) and [this](https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration)) should give some more information.

**Comment by Karthik99999** [comment]
I used the default kernel and when I use setup-headers it says amd64 is not supported.

**Comment by tblaschke** [comment]
I'm not sure which setup-headers you exactly mean but I suppose you mean the one from divx118's repo. As stated in the ReadMe. It's broken (and is probably never going to get fixed, since the kernel versions of chros are changing too often). You have to recompile the VBox modules for your kernel on your own. Follow @icecream95 links. They include everything you need to make VBox run in chros (not an easy way though).  It would be much simpler to setup a dual boot with GalliumOS and use VBox from GalliumOS.
