### ISSUE TITLE
su

### ISSUE THREAD

**Issue by jmccoy** [dnschneid/crouton#3419]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170315143304~master:95589555
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 9592.96.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:34:01 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 9592.96.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:34:01 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:

Catfish works in trusty, but not xenial
[Catfish.docx](https://github.com/dnschneid/crouton/files/1319341/Catfish.docx)

**Comment by DennisLfromGA** [comment]
@jmccoy,

I'm gonna post your issue description here since not everyone will make the effort to open your docx file and read it, you'll get more eyes on the issue this way -

> I have an Acer Chromebook C710-2487, Chrome Version 60.0.3112.114, Firmware Version Google_Parrot.2685.37.0, Release Version 9592.96.0.

> Output of croutonversion:

>> crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 9592.96.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:34:01 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

> I’m trying to upgrade from trusty, which works pretty well, but is obsolescent, to xenial. The installation seems to go normally, but after I start xenial (sudo startxfce4 -n xenial), when the desktop comes up, I get a small window saying “System program problem detected”, and the following line appears in the crosh shell window. This sequence repeats randomly during my xenial session:

>> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

> I mention this since it may have something to do with my real problem, which is that Catfish doesn’t work: when I launch Catfish and enter a filename followed by <Enter>, these lines appear in the crosh shell window, but nothing happens in the Catfish window:

>> (xfce4-panel:15705): Gtk-CRITICAL **: IA__gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

>> (catfish:18496): Gtk-WARNING **: /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkwidget.c:8456: widget not within a GtkWindow

>> ** (catfish:18496): CRITICAL **: atk_object_set_description: assertion 'ATK_IS_OBJECT (accessible)' failed

>> (catfish:18864): Gtk-WARNING **: /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkwidget.c:8456: widget not within a GtkWindow

>> ** (catfish:18864): CRITICAL **: atk_object_set_description: assertion 'ATK_IS_OBJECT (accessible)' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/catfish/CatfishWindow.py", line 1574, in perform_query
    self.builder.get_object("splash_title").set_text(_("Searching\u2026"))
UnicodeDecodeError: 'locale' codec can't decode byte 0xe2 in position 9: Invalid or incomplete multibyte or wide character

> Any ideas?  Thanks in advance!

> Jim McCoy

Both of your chroots are out of date, please update at least xenial and get it working before installing catfish.
- How did you install catfish, from a gui app or from the command-line?
- Did you get any errors when it installed?

It's available in synaptic, see below, that's the app I use and trust.

![screenshot from 2017-09-20 17-43-30](https://user-images.githubusercontent.com/3418772/30671344-097b6670-9e2c-11e7-80fb-a9b6a4886ee9.png)

*Hope this helps,*
-**DennisL**

**Comment by jmccoy** [comment]
Thanks, @DennisLfromGA - I'll paste my descriptions into any future problems.
I've updated my chroots. does this look better?

name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170901092920~master:0216f9d1
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 9592.96.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:34:01 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 9592.96.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:34:01 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

(When I look at the Preview, it appears that something is wrong with trusty?)
*********************

In answer to your quetions, I had installed Catfish both with apt-get and the Ubuntu Updater GUI, and got no errors in either case. Now I've usd Synaptic, but Catfish still doesn't do anything. However, the output in the crosh shell is somewhat different:

(catfish:27119): Gtk-WARNING **: /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkwidget.c:8456: widget not within a GtkWindow

** (catfish:27119): CRITICAL **: atk_object_set_description: assertion 'ATK_IS_OBJECT (accessible)' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/catfish/CatfishWindow.py", line 1574, in perform_query
    self.builder.get_object("splash_title").set_text(_("Searching\u2026"))
UnicodeDecodeError: 'locale' codec can't decode byte 0xe2 in position 9: Invalid or incomplete multibyte or wide character

**jmccoy**

**Comment by DennisLfromGA** [comment]
@jmccoy,

> When I look at the Preview, it appears that something is wrong with trusty?

Let's work on 'xenial' for now since that's what you want to end up with.

I simply googled the errors you're getting -

> (catfish:27119): Gtk-WARNING **: /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkwidget.c:8456: widget not within a GtkWindow

> ** (catfish:27119): CRITICAL **: atk_object_set_description: assertion 'ATK_IS_OBJECT (accessible)' failed

And found what looks to be an upstream bug, not related to crouton -

- [Catfish fails to update database](https://bugs.launchpad.net/ubuntu/+source/catfish/+bug/1507765)

I would pursue a resolution there.

*Hope this helps,*
-**DennisL**

**Comment by jmccoy** [comment]
@DennisLfromGA 

The Catfish link you sent relates to v. 1.2.2 and mine is 1.4.2.  At the end it says "Fix released." I found a later bug report (2017/01/11):

[https://bugs.launchpad.net/catfish-search/+bug/1655530](url)

which comes to no resolution.

I, too, doubt that this is a crouton problem.

If this issue can't be resolved, I'll ask for help with the trusty install - should it be brought up as a separate issue?

Thanks, again.
**jmccoy**

**Comment by DennisLfromGA** [comment]
Closing. The issue seems to point to an upstream but, not crouton related.
