### ISSUE TITLE
malloc reboots chromeos

### ISSUE THREAD

**Issue by abc123me** [dnschneid/crouton#3425]
When compiling and running the following program
```
#include <stdlib.h>
int main(){
     while True{
          malloc(1);
     }
     return -1;
}
```
It allocates all of memory and causes chromeos to fully reboot, unlike in linux and windows when it just lags the operating system to hell

**Comment by dnschneid** [comment]
Don't run that program, then?

ChromeOS's memory management is optimized for the tab case, where it handles OOM events by discarding tabs.  I don't think it kills random processes like normal Linux distros do, since that would usually be a bad idea.

The lagginess you see on Linux and Windows is probably because you have a multi-gigabyte page file, so it thrashes your disk until the page file is full before killing processes.  That's definitely not a good behavior for ChromeOS, where you will quickly fill up (and shorten the lifespan of) your internal flash.

**Comment by abc123me** [comment]
I'm fairly new to C++ so I may be completely wrong here but doesn't malloc(<bytes>) allocate on RAM, not disk space?

According to `htop` it uses all the ram and then starts using swap
