### ISSUE TITLE
(newbie) problem with the password

### ISSUE THREAD

**Issue by Ren196** [dnschneid/crouton#3430]
hello sorry in anticipation for not using the appropriate technical words but I don't really belong to the computer world. Anyway, I just bought a Chromebook and I was trying to run Linux on my device. 
I downloaded crouton and after all the procedures I had to select a new username and password for entering the chroot, but when I tried to type the password it didn't type anything. At first, I thought that it was just a way to hide the password from other eyes (like ****), so I wrote the password (even if I couldn't see it) and pressed enter and it worked. But now, after I returned in ChromeOS, I'm trying to enter the chroot again and when it asks me for the password it still doesn't write what I type so now I'm like locked outside the chroot. (I remember the password, but when I type it doesn't get written on the screen, and if I press enter anyway, it says that the password isn't correct).
I hope I explained myself, thank you for the answers

**Comment by DennisLfromGA** [comment]
@Ren196,

Hopefully, you didn't 'encrypt' your chroot using crouton's '-e' option because that will prompt you for a *different* password than the one you gave to the username in the chroot. When you enter the chroot it shouldn't prompt you for the username's password.

You can get into your chroot as 'root' and then change the password for the username you entered when it installed. Try this:

`sudo enter-chroot -u root`
`passwd [username]`

Enter the same password you gave it earlier or a new one, it'll prompt you for it twice.
It won't be displayed for security purposes but it will accept it.

Once that's done exit the chroot and re-enter as the normal user (without '-u root').

*Hope this helps,*
-**DennisL**

**Comment by Ren196** [comment]
Hi and thank you for your answer. I managed to enter the chroot eventually, but if I try to use the terminal, it asks me for the password every time I use `sudo` and even if I try `passwd [user]` it asks me for the UNIX password. 
Then I have another question that I hope is not a stupid one. Which kind if linux is the one I'm running through crouton? For example, if I want to download firefox, which operative system do I select?
Thank you

**Comment by DennisLfromGA** [comment]
@Ren196,

> if I try to use the terminal, it asks me for the password every time I use sudo and even if I try passwd [user] it asks me for the UNIX password.

That's normal, you should enter the password you gave for [username].

> Which kind if linux is the one I'm running through crouton? For example, if I want to download firefox, which operative system do I select?

If you didn't specify a 'release' on the command-line using the '-r' option when you installed your chroot it will default to the 'xenial' release which is [Ubuntu 16.04.3 LTS (Xenial Xerus)](https://wiki.ubuntu.com/XenialXerus/ReleaseNotes).

*Hope this helps,*
-**DennisL**

**Comment by EnderNightLord-ChromeBook** [comment]
It is a security feature in linux that the writing does not come up its kinda like ****  but invisible 
And I don't remember how to change passowords cause I don't do it much sorry
