### ISSUE TITLE
Installed CHROOT successfully bricked device

### ISSUE THREAD

**Issue by jamesestes1711** [dnschneid/crouton#3436]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
I installed crouton with no problems. However, on reboot it goes to the chrome os is repairing itself screen (which in my opinion should be named DEATH SCREEN) and continually reboots to this screen. I was using cloudready if this helps.

**Comment by ZeldaMaster501** [comment]
Hello!  Did you manage to repair the chrome os or do you need some help with that?

**Comment by DennisLfromGA** [comment]
@ZeldaMaster501,

I don't think the OP is using a Chromebook at all.

> I was using cloudready if this helps.

-**DennisL**

**Comment by ZeldaMaster501** [comment]
Your right @DennisLfromGA ... Trying to install chroot on a nonchrome os would definitely mess something up since Chroot is designed for chrome os, not cloud ready...

**Comment by ZeldaMaster501** [comment]
I don't know how @jamesestes1711 would recover his cloud-ready os, but if he installed it through a USB or cd, he could probably enter the recovery part of the installation drive if it has one. But otherwise, don't try to install Chroot on a system that was not designed for Chroot and if you can't get it recovered, contact their support center...

**Comment by EnderNightLord-ChromeBook** [comment]
A few things that might have happend are
You used gparted improperly 
To much memory usage 
And other than that I would not know without more details!
