### ISSUE TITLE
Black Screen After Start

### ISSUE THREAD

**Issue by ekharrington** [dnschneid/crouton#3441]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: arm64
xmethod: xorg
targets: xfce
host: version 9592.96.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.64-09103-g92105e8327f9 #1 SMP PREEMPT Sat Sep 16 09:40:52 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
When I try to run sudo enter-chroot startxfce4, the screen goes black and the computer restarts. I have a Samsung Chromebook Plus Convertible Touch Laptop (XE513C24-K01US).  

#### If known, describe the steps to reproduce the issue:
Running sudo enter-chroot startxfce4

**Comment by EnderNightLord-ChromeBook** [comment]
May be accidentally running exit commands at the start? I have heard this has happend with my friend

**Comment by DennisLfromGA** [comment]
@ekharrington,

As a temporary workaround you may be able to add & use the 'xiwi' xmethod instead of 'xorg'.

To add it to your existing chroot use this -
- sudo sh ~/Downloads/crouton -n xenial -t xiwi -u`

Then be sure to add the [crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension.

Once that's done you can launch it three different ways -
- To launch in a window (the default): `sudo startxfce4` 
- To launch in a fullscreen: `sudo startxfce4 -X xiwi-fullscreen`
- To launch in a tab: `sudo startxfce4 -X xiwi-tab` 

*Hope this helps,*
-**DennisL**

**Comment by danielbelum** [comment]
Same Chromebook, same issue, the above fix fixed it :)
