### ISSUE TITLE
Chromebook sudden crash/reboot when out of memory

### ISSUE THREAD

**Issue by roboton** [dnschneid/crouton#3445]
```
chronos@localhost / $ more /var/spool/crash/kernel.20171005.150059.0.meta 
sig=kernel-Out of memory and no killable processes.-40122954
exec_name=kernel
ver=9592.96.0
payload=/var/spool/crash/kernel.20171005.150059.0.kcrash
payload_size=108985
done=1
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,cli-extra,touch,xfce,keyboard
host: version 9592.96.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Sep 16 09:51:02 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Doing some memory intensive data work in xenial crouton and when hitting memory constraints the chromebook reboots.  Crash report above.  Running on a Pixel 2015 LS.

#### If known, describe the steps to reproduce the issue:
Running some statistical analysis in RStudio server and see memory usage and CPU usage spike.  System slows down to a halt and then reboots.

**Comment by EnderNightLord-ChromeBook** [comment]
Yes this happens a lot to be sure you wont use your memory to fast use kde,xfce,lxde unity is a bit too big to run on a small laptop so dont push it to far

**Comment by roboton** [comment]
I'm actually not using any window manager, just command-line.  I also have
Pixel LS with 16GB of ram.  Is there a way to prevent the reboot?  Use swap
memory?  It doesn't seem like expected behavior in Linux or any modern OS
to reboot when memory runs out.

**Comment by tblaschke** [comment]
I'm not sure about the Pixel LS, but all other Chromebooks don't have a SWAP partition and only rely on zram.  If you have a very memory intense application you could simply run out of memory completely and the linux kernel has to kill applications. It seems that in your case it kills some important chromeos processes which cause a reboot (not sure why it doesn't simply kill your memory intense application, as this would be the expected behavior). As a workaround you could create a SWAP file on your internal memory (if you have enough space) or on the sd card (which will cause extrem slowdowns). This should solve your reboots.
