### ISSUE TITLE
What's a good way to recover from `Disconnected` due to power management?

### ISSUE THREAD

**Issue by darcyparker** [dnschneid/crouton#3451]
If I leave my chromebook with chroot open over night (or a long time) and come back, I get this message:
>Message received (WERROR: Connection failed (code: -2). Disconnected, please close the window.)

... and I get a black screen.  Closing the window and trying to reconnect doesn't help.

I can open a `crosh` shell and run `sudo startcli` and I can access the `tmux` session I was last in.  Jumping to the other tmux session is a good workaround to backup shutting down the `chroot`.

But I wonder if there is a better way?  I know I should probably dig deeper into the wiki about disabling power management.  But I am not sure I want to disable it... And I wonder if there is another way such as a quick way I could restart the process that Crouton Extensions connects when I `startcli`?

**Comment by DennisLfromGA** [comment]
@darcyparker,

> I know I should probably dig deeper into the wiki about disabling power management. But I am not sure I want to disable it...

This is probably not ideal but the latest Chrome OS stable channel update has added some power features -
- Toggle 'Sleep' on/off when the lid is closed.
- When idle -
- 1.  turn off display & sleep
- 2.  turn off display
- 3.  keep display on

Also, I wonder if instead of using `startcli` you could instead use `startxiwi` which allows you to use the 'crouton integration' extension to switch to/from Chrome OS and your chroot. Something like -
- `startxiwi -n xenial xterm`

*Hope this helps,*
-**DennisL**

**Comment by darcyparker** [comment]
Thanks for tips. I just turned off sleep when lid is closed and idle.  That's a nice feature.  I will also try out xiwi.  I thought I was using the crouton integration extension with `startxfce4 -b`.  But I do like the idea of just running my terminal via xiwi without the desktop.
