### ISSUE TITLE
question: aptitude inside vs outside chroot

### ISSUE THREAD

**Issue by gardwired** [dnschneid/crouton#3469]
what is the difference between 1) installing things via crouton -t  and/or upgrading chroot with crouton  and 2) doing the same thing inside the chroot with regular aptitude.

eg if i wanted to install a different desktop like mate, can i just do that inside the chroot or is there some magic.

is the packages that i see updating when i update with crouton editing the same repo i see inside with aptitude.

is there anything i shouldn't do inside the chroot with aptitude?

sorry, just can't find any simple explanation about this.  maybe it's not simple.  :)

**Comment by kapilhp** [comment]
> is there anything i shouldn't do inside the chroot with aptitude?

a. There are some packages that are put on hold by crouton. There are some packages required for crouton to work.

b. Crouton has configuration files in /etc/crouton.

c. There are some executables and librarires installed by crouton under `/usr/local/`.

In general, don't remove packages as in (a), don't change the config files in `/etc/crouton` and don't remove the libraries and executables in `/usr/local` unless you know what you are doing.

If you add packages using `aptitude`, you should be OK. In some cases, adding a target using crouton gives some additional functionality ("magic") so that you can start crouton differently. For example, you *could* install a minimal crouton with `-t xorg` and then add `xfce` using aptitude, but that would not give you the `startxfce` script (outside the chroot) to jumpstart crouton into xfce. To get that script and related functionality, it is better to use `-t xfce` to add this target with crouton.

Hope this clarifies.

-Kapil.
