### ISSUE TITLE
Debian stretch - cannot enter chroot

### ISSUE THREAD

**Issue by kgingging** [dnschneid/crouton#3473]
```
name: stretch
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20170901092920~master:0216f9d1
release: stretch
architecture: amd64
xmethod: xorg
targets: kde
host: version 9901.49.0 (Official Build) beta-channel reks 
kernel: Linux localhost 3.18.0-16036-g30f3f9ed6ff1 #1 SMP PREEMPT Tue Oct 17 18:44:49 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
```

#### Please describe your issue: 
Hello, an error has come up when I try to enter my Debian stretch chroot. It installed perfectly on the second time, the first time I tried to install it; it returned a "Hash Sum Mismatch" error. It seems this is a server/ X.Org fault.

#### If known, describe the steps to reproduce the issue:
I type ``` sudo startkde ``` and the following output is this:
```
Entering /mnt/stateful_partition/crouton/chroots/stretch...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-3-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-16036-g30f3f9ed6ff1 #1 SMP PREEMPT Tue Oct 17 18:44:49 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=1277a6fb-f707-b046-b18d-2eba3e2afa9c/PARTNROFF=1 hashtree=PARTUUID=1277a6fb-f707-b046-b18d-2eba3e2afa9c/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=b2395e674405f7fc69e397a280fcc1af18d69354 salt=1fae5bbeca5cec504d7e2c2bfc8c2d16a95f0dbd9ed6d986e56fd2938c8f269d" noinitrd vt.global_cursor_default=0 kern_guid=1277a6fb-f707-b046-b18d-2eba3e2afa9c add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 07 July 2017  06:14:06AM
xorg-server 2:1.19.2-1+deb9u1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Oct 24 12:11:38 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
```
Help would be appreciated quickly because I want to get to know Debian more. Thanks in advance!

**Comment by FlashnRom** [comment]
I have the same problem.

I'm trying to put Kali-rolling onto my C201pa, and every time I try to start it using `sudo startxfce4` it comes back with this code, 

`chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.5
Release Date: 2017-10-12
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Sun Oct 15 17:37:03 PDT 2017 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=ff808309-404e-da43-88dd-544d2b7508b4/PARTNROFF=1 hashtree=PARTUUID=ff808309-404e-da43-88dd-544d2b7508b4/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=ff00ebe381853db1e7cbc1da36ac5fea8d667eed salt=d2bc97e1ae24431ac2f79d5f09ab394e76fc573bf07f41ae014cdbb63dc6d3b9" noinitrd vt.global_cursor_default=0 kern_guid=ff808309-404e-da43-88dd-544d2b7508b4  
Build Date: 16 October 2017  03:15:10PM
xorg-server 2:1.19.5-1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Oct 27 10:39:20 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error`

I tried updating crouton, like so `sudo sh ~/Downloads/crouton -u -t xfce -n kali-rolling` and after it was done it and I tried to run it, it came back with the same fatal error. 

This bug has been documented by multiple people, using crouton and without. There is a fix for those running it normally, but I don't know how to access the file directory crouton is stored on, and because of this I can't fix it.

Any input?

**Comment by FlashnRom** [comment]
Fix found 

Thanks @zguithues for the easy fix!

A quick fix is to enter the chroot with
`sudo enter-chroot -n CHROOTNAME`
and run
`sudo apt remove xserver-xorg-legacy`

Then start the chroot normally!

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by githubgnulinux** [comment]
Please reopen, similar to:

https://github.com/dnschneid/crouton/issues/3510

The suggestion to remove xorg legacy doesn't work because it was not installed.

**Comment by DennisLfromGA** [comment]
@githubgnulinux,

Please see my response to your other post here: https://github.com/dnschneid/crouton/issues/3310#issuecomment-343778118

*Hope this helps,*
-**DennisL**
