### ISSUE TITLE
Keyboard layout for Wayland?

### ISSUE THREAD

**Issue by ryanpcmcquen** [dnschneid/crouton#3526]
There is currently no keyboard layout available for Wayland installs, is there a plan to port the [current X11 one](https://github.com/dnschneid/crouton/blob/master/targets/keyboard)?

**Comment by Paviluf** [comment]
I use a slightly modified version of the script and it doesn't seem to work on Wayland (Gnome Shell). On Gnome Shell wayland the keyboard layout/model doesn't show up in settings. It should not be that hard to make it work with Wayland since Wayland still use Xkb.

**Comment by Paviluf** [comment]
Well after some research it seem that the script doesn't need any modification. The problem is that Gnome Shell doesn't allow to change the keyboard model. On X11 it's not a problem since we use some X11 tools to do so but they doesn't work with wayland. I hope the feature will be add to Gnome.

https://bugzilla.gnome.org/show_bug.cgi?id=777000
