### ISSUE TITLE
How to Run CHROOT on SD Card

### ISSUE THREAD

**Issue by noahcoetsee** [dnschneid/crouton#3554]
```
No chroots found in /mnt/stateful_partition/crouton/chroots
```

#### Please describe your issue:
I can't figure out how to run the full xfce desktop from the installed chroot which is on my MicroSD Card (which is formatted to ext4).

#### If known, describe the steps to reproduce the issue:
Follow known guides on this github wiki, and you probably will find yourself in a similar predicament if you know nothing about Linux like me...

Hey! I really need help figuring out how to run the chroot correctly. I followed the tutorial for formatting exactly, so my Card is called: Sam64GBext4 (which is from the formatting tutorial).The installation location is: "/media/removable/Sam64GBext4"

I've succesfully run CHROOTs on this device before, so I know it's still possible to do it using the SD Card. My simple 8GB Hard Drive on this thing simply won't do, and I can't install steam games and other things on removable drives :(

Any help will be much appreciated!

**Comment by TheCodeCrafter** [comment]
I have figured it out. Navigate to the /media/removable/[NAME]/bin/ and run "sudo sh enter-chroot startxfce4"

Now I'm having issues, because I wanted this so that I could store things that go into .local and things on a 64 GB space instead of a Chromebook's 8 GB drive.... How can I do that... Downloads on teh official chromebook is what it's using, when I want it to be using the Downloads on the Chromebook's SD Card.

**Comment by DennisLfromGA** [comment]
@TheCodeCrafter,

> I have figured it out. Navigate to the /media/removable/[NAME]/bin/ and run "sudo sh enter-chroot startxfce4"

That's one good way, another way is to create an alias to do it for you that makes it a little easier to invoke with something like:

`alias stxfce4='sh /media/removable/Sam64GBext4/bin/startxfce4`

Then launch it with: `sudo stxfce4`

See this comment for how to use aliases: https://github.com/dnschneid/crouton/issues/2980#issuecomment-351139397

----

> How can I do that... Downloads on teh official chromebook is what it's using, when I want it to be using the Downloads on the Chromebook's SD Card.

I would recommend just using the Chromebook's 'Files' app.  Open two windows, one with `~/Downloads` and the other with `Sam64GBext4` and then drag-n-drop or cut-n-paste between the two.

You could change the Downloads folder location to be on your external drive in Chromebook Settings but I wouldn't recommend that.

*Hope this helps,*
-**DennisL**

**Comment by TheCodeCrafter** [comment]
> You could change the Downloads folder location to be on your external drive in Chromebook Settings but I wouldn't recommend that.

That's exactly what I want though.. Why would you not recommend that? 

If you want me to get really specific, I can tell you that my issue is with not having enough space to install steam games (I know I know, it's a Chromebook, but still). I wanted to change where the .local file was for the steam games, because steam doesn't let you specify a removable drive as a download folder or something. That's why I was researching installing a Chroot on an SD Card.

**Comment by DennisLfromGA** [comment]
@TheCodeCrafter,

Okay, goto '[chrome:settings/downloads](chrome://settings/downloads)' and change the Location to your external media.

I have no clue if this'll work with Steam though, you'll probably have to try it to find out.

> Why would you not recommend that?

I think you may run into problems with it staying mounted, corruption, etc. plus you may have to leave it plugged in.  It's just something I'd rather avoid but YMMV.

*Hope this helps,*
-**DennisL**

**Comment by TheCodeCrafter** [comment]
Ah, ok. I'll try your suggestion, and if there's any further troubles, then I'll reply to this thread again. The reason I thought to install the actual CHROOT on an SD Card was because I assumed then the var folders and stuff would be created for it, but it turns out the CHROOT just uses the Chrome OS's folders..
