### ISSUE TITLE
Google Assistant in 2015 Chromebook Pixel

### ISSUE THREAD

**Issue by brianmingus** [dnschneid/crouton#3562]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171109145451~master:35a16889
release: xenial
architecture: amd64
xmethod: xorg
targets: kde,touch
host: version 9901.77.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Nov 13 16:28:58 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:

I see no technical reason that we wouldn't be able to run the Google Assistant on the 2015 Chromebook Pixel.

How can we get it installed?

**Comment by DennisLfromGA** [comment]
@brianmingus,

It's coming to some Chromebooks in the form of '<kbd>Search</kbd>+<kbd>A</kbd>'
See this CL for a few more details: [Add UMA metrics for Assistant key](https://chromium-review.googlesource.com/#/c/chromium/src/+/576223/)
I'm not sure when it will land and on what devices, guess we'll have to wait and see.

I'm closing this since it's not strictly 'crouton' related.

*Hope this helps,*
-**DennisLfromGA**
