### ISSUE TITLE
Minor Issue: Battery Offset

### ISSUE THREAD

**Issue by bfayers** [dnschneid/crouton#3577]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: artful
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/artful...
crouton: version 1-20171122220410~master:99877eaf
release: artful
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce,touch
host: version 9901.77.0 (Official Build) stable-channel reef 
kernel: Linux localhost 4.4.79-11654-g7e0f59a105a1 #1 SMP PREEMPT Mon Nov 13 16:39:00 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/artful...
```

#### If known, describe the steps to reproduce the issue: Add battery panel to XFCE4

Slight annoyance, but really a minor issue. Any help appreciated

Thanks,

Ben

**Comment by bfayers** [comment]
One other minor annoyance thing is that lots of disk partitions (OEM-A, EFI, etc) show up on my chroot desktop, ideas?

**Comment by DennisLfromGA** [comment]
@bfayers,

> One other minor annoyance thing is that lots of disk partitions (OEM-A, EFI, etc) show up on my chroot desktop, ideas?

Yes, right-click on a blank area on the desktop and select *'Desktop Settings'* from the drop-down.
Then uncheck '**Removable Devices**', see below -

![screenshot_2017-12-26_12-31-58](https://user-images.githubusercontent.com/3418772/34361575-4792e2ea-ea39-11e7-9f96-76a59df7ee9f.png)

*Hope this helps,*
-**DennisLfromGA**

**Comment by bfayers** [comment]
>Yes, right-click on a blank area on the desktop and select 'Desktop Settings' from the drop-down.
Then uncheck 'Removable Devices' under 'Default Icons'

Perfect! bugs me I forgot about this considering I use the option on my desktop

**Comment by dnschneid** [comment]
As for battery offset, that's likely due to the different algorithms used.  A lot of Linux apps (xfce included) mostly just reflect whatever the underlying battery driver says the percentage is (usually remaining capacity divided by design or last full capacity).  ChromeOS uses a different algorithm that is a bit more intuitive.  For instance, it's a common occurrence in Linux/xfce that your battery may not actually get to 100% no matter how long you charge it.  ChromeOS ensures you can actually charge to 100%, so that would be one factor that could bump its reported percentage higher.
