### ISSUE TITLE
lightdm-gtk-greeter for different DE's

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [dnschneid/crouton#3660]
is there a way that you could merge two de's together and when starting crouton you would start at lightdm...

**Comment by DennisLfromGA** [comment]
@EnderNightLord-ChromeBook,

It was considered in crouton's very early days and discussed '**[here](https://github.com/dnschneid/crouton/issues/61#issuecomment-15979869)**'.

Basically, it didn't play well with CrOS so it was shot down and I don't think that has changed much since then.

*Hope this helps,*
-**DennisLfromGA**

**Comment by EnderNightLord-ChromeBook** [comment]
Thanks 👍

**Comment by DennisLfromGA** [comment]
Closing. No response or follow-up (needed) at this time.

-**DennisLfromGA**
