### ISSUE TITLE
Is there a way to do something before unmount?

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#3707]
If I press `ctrl`+`d` while in the chroot (f.e. I am inside `sudo enter-chroot`), then the process will exit, and if it is the last process, it will unmount. How do I hook into this part? For example, I'd like to clean up the `/tmp` or something.

When I start `sudo enter-chroot`, if the file in `/tmp` doesn't exist, I know I should initialize some stuff (f.e. calling `sudo sysctl -p` in my `zshrc` to init some settings. When I exit the chroot and return, the `/tmp` files are the same. Does this mean the configuration inside the Linux environment is the same, as if the Linux machine was put on suspend then resumed?

**Comment by dnschneid** [comment]
/tmp is bindmounted across all chroots and Chromium OS itself, so nothing gets cleaned up until you reboot.

You can init stuff on first launch of your chroot by adding it to the chroot's /etc/rc.local.

There isn't an explicit script run upon unmount, but unmount-chroot will send a SIGTERM to anything that doesn't automatically quit when the terminal HUPs.  So you could launch a daemon in /etc/rc.local that sits around until it gets a SIGTERM and then runs whatever cleanup code you want.  You should also make sure the daemon holds open any directories or files it wants, because unmount-chroot may unmount stuff like /tmp before sending out the SIGTERM.

In retrospect, I wonder if that's really the best behavior...
