### ISSUE TITLE
(bug) crouton needs a real logged user ? or cannot run from "guest" user?

### ISSUE THREAD

**Issue by mckaygerhard** [dnschneid/crouton#3731]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: linux
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/linux..
crouton: version 1-20180329190032~master:d287904a
release: stretch
architecture: armhf
xmethod: xorg
targets: core,audio,lxde-desktop,x11
host: version 10323.67.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 3 11:52:52 PDT 2018 armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/linux...
```

#### Please describe your issue:

i not have and user due my network connection are not always available, so i use "guest" session in the crhomebook

the crouton start session chroot graphical programs must be started in a logged accout or cannot be used in the guest session?

#### If known, describe the steps to reproduce the issue:

install crouton and lxde but in the guest sesion and no login in any gmail account

**Comment by DennisLfromGA** [comment]
@mckaygerhard,

The guest session is restricted by design, see '[Use a Chromebook as a guest](https://support.google.com/chromebook/answer/1057090?hl=en&vid=0-986324113273-1523598911667)'

You will not be able to run any crouton chroots using the 'xiwi' xmethod since it requires the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension.

However, you should still be able to get to crosh & a shell session while signed in as guest, see this article for details:

- [Getting the command prompt through crosh](https://www.chromium.org/chromium-os/poking-around-your-chrome-os-device#TOC-Getting-the-command-prompt-through-crosh)

Then you can launch any crouton chroot that utilizes the 'xorg' xmethod, easy-peasy.

*Hope this helps,*
-**DennisLfromGA**

**Comment by mckaygerhard** [comment]
why i cannot use from VT? can noted that seems normal session need internet connection and if support for chrome book will end this will have nonsense!

**Comment by Axloqsizlik** [comment]
A normal session doesn't need internet connection. Guest Mode is impossible to use because of it's crippled access through Google. If you want, you could code something to fix it, but that's up to you.
