### ISSUE TITLE
i3wm

### ISSUE THREAD

**Issue by codingJWilliams** [dnschneid/crouton#3732]
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xorg
targets: x11
host: version 10323.62.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 20 23:39:57 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 
```

#### Please describe your issue:

I've followed your i3 guide in the wiki (works fine :D) and I've followed your `chroot on boot` guide, but I can't figure out what to put as the START_DE variable :( Help would be appreciated @dnschneid , thanks!

**Comment by MCJack123** [comment]
You can use `xinit` as START_DE (unless you used xfce, then it would be `startxfce4`).

**Comment by DennisLfromGA** [comment]
@codingJWilliams,

The 'START_DE' variable in the `crouton.init` script is intended to be used with one of the crouton desktop targets, xfce by default.  Since you only specified 'x11' as a target then you'll need to set it to `enter-chroot` to give you a shell session in your chroot, the following should work for your `~/Downloads/crouton.init` file:

```
 DELAY=10  
 CHROOT=xenial  
 START_DE=enter-chroot 
 CHROOT_APP=none
 XMETHOD=default  
 RUN_STATE=y 
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by codingJWilliams** [comment]
Thanks so much for your response! I'll try it when I get back home
