### ISSUE TITLE
Openvpn startup problem

### ISSUE THREAD

**Issue by wymby** [dnschneid/crouton#375]
I'm able to run an openvpn client from my Debian wheezy chroot, but starting it generally requires two or more attempts.  When it fails, its log ends with:

> Sat Sep 21 17:32:18 2013 TUN/TAP device tun0 opened
> Sat Sep 21 17:32:18 2013 TUN/TAP TX queue length set to 100
> Sat Sep 21 17:32:18 2013 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
> Sat Sep 21 17:32:18 2013 /sbin/ifconfig tun0 10.21.83.11 pointopoint 10.21.83.12 mtu 1500
> SIOCSIFADDR: No such device
> tun0: ERROR while getting interface flags: No such device
> SIOCSIFDSTADDR: No such device
> tun0: ERROR while getting interface flags: No such device
> SIOCSIFMTU: No such device
> Sat Sep 21 17:32:18 2013 Linux ifconfig failed: external program exited with error status: 1
> Sat Sep 21 17:32:18 2013 Exiting

When successful:

> Sat Sep 21 17:33:46 2013 TUN/TAP device tun0 opened
> Sat Sep 21 17:33:46 2013 TUN/TAP TX queue length set to 100
> Sat Sep 21 17:33:46 2013 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
> Sat Sep 21 17:33:46 2013 /sbin/ifconfig tun0 10.21.83.11 pointopoint 10.21.83.12 mtu 1500
> Sat Sep 21 17:33:46 2013 /sbin/route add -net 10.21.83.31 netmask 255.255.255.255 gw 10.21.83.12
> Sat Sep 21 17:33:46 2013 /sbin/route add -net 10.20.40.83 netmask 255.255.255.255 gw 10.21.83.12
> Sat Sep 21 17:33:46 2013 GID set to nogroup
> Sat Sep 21 17:33:46 2013 UID set to nobody
> Sat Sep 21 17:33:46 2013 Initialization Sequence Completed

Once up it works fine.  If killed, it will re-start on the first try.  It looks like a problem creating and/or accessing the tun0 device.  Suggestions?

**Comment by ammathew** [comment]
"all it does during execution is try to create a new tunnel instead of using the existing one". same here. any help?

**Comment by bennyprofane** [comment]
I've been having the same problem. the openvpn --mktun --dev tun0 seems to work sometimes but honestly I'm not sure if it works at all because other times I try that I still get the same errors everyone else has been getting with the 'no such device' stuff. But what has been working for me recently is to power off my chromebook completely and then power back up and then run the openvpn commands again.

**Comment by vevmesteren** [comment]
using the --mktun ends me at 
    resolvconf: Error: /run/resolvconf/interface either does not exist or is not a directory

**Comment by Flamewires** [comment]
If you are getting the issue where OpenVPN tries to create another tunnel when using:

    openvpn --mktun --dev tun0

Changing the OpenVPN config file from `dev tun` to `dev tun0` should cause it to use the one you created.

I've personally been using the following because I had some issues rerunning OpenVPN but it might not be necessary.

```
openvpn --rmtun --dev tun0
openvpn --mktun --dev tun0
openvpn --config /path/to/config
````

**Comment by Gandalf-** [comment]
Following Flamewires' suggestions has worked very well for me so far with an Ubuntu 14.04 chroot on a Toshiba Chromebook 2

**Comment by pippo0312** [comment]
In case of problem of stability of the tun0 interface you can have a look [[Using-Cisco-AnyConnect-VPN-with-openconnect#solution-to-make-the-tun0-interface-stable-and-the-openvpn-command-reliable][here]]

**Comment by phedders** [comment]
Thankyou thankyou @pippo0312!

  sudo stop shill
  sudo start shill BLACKLISTED_DEVICES=tun0

did the trick for me!
