### ISSUE TITLE
Crouton randomly seems to be deleted?

### ISSUE THREAD

**Issue by Yolotroll101** [dnschneid/crouton#3759]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
```chronos@localhost / $ sudo edit-chroot -all
Password: 
sudo: edit-chroot: command not found
chronos@localhost / $ █
```
#### Please describe your issue:
I was minding my own business when I decided to reboot ubuntu, and when I tried starting it up it said:
```
sudo: startxfce4: command not found
chronos@localhost / $ █
```
This happened out of nowhere, and I am confused...
#### as far as I know, there is no way to replicate this.

**Comment by xsublinialx** [comment]
This seems to be an easy fix. Try downloading crouton from the google link and try running ``sudo startxfce4``. This should work as deleting the crouton file doesn't delete your chroots.

**Comment by Yolotroll101** [comment]
did not work, `sudo startxfce4` still does not work

**Comment by DennisLfromGA** [comment]
@Yolotroll101,

Make sure you're signed-in to the same account that you installed crouton, although if it's in the default location that shouldn't be a problem.  If your chroot(s) are still there you can download crouton again if you don't have it and run the following to restore your scripts:

- `sudo sh ~/Downloads/crouton -b`

Also, if you've powerwashed since you installed your crouton chroot(s) it and all the startup scripts will be gone and you'll have to start over.

**Comment by Yolotroll101** [comment]
it worked, thanks!
