### ISSUE TITLE
it gave me an error

### ISSUE THREAD

**Issue by Yay1** [dnschneid/crouton#3762]
um i typed what the youtube tutoral said to do and it didnt work i have a samsung chromebook and i dont know what to do to fix this or if i cant do this
![ink](https://user-images.githubusercontent.com/12160423/40212414-5ba14226-5a15-11e8-959b-a3e8e1f55820.png)
i looked at another tutorial and it still didnt work any suggestions 
![screenshot 2018-05-17 at 9 26 00 pm](https://user-images.githubusercontent.com/12160423/40213048-0d90e01a-5a19-11e8-9208-f8e4185489df.png)

**Comment by DennisLfromGA** [comment]
@Yay1,

Linux is case sensitive so 'downloads' should be 'Downloads'.
And that's evidently an old youtube video since the `-e` in the `sudo sh -e` part is no longer required.
I like this ChromeUnboxed article and video, it might give you the needed detail to get you going:
- [Install Apps on Your Chromebook With Ubuntu Linux](https://chromeunboxed.com/install-native-apps-on-your-chromebook-with-ubuntu-linux/)

*Hope this helps,*
-**DennisLfromGA**
