### ISSUE TITLE
can't type in password

### ISSUE THREAD

**Issue by owenhat** [dnschneid/crouton#3782]
```
crosh> shell
chronos@localhost / $ sudo sh ~/Downloads/crouton -e -t xfce

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 

Sorry, try again.
Password: 

Sorry, try again.
Password: 

3 incorrect password attempts


when I run: sudo sh ~/Downloads/crouton -e -t xfce I can't type in the password at all. 


to reproduce the issue: type shell then hit enter.
type sudo sh ~/Downloads/crouton -e -t xfce hit enter.

**Comment by owenhat** [comment]
P.S. the croution downloaded as a text document, that may have something to do with it.

**Comment by DennisLfromGA** [comment]
@owenhat,

If you enable [Debugging Features](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features) on the initial sign-in screen and choose not to assign a password of your own then the default password is: test0000

If that's not the case then perhaps this is what's happening - when you use crouton's '-e' option it will encrypt your chroot which requires a password but it also sets up a password for chronos.

If you don't know the passwords then you may have to powerwash your Chromebook and start over.
Before you do that please take a look at some of these related topics that might help:

- when i type in sudo sh ~/Downloads/crouton -e -t xfce it asks for a password? #3619
- sudo password? #3741
- Chroot asking for password that I did NOT set [Solved] #2050

*Hope this helps,*
-**DennisLfromGA**

**Comment by Beaversl** [comment]
I have the same issue, i am trying to download mrchromebox.tech ect so i can custom install windows on my chromebook. But i can't enter any passwords at all as it will only accept newline and then clear any text i enter and tell me i have an invalid password
also i specifically set the password to admin, so it can't be invalid

**Comment by DennisLfromGA** [comment]
@Beaversl,

> But i can't enter any passwords at all as it will only accept newline and then clear any text i enter and tell me i have an invalid password

When you enter a password at the prompt it will *not* be displayed for security but it *is* being recorded. It will have you enter the same one a second time just to ensure it's the same.

> i specifically set the password to admin

How did you do that, do you mean you set a root password or a chronos password?

*Hope this helps,*
-**DennisLfromGA**

**Comment by Beaversl** [comment]
@DennisLfromGA 
i set the root password, and that is the password i am currently using for the password prompt, unless i shouldn't be?
it will go something like this

Password: [admin][newline]
Sorry, try again.

i tried

Password[admin][newline]
[admin][newline]
Sorry, try again.

and 

Password[admin][newline]
[admin]Sorry, try again.

but those don't work, if that is what you mean by having me enter it a second time

**Comment by DennisLfromGA** [comment]
@Beaversl 

I'm still unsure where 'admin' is coming from but maybe you're running into another issue resolved in this comment: https://github.com/dnschneid/crouton/issues/2927#issuecomment-264746586,

*Hope this helps,*
-**DennisLfromGA**

**Comment by Beaversl** [comment]
@DennisLfromGA 
admin is just the root password i was using

**Comment by Beaversl** [comment]
alrighty-O, i fixed the problem for me
 instead of using the console ctrl +alt+T, i used a different console, ctrl+alt+f2 (its the arrow pointing to the right)
then it asked me to login as local host, and i logged in as root using the admin password i set when i entered dev mode then i launched chrome shell, then launched (linux?) shell after that and i didn't have to go thru the stupid loop
if somebody else wants to try:
1) press keys ctrl+alt+f2(arrow key pointing to the right at the top of your keyboard)
i think the terminal/console/whatever you want to call it, is named vt2
2)enter "root" (no quotations, those just show the text to enter) for the localhost:
3)(IMPORTANT NOTE: even if you don't see it on the screen it is still being recieved) enter whatever you set the root password to be when you entered dev mode, if you don't know what that is, see footnote 3 or try your luck with the default password "test0000" (zeroes not O's)
4)now type "crosh" this starts the chrome shell
5) now type "shell" this starts the linux shell (it might seem redundant to leave what i think is linux shell, to enter chrome shell, then linux shell again, i had to for my commands to work, so just try it out, you can always try a different way
6) now you can do whatever you want without the pesky loop stopping you midstream 


footnote 3: there is an option _after you first enter dev mode _  (just exit and then re-enter dev mode if you can't get to it) after you enter ctrl+d to skip the OS unverified screen, right underneath the WELCOME! there is a link that says Enable debugging features, click on that, you should see a screen that says enable debugging features, enter your new root password there, you now have the root password, now click lets go, and set up your internet, ect ect, once you get to the chrome desktop resume at step 1

and thanks @DennisLfromGA  for helping me with this
