### ISSUE TITLE
sudo: enter-chroot: command not found

### ISSUE THREAD

**Issue by econcrank** [dnschneid/crouton#3793]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
crosh> shell
chronos@localhost / $ sudo enter-chroot
Password:
sudo: enter-chroot: command not found

#### Please describe your issue:

I just instaled chroots but I enter-chroot is not there.

**Comment by DennisLfromGA** [comment]
Try re-installing the host-bin files with: 
- `sudo sh ~/Downloads/crouton -b`

Then try `enter-chroot` again.

*Hope this helps,*
-**DennisLfromGA**

**Comment by econcrank** [comment]
Thank you. This works for enter-chroot but now I have the same problem with
startxfce4

Can you help me?

**Comment by DennisLfromGA** [comment]
@econcrank,

Please show us the output of the following command: `sudo edit-chroot -all`

-**DennisLfromGA**

**Comment by econcrank** [comment]
name: bin
encrypted: no
Entering /media/removable/USB Drive/chroots/bin...
/usr/local/bin/enter-chroot: 511: /usr/local/bin/enter-chroot: cannot
create /var/run/crouton/media/removable/USB
Drive/chroots/bin/etc/crouton/name: Directory nonexistent
Unmounting /media/removable/USB Drive/chroots/bin...
name: chroots
encrypted: no
Entering /media/removable/USB Drive/chroots/chroots...
/usr/local/bin/enter-chroot: 511: /usr/local/bin/enter-chroot: cannot
create /var/run/crouton/media/removable/USB
Drive/chroots/chroots/etc/crouton/name: Directory nonexistent
Unmounting /media/removable/USB Drive/chroots/chroots...
name: precise
encrypted: no
Entering /media/removable/USB Drive/chroots/precise...
/usr/local/bin/enter-chroot: 511: /usr/local/bin/enter-chroot: cannot
create /var/run/crouton/media/removable/USB
Drive/chroots/precise/etc/crouton/name: Directory nonexistent
Unmounting /media/removable/USB Drive/chroots/precise...
name: precise2
encrypted: yes, locked
Unmounting /media/removable/USB Drive/chroots/precise2...
name: precise3
encrypted: yes, locked
Unmounting /media/removable/USB Drive/chroots/precise3...
name: xenial
encrypted: yes, locked
Unmounting /media/removable/USB Drive/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@econcrank,

We assume you are using the *default* location for your chroots under `/usr/local` unless you tell us otherwise - _**you didn't tell us otherwise.**_ 😉

To re-install your host-bin files *based on the chroots on your external media* try this:

- `sudo sh ~/Downloads/crouton -p "/media/removable/USB Drive/" -b`

Aside from that, you *can* run the scripts directly from the `/bin` folder on your external media.
Try something like this for instance:

- `sudo sh "/media/removable/USB Drive/bin/startxfce4" -n xenial`

( Use the '`sh`' prefix if it's mounted 'noexec'. )

*Hope this helps,*
-**DennisLfromGA**

**Comment by econcrank** [comment]
Thank you for the spoon feed. I owe you a beer or tacos when you stop by DC.

Cheers

**Comment by econcrank** [comment]
Or beers and tacos.
