### ISSUE TITLE
Xenial

### ISSUE THREAD

**Issue by McFoeNem** [dnschneid/crouton#3819]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180611074759~master:3697b784
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 10718.13.0 (Official Build) dev-channel cyan 
kernel: Linux localhost 3.18.0-17844-g7b8a3c85d4e1 #1 SMP PREEMPT Mon Jun 4 22:19:52 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue: 
Everytime i type in "sudo sh -e ~/Downloads/crouton -t xfce" it says that it's downloading latest crouton installer, then say "/usr/local/chroots/xenial already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it." 

I don't know why it's saying this and I just want Ubuntu on my Chromebook. please help

**Comment by DennisLfromGA** [comment]
@McFoeNem,

> Everytime i type in "sudo sh -e ~/Downloads/crouton -t xfce" it says that it's downloading latest crouton installer, then say "/usr/local/chroots/xenial already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it."

> I don't know why it's saying this...

Since you have an 'xenial' chroot installed already when you try to install another chroot without specifying a different name or release it tries to install 'xenial' again and finds one already exists.

> ... I just want Ubuntu on my Chromebook. please help

You can *add* targets to your existing 'xenial' chroot.  Since you already have 'xfce' I'm going to assume when you say '*Ubuntu*' you mean you want the '*Unity*' desktop so I'll describe how to do that below:

- `sudo sh ~/Downloads/crouton -n xenial -t unity -u`

That gives you the plain vanilla 'Unity' desktop. If you want more bells & whistles then install the full desktop like this:

- `sudo sh ~/Downloads/crouton -n xenial -t unity-desktop -u`

Here's a brief summary of the different footprints, etc. for the two 'Unity' desktops available -
```
unity
        Installs the Unity desktop environment. (Approx. 700MB)
        Requires: gtk-extra
unity-desktop
        Installs Unity along with common applications. (Approx. 1100MB)
        Requires: unity
```
You can *add* other targhets like 'xiwi', etc. using the same 'update' method with the '-u' option as shown in the examples above.

*Hope this helps,*
-**DennisLfromGA**
