### ISSUE TITLE
Starting crouton installed on SD card, after "powerwash"

### ISSUE THREAD

**Issue by nickbailuc** [dnschneid/crouton#3822]
I wish to test out crostini, however do not wish to break my crouton installation. I have Debian 9 running on x.org normally, and it is installed on an SD card, channeled via symbolic link onto the SD card. If I switch Chrome OS channels, I will have to powerwash the computer, which will remove the binary files "enter-chroot" and "startgnome".

After powerwashing, can I reestablish the symbolic link to the chroot installation, and simply copy the binary files "enter-chroot..." back into "/usr/local/bin" ? Will that be enough to get crouton to work again?

-----------------------------------------------------------------------------------------------

In terms of this being an issue, it isn't exactly one, however I haven't seen a solution to this in the crouton instructions or installer file, and I hope that this is grounds for considering it acceptable for posting as an issue here on github.

**Comment by DennisLfromGA** [comment]
@nickbailuc,

You can restore your 'host-bin' files using crouton's '-b' option along with the '-p' option with the path to the parent folder containing the 'chroots' & 'bin' folders on your external drive, like:

- `sudo sh ~/Downloads/crouton -b -p "/path/to/external/drive"`

You can also copy the 'host-bin' files to your '/usr/local/bin' folder if you like and then link your chroots folder on the external drive to make it a little easier for launching things. 

Of course you can just launch things giving the full path to the 'bin' folder on your external drive like this for example:

- `sudo sh "/path/to/external/drive/bin/startxfce4"` 

(note: use 'sh' if the external media is mounted 'noexec'.

Instead of typing in the full path each time you can create aliases to do it, something like:

alias `e.startxfce4='sudo sh "/path/to/external/drive/bin/startxfce4"'`

*Hope this helps,*
-**DennisLfromGA**

**Comment by mareedsmdphd** [comment]
Excellent advice, DenniisLfromGA; everything you say helps, and very often helps me!

**Comment by bahaaaldin214** [comment]
```Installing xenial-amd64 chroot to /usr/local/chroots/xenial
################################################################################################################################################################### 100.0%
Patching debootstrap...
Downloading bootstrap files...
E: You must install wget to download packages.
debootstrap error log:
tail: cannot open '/tmp/crouton.dlj/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.```
right after that update

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
