### ISSUE TITLE
sudo sh crouton -e -r wheezy -t xfce = password asked

### ISSUE THREAD

**Issue by christi9n** [dnschneid/crouton#3825]
Hi,

I try to run the following command (on an ACER R13) in a shell `sudo sh crouton -e -r wheezy -t xfce` and I'm always been asking the sudo password !!!

Any idea of this issue ?

**Comment by DennisLfromGA** [comment]
@christi9n,

> Any idea of this issue ?

Yes, the `-e` option you specified in your command string tells crouton to encrypt the chroot and invokes `chromeos-setdevpasswd` which asks for and sets a chronos password.

You can install your chroot as above without the `-e` option then when you've got everything working the way you want you can still encrypt it if you like with an update similar to the following:

`sudo sh ~/Downloads/crouton -e -n wheezy -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by christi9n** [comment]
Many thanks for your feedback, but I've already tried withour `-e` wich also doesn't work... I'm still having password asked !

**Comment by DennisLfromGA** [comment]
@christi9n,

When it first prompted you for a password did you enter one?
If so, then that's the one you should enter at that prompt.

Can you get to a shell session now without a password?
If so, then I would delete the chroot and start over.
If not, then you may have to powerwash and start over.

*Hope this helps,*
-**DennisLfromGA**

**Comment by christi9n** [comment]
> When it first prompted you for a password did you enter one?
> If so, then that's the one you should enter at that prompt.
... ;o) I obviously ;o)) did it I powerwashed already times to try everything (?) 

> Can you get to a shell session now without a password?
> If so, then I would delete the chroot and start over.
I can get a shell session without password ... I only need password when I do a SUDO.
How do you delete the CHROOT ?

**Comment by DennisLfromGA** [comment]
@christi9n,

Okay, if you can get to a shell session without a password then there's a chance you can delete the chroot and start over.  

When you enter `sudo` and it prompts you for a password can you enter your password and continue?
If so, then this is how to delete the chroot: `sudo delete-chroot wheezy`
If not, you may have to powerwash it *again*, especially if the following file is present:

`/mnt/stateful_partition/etc/devmode.passwd`

That file indicates a chronos password was set, if you don't know it then you need to powerwash to remove it.

*Hope this helps,*
-**DennisLfromGA**

**Comment by christi9n** [comment]
Many thanks for your feedback again but as I said 

- I powerwashed 4 times and I've got at the end the same pb

- When I enter SUDO I'm asked to enter a password ... and I tried all passwords which could be OK

So impossible to use a SUDO at all!

**Comment by DennisLfromGA** [comment]
@christi9n,

> I powerwashed 4 times and I've got at the end the same pb

That is highly unusual, I actually was experimenting with mine and had no problems.

> So impossible to use a SUDO at all!

After you powerwashed when at the initial sign-in screen did you enable ['Debugging Features'](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features)

![dev-ui](https://user-images.githubusercontent.com/3418772/42692982-8bc8c2de-867b-11e8-8b2a-ee2f5e0d03f4.png)

If so, you'll have to first open the 'Developer Console' on VT2 using the key-combo <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>F2</kbd> and login as root with the password you entered on the screen above.
If you didn't enter a root password it will default to: `test0000`

Once you get a shell as root you'll need to set a password for 'chronos' using: `chromeos-setdevpasswd`

> Is this pb linked to the model of the chromebook : ACER R13 ?

Also highly unlikely since others with that device haven't reported this pb.

> I didn't find at all around the web this pb !?

Show us or tell us what the first five lines display when you navigate to: [chrome://version](chrome://version)
In that output, line \#3 that begins with 'Platform:' will tell us what the actual 'codename' is of your device.
Then you can cross-reference that with those listed here to find your device -
- [Developer Information for Chrome OS Devices](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices#goog-ws-list-table)

*Hope this helps,*
-**DennisLfromGA**

**Comment by christi9n** [comment]
Impossible to log as root as you proposed.
I just powerwashed again and it's the same situation !

chrome://version
4th line = 10575.58.0.............................;

**Comment by DennisLfromGA** [comment]
@christi9n,

> chrome://version
4th line = 10575.58.0.............................;

Good to know, I had asked for the *third* line.

Just so we're clear, here's the ['powerwash'](https://support.google.com/chromebook/answer/183084?hl=en) procedure:

1. Sign out of your Chromebook.
2. Press and hold <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>r</kbd>.
3. Click Restart.
4. In the box that appears, click 'Powerwash' and then 'Continue'.
5. Follow the steps that appear and sign in with your Google Account.
    Note: The account you sign in with after you reset your Chromebook will be the owner account.
6. Do NOT enable 'Debugging Features'.

Once you've reset your Chromebook:
- Follow the onscreen instructions to set up your Chromebook
- Check if the problem is fixed
- If not then perhaps perform a ['Chromebook Recovery''](https://support.google.com/chromebook/answer/1080595?hl=en)

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@christi9n,

> ... my problem came from the 'Debugging feature' I enabled.

As I suspected, that can be a bit tricky but the new root password prompts make it a tad less troublesome.

> So I wanted today to try with ChruBuntu but unfortunately http://goo.gl/9sgchs gives an error page ... impossble to doncload this script !

> Do you kno by chance where else I could find this 9sgchs ?

The ChrUbuntu effort has been abandoned for a while now so I wouldn't try to use it any longer.

The good news is there is a 'new & improved' method called ['chrx'](https://github.com/reynhout/chrx) that can do what ChrUbuntu did and a whole lot more. With it you can setup a dual-boot system with Chrome OS and a Linux distro, that's what I've done. If you choose this option just make sure you leave enough storage space for Chrome OS to run and function properly, 'chrx' should suggest the proper sizes when you run it.

Another advantage to this dual-boot setup is you can use some of that space (on partition 7) for your crouton chroots eliminating the need to re-install them after a powerwash, pretty handy.

*Hope this helps,*
-**DennisLfromGA**

**Comment by christi9n** [comment]
Unfortunately ACER R is not supported... [https://wiki.galliumos.org/Hardware_Compatibility#cite_note-ARM-2](url)

**Comment by christi9n** [comment]
I won this ACER R13 and I can't stand using it under ChromeOS.

I keep on searching a LINUX solution in dual boot for it .... any suggestions ?

**Comment by DennisLfromGA** [comment]
@christi9n,

Not being able to use 'chrx' is a bit of a bummer but 'crouton' is still a very good option if you want to run a Linux distro with a full desktop gui, its probably your best bet for a LINUX solution.

-----
In fact, let me suggest one that might work for you:

- sudo sh ~/Downloads/crouton -r stretch -t xiwi,xorg,xfce-desktop,cli-extra,keyboard,touch,chrome`

Note: substitute 'stretch' with 'buster' or 'sid' if you're adventurous.
Also, you'll need to install the ['crouton integration'](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension from the Chrome Web Store.

Once that installs successfully you can launch your desktop in a number of ways: 

1. `sudo startxfce4 -n stretch -X xorg`
2. `sudo startxfce4 -n stretch -X xiwi` (launches in a window)
3. `sudo startxfce4 -n stretch -X xiwi-fullscreen` (launches fullscreen)
4. `sudo startxfce4 -n stretch -X xiwi-tab` (launches in a tab - my favorite)

*Hope this helps,*
-**DennisLfromGA**

**Comment by christi9n** [comment]
@DennisLfromGA 
Yes I agree with you CROUTON seems quite efficient for that kind of Computer.
What I dislike with this solution is to run "through" ChromeOS, not "beside", and to logged in a ChromeOS session before launching another linux one.

I'm going to test and try the way you just gave me and let you know ... many thanks.

**Comment by christi9n** [comment]
Excuse me @DennisLfromGA for the delays of my return

Following your very explanations make me doing the right things and now DEBIAN runs as you explained.

Unfortunately I found this way of access to debian quite heavy .. you've to make "Ctrl + D" and after open a new "Crosh > shell" to run one you the fourth command you gave ... ouf !!
The received Chromebook is for my daughter and I don't want to make her get bored ;o))

I saw in your clear WIKI you gave the opportunity to autostart a Crouton (debian) session ... https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup
It doesn't work on my ACER R 13 !

Have you a last idea to boot the DEBIAN session ?

**Comment by DennisLfromGA** [comment]
@christi9n,

> Have you a last idea to boot the DEBIAN session ?

Nope, not with that device at least ATM.

Don't know if you've heard but there is a new Project Termina making it's debut in the dev channel on the Pixelbook and a few other devices currently. This will bring Crostini / Linux apps to a lot of the newer Chromebooks and some of the older capable ones. It installs a Debian Stretch container on your Chromebook and doesn't require Development mode. If you're interested, keep an eye on this r/Crostini thread that talks about the R13's future prospects:

- [Where should I watch for updates for aarch64?](https://www.reddit.com/r/Crostini/comments/8pkb72/where_should_i_watch_for_updates_for_aarch64/?st=jjsvol7i&sh=0f6fc598)

-**DennisLfromGA**

**Comment by christi9n** [comment]
I didn't know Crostini ... thanks again for this track.
I'm going to have a watch on this project.
