### ISSUE TITLE
need to install jamovi (.org) 

### ISSUE THREAD

**Issue by olioliv1** [dnschneid/crouton#3855]
Hi everyone, i just installed crouton with xfce distribution on my chromebook  acer r13 (arm, mediatek).
I discover the linux environment now, i'm a beginner and i need some help to install this statistical software Jamovi (https://www.jamovi.org/).

Thank you for your help,

Oli

**Comment by DennisLfromGA** [comment]
@olioliv1,

Welcome to Linux. 👍 

Since this site is for crouton support let me point you to some info. that is for Jamovi instead.

Here is the main site for Jamovi that might help you on your way:
- https://www.jamovi.org/

It has a forum that might be of help also:
- https://forum.jamovi.org/

If you install it and run into issues you could check on the forum above or look at issues on the GitHub site:
- https://github.com/jamovi/jamovi/issues

*Hope this helps,*
-**DennisLfromGA**
