### ISSUE TITLE
Dropbox warning - move to an Ext4 drive or synching will stop in November

### ISSUE THREAD

**Issue by pjchamberlain** [dnschneid/crouton#3874]
```
crosh> shell
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: xenial
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,touch
host: version 10895.40.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-18121-g8c0cb17dd7e0 #1 SMP PREEMPT Wed Aug 29 13:55:15 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
chronos@localhost / $ 
```
I've been getting warnings popup when logging in to an XFCE session  and today an email arrived from Dropbox saying I need to move Dropbox to an Ext4 drive.

I'm confused, as far as I can see my Dropbox folder under /home/<user> is already ext4. Is there a location  where Dropbox will be happy?

Dropbox pops up a warning every time I start an XFCE session.

**Comment by dnschneid** [comment]
Actually, since your chroot is encrypted, the filesystem is technically ecryptfs as far as Dropbox is concerned.

You'll need to make a [share](https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders) that uses the "shared" prefix to import an unencrypted directory into your chroot; Dropbox should be happy running from that.  Of course, then you'll have an unencrypted Dropbox directory on your system, so there's a tradeoff there.

**Comment by fortran77** [comment]
The following recipe worked nicely for me on Crouton. 

https://www.linuxuprising.com/2018/11/how-to-use-dropbox-on-non-ext4.html
