### ISSUE TITLE
Root password changed on its own?

### ISSUE THREAD

**Issue by Kenpoman** [dnschneid/crouton#3882]
```
crosh> shell
chronos@localhost / $ sudo edit-chroot all
Password: 
Sorry, try again.
Password: 
Sorry, try again.
Password: 
sudo: 3 incorrect password attempts
```

**Comment by DennisLfromGA** [comment]
@Kenpoman,

> Is there a way I can fix this without powerwashing?

I don't think so. 
Have you enabled '[Debugging Features](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features)' ?

*If* you know the root password then this might work:

- https://github.com/dnschneid/crouton/issues/2050#issuecomment-348382431

Otherwise, I think a powerwash is necessary.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Kenpoman** [comment]
@DennisLfromGA Powerwashed my chromebook, but now I can't get into the CTRL+ALT+F2 Terminal, it just shows a black screen. Do I have to enable debugging features to get to this terminal? If not, should I enable debugging features for some other reason?

**Comment by DennisLfromGA** [comment]
@Kenpoman,

If you still have Developer mode enabled you should get the Developer Console on VT2, you don't need to enable Debugging Features for that.  But the preferred way of accessing a shell session is to sign-in and press <kbd>**ctrl**</kbd>+<kbd>**alt**</kbd>+<kbd>**t**</kbd> to get a crosh prompt and then enter `shell`.

[Debugging Features](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features) will enable the following -
- Remove rootfs verification so you can modify OS files
- Enable SSH access to the device using the standard test keys so you can use tools such as cros flash to access the device
- Enable booting from USB so you can install an OS image from a USB drive
- Set both the dev and the system root login password to a custom value so you can manually SSH into the device

I don't enable them on mine since I don't need or want all of those features. You can enable one or more if them from the command line if you like by running the individual scripts here:   
```
/usr/libexec/debugd/helpers/dev_features_chrome_remote_debugging
/usr/libexec/debugd/helpers/dev_features_password
/usr/libexec/debugd/helpers/dev_features_rootfs_verification
/usr/libexec/debugd/helpers/dev_features_ssh
/usr/libexec/debugd/helpers/dev_features_usb_boot
```

I enable rootfs_verification & ssh but none of the others.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Kenpoman** [comment]
@DennisLfromGA 
Is there a way I can set the root password from shell?

**Comment by Kenpoman** [comment]
@DennisLfromGA Nevermind figured it out
```sudo chromeos-setdevpasswd```
worked, still getting a blackscreen with the CTRL + ALT + F2 screen though.

**Comment by DennisLfromGA** [comment]
@Kenpoman,

No, I don't know why you're getting a blank screen on VT2. Out of curiosity, why do you need it?

Actually, CrOS runs other 'getty's on VT3/F3 & VT4/F4 - 
```
root       283  0.0  0.0   4276     0 pts/1    Ss+  Sep17   0:00 /sbin/agetty - 9600 xterm
root       285  0.0  0.0   4276     0 pts/2    Ss+  Sep17   0:00 /sbin/agetty - 9600 xterm
root       287  0.0  0.0   4276     0 pts/3    Ss+  Sep17   0:00 /sbin/agetty - 9600 xterm
```
Maybe one of those would work.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Kenpoman** [comment]
I don't need it, just kind of unnerved as to why it isn't working. All those (I assume you bring them up the same way with CTRL + ALT + F3/F4) come up blank.

**Comment by DennisLfromGA** [comment]
@Kenpoman,

Yup, with ctrl+alt+F2/F3/F4.

I'm gonna close this since the original issue is resolved.

-**DennisLfromGA**
