### ISSUE TITLE
failed to run debbootstrap

### ISSUE THREAD

**Issue by Merith-TK** [dnschneid/crouton#3883]
https://pastebin.com/cLBD6AF8

#### Please describe your issue:
im trying to install trusty with xiwi and core targets,  but keep getting the error in the title

**Comment by Merith-TK** [comment]
Okay, I have found the issue behind this.

Merely having ChromeBrew installed breaks debootstrap

**Comment by DennisLfromGA** [comment]
Yup, I had what may have been a similar problem with `busybox` installed. It was using the wrong 'extractor' and kept bombing out. There was a PR https://github.com/dnschneid/crouton/pull/3420 that fixed it but maybe the chromebrew `ar` is causing problems for you.

-**DennisLfromGA**

Closing. Please re-open if this issue is still a concern.
