### ISSUE TITLE
LIGHTEST POSSIBLE INSTALL

### ISSUE THREAD

**Issue by Merith-TK** [dnschneid/crouton#3890]
So, i am trying to install the smallest possible chroot, using SSH, X, XIWI so i can access my server and forward X windows to my chromebook

i essentially just wanna do this
`
Chronos@localhost: sudo startxiwi -b xterm #I will have an alias
#in xterm
chroot@localhost: ssh $(serverIP) -X
user@server: foo-bar` 
and have the window popup on my Chromebook

**Comment by DennisLfromGA** [comment]
@DovaMerith,

'xiwi' will automatically pull in a few other needed targets but it will be minimal, here's what it requires:

- audio,extension,core,x11

You *may* want to add the 'cli-extra' target since it installs these packages: dbus openssh-client kbd

So your command line would look like:

- `sudo sh ~/Downloads/crouton -t xiwi,cli-extra`

*Hope this helps,*
-**DennisLfromGA**
