### ISSUE TITLE
Terminal to launch Linux keeps crashing and when trying to download Crouton by Crosh.

### ISSUE THREAD

**Issue by Chillthuggin1** [dnschneid/crouton#3905]
When I installed crouton my internet cut out in the middle of the download and I tried to re-install Crouton with 

"sudo sh ~/Downloads/crouton -r trusty -t xfce" or with "sudo sh ~/Downloads/crouton -r list" it keeps saying 

Output: "Downloading latest crouton installer...
Warning: Transient problem: timeout Will retry in 1 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 1 retries left.
curl: (6) Couldn't resolve host 'github.com'
Failed to download crouton"

It won't let install Crouton no matter what! I did "sudo delete-chroot precise" but it doesn't exist so I did "sudo delete-chroot precise -d" And it said all Chroots deleted but I cannot delete all of Crouton!

I don't know if this error can be reproduced.

**Comment by Chillthuggin1** [comment]
I thyped "sudo sh ~/Downloads/crouton -r list" and the out put is this:"Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy jessie stretch buster sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty utopic! vivid! wily! xenial yakkety! zesty! artful* bionic*
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort."

**Comment by DennisLfromGA** [comment]
@Chillthuggin1,

> When I installed crouton my internet cut out in the middle of the download and I tried to re-install Crouton with  

> "sudo sh ~/Downloads/crouton -r trusty -t xfce

That will attempt to install a *new* crouton chroot and fail since one will have been found on the device already.

> " or with "sudo sh ~/Downloads/crouton -r list" it keeps saying

That will list the 'releases' available in crouton but nothing else.

> It won't let install Crouton no matter what! I did "sudo delete-chroot precise" but it doesn't exist so I did "sudo delete-chroot precise -d" And it said all Chroots deleted but I cannot delete all of Crouton!

You specified the 'trusty' release originally so the 'precise' release isn't installed and therefore cannot be deleted.

-----

When things go awry with an installation you *may* be able to recover and finish the installation with a crouton update using the '-u' option. In your situation try this:

- `sudo sh ~/Downloads/crouton -n trusty -u`

If that fails to complete successfully you may have to delete it with this and start over:

- `sudo delete-chroot trusty`

If you do start over I would recommend using the newer default release 'xenial' instead of trusty. You can do that with this command:

- `sudo sh ~/Downloads/crouton -t xfce`

*Hope this helps,*
-**DennisLfromGA**
