### ISSUE TITLE
less than default unity desktop environment

### ISSUE THREAD

**Issue by MikeEnders** [dnschneid/crouton#3951]
```
Please paste the output of the following command here: sudo edit-chroot -all
sudo: edit-chroot: command not found

```

#### Please describe your issue:
I used Crouton to install Unbuntu Xenial with Unity desktop environment on my HP Chromebook.  On reading documentation for Ubuntu Unity, it appears some applications that usually come with default install are missing, most notably, the Ubuntu Software Center.  I am new to Linux.  Is there a way to get the missing pieces? Or should I have followed your advice and used xfde desktop environment instead?

**Comment by MikeEnders** [comment]
I tried it.  It downloaded a lot of stuff, but it wouldn't start when I started Unity.  I should have written down the error message, but I didn't.  Instead I tried to start again with a clean slate and rebooted Chrome regular mode, which I understand (maybe incorrectly)  erases everything that was done in developer mode.  When I got back into the shell and gave it the command you suggested, I got:

> ...

Downloading latest crouton installer ...
[a whole bunch of # symbols] 100.0%
[a whole bunch of # symbols] 100.0%
/mnt/stateful partition/crouton/chroots not found.
/usr/local/chroots/xenial does not exist; cannot update.
Valid chroots:
chronos@localhost / $

> 

I take that to mean that my attempt to clean the slate and start over didn't work and left some junk behind. If I get it all to work again, I will post another comment saying how I resolved it and close this thread.

**Comment by DennisLfromGA** [comment]
@MikeEnders,

I take it to mean that you were using the '-u' update option on a non-existing crouton chroot.

> Valid chroots:
chronos@localhost / $

The above output shows no chroots installed.

You need to install it from scratch since leaving and re-entering Developer mode will wipe the user partition clean. If you want to try again I would suggest the following for an Ubuntu Desktop with a few other handy targets:

- `sudo sh ~/Downloads/crouton -r xenial -t xorg,xiwi,cli-extra,keyboard,touch,unity-desktop,chrome` 

Then install the '**[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)**' extension from the Chrome Web Store.
You can then use either the 'xorg' or 'xiwi' xmethod by launching them with the '-X' option:

- For 'xorg' in a full screen: `sudo startunity -n xenial -X xorg`
- For 'xiwi' in a full screen: `sudo startunity -n xenial -X xiwi-fullscreen`
- For 'xiwi' in a tab: `sudo startunity -n xenial -X xiwi-tab`
- For 'xiwi' in a window: `sudo startunity -n xenial -X xiwi`

*Hope this helps,*
-**DennisLfromGA**
