### ISSUE TITLE
Existing distro into separate partition install into crouton.

### ISSUE THREAD

**Issue by barolo** [dnschneid/crouton#3983]
Is it possible to use crouton with existing linux install? I have gentoo/kde_plasma in dual boot. Well, I can chroot just fine into it but would love to use graphical apps, wayland ones & xiwi integration

**Comment by DennisLfromGA** [comment]
Nope, crouton relies on Chrome OS so it's not possible.

Here's a snippet from the [README](https://github.com/dnschneid/crouton#whats-a-chroot)
> crouton is a set of scripts that bundle up into an easy-to-use, Chromium OS-centric chroot generator.

It's explained in more detail here: [What's a chroot?](https://github.com/dnschneid/crouton#whats-a-chroot)

*Hope this helps,*
-**DennisLfromGA**

**Comment by icecream95** [comment]
This actually is possible.

Create an Ubuntu (or Debian) chroot using crouton, with the xorg and/or xiwi targets.

Then, enter your chroot as a root user with `sudo enter-chroot -u root`.

Put something like this into .xinitrc:

```bash
#!/bin/bash

# noatime speeds things up and increases drive lifetime, but can break some things - change it to relatime if it does
mount -o noatime /dev/sdX1 /mnt

# For debugging
xterm &

mount -B ~/Downloads /mnt/home/USER/Downloads

# You might get problems with D-Bus if you don't do this
mount -B /var/host /mnt/var/host

# Mount system directories
mount -B /dev /mnt/dev
mount -B /media /mnt/media
mount -B /proc /mnt/proc
mount -B /run /mnt/run
mount -B /sys /mnt/sys
mount -B /tmp /mnt/tmp

# Start DE - I'm not sure if this is correct for KDE
chroot /mnt su USER -c "cd ~; startkde"
```

To start KDE in your gentoo installation, just run `sudo enter-chroot -X xorg `(or xiwi)` -u root xinit` from the Chrome OS shell.

With a bit of scripting and sticking files in tmp, you could make the xinitrc script so that it can start single applications in an xiwi window rather than start the whole of KDE - /usr/local/bin in Chrome OS is writable, so you can stick any helper scripts there.
