### ISSUE TITLE
Crouton screen refresh freezing

### ISSUE THREAD

**Issue by Alizter** [dnschneid/crouton#3992]
#### Please describe your issue:
On a fresh install of crouton. Happens on both xenial and bionic that I've tested. There is a lot of screen lag.

You will be using your chromebook until the screen suddenly freezes. I can tell its just the refresh since I am pretty sure everything else is still running. A quick fix is to switch back and forth between chromeos and crouton. This refreshes the screen and you are good again for some amount of time before it happens again. It can unfreeze itself but this takes a while.

This is the only fix that I have found:

In the ChromeOS terminal, without starting crouton do this:
```
sudo enter-chroot
cd /usr/share/X11/xorg.conf.d
sudo ln -s /etc/crouton/xorg-intel-sna.conf 20-crouton-intel-sna.conf
```
After which when you start crouton the issue shouldn't come up again.

I am opening this issue so that it can be documented correctly as it has been alluded to in other issues but I don't think anyone can read 100s of posts.

I tested this solution on a Dell Chromebook 11 and an Asus flip C302.

**Comment by Mazzer797** [comment]
Tested on an AMD Based HP Chromebook also - Worked for me as I was getting the fault on the initial install. 
Thanks!

**Comment by beadsland** [comment]
Experiencing same issue with fresh install of bionic. Unfortunately, the intel-nsa.conf suggestion didn't work for me. Got flickering in chromium window running under chroot before chroot crashed to black screen. Didn't even stay up long enough to determine if the refresh freeze was otherwise addressed.

Shortcut removed from /etc/crouton, and search continues for solution to refresh freezes.

**Comment by beadsland** [comment]
This seems to be related to [Issue #3957](https://github.com/dnschneid/crouton/issues/3957), as the freezing only occurs when chromium is running in the current workspace. I've moved chromium to a dedicated workspace and haven't seen any freezing for hours so long as I'm only working in the non-chromium workspace. 

That said, a refresh freeze can be triggered simply by switching to the chromium workspace. Also, my sense is that refresh freezes become more likely if other things are running in the workspace that is also showing chromium.

Note: I'm running xfce in bionic, rather than KDE or Gnome as per Issue 3957, but the same mitigation strategy does isolate the problem. OTOH, my long-running xenial chroot (Unity) saw refresh freezing  also, although I haven't tested to determine if this was also chromium-related. But where in xenial/unity it was a few times a day refresh freeze, in a newly generated bionic/xfce chroot it was multiple times an hour.
