### ISSUE TITLE
Bionic install failure: The following packages have unmet dependencies (xorg, xserver-xorg-video-intel)

### ISSUE THREAD

**Issue by mwsduelle** [dnschneid/crouton#3995]
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190120145639~master:5bf96711
release: bionic
architecture: amd64
targets: xfce-desktop,keyboard,touch
host: version 11633.0.0 (Official Build) dev-channel cave 
kernel: Linux localhost 3.18.0-18768-gbbede230dcf1 #1 SMP PREEMPT Tue Jan 22 19:35:27 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
```

#### Please describe your issue:
Installation of chroot fails with this:
```
Package 'xserver-xorg-video-all' is not installed, so not removed
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xorg : Depends: xserver-xorg (>= 1:7.7+19ubuntu7.1)
 xserver-xorg-video-intel : Depends: xorg-video-abi-23
                            Depends: xserver-xorg-core (>= 2:1.18.99.901)
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
```

#### If known, describe the steps to reproduce the issue:
Attempt to install bionic with current script on CAVE.

**Comment by Mario253** [comment]
Can confirm that the bug exists on CELES as well.

For those who don't understand, CAVE and CELES are just the codenames for different types of Chromebooks; CAVE is the ASUS Flip C302, and CELES is the Samsung Chromebook 3.

**Comment by efrankb3** [comment]
I was able to fix this from inside bionic with:
sudo apt install xserver-xorg-core xserver-xorg-video-dummy xserver-xorg-video-intel

**Comment by butch7903** [comment]
what commands did you type to get bionic to install enough to get to do this?

**Comment by efrankb3** [comment]
> what commands did you type to get bionic to install enough to get to do this?

My upgrade went pretty smoothly.  I was just left with those xorg packages that wouldn't upgrade.

**Comment by helge000** [comment]
I was only able to setup bionic core without issues. From there you can install the xorg packages into the chroot:
`sudo sh Downloads/crouton -r bionic -t core`

**Comment by efrankb3** [comment]
I did a sudo do-release-upgrade from within ubuntu

**Comment by y2kbug-hk** [comment]
I have got the same problem.
May I know, if I install bionic with "-t core" only, how to install gnome back afterwards?

**Comment by helge000** [comment]
@y2kbug-hk - run update by adding the *-u* swtch and *-t* with all the targets as normal: `sudo sh Downloads/crouton -u -t [....]`

**Comment by y2kbug-hk** [comment]
@helge000 Thanks. It works.
But it seems installing Bionic with GNOME is too heavy for my Pixel Slate M3...
I'd better remove it and use xenial.

**Comment by rovitotv** [comment]
I have had the exact same issue on my Samsung Chromebook Pro.  After reading this post and another post on reddit:
https://www.reddit.com/r/Crouton/comments/b4xovz/unable_to_create_a_ubuntu_1804_lts_chroot_with/

Gnome is to too slow on my m3 CPU so I am sticking to xfce for the moment. Keep in mind I am using the -p option to install on a sd card since I am still experimenting with the setup.  Depending on your setup you might want to remove the "-p".  I was able to get bionic to install with xorg and xfce support by following these exact steps:

```bash
sudo sh ~/Downloads/crouton -t core -r bionic -p /media/removable/TVR400GBext4/crouton
```
Next you have to enter-chroot and install the xserver with the following commands:

```bash
sudo sh /media/removable/TVR400GBext4/crouton/bin/enter-chroot
sudo apt-get install xserver-xorg-video-all xserver-xorg xserver-xorg-video-intel
exit
```

Finally execute this step to update the bionic install with xfce.

```bash
sudo sh ~/Downloads/crouton -u -t xfce -r bionic -p /media/removable/TVR400GBext4/crouton
```

I plan to try xiwi and maybe try some experiments with gnome to see if I can optimize my setup.

**Comment by dimaatkaev** [comment]
https://github.com/dnschneid/crouton/issues/3995#issuecomment-460397430
please, be careful with this, I get unavailable keyboard and mouse after install and reboot

**Comment by Windexi** [comment]
Everything worked fine for me when I followed these steps (replace crouton with wherever you have crouton installed)

Install bionic with only core as target
`sudo crouton -r bionic -t core`

When that's done, enter bionic with
`sudo enter-chroot`

Install the xserver stuff the installer whines about (like @efrankb3 previously stated)
`sudo apt install xserver-xorg-core xserver-xorg-video-dummy xserver-xorg-video-intel`

Exit the chroot
`exit`

Update the chroot with Unity/Gnome/Xfce/Whatever (replace unity with whatever desktop environment you want)
`sudo crouton -u -n bionic -t unity`

You're finished!
`sudo startunity`

**Comment by DennisLfromGA** [comment]
Offering another workaround.
I installed my crouton chroot using:
- `sudo crouton -r bionic -t xorg,xiwi,cli-extra,keyboard,touch,chrome-beta,chromium,lxde-desktop`  

Then when it bailed and exited with the xserver-xorg  error I ran this as root since the UID 1000 hadn't been set up yet:
- `sudo enter-chroot -n bionic -u root`  

When it asks about finishing the setup script enter 'n' then run:
- `sudo apt install xserver-xorg-core xserver-xorg-video-dummy xserver-xorg-video-intel`  

When it completes just exit.

*Hope this helps,*
-**DennisLfromGA**

**Comment by nish125** [comment]
if you only download the core, you can install gnome or xfce by typing "sudo crouton -r bionic -t gnome-desktop"

**Comment by Lerie82** [comment]
> what commands did you type to get bionic to install enough to get to do this?

I would also like to know, since my install failed also.
