### ISSUE TITLE
Does not using the -k option mean that someone can unencrypt the files?

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#3998]
If I don't specify `-k` to store the encryption key somewhere off-device, does this mean that someone who may find my lost device can easily unencrypt the chroot?

**Comment by trusktr** [comment]
Isn't the whole Chrome OS filesystem encrypted by default, so if they can't log into my Chromebook, then do I even need to worry about encrypting the chroot?

**Comment by DennisLfromGA** [comment]
The user accounts are encrypted under `/home/user/$CROS_USER_ID_HASH` but the chroots under `/usr/local/chroots` by default are not. You can even gain access to them when not signed-in on VT-2, etc.

But to your first question, the keys are stored in the encrypted chroot -
```
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
```
You could probably also store them in your $HOME folder or a subfolder since that is encrypted too.

However, I don't use encryption so I can't be absolutely positive about this. Maybe someone else with more knowledge about this will chime in.

*Hope this helps,*
-**DennisLfromGA**

**Comment by dnschneid** [comment]
If you don't encrypt at all, and store the chroot in the default location, your chroot will we available to anyone who logs in -- even guest mode or VT2.

If you encrypt but don't use `-k`, your encryption keys will only be as strong as the passphrase you use to wrap them.

If you encrypt and use `-k` to store the keys in your $HOME folder, your keys will be as strong as your account passphrase plus the password you used to wrap the keys...however, if your profile gets wiped for whatever reason, you'll permanently lose access to your chroot.

If you encrypt and use `-k` to store the keys on a USB stick attached to your keychain, only you, with your passphrase and your keychain, will be able to decrypt your chroot.  This is a form of (weak) two-factor authentication.

Note that as long as you are logged into your chroot, it is accessible by root and by extension any root exploits.  So the safest thing to do is to log out when you're done with your chroot, and make sure the terminal says "unmounting chroot".

**Comment by DennisLfromGA** [comment]
What he said. ☝ 😁
