### ISSUE TITLE
Method https has died unexpecctedly

### ISSUE THREAD

**Issue by leofrk2** [dnschneid/crouton#3999]
Hello
I'm totally new with Chromebook and I jnly knew a few things with Linux..
Today I tried to install Linux on my Chromebook Acer 14 using crouton.
All works nice but when I try for example sudo apt-get update or sudo apt-get upgrade I have this following errors : 
E: Method https has died unexpectedly!
E: Subprocess http made ​​a memory access violation

I have try to search on the web and a user suggest to try to purge apt.

So now when I try sudo apt-get update it's return me apt-get : command not found..

If anyone could suggest me what to do, i'm totally lost..

(Where should I paste the command : sudo edit-chroot-all ? )

**Comment by icecream95** [comment]
When using apt-get, you need to run it from inside your chroot.

After pressing Ctrl+Alt+T, you get to the crosh shell. This is a basic shell you can use on a Chromebook that's not in developer mode.

When you type `shell`, you get to the Chrome OS shell, where the prompt looks like this: `chronos@localhost / $`. This shell lets you do stuff to Chrome OS like install chroots or restart Chrome OS services.

Typing `sudo enter-chroot` gets you to the chroot shell, where you can use apt-get to install programs and start graphical programs.

It looks like you were trying to use apt from either the crosh shell or Chrome OS shell, rather than chroot shell.

**Comment by sajjaadf** [comment]
close please?

**Comment by DennisLfromGA** [comment]
@leofrk2,

> E: Method https has died unexpectedly!

This issue is a duplicate, please track here:
- Method http has died unexpectedly during software installation #2688

> So now when I try sudo apt-get update it's return me apt-get : command not found..

This issue was addressed by @icecream95 , see above.
