### ISSUE TITLE
chroot setup failure

### ISSUE THREAD

**Issue by bigweeboo** [dnschneid/crouton#4008]
Alright so I'm pretty new to this so apologies if this is all very poorly put.
I've tried installing chroot for my chromebook and it has not worked this is what is was met with 
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by skolpojkaN** [comment]
Maybe you should reset.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bigweeboo** [comment]
How?

**Comment by DennisLfromGA** [comment]
@bigweeboo,

Show us your full command-line when you tried to install your chroot including the targets, etc.
That might give us enough info. to help out.

*Hope this helps,*
-**DennisLfromGA**

**Comment by bigweeboo** [comment]
`sudo sh ~/Downloads/crouton -e -t xfce`

**Comment by DennisLfromGA** [comment]
@bigweeboo,

Try to 'update' the chroot with the '-u' option like:
- `sudo sh ~/Downloads/crouton -n xenial -u`

There's a chance that might work.

If that doesn't work you may have to delete the chroot with:
- `sudo delete-chroot xenial`

Then start over and, just to keep things simple, try it without the '-e' encryption option like this:
- `sudo sh ~/Downloads/crouton -t xfce`

And see if it completes like that, you can encrypt it later if you like.

*Hope this helps,*
-**DennisLfromGA**

**Comment by flexhornmoringstar** [comment]
I'm currently having a issue trying to get courton to work as well. I'll attach two screenshots one of my command history and of the install script issue that I and others have been running into. 
More interested on how I could run more programs on my chomebook such as League of legends or even diablo 2 just to do more on the chrome book I don't fully understand a whole lot on hardware requirements with the chromebook, Maybe I could just run wine with regular  Crostini  instead of courton? Not sure how I pull this off properly to be honest.
![Screenshot 2021-07-01 11 37 01 PM](https://user-images.githubusercontent.com/82354112/124221864-27244400-dac6-11eb-804a-09fb6c5e3945.png)


![Screenshot 2021-07-01 11 44 15 PM](https://user-images.githubusercontent.com/82354112/124221922-48853000-dac6-11eb-98fc-734a510801a1.png)

Trying to tread carefully with dev mode on this chomebook.

**Comment by MrHallway0** [comment]
@flexhornmoringstar this issue is from two years ago and is closed.
