### ISSUE TITLE
VLC doesn't play from SMB share

### ISSUE THREAD

**Issue by mlozier** [dnschneid/crouton#401]
Hi!

Love the crouton concept!  Only problem that I've had thus far is that VLC will not play any video files from my SMB share.  My Samba server is the Synolog DS212j NAS.  I can connect to it just fine, but when I attempt to play a video file, I only see the first frame of the video.  The video will not play.

Any thoughts?

Thanks!

**Comment by R3vXX** [comment]
Not to resurrect an old thread, but if anyone has this same issue and was wondering, you can make it work by following these directions: http://jorisvandijk.com/2013/vlc-wont-play-smb-shares/

Summary:
1. Open VLC
2. Go to Tools > Preferences
3. Under the header Show Settings (bottom left), select the All button
4. Select Input / Codecs > Access Modules > SMB on the left
5. Enter credentials

This got VLC playing videos via samba for me.

**Comment by slocodemonkey** [comment]
None of the suggestions on this page work using straight ChromeOS. I'm just saying to save people time. I'm sure they work fine with Crouton / Linux.

**Comment by HubKing** [comment]
I tried the comment of "R3vXX commented on Aug 9, 2015", and it worked. But the problem is that there is only one credential, not per shares. So, I cannot use two SMB shares.

Also, this is very awkward. I have already saved the credentials (permanently) for that SM share in the file manager (Thunar), and shouldn't it be used by all applications on the system, like in Windows? I know I may not complain about software I use for free, but this is very, very anti-user-friendly. I mean, I installed the SMB plugin from the Software Manager, and I dragged a file from a SMB share on the file manager to VLC. It only showed something like "An error occurred, check the log for details."  And I had no clue where the log was.

A Google search gave me some txt file on the Windows profile, but in my case it is Linux. I kept searching and found that there is no log file in Linux but I must see it in "Tools -> Messages". The developer of the error dialogue just assumed an average user just know there the log was. Why couldn't he just put a details button to the dialogue?

I examined the log and found something like "access denied". Why couldn't the SMB module just show credential-input dialogue instead of failing? And there was no hint how to solve the problem. So I had to search Google again and found this page. The credential-input was buried deep in the preference dialogue (not even be accessible from the default view). 

I mean... it seems as if those developers assume all users are just as knowledgeable as themselves.

**Comment by sargenthp** [comment]
I know this is old...  But want to get this out here since I was having the same issue.

Turns out I need to install the package gvfs-fuse.  That will make a mount point under the user folder to allow applications to access the CIFS share.

**Comment by timcrice** [comment]
9 year thread!  Throwing this out there.... was searching for an answer for the same problem happening on Armbian.  Cure for me was      sudo apt install vlc-plugin-samba

**Comment by ghost** [comment]
> 9 year thread! Throwing this out there.... was searching for an answer for the same problem happening on Armbian. Cure for me was sudo apt install vlc-plugin-samba

that worked for me on fedora! ty
