### ISSUE TITLE
Switching from Ubuntu to Chrome OS

### ISSUE THREAD

**Issue by UnisexSigntaure** [dnschneid/crouton#4024]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190120145639~master:5bf96711
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 11316.165.0 (Official Build) stable-channel snappy 
kernel: Linux localhost 4.4.164-15546-gd8c7defc947f #1 SMP PREEMPT Sun Mar 3 22:54:30 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

Just gotten into Chromebook and Linux so a newbie but having issues switching between Chrome OS and Ubuntu.

I installed Ubuntu on my HP Chromebook 14 G5 using the official tutorial on the Ubuntu website. Seemed to install fine, takes a few secs opening things and not as slick as Chrome OS but works fine for what I need it for. 
In order for me to start Ubuntu, I have to open chronos and then stype shell and sudo startunity. It boots up fine. 
However, there is no other way for me to get into Ubuntu without doing this. I presumed that I could just use control-alt-forward but this does not work as it takes me into the developer console which is not what I want. (interesting, in order for me to get back to Chrome OS from Ubuntu, it's control-alt-SHIFT-forward) 

Is it possible to have Ubuntu loaded as the Chromebook starts? Or have I misunderstood

Thanks a lot in advance.

**Comment by Merith-TK** [comment]
In theory you can have Ubuntu automatically start, but it would be more trouble than it's worth in my opinion.

And the ctl+alt+shift+=> is needed to keep the Chromos and Ubuntu different from eachother. Don't know why, it just is

**Comment by DennisLfromGA** [comment]
@UnisexSigntaure 

> Is it possible to have Ubuntu loaded as the Chromebook starts? Or have I misunderstood

The crouton chroot does not launch with Chrome OS upon startup or sign-in, you have to do it manually by getting into a shell session and running `sudo startubuntu` as you stated above.

Also, as mentioned above, you can change it to [automatically start](https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup) but it's a bit more complicated and may not be worth it in the end.

*Hope this helps,*
-**DennisLfromGA**

Closing. Please re-open if this issue is still a concern.
