### ISSUE TITLE
Encrypted chroot on USB media causes high ChromeOS CPU usage when Play Store enabled

### ISSUE THREAD

**Issue by rodhull** [dnschneid/crouton#4042]
```
crouton: version 1-20190403182822~master:174af0eb
release: bionic
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,core
host: version 11647.104.0 (Official Build) stable-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Mar 20 23:37:26 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

name: bionic
encrypted: yes, locked

ChromeOS: Stable (v73) (and also observed on Beta (v74)
**Google Play Store/Android apps enabled - this is key!**
```

In recent versions of ChromeOS (certainly 72-73) I've noticed that if the Play Store is enabled along with the existence of an encrypted chroot (with symlink to /usr/local/chroots) on a connected USB drive (you don't have to have it mounted) that a few ChromeOS processes hog CPU significantly (on my dual-core Gandof, 70% of total) for a period of time each time the machine is booted, or after waking from sleep/lid opened, before eventually after some minutes calming down again.

This only seems to happen with an encrypted chroot - the presence of an unencrypted one does not seem to cause this behaviour.

When on Stable (v73), the processes concerned are chiefly:

- android.process.media
- mount-passthrough

I have rarely/additionally noticed the following:

- com.google.android.gms:snet

When on Beta (v74) the two main ones as on Stable are active plus the more troublesome (and definitely more CPU-heavy):

- anomaly_collector
- rsyslogd
- systemd-journal

The symptoms are exacerbated on Beta currently since anomaly_collector consumes almost all the CPU time for many minutes. If you kill it with sudo, it keeps coming back over and over and rsyslogd and systemd-journal go crazy spamming /var/log/messages until it reaches a few GB in size.

I have powerwashed a few times (on Beta and Stable) and the behaviour still stands.

On Stable I have done additional tests by creating a very small chroot with only the "core" target installed and comparing the length of time the CPU hogging lasts compared to a larger chroot with xiwi, xorg and a full Mate desktop env. installed.

The smaller the chroot, the less time the CPU is hogged by these errant processes.

If you disable the Play Store, the problem vanishes.

If you have an unencrypted chroot the problem doesn't occur.

I presume this could be linked to the introduction of a change in how the Android container stuff in ChromeOS now handles external storage: https://bugs.chromium.org/p/chromium/issues/detail?id=936814

It seems to have recently (without permission) started creating an "Android" folder with some empty appdata dirs within on any/all removeable media device you might connect to your ChromeOS device.

Can anyone help? I've yet to report this to the Chromium issue tracker since for me at least it only happens in conjunction with the existence of crouton/encrypted chroots.

**Comment by rmartin16** [comment]
RE: android.process.media and mount-passthrough

I've been seeing high CPU usage from these processes for at least a few weeks possibly correlated with v73 upgrade. This includes fresh booting and seemingly resuming from sleep.

I don't think crouton can fix this though....unless maybe android.process.media supports some kind of folder blacklist to avoid scanning chroots. Via lsof, it's definitely the case that android.process.media is just rummaging around in the sd_card chroots. I am perhaps surprised that encrypted chroots are affected....but my unencrypted sd_card chroot definitely causes this.

Anyhow, **the simplest solution for me so far is disabling the Media Storage app in the Android settings.** I cant fully speak to the downstream effects of this setting change but I don't use Android on my chromebook much anyway.

**Comment by rodhull** [comment]
Great tip on disabling "Media Storage"!

I have tested the Android MS Word app that certainly reads/writes to internal storage and it still worked fine as does Retroarch (even to a USB device) which is the one app I couldn't live without Android-wise ...Amazon Prime Video didn't although honestly some of the Android stuff on ChromeOS is flaky at the best of times.

I'm sure when I tested with an unencrypted chroot initially that I didn't see the behaviour but it could be that I only did this on a very small chroot. Certainly the larger the chroot, the larger the problem. I wonder if a USB device with any kind containing a very large file structure would cause this too - I agree it's not necessarily a crouton problem per se, but since this is pretty much all I have on my USB device it's the only thing that causes it for me...

**Comment by rmartin16** [comment]
Yeah, I think the underlying issue is more generically related to a large file/directory hierarchy such as one that a chroot would create.

Apparently, or at least theoretically, putting a file named ".nomedia" in the directory hierarchy should prevent scanning of that portion of the directory tree from there on....however, my efforts to prove this have been futile.

I believe the underlying source code is [here](https://android.googlesource.com/platform/packages/providers/MediaProvider/+/jb-dev/src/com/android/providers/media). It looks like anytime external media is mounted a scan is initiated. There is code in there (I think mediaprovider.java) that prevents scanning in the presence of a .nomedia file but alas...

**Comment by dnschneid** [comment]
I was going to suggest `.nomedia` (sorry I was a bit slow)...but make sure to put it either in the chroots/ directory itself or at least as a plain file in the encrypted directory (e.g., alongside all of the crazy fnek filenames).  If you put it in / inside the chroot, the filename will be encrypted and it won't do its magic.

If that works, we may want to roll it out to everyone (probably as chroots/.nomedia).

**Comment by rmartin16** [comment]
My attempts with the .nomedia file in the top level of the chroot or in the chroots directory are not successful in preventing high cpu from android.process.media and mount-passthrough.

I've looked through more of that [code](https://android.googlesource.com/platform/packages/providers/MediaProvider/+/refs/heads/master/src/com/android/providers/media)...but i'm not native with java or even sure if that's the code.

Nonetheless, I don't think ".nomedia" was implemented the way we're thinking/anticipating. Instead of the scanner omitting directories (and subdirectories) with a .nomedia file, it appears to continue indexing the files simply with a database flag that says "this isn't media (despite I am a media indexer...)." Soooo, this might stand a chance to at least decrease the time the scanner runs.

Feel free to let me know if I'm on the wrong path...

**Comment by rodhull** [comment]
I also tried moving my chroots dir to ".chroots" and re-creating the symlink in /usr/local since other reading around suggests the media scanner might ignore hidden folders but unfortunately this doesn't work either.

**Comment by rodhull** [comment]
I notice someone has reported this problem on the Chromium issue tracker now: https://bugs.chromium.org/p/chromium/issues/detail?id=947901

I've added my 2-pence worth - perhaps any others can chip in/star the issue to raise awareness to the Chromium/ChromeOS devs...
