### ISSUE TITLE
How to boot and chroot into the same Linux install?

### ISSUE THREAD

**Issue by dmos62** [dnschneid/crouton#4047]
On my Chromebook booting into Linux leaves you with suboptimal hardware support, so for some tasks it's better to boot into CrOS and chroot (ideally using Crouton). I'd like to be able to alternate between booting into a Linux installation, and booting into CrOS and then chroot'ing into that same Linux installation.

I've searched the issues here on Github and the reddit forum, but haven't really found anything. Except for [this](https://github.com/dnschneid/crouton/issues/3983), but it's a bit vague (@icecream95 is talking about a chroot within a chroot, right?), plus the degree of resulting functionality compared to a regular crouton chroot is unclear.

How would one go about doing this? Creating a crouton chroot and then making it bootable in some way? Or creating a dual-boot Linux install and porting crouton's utilities to it so that when chrooting they can be used like with a regular crouton chroot?

The particularly useful Crouton features that I'd like to use when chrooting are audio forwarding, xiwi and shared clipboard.

**Comment by icecream95** [comment]
Crouton needs to make a [few changes](https://github.com/dnschneid/crouton/blob/master/targets/xiwi) to Xorg to make it work properly with Chrome OS, and these changes will interfere with trying to use X when booting natively into the chroot.
I'm sure there is a workaround to all this, but it's easiest to use two chroots, and then you get to use a distro other than Ubuntu/Debian 😄.

The first step is to get a Linux installation you can boot to natively. A few distribution wikis (such as [Arch](https://wiki.archlinux.org/index.php/Chrome_OS_devices)) have instructions on this.

Once you've got that set up, create a chroot using crouton with the xiwi (and/or xorg) target.

You'll need to enter the chroot as root (`-u root`), and edit `.xinitrc`, putting in this:

```bash
#!/bin/bash

# Use lsblk to find what device node your SD card / USB stick gets assigned to.
# Put any mount options such as noatime here.
mount /dev/sdX2 /mnt

# Mount your downloads folder from Chrome OS.
# You might want to change USER/Downloads to something else if you want to make sure web browsers etc. don't save into Chrome OS (see warning at bottom of post).
mkdir -p /mnt/USER/Downloads
mount -B ~/Downloads /mnt/home/USER/Downloads

# Let your Linux installation use the Chrome OS dbus socket for brightness etc. 
touch /mnt/var/host/dbus/cros_system_bus_socket
mount -B /var/host/dbus/system_bus_socket /mnt/var/host/dbus/cros_system_bus_socket

# Mount system directories
mount -B /dev /mnt/dev
mount -B /media /mnt/media
mount -B /proc /mnt/proc
mount -B /run /mnt/run
mount -B /sys /mnt/sys
mount -B /tmp /mnt/tmp

# Mount your crouton chroot inside your Linux installation. Infinite recursion!
# You might need to change this if you gave your usb stick / sd card the label of 'chroot'.
mkdir -p /media/removable/chroot
mount -B / /media/removable/chroot

# Start DE
chroot /mnt su USER -c "cd ~; SOME COMMAND TO START YOUR DESKTOP ENVIRONMENT"
```
Substitute /dev/sdX and USER as appropriate. 

Exit your chroot, then run `sudo enter-chroot -X xiwi -u root xinit`. You *should* end up at the desktop of whatever you installed onto your USB stick or SD card.

You shouldn't have any problems with xiwi, and the clipboard should sync fine, though clipboard managers might conflict with it.

<hr>

Audio is a bit harder. If you don't need audio from ChromeOS at the same time, you can just follow [this guide](https://github.com/dnschneid/crouton/wiki/Access-audio-hardware-directly-(ALSA,-JACK)) on the crouton wiki.
It should be possible to get your linux installation to use cras, though. Looking through the [audio target](https://github.com/dnschneid/crouton/blob/master/targets/audio), it looks like this can be done with a few bind mounts between your chroots, which you can put in your .xinitrc above the line to start your DE:

```bash
touch /mnt/usr/local/lib/libcras.so.0{,.0.0}
mount -B {,/mnt}/usr/local/lib/libcras.so.0
mount -B {,/mnt}/usr/local/lib/libcras.so.0.0.0

# I'm not sure this is correct - you'll need to poke around to see where alsa-lib is in the crouton chroot
#   and your linux installation.
# If you have a multilib (i.e. you have 32 and 64 bit programs at the same time) installation, you will have to duplicate this section, replacing amd64 with i386
touch /mnt/usr/lib/alsa-lib/libasound_module_{pcm,ctl}_cras.so
mount -B /usr/lib/amd64-linux-gnu/alsa-lib/libasound_module_pcm_cras.so /mnt/usr/lib/alsa-lib/libasound_module_pcm_cras.so
mount -B /usr/lib/amd64-linux-gnu/alsa-lib/libasound_module_ctl_cras.so /mnt/usr/lib/alsa-lib/libasound_module_ctl_cras.so

touch /mnt/usr/share/alsa/alsa.conf.d/10-cras.conf
mount -B {,/mnt}/usr/share/alsa/alsa.conf.d/10-cras.conf

mkdir -p /mnt/home/USER/.config/pulse/
touch /mnt/home/USER/.config/pulse/default.pa
mount -B /etc/crouton/pulseaudio-default.pa /mnt/home/USER/.config/pulse/default.pa
```

<hr/>

If you want utilities such as `brightness` and `volume` to be usable from inside your linux installation, you can copy it over (from your Linux installation):

`sudo cp -a /media/removable/chroot/usr/local/bin/* /usr/local/bin`

You'll then need to edit `/usr/local/bin/host-dbus` and replace `/var/host/dbus/system_bus_socket` with `/var/host/dbus/cros_system_bus_socket`

<hr/>

If you want to access files from Chrome OS when your Linux installation is running natively, you might see the eMMC with no partitions - you'll need to run `sudo partx -u /dev/mmcblk2`, depending on where the eMMC is located. You can then mount `/dev/mmcblk2p1` somewhere, which will give you `/usr/local` from Chrome OS.
AFAICT, due to the way the TPM works, it is absolutely impossible to access your Chrome OS Downloads folder from outside Chrome OS, unless you somehow manage to get the encryption key when Chrome OS is running. You have been warned.

<hr>

After doing this, the chroot should feel like a normal chroot, except you'll need to update programs inside it with a package manager instead of just using crouton with `-u`, and everything should work fine (well, as fine as it ever was) when running natively.

Hopefully this helps. Feel free to ask questions if you're still confused, or if you're having problems.

**Comment by icecream95** [comment]
If you want to be able to use xiwi for single apps, change the last line of your .xinitrc to this:

```bash
if [ "$(cat /tmp/chroot-command)" ]; then
    # Change openbox to your favourite window manager. Tiling ones work well, but might need bindings changed to work with Chrome OS.
    COMMAND_TO_RUN="openbox &; export "'$(dbus-launch)'"; export QT_STYLE_OVERRIDE=Breeze; $(cat /tmp/chroot-command)"
    rm /tmp/chroot-command
else
    COMMAND_TO_RUN="COMMAND TO START DESKTOP ENVIRONEMNT"
fi

chroot /mnt su USER -c "cd ~; $COMMAND_TO_RUN"
```

If you want to use the window manager crouton uses for xiwi by default, copy `/etc/crouton/xiwi.conf` into your linux installation, install i3 there, then replace openbox in your xinitrc with `i3 -c /where/i/placed/xiwi.conf`

Make a script to run your .xinitrc with:
```bash
echo bash /root/.xinitrc | tee /usr/local/bin/startchrootxiwi
chmod +x /usr/local/bin/startchrootxiwi
```
It's important that the script starts with 'start', otherwise it won't work properly.

Then, to start, say, `konsole`, you would run `echo konsole >/tmp/chroot-command; sudo enter-chroot -X xiwi -u root xiwi -T startchrootxiwi`.

If you want to make this easier, you can make a script in Chrome OS:

```bash
echo 'if [ "$(head -c1 <<<"$1")" = "-" ]; then XIWIOPT="$1"; shift 1; fi; echo "$@" >/tmp/chroot-command; sudo enter-chroot -X xiwi -u root -n crouton xiwi $XIWIOPT startchrootxiwi' | sudo tee /usr/local/bin/myxiwi
sudo chmod +x /usr/local/bin/myxiwi
```

You can then just run `myxiwi konsole`, or `myxiwi -T firefox` (you can use startxiwi options) to start an application.

**Comment by dmos62** [comment]
Your answer is excellent. It is clear and extremely in depth. My question is answered. Thank You for putting in all this effort!

**Comment by Imperial-Industries** [comment]
Then please close this question/stream
