### ISSUE TITLE
Downloads folder on chrome os side is now MyFiles, how to mount in crouton?

### ISSUE THREAD

**Issue by dochench** [dnschneid/crouton#4051]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190403182822~master:174af0eb
release: bionic
architecture: amd64
xmethod: xorg
targets: audio,xorg,extension,xiwi,gnome-desktop,touch
host: version 12105.25.0 (Official Build) dev-channel eve 
kernel: Linux localhost 4.4.178-16492-g4245c5e16521 #1 SMP PREEMPT Thu May 2 00:43:09 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...

#### Please describe your issue:
Inside the chroot in /etc/crouton/shares there are only three options for automounting.
# The only directories that can be mapped from outside of the chroot are
# subdirectories of the following locations:
#  downloads: ~/Downloads
#  shared: /mnt/stateful_partition/crouton/shared
#  encrypted: ~/crouton/shared

It looks as if the ~/Downloads folder has been relocated to ~/MyFiles/Downloads on the chrome OS side of things.

How should this now be accessed? Symlinking?

**Comment by DennisLfromGA** [comment]
@dochench,

On my Pixelbook using version 74.0.3729.125 (Official Build) beta (64-bit) with support for new files and folders under the “My files” local root I have both (identical) folders listed below:

`/home/chronos/user/Downloads`
`/home/chronos/user/MyFiles/Downloads`

So you don't need to symlink Downloads since crouton still bind mounts it in `~/Downloads` but any *other* folders besides Downloads that you create under `/home/chronos/user/MyFiles` will not be accessible in your chroot IIUC. 
I believe that the `enter-chroot` script will have to be updated to include 'MyFiles' for those other folders to be shared in your chroot. The crouton developers will have to decide if this is important enough to warrant changes.

I don't understand the reason to create folders under MyFiles and outside of Downloads since they are still a part of the user's profile and subject to getting wiped with a powerwash, recovery, or profile corruption but I guess there are some valid reasons since they went to great lengths to add this feature. Maybe I'll understand it better after using it more.

*Hope this helps,*
-**DennisLfromGA**

**Comment by dochench** [comment]
Fixed. :)

[chroot.txt](https://github.com/dnschneid/crouton/files/3150845/chroot.txt)

**Comment by dochench** [comment]
can add using myfiles and it bind-mounts.
myfiles/Documents ~/Documents
myfiles/Downloads ~/Downloads

**Comment by DennisLfromGA** [comment]
@dochench,

Nice!
Maybe submit a [pull request](https://github.com/dnschneid/crouton/compare) and see what happens.

-**DennisLfromGA**

**Comment by mjmartis** [comment]
I had this same question ("how can I mount MyFiles in crouton?"), and the solution presented here worked for me. Is now a good time to reprioritise this bug?

**Comment by levinit** [comment]
How can I mount other dirs in crouton, I wanto mount MyFiles or MyFiles/Documents in crouton, please?

**Comment by DennisLfromGA** [comment]
@levinit,

The crouton devs have weighed in on this request, see https://github.com/dnschneid/crouton/pull/4055#issuecomment-490929550

The workaround shown above in https://github.com/dnschneid/crouton/issues/4051#issuecomment-489907728 may be the best way forward ATM.

*Hope this helps,*
-**DennisLfromGA**

**Comment by levinit** [comment]
> I had this same question ("how can I mount MyFiles in crouton?"), and the solution presented here worked for me. Is now a good time to reprioritise this bug?

1. enter chroot ,eg buster

```shell
sudo enter-chroot -n buster
```

3. modify /etc/crouton/shares

modify `downloads` > `myfiles` , `Downloads` > `MyFiles`
```shell
sed -i -e "s/Download/MyFile/g" -e "s/download/myfile/g" /etc/crouton/shares
```

3. modify /usr/local/bin/enter-chroot ,[reference](https://github.com/dnschneid/crouton/pull/4055/commits/3640998f4f8666afd3fed7710853d57f361600e6)

modify `downloads` > `myfiles` , `Downloads` > `MyFiles`

```shell
sed -i -e "s/Download/MyFile/g" -e "s/download/myfile/g" /usr/local/bin/enter-chroot
```
4. enter chroot buster again, it will ask you 

> Would you like to finish the setup? [y/n/d]

type <kbd>d</kbd>

will find that `Myfiles` in home dir.

**Comment by binMonkey** [comment]
I don't know if anyone still needs help with this.  I installed focal and got it working perfectly except that I couldn't download into my ~/Downloads folder.  I had to sudo umount /home/rich/Downloads every time I started my chroot. I used part of @mjmartis ' post above:  

modify /etc/crouton/shares
modify downloads ~/Downloads -> myfiles ~/MyFiles

I simply capitalized 'downloads'  so that it reads 'Downloads ~/Downloads' and now I have no problem download into my chroot's Download folder.

I hope this helps someone.  My focal installation is now perfect.
