### ISSUE TITLE
Desktop freeze

### ISSUE THREAD

**Issue by casheta** [dnschneid/crouton#4063]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 11647.154.0 (Official Build) stable-channel grunt 
kernel: Linux localhost 4.14.94-09797-gd6114dbb2c01 #1 SMP PREEMPT Sun Apr 14 19:12:23 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Hello guys, so i just installed Crouton 4 days ago but when i start it the desktop freezes.
I tried every subrredit and gthub command that i got my hand on.
![59961593_305043320377841_2338029854907170816_n](https://user-images.githubusercontent.com/50510914/57565721-5a2d8a00-73cb-11e9-9800-e9de0e51ffe2.jpg)
![60559155_410064702910064_631251753177710592_n](https://user-images.githubusercontent.com/50510914/57565722-5a2d8a00-73cb-11e9-85da-0d211414616c.jpg)

Idea is that i am a noob in this and i really want to learn.

**Comment by mcjlmb** [comment]
I have the same issue as you and I believe the same model of Chromebook. From the little bits of info I've been able to gather this model (or perhaps AMD chromebooks in general) have problems running linux, both with crouton and chrx with GalliumOS. Hopefully someone smarter than us will be able to provide a solution or at least an answer one way or the other.

**Comment by mhyzon** [comment]
It happens for me as well. I've also got an HP AMD chromebook.  I'm trying to get Minecraft working in full screen mode so that hardware acceleration works.

If you don't need that, I did find that using xiwi XMETHOD works fine.

**Comment by Thespy799** [comment]
This is also happening to me....

**Comment by DennisLfromGA** [comment]
All,

I wonder if this issue is just when using the 'xorg' xmethod and/or the xfce desktop?

If someone is willing to try 'xiwi' and/or another desktop like lxde for instance it might help narrow down the cause.

You can install them with an update like:
- `sudo crouton -n xenial -t xiwi -u`
and
- `sudo crouton -n xenial -t lxde -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by mhyzon** [comment]
xiwi works fine (if slow).

Something else of note is that while the display doesn't update, if one switches back to the ChromeOS display, then back to xorg, the screen had updated (ie the mouse has moved or whatever you clicked on responds), but it is "frozen" in the new state.  Basically, what is shown is only updated if you switch away and then back.

**Comment by DennisLfromGA** [comment]
@mhyzon,

Thanx for confirming it's an 'xorg' issue.
I suppose it could be an issue with AMD and [frecon](https://chromium.googlesource.com/chromiumos/platform/frecon/) and/or the [xorg.conf](https://wiki.archlinux.org/index.php/AMDGPU#Xorg_configuration), I'm not sure.

-**DennisLfromGA**

**Comment by franky58** [comment]
Same problem here. I have tried to HP14 AMD chromebooks (AMD a6-9220c and a4-9120c) and they hav both the sam problems. Distorted blocked screen with cursur moving over the graphic blocked screen. The only way to get out is to hold the powerbutton 10 seconds. I have tried Xfce, Lxde, Unity and Debian. All hold. The problem lies in de AMD GPU. Crostini also give somtimes blocked windows.

**Comment by franky58** [comment]
Xiwi works on the HP 14 with AMD a6-9220c but very slow.
How can we solve this problem and work normal with Xorg on the HP 14 with AMD processor?
I also noticed that a SD card formatted to EXT4 drains the accu and processor is always running at >85%.
