### ISSUE TITLE
Crouton installation progress bar(feature request)

### ISSUE THREAD

**Issue by justchen1369** [dnschneid/crouton#4068]
is it possible for there to be a progress bar as a rough indicator of how close to finishing an installation is?

**Comment by divx118** [comment]
This will be something that is a very hard thing to do since you don't know exactly which dependencies will need to be installed for packages(targets). IMO Progress bars are a nightmare to program certainly if you have so many variables. I understand you would like them, but I don't think it will ever happen for crouton. However I could be wrong and someone has a brilliant idea on how to integrate it well.

**Comment by justchen1369** [comment]
yep, I figured it would be that difficult
maybe you could
1)find how many dependencies are to be installed
2)increment a variable every time one is installed
3)do magic voodoo with carriage returns

of course, the difficult part is probably 1 and 2

**Comment by justchen1369** [comment]
welp, accidentally closed this thread
