### ISSUE TITLE
enter-chroot fails to enter bionic chroot

### ISSUE THREAD

**Issue by clvgt12** [dnschneid/crouton#4076]
```bash
chronos@localhost /usr/local/bin $ sudo enter-chroot bionic
Entering /mnt/stateful_partition/crouton/chroots/bionic...
-su: 1: bionic: not found
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/bionic...
chronos@localhost /usr/local/bin $ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190403182822~master:174af0eb
release: bionic
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 12236.0.0 (Official Build) dev-channel snappy 
kernel: Linux localhost 4.4.180-16533-g77dd0cb94c17 #1 SMP PREEMPT Wed May 29 14:19:30 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
```
#### Please describe your issue:
After bionic release installation, enter-chroot fails to complete, unmounts chroot, and exits to host shell.

#### If known, describe the steps to reproduce the issue:
1)  sudo crouton -r bionic -t xiwi,xfce
2)  sudo enter-chroot bionic

**Comment by DennisLfromGA** [comment]
@clvgt12,

That is strange, `edit-chroot -all` reports a valid bionic chroot but yet it won't let you enter it and shows -
> `-su: 1: bionic: not found`

Try entering your chroot as the root user with -
- `sudo enter-chroot -u root -n bionic`

And see if that works, if it does then it may indicate some problems with the normal user's permissions, sometimes these can be sorted in the chroot with: `sudo chown -R 1000:1000 "$HOME"`

This *may* be related to a problem with `su` that is currently affecting certain debian distros, the following pull request will address that once it's reviewed and merged -
- Use sudo instead of su. #3956


Or it could be something else entirely, if any of the above doesn't help come back and let us know and we'll try to dig deeper.

*Hope this helps,*
-**DennisLfromGA**

**Comment by clvgt12** [comment]
Ok, I removed the previous bionic chroot, reinstalled it using the recreate setups and duplicated the 
```
su: 1: bionic: not found
``` 
issue.

Then I ran  ```sudo enter-chroot -u root -n bionic```
And verified I could enter the chroot as the root user.
Then I ran
```
sudo chown -R "1000:1000" /home/user
sudo chown -R "0:0" /root
exit
sudo enter-chroot -n bionic
```

And now I can enter the chroot.   I suppose the reset of the file permissions on the home directories solved the issue...

Thanks...
