### ISSUE TITLE
The extension corrupted after last update dev chanel(ASUS C302)

### ISSUE THREAD

**Issue by liuxiawei** [dnschneid/crouton#4078]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version git
release: xenial
architecture: amd64
xmethod: xiwi
targets: extension,audio,xiwi,keyboard,kde-desktop,gtk-extra,xorg,touch,cli-extra
host: version 12236.0.0 (Official Build) dev-channel cave 
kernel: Linux localhost 3.18.0-19671-g83419c049dc9 #1 SMP PREEMPT Wed May 29 14:04:09 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:
The extension corrupted after last update dev chanel(ASUS C302).
When the first time open xiwi is correct, but when close xiwi and open it agin is corrupted.
I open the extions dev model and find 
WebSocket connection to 'ws://localhost:30011/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
Context
window.html?display=1&debug=0&hidpi=0&title=xenial%2Fpycharm%3A%20tdb%20%5B~%2FPycharmProjects%2Ftdb%5D%20-%20...%2Fsvd%2Fmodels.py%20%5Btdb%5D%20-%20PyCharm&mode=w
Stack Trace
window.html?display=1&debug=0&hidpi=0&title=xenial%2Fpycharm%3A%20tdb%20%5B~%2FPycharmProjects%2Ftdb%5D%20-%20...%2Fsvd%2Fmodels.py%20%5Btdb%5D%20-%20PyCharm&mode=w:0 (anonymous function)

**Comment by jazzgroove** [comment]
Same issue as well:

name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20190403182822~master:174af0eb
release: buster
architecture: amd64
xmethod: xiwi
targets: audio,core,extension,lxde,xiwi
host: version 12236.0.0 (Official Build) dev-channel eve 
kernel: Linux localhost 4.4.180-16533-g77dd0cb94c17 #1 SMP PREEMPT Wed May 29 14:01:13 PDT 2019 x86_64 GNU/Linux
freon: yes

**Comment by GitCrouton** [comment]
Same here Asus C302 on dev channel - Version 76.0.3807.0 (Official Build) dev (64-bit)

Worked flawlessly for 6 months until the last update, now the extension corrupts when a chroot is launched. 

As a workaround, you can select 'repair extension' from the extensions menu in chrome, then click on the icon to select your chroot.

**Comment by jazzgroove** [comment]
> Same here Asus C302 on dev channel - Version 76.0.3807.0 (Official Build) dev (64-bit)
> 
> Worked flawlessly for 6 months until the last update, now the extension corrupts when a chroot is launched.
> 
> As a workaround, you can select 'repair extension' from the extensions menu in chrome, then click on the icon to select your chroot.

Confirmed this works for me. it's just a pain to repair the extension over and over again to access the chroot.

**Comment by liuxiawei** [comment]
background.js:352 (websocketConnect)
![image](https://user-images.githubusercontent.com/5093541/59240978-6dd14800-8c38-11e9-8a64-0d999c6d2e18.png)

**Comment by GitCrouton** [comment]
sudo startxfce4 -X xiwi
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-128-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-19674-gc5ed4b68fc2c #1 SMP PREEMPT Wed Jun 5 00:35:58 PDT 2019 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3686400 verity payload=PARTUUID=5f0c56f7-dbc8-5e42-9246-d5af7cb2842e/PARTNROFF=1 hashtree=PARTUUID=5f0c56f7-dbc8-5e42-9246-d5af7cb2842e/PARTNROFF=1 hashstart=3686400 alg=sha1 root_hexdigest=4a6b7311d614ce72947156e5dad5e13e173cefc3 salt=a122a68626db19998af068582df6a6e1deb80bfdccc4711bbb4223bca6c0dc95" noinitrd vt.global_cursor_default=0 kern_guid=5f0c56f7-dbc8-5e42-9246-d5af7cb2842e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7  
Build Date: 10 August 2018  09:33:05AM
xorg-server 2:1.18.4-0ubuntu0.8 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jun 11 10:23:22 2019
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,xfce,extension,xorg,xiwi,touch
host: version 12239.3.0 (Official Build) dev-channel cave 
kernel: Linux localhost 3.18.0-19674-gc5ed4b68fc2c #1 SMP PREEMPT Wed Jun 5 00:35:58 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
Error: not connected.
Cannot connect to extension, retrying...
Cannot open /sys/class/tty/tty0/active: No such file or directory
Connected to extension, launched crouton in a window.
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
xfce4-session: No GPG agent found

(xfsettingsd:5746): xfsettingsd-WARNING **: Unknown mode '1536x864 @ 59.5' for output default, aborting.
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
[WARN 10:23:26.526892] [Environment:161] XDG_SESSION_CLASS not set in this environment!
[WARN 10:23:26.527149] [Environment:192] XDG_SESSION_TYPE not set in this environment!

(polkit-gnome-authentication-agent-1:5834): polkit-gnome-1-WARNING **: Unable to determine the session we are in: No session for pid 5834
[WARN 10:23:26.842032] [Preferences:192] '/usr/share/plank/themes/Default/dock.theme' is read-only!
[WARN 10:23:27.056446] [TrashDockItem:35] GSettingsSchema 'org.gnome.nautilus.preferences' not found
[WARN 10:23:27.189390] [SurfaceCache:196] Creating surface took WAY TOO LONG (34ms), enabled downscaling for this cache!

**Comment by GitCrouton** [comment]
sudo startxfce4 -X xiwi
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-128-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-19674-gc5ed4b68fc2c #1 SMP PREEMPT Wed Jun 5 00:35:58 PDT 2019 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3686400 verity payload=PARTUUID=5f0c56f7-dbc8-5e42-9246-d5af7cb2842e/PARTNROFF=1 hashtree=PARTUUID=5f0c56f7-dbc8-5e42-9246-d5af7cb2842e/PARTNROFF=1 hashstart=3686400 alg=sha1 root_hexdigest=4a6b7311d614ce72947156e5dad5e13e173cefc3 salt=a122a68626db19998af068582df6a6e1deb80bfdccc4711bbb4223bca6c0dc95" noinitrd vt.global_cursor_default=0 kern_guid=5f0c56f7-dbc8-5e42-9246-d5af7cb2842e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7  
Build Date: 10 August 2018  09:33:05AM
xorg-server 2:1.18.4-0ubuntu0.8 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jun 11 10:29:51 2019
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,xfce,extension,xorg,xiwi,touch
host: version 12239.3.0 (Official Build) dev-channel cave 
kernel: Linux localhost 3.18.0-19674-gc5ed4b68fc2c #1 SMP PREEMPT Wed Jun 5 00:35:58 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Cannot open /sys/class/tty/tty0/active: No such file or directory
Connected to extension, launched crouton in a window.
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
xfce4-session: No GPG agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(xfsettingsd:15825): xfsettingsd-WARNING **: Unknown mode '1536x864 @ 59.5' for output default, aborting.
[WARN 10:29:55.597234] [Environment:161] XDG_SESSION_CLASS not set in this environment!
[WARN 10:29:55.597336] [Environment:192] XDG_SESSION_TYPE not set in this environment!

(polkit-gnome-authentication-agent-1:15873): polkit-gnome-1-WARNING **: Unable to determine the session we are in: No session for pid 15873
[WARN 10:29:55.869020] [Preferences:192] '/usr/share/plank/themes/Default/dock.theme' is read-only!
[WARN 10:29:56.144996] [TrashDockItem:35] GSettingsSchema 'org.gnome.nautilus.preferences' not found

At this point the chroot is running, but the chrome extension has corrupted.
By going to manage extensions and repair extension (which just re-installs it) I can run the extension and enter the chroot. From then on everything works fine.

**Comment by GitCrouton** [comment]
I've just found the extension doesn't corrupt when using xorg. For example:- 'sudo startxfce4 -X xorg' 

I can then jump between windows using ctrl-alt-shift and the back or forward keys, and jump into the chroot using the extension.

**Comment by kayshcache** [comment]
Is there a solution for this. Do we get xiwi back or not?

**Comment by DennisLfromGA** [comment]
@kayshcache,

No, a solution/fix has not yet been implemented/merged.

But, one workaround was [posted above](https://github.com/dnschneid/crouton/issues/4078#issuecomment-499035932), I'll provide it here also:

> As a workaround, you can select 'repair extension' from the extensions menu in chrome, then click on the icon to select your chroot.

Another workaround is to use the 'xorg' xmethod instead, also [posted above](https://github.com/dnschneid/crouton/issues/4078#issuecomment-503516861).

I prefer 'xiwi' so I use the first workaround and repair the extension.

*Hope this helps,*
-**DennisLfromGA**

**Comment by kayshcache** [comment]
@DennisLfromGA Thank you for taking the time, Dennis. I was already aware that xorg is still working as before. I was hoping to get my xiwi workflow back again. The workarounds mention here, repairing the extension, either isn't working for me as it does for the person mentioning it, or just doesn't bring back single apps running in chrome windows as I knew it.

**Comment by DennisLfromGA** [comment]
@kayshcache,

Sorry to hear the extension repair workaround doesn't work for you.
I just tried it myself and if I attempt to launch a xiwi app it will fail but if I repair the extension and immediately try to launch it again it works - for me at least -
![IMG_20190701_070406](https://user-images.githubusercontent.com/3418772/60432133-7bdb0e80-9bcf-11e9-8cc7-01943468adec.jpg)

*Hope this helps,*
-**DennisLfromGA**

**Comment by kayshcache** [comment]
@DennisLfromGA I really do appreciate you taking the time to advise me personally. Xiwi really is utterly broken for me. Since the last update on the Beta channel last week xiwi no longer successfully connects under any troubleshooting condition I have tried: with any app, either of my well functioning chroots, with any google account, all other extensions disabled, repairing repeating, repairing rebooting, etc.

**Comment by liuxiawei** [comment]
I fund a way to solve this problem. Just load the unpacked extension.
copy the unpacked app to some directory 
`cp ~/Extensions/gcpneefbbnfalgjniomfjknbcgkbijom/2.5.2_0/  ~/Downloads/crouton-integration/
`
then go to  chrome://extensions/ and open dev mode and load  the ~/Downloads/crouton-integration/.
But when open the xiwi windows,It's very slow

**Comment by brizzbane** [comment]
I just came here to create an issue about this...I have same problem.  

As a 'solution', I have been repairing extension after running the command for the 1st time.  It then runs on the second attempt.

My chroot is buster.  The following is the command I've been using to launch my chroot desktop:

(I get 'timeouts' if I try to do sudo startgnome directly [with the extension connecting], which is another problem I've had.  Works sometimes, most of the time not.  But the below command always launches.)

`sudo startxiwi -f startgnome`

I am on beta channel.

**Comment by qwertpi** [comment]
> > Same here Asus C302 on dev channel - Version 76.0.3807.0 (Official Build) dev (64-bit)
> > Worked flawlessly for 6 months until the last update, now the extension corrupts when a chroot is launched.
> > As a workaround, you can select 'repair extension' from the extensions menu in chrome, then click on the icon to select your chroot.
> 
> Confirmed this works for me. it's just a pain to repair the extension over and over again to access the chroot.

I also have this issue on an Acer Chromebook 15 CB5-571 https://www.reddit.com/r/Crouton/comments/ccsyps/crouton_integration_crashing/

**Comment by kenmanheimer** [comment]
As one of probably many sidetracked for a while by this issue, I suggest that more be done to detect the problem and notify the user, eg by detecting the corrupt extension and posting a warning message with a link to this issue. Many will not notice the corrupt extension and try updating crouton (possibly spending a while, as I did, on a tangent fussing with the recent mounted-fs noexec situation). A warning in the updated crouton start scripts would save lots of people some substantial time, until the problem is actually fixed.

That said, thanks very, very much for crouton, and the work everyone puts into it! I understand that Chrome OS is an especially active platform, and probably offers lots of challenges to maintaining an elaborate (but vital) add-on like this.

**Comment by tootai** [comment]
+1 with ASUS C302 in dev mode, xenial and bionic. The "repair" workaround does the job but would be nice to get back to a non corrupted plugin.

I'm joining kenmanheimer for the crouton great job, thanks a lot.

Daniel

**Comment by kenmanheimer** [comment]
Perhaps useful additional information: it's looking like my xiwi sessions are always gone after a system suspend. This makes the problem more serious, of course, since restarting is more frequently necessary.

**Comment by danopia** [comment]
I just received 76.0.3809.77 on beta channel and haven't been seeing 'corruption' anymore. The crouton windows still disappear as soon as the laptop lid is closed (even for a second) but now when I select them from the crouton icon, the windows just immediately reopen. Way better than having to 'repair' and turn hidpi back on every time.

Does this match other's experience with the latest beta?

**Comment by kenmanheimer** [comment]
> I just received 76.0.3809.77 on beta channel and haven't been seeing 'corruption' anymore. The crouton windows still disappear as soon as the laptop lid is closed (even for a second) but now when I select them from the crouton icon, the windows just immediately reopen. Way better than having to 'repair' and turn hidpi back on every time.
> 
> Does this match other's experience with the latest beta?

I'm seeing something a bit more complicated.
* If I let the system sleep while a xiwi session is going the windows disappear, but the processes are still going.
* On one hand that's great - I can, for instance, use emacsclient to open new frames on my ongoing emacs session, when I forget and let the system sleep. And no need any more to repair the extension. Yay!
* On the other hand, those processes accumulate, wasting resources and leaving the linux image unencrypted and mounted. That's not good.

I can explicitly track down the residual processes (ps a) and send TERM signal to the enter-chroot process (sudo kill -TERM <pid>), so I feel like this situation is better. It would be a lot better still, though, if the xiwi windows survived system sleep.

Thanks, @danopia, for bring attention to the changed status!

**Comment by kenmanheimer** [comment]
In response to what I wrote:

> I can explicitly track down the residual processes (ps a) and send TERM signal to the enter-chroot process (sudo kill -TERM ), so I feel like this situation is better. It would be a lot better still, though, if the xiwi windows survived system sleep.

Looks like `unmount-chroot` can be used to do all of this, more easily:

    chronos@localhost ~ $: sudo unmount-chroot -fy xenial

**Comment by danopia** [comment]
>On the other hand, those processes accumulate, wasting resources and leaving the linux image unencrypted and mounted. That's not good.

Hmm, have you tried re-opening the windows from the crouton icon? Any time a xiwi window closes without being shut down, you should be able to re-open it from the extension's window. Like so: https://drive.google.com/file/d/1ivOagkOTCJWOLWgG6rujXuPVXfIGRcvP/view Though I definitely lost one of the 5 when recording that 😏 This is how I'm dealing with the sleep issue now, and it's _okay_.

Obviously the windows surviving sleep would be better if we can figure out wtf these beta builds are doing. Maybe this ticket needs a rename - there's no corruption being reported for me anymore, the windows just close on lid close.

**Comment by DennisLfromGA** [comment]
As mentioned by @kenmanheimer above, `unmount-chroot` can take care of all of the processes that `crouton` kicks off. Here's the usage message -
```
chronos@localhost ~ $ unmount-chroot
unmount-chroot [options] name [...]

Unmounts one or more chroots, optionally killing any processes still running
inside them.

By default, it will run in interactive mode where it will ask to kill any
remaining processes if unable to unmount the chroot within 5 seconds.

Options:
    -a          Unmount all chroots in the CHROOTS directory.
    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots
    -f          Forces a chroot to unmount, potentially breaking or killing
                other instances of the same chroot.
    -k KILL     Send the processes SIGKILL instead of SIGTERM.
    -p          Print to STDOUT the processes stopping a chroot from unmounting.
    -t TRIES    Number of seconds to try before signalling the processes.
                Use -t inf to be exceedingly patient. Default: 5
    -x          Keep the root directory of the chroot mounted.
    -y          Signal any remaining processes without confirmation.
                Automatically escalates from SIGTERM to SIGKILL.
```
You can just list the processes if you're curious, I only have the `lxde-desktop` running on mine so that's all that's shown -
```
chronos@localhost ~ $ sudo unmount-chroot -ap
 4466 su -s /bin/sh -c export SHELL='/bin/bash'; export XMETHOD='xiwi-tab';'exec' 'xinit' '/usr/bin/startlxde'  - denny
Not unmounting /var/crouton/chroots/trusty as another instance is using it.
```
`unmount-chroot` is probably the best tool to use for this.

*Hope this helps,*
-**DennisLfromGA**

**Comment by kenmanheimer** [comment]
> > On the other hand, those processes accumulate, wasting resources and leaving the linux image unencrypted and mounted. That's not good.
> 
> Hmm, have you tried re-opening the windows from the crouton icon? Any time a xiwi window closes without being shut down, you should be able to re-open it from the extension's window. Like so: https://drive.google.com/file/d/1ivOagkOTCJWOLWgG6rujXuPVXfIGRcvP/view Though I definitely lost one of the 5 when recording that 😏 This is how I'm dealing with the sleep issue now, and it's _okay_.

Ah - that's very helpful!

My browser Crouton extension icon was hidden in the overflow area, and the shelf icon disappears when the windows go away, so I didn't realize this was an option! I've moved the browser extension icon to a more prominent place, and it's a great avenue for getting back the windows, without costing any more resources. Thanks!

> Obviously the windows surviving sleep would be better if we can figure out wtf these beta builds are doing. Maybe this ticket needs a rename - there's no corruption being reported for me anymore, the windows just close on lid close.

Same for me. The ability to get my xiwi window back intact relieves the pain of the problem, leaving it more as a complicating quirk. But I'm not sure how much attention this is getting from anyone actively working on Crouton, who might change the name of the thread?

I do wonder whether some among Chrome OS developers might be aware of this thread, though. Maybe the beta alleviated the problem coincidentally, as part of addressing an issue noticed for other symptoms. Then again, maybe Crouton is among the Chrome OS developers and they addressed the Crouton issue directly? (If so, I wonder whether Crouton will become superfluous to them as Crostini advances...) Curious.

**Comment by jazzgroove** [comment]
Update:

With the latest Chrome Dev - Version 77.0.3865.18 (Official Build) dev (64-bit) and the latest crouton I don't have to repair the extension anymore and things reconnect after locking the screen. It appears to be fixed.

crouton: version 1-20190807171712~master:6f45f06a
release: bullseye
architecture: amd64
xmethod: xiwi
targets: xorg,audio,core,extension,lxde,xiwi
host: version 12371.11.0 (Official Build) dev-channel eve 
kernel: Linux localhost 4.4.186-16711-gde724c1209ce #1 SMP PREEMPT Tue Aug 6 00:25:30 PDT 2019 x86_64 GNU/Linux
freon: yes

**Comment by lesatdgl** [comment]
Great news that new build works

I'm on Version 76.0.3809.102 (Official Build) (64-bit) and I'd rather stay out of dev

I've tried to repair the extension, however, when I go to More Tools > Extensions (search for crouton) found it - I don't see a "repair" option ???? - there's "Load Unpacked" "Pack Extension" "Update" "Manage Kiosk Applications" ???
