### ISSUE TITLE
crouton update fails due to cras_test_client.c not found

### ISSUE THREAD

**Issue by pshotton** [dnschneid/crouton#4115]
```
Please paste the output of the following command here: sudo edit-chroot -all

 $ sudo edit-chroot -all
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 

```

#### Please describe your issue:

Attempting to update chroot. Does most of it but then says:

sed: can't read tests/cras_test_client.c: No such file or directory
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.

#### If known, describe the steps to reproduce the issue:

Run 
sudo crouton -u -n xenial

**Comment by DennisLfromGA** [comment]
@pshotton,

You didn't show us the full output of '`edit-chroot -all`' so we don't have a lot of details like device, channel, version, etc. but another similar issue is listed below -

- chroot install - sed: can't read tests/cras_test_client #4098

That issue may be due to the dev channel version, at the time, but it's still open and unclear.
Closing this issue and duping to #4098, *please track it there*.

-**DennisLfromGA**

**Comment by pshotton** [comment]
@DennisLfromGA that was the complete output from edit-chroot -all !
I think the failed update has stopped the command from working properly.

**Comment by DennisLfromGA** [comment]
@pshotton,

That output shows an encrypted chroot that is still *locked*.
You could get into the chroot with your password using `enter-chroot` and then run `croutonversion` to show us the complete output but, in the end, we want to track this issue in #4098. 

*Hope this helps,*
-**DennisLfromGA**

**Comment by pshotton** [comment]
Just applied the latest update. No errors, and now I can switch from
Crouton to Ubuntu and back with no colour issues. What a huge improvement.
A great thank you to all involved in sorting this out. You've just improved
my life immensely.
Special thanks to David Schneider for making this all happen.

Best
Phil Shotton
