### ISSUE TITLE
Disco Fails Yet Again

### ISSUE THREAD

**Issue by MetaNite64** [dnschneid/crouton#4127]
```
name: disco
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/disco...
crouton: version 1-20190807171712~master:6f45f06a
release: disco
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12239.67.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-19679-gd1d0bbedf35d #1 SMP PREEMPT Tue Aug 6 05:48:51 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/disco...
```

#### Please describe your issue:
After taking over 2 days to install (repeated hanging after sending messages to dbus), the installation timed out. It then asked for username and password, and upon running `sudo startxfce4`, it gives `dbus[19046]: Unknown username "whoopsie" in message bus configuration file` and then is stuck. You can Ctrl-C it to stop it, but you cannot enter the chroot with `startxfce4` or `enter-chroot`. In addition, updating it gives the same error.
#### If known, describe the steps to reproduce the issue:
1.) Install disco

**Comment by DennisLfromGA** [comment]
@Mario253,

Maybe run the prepare script explicitly with: `sudo enter-chroot -n disco --xx`
You may also be able to get into the chroot as root with: `sudo enter-chroot -n disco -u root`

*Hope this helps,*
-**DennisLfromGA**

**Comment by corlesss** [comment]
Hi, I'm having the exact same issue.

I'm installing Eoan on my chromebook (I haven't tried Disco due to how long Eoan takes due to sending messages to dbus); but after I install and try to enter-choort it provides this message. 

`WARNING:` Unable to register core dump handler.
dbus[8421]: Unknown username "whoopsie" in message bus configuration file`
where it will hang for a few minutes before writing 
`Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/eoan...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/eoan...`

**Comment by silversoul42** [comment]
Eat a dock n find your phone lmfao
