### ISSUE TITLE
No sound in Chroot

### ISSUE THREAD

**Issue by SirFireball3521** [dnschneid/crouton#4145]
```name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20190902190258~master:9a594a66
release: buster
architecture: amd64
xmethod: xorg
targets: lxde,core,audio
host: version 12371.75.0 (Official Build) stable-channel reef 
kernel: Linux localhost 4.4.186-16721-gcdc0ab99cc00 #1 SMP PREEMPT Wed Sep 25 23:52:33 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/buster...
```

#### Please describe your issue:
No sound in chroot. I have reinstalled it twice, with the audio target both times.
I haven't done anything on my own in the filesystem since the last powerwash, and everything should be running  normally.

I noticed the issue while trying to run Geometry Dash in Steam.

**Comment by SirFireball3521** [comment]
Update: I noticed a recurring error in crosh when crouton is running.
`Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files`

**Comment by Black-Alpha** [comment]
dun dun dun

**Comment by d2cmath** [comment]
I have the same problem, but it is resolved after updating my chroot. I think the problem is that CRAS needs to be recompiled after the OS update, and updating chroot does that. 

The instruction for updating chroot can be found on the main page of crouton. 

Notes:
- You may run into a problem of unable to compile CRAS, then you may need to remount /tmp with exec permission, as this was found in issue #4098 (I did this remount in my case and everything runs smoothly except few harmless warnings).
- @SirFireball3521: The warning you found related to LibCrosService is harmless and it only occurs when you switch the screen between Chrome OS and the X server of chroot. This is probably an artifact of crouton's src/freon.c which always tries the old method to communicate back to Chrome browser, if it fails then the new method is used. I think the old method is pretty much obsolete now.
- The new Chrome OS update also brings another warning: "Unable to register core dump handler", and I think it is related to crouton's host-bin/crash_reporter_wrapper script, it is somehow misaligned with the new system.

**Comment by SirFireball3521** [comment]
Issue fixed. I simply updated the Chroot using the `-u` flag.
