### ISSUE TITLE
Video playback (Reddit) not working on chroot.

### ISSUE THREAD

**Issue by Moire9** [dnschneid/crouton#4188]
Output of `sudo edit-chroot -all`:
```
name: xenial
encrypted: no
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome
host: version 12499.66.0 (Official Build) stable-channel candy 
kernel: Linux localhost 4.4.190-16770-gb3c36ab5af98 #1 SMP PREEMPT Thu Nov 14 23:21:08 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
Watching videos on Reddit (which are embedded video files, like mov, m4a, mp4, gif, gifv, etc.) does not work. The first frame of the video ('thumbnail') displays but the video does not play.

#### If known, describe the steps to reproduce the issue:
1. Open Reddit
2. Click on post containing video
3. Be sad that you can't watch the video

**Comment by SirNapkin1334** [comment]
I suppose I'll also ask 2 questions I have: is it possible to decrypt a chroot, and can you undo making a chroot autostart?

**Comment by DennisLfromGA** [comment]
@SirNapkin1334,

>  is it possible to decrypt a chroot, ...

Maybe but it's not easy, see this comment by the crouton author -
- https://github.com/dnschneid/crouton/issues/1024#issuecomment-55548474

> ... and can you undo making a chroot autostart?

Yes, you can *undo* it by removing `/etc/init/crouton.conf` and/or by changing the run state in your `croutn.init` file to 'n' like: `RUN_STATE=n` 

> And is it possible to make an encrypted boot autostart?

I don't know of a way but I haven't played with it since doing the autostart stuff.

*Hope this helps,*
-**DennisLfromGA**
