### ISSUE TITLE
Can't install any chroot, CRAS script fucks itself up

### ISSUE THREAD

**Issue by daemonspudguy** [dnschneid/crouton#4204]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Compiling CRAS (i386)...
sh: 119: Bad substitution
during bootstrapping

#### If known, describe the steps to reproduce the issue:
Try to make a chroot, any chroot.

**Comment by CINJ** [comment]
Same problem updating a target!

See log below. Lost audio output since CRAS died, oh, and lost about 12 hours trying to find the hang when using SDL apps in the chroot - turns out, when it tried to use the sound device it locked up waiting for it. Killing the audio sink got the application working again. All due to chronic crouton being a CRASshole.

LOG:
chronos@localhost / $ sudo crouton -p /media/removable/sammy/ -n xenial -u
/media/removable/sammy/chroots/xenial already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxiwi into the host...
Installing croutoncycle into the chroot...
Installing croutonfindnacl into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xiwi into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xiwi.conf into the chroot...
Installing xorg-dummy.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xiwi into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease                              
Hit:2 http://repository.spotify.com stable InRelease                                                           
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                                       
Hit:4 https://packages.microsoft.com/repos/vscode stable InRelease                                                  
Hit:6 https://download.sublimetext.com apt/stable/ InRelease                       
Get:7 http://archive.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Ign:5 https://debian.trikaliotis.net stable InRelease        
Hit:8 https://debian.trikaliotis.net stable Release
Fetched 218 kB in 4s (50.6 kB/s)
Reading package lists... Done
W: http://debian.trikaliotis.net/dists/stable/Release.gpg: Signature by key ECC5D8FD6374CFBD42A1991728E1D6A42AF47E44 uses weak digest algorithm (SHA1)
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.2.32).
ca-certificates is already the newest version (20170717~16.04.2).
sudo is already the newest version (1.8.16-0ubuntu1.8).
wget is already the newest version (1.17.1-1ubuntu1.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Syncing timezone...
Installing target audio...
Fetching CRAS (branch da64d1c5d016ada6b231ae675752d6bf3354a6f4)...
--2020-01-12 22:42:20--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/da64d1c5d016ada6b231ae675752d6bf3354a6f4.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 74.125.24.82, 2404:6800:4003:c03::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.24.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '/tmp/crouton-cras.IS2y6S/adhd.tar.gz'

     0K .......... .......... .......... .......... ..........  293K
    50K .......... .......... .......... .......... ..........  427K
   100K .......... .......... .......... .......... ..........  900K
   150K .......... .......... .......... .......... .......... 1.16M
   200K .......... .......... .......... .......... .......... 1.27M
   250K .......... .......... .......... .......... .......... 1.78M
   300K .......... .......... .......... .......... .......... 2.28M
   350K .......... .......... .......... .......... .......... 2.62M
   400K .......... .......... .......... .......... .......... 3.01M
   450K .......... .......... .......... .......... .......... 2.99M
   500K .......... .......... .......... .......... .......... 3.42M
   550K .......... .......... .......... .......... .......... 3.75M
   600K .......... .......... .......... .......... .......... 4.15M
   650K .......... .......... .......... .......... .......... 4.72M
   700K .......... .......... .......... .......... .......... 4.52M
   750K .......... .......... .......... .......... .........  4.67M=0.6s

2020-01-12 22:42:22 (1.31 MB/s) - '/tmp/crouton-cras.IS2y6S/adhd.tar.gz' saved [818710]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
alsa-utils is already the newest version (1.1.0-0ubuntu5).
libasound2:i386 is already the newest version (1.1.0-0ubuntu1).
libspeexdsp1:i386 is already the newest version (1.2~rc1.2-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
gcc-multilib is already the newest version (4:5.3.1-1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu1).
Suggested packages:
  glibc-doc:i386 manpages-dev:i386 speex:i386
The following NEW packages will be installed:
  libc6-dev:i386 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 linux-libc-dev:i386
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/2719 kB of archives.
After this operation, 14.8 MB of additional disk space will be used.
Selecting previously unselected package linux-libc-dev:i386.
(Reading database ... 309818 files and directories currently installed.)
Preparing to unpack .../linux-libc-dev_4.4.0-171.200_i386.deb ...
Unpacking linux-libc-dev:i386 (4.4.0-171.200) ...
Selecting previously unselected package libc6-dev:i386.
Preparing to unpack .../libc6-dev_2.23-0ubuntu11_i386.deb ...
Unpacking libc6-dev:i386 (2.23-0ubuntu11) ...
Selecting previously unselected package libspeex1:i386.
Preparing to unpack .../libspeex1_1.2~rc1.2-1ubuntu1_i386.deb ...
Unpacking libspeex1:i386 (1.2~rc1.2-1ubuntu1) ...
Selecting previously unselected package libspeex-dev:i386.
Preparing to unpack .../libspeex-dev_1.2~rc1.2-1ubuntu1_i386.deb ...
Unpacking libspeex-dev:i386 (1.2~rc1.2-1ubuntu1) ...
Selecting previously unselected package libspeexdsp-dev:i386.
Preparing to unpack .../libspeexdsp-dev_1.2~rc1.2-1ubuntu1_i386.deb ...
Unpacking libspeexdsp-dev:i386 (1.2~rc1.2-1ubuntu1) ...
Setting up linux-libc-dev:i386 (4.4.0-171.200) ...
Setting up libc6-dev:i386 (2.23-0ubuntu11) ...
Setting up libspeex1:i386 (1.2~rc1.2-1ubuntu1) ...
Setting up libspeex-dev:i386 (1.2~rc1.2-1ubuntu1) ...
Setting up libspeexdsp-dev:i386 (1.2~rc1.2-1ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
libc6-dev:i386 set to automatically installed.
libspeexdsp-dev:i386 set to automatically installed.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libc6-dev:i386 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 linux-libc-dev:i386
Use 'apt autoremove' to remove them.
Suggested packages:
  libasound2-doc:i386
The following NEW packages will be installed:
  libasound2-dev:i386
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/114 kB of archives.
After this operation, 544 kB of additional disk space will be used.
Selecting previously unselected package libasound2-dev:i386.
(Reading database ... 310150 files and directories currently installed.)
Preparing to unpack .../libasound2-dev_1.1.0-0ubuntu1_i386.deb ...
Unpacking libasound2-dev:i386 (1.1.0-0ubuntu1) ...
Setting up libasound2-dev:i386 (1.1.0-0ubuntu1) ...
libasound2-dev:i386 set to automatically installed.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
patch is already the newest version (2.7.5-1ubuntu0.16.04.2).
The following packages were automatically installed and are no longer required:
  libasound2-dev:i386 libc6-dev:i386 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 linux-libc-dev:i386
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (i386)...
sh: 119: Bad substitution
Failed to complete chroot setup.
Unmounting /media/removable/sammy/chroots/xenial...

**Comment by gerardwr** [comment]
Hi,

Same problem here.

Installed my new Acer R13 Chromebook today in Developer Mode, and ran the Crouton installation script.

I also get the ¨119 bad substitution¨ error while compiling CAS :
```
Compiling CRAS (native)...
sh: 119: Bad substitution
Failed to complete chroot setup.
```

**Comment by FadeShock** [comment]
Solution (At least for me):
I run a Hewlett-Packard Chromebook, Model Name: Chell. 

All I did was switch the channel back to stable, and it seemed to fix the CRAS script. Before, it wouldn't work because I was on the developer channel. 
So there you have it.

**Comment by gerardwr** [comment]
@FadeShock 
Thx for the hint, appreciate it!

I'm currently using the 81.0.xxxxx dev channel. Tonight I will switch back to "stable" and install Crouton again.

Fingers crossed!

**Comment by FadeShock** [comment]
No problem! Hope it works out for you!

**Comment by gerardwr** [comment]
@FadeShock 

ISSUE SOLVED :-)

Used this procedure, maybe it helps others.

I re-installed Crouton after switching back to the Stable channel:
- was using the 81.0.xxxxx dev channel
- switching to "stable" executes a Powerwash, so a full reset.
- when rebooted the Chromebook is still in Developer Mode, and now running 79.0.xxx (official build)
- installed Crouton acc. this Github using "The easy way"
- the installation runs OK, "compiling CAS" now runs fine, the "119 bad substitution" error is now gone.
- installation fully completes, asking for "... specify username ......", so all is well.

Excellent, many thanks for your help !! Spent many, many hours while trying to solve the issue on my own, in the end the solution is simple.

**Comment by FadeShock** [comment]
No problem!

**Comment by daemonspudguy** [comment]
All of a sudden, it works. (On beta, at least)

**Comment by DennisLfromGA** [comment]
All,

Please download a fresh **[crouton installer](https://goo.gl/fd3zc)** and update your chroot(s).
A fix has been merged for the [CrOS CRAS changes](https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/1968111) now.

*Hope this helps,*
-**DennisLfromGA**
