### ISSUE TITLE
Can't open crosh (solved)

### ISSUE THREAD

**Issue by BlockHackTk** [dnschneid/crouton#4205]
Here is the key combination
> ctrl +alt + t

Hello, I'm just having trouble opening the shell in chrome.
I'm using an Asus C301 on which I installed and uninstalled a countless number of times crouton, so I could access crosh (shell), but overnight I encounter this problem.
Version 80.0.3987.39 (Build officiel) beta (64 bits)

> [Conseil de pro] Utilisez "Ouvrir dans une fenêtre" ou "Plein écran" pour éviter que le raccourci Ctrl+W ferme votre terminal.
[Conseil de pro] Consultez [crosh] pour plus d'informations.
crosh n'est pas compatible avec cette version de Chrome
La commande "crosh" s'est terminée avec le code d'état 1.
Reconnecter (r), sélectionner (c) une autre connexion ou quitter (x) ?

Would you be able to help me?

![Screenshot 2020-01-13 at 11 23 33](https://user-images.githubusercontent.com/51758614/72248390-55bf0e00-35f7-11ea-8961-6c9e6c19c206.png)

**Comment by BlockHackTk** [comment]
I've switched chrome from Beta to Dev and I've got access to the terminal again.

**Comment by Underscore13** [comment]
This is due to the crosh URL being changed to chrome://terminal, I reverted it back to the old URL by switching chrome://flags/#terminal-system-app to "Disabled", which worked.

**Comment by DennisLfromGA** [comment]
It may be solely due to the [chrome://terminal](chrome://terminal) issue but take a look at this seemingly related crbug also:
- [Issue 1040999](): Chrome OS - Large Spike on >Linux>AppsNotWorking "vmshell is not supported on this version of Chrome" Beta 80.0.3987.39

It's at Pri-0 and is a Release Block Stable so it *should* get fixed *very* soon.
A workaround is to use the [Secure Shell App](https://chrome.google.com/webstore/detail/secure-shell-app/pnhechapfaindjhompbnflcldabbghjo).

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
