### ISSUE TITLE
Unable to trash file across file system boundaries

### ISSUE THREAD

**Issue by Kreikon** [dnschneid/crouton#4215]
```
Please paste the output of the following command here: sudo edit-chroot -all
crouton: version 1-20200116214215~master:9017d640
release: sid
architecture: amd64
xmethod: xorg
targets: xfce,core,x11,keyboard,audio,chrome
host: version 12607.82.0 (Official Build) stable-channel kip 
kernel: Linux localhost 4.4.196-16940-geab5e6346fdb #1 SMP PREEMPT Thu Jan 9 23:21:52 PST 2020 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

Using an HP G4 Chromebook and is still an amateur at Linux related technicalities.
I am unable to trash files in my download folder, however, I can trash files outside of the folder. I've tried every Debian release and updated my chroot, but they still produce the same issues. My download folder also seems to be recognized as an external drive.

![Screenshot_2020-01-24_23-36-58 (1)](https://user-images.githubusercontent.com/33871837/73118744-2c628400-3f0d-11ea-82b7-3976c00ad3cd.png)

#### If known, describe the steps to reproduce the issue:

It seems to be a problem for Debian only and not Ubuntu.

**Comment by DennisLfromGA** [comment]
@Kreikon,

Hmmm, I've never seen that before and I can't repo it on my xfce desktop either, but it's Ubuntu xenial.
For some reason, your Downloads is listed under 'Devices' instead of under 'Places'. 
Do you have any external media plugged into your Chromebook? Maybe that could interfere with it.
I don't have any Debian releases installed on my Chromebook so I can't test it ATM, if I get a chance I'll install one and see how it behaves - I'll get back to you here if I do.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Kreikon** [comment]
@DennisLfromGA 

There is nothing plugged into my Chromebook at the moment. I've tried resetting my Chromebook, however, it yielded the same results.

**Comment by DennisLfromGA** [comment]
@Kreikon,

Sorry, without being able to repo it and seeing no other reports it remains a mystery to me.
Hopefully, someone else will see this and pop in to help out.

-**DennisLfromGA**

**Comment by juntakemura** [comment]
I have exactly the same issue. I'm running Debian buster on a chromebook using crouton. My Downloads folder is in the right place and I'm not using any external device either.

I changed the owner of Trash but it didn't work.
