### ISSUE TITLE
Can't return to chromebook from xfce

### ISSUE THREAD

**Issue by kvnloughead** [dnschneid/crouton#4223]
```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/edit line 528.
Error: no "edit" mailcap rules found for type "cannot open `chroot-all' (No such file or directory)"
(xenial)kloughead@loc
```
Hi, having difficulty returning to chromebook from  xfce.  Here is what happens:

`Ctrl+Alt+Shift+Back` goes to a black screen (for at least 5 minutes, I haven't waited longer than that yet), `Ctrl+Alt+Shift+Forward` goes either to a black screen (from xfce) or back to xfce (from the aforementioned black screen).  `Ctrl+Alt+Shift+Refresh` returned me to xfce.   Any other suggestions?

**Comment by DennisLfromGA** [comment]
@kvnloughead,

Try switching to CrOS the programmatic way and see if it's any quicker.
In a terminal session *in your chroot* enter:
- `croutoncycle cros`

I like to use that since I'm usually at the keyboard in my chroot a lot of the  time.
Here's the `croutoncycle` usage for other options if you're interested:
```
croutoncycle next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number
```
*Hope this helps,*
-**DennisLfromGA**

**Comment by justinfrankel** [comment]
I found after upgrading my C101PA to 83.0.4103.97 (it hadn't been updated since February), I have this too. If I try to switch away (via ctrl/alt/shift or croutoncycle), the display freezes (still showing Xfce or whatever WM, but frozen). It appears that the VT support broke (probably in ChromeOS). If I switch back via ctrl/alt/shift/next, everything goes back to normal. So the only way back to ChromeOS is to log out. I'm going to try switching to the beta channel to see if it fixes.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
