### ISSUE TITLE
chromebook acer linux install error

### ISSUE THREAD

**Issue by hqnt** [dnschneid/crouton#4233]
```
Please paste the output of the following command here: sudo sh ~/Downloads/crouton -r trusty -t xfce
```

#### Please describe your issue:
i am trying to install linux on my chromebook and when i done this command, i got this "sh: 0: /home/chronos/user/Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
WARNING: trusty has reached upstream end-of-life.
That means there will be no package updates available.
You also have to specify a mirror to crouton (-m) for installation to proceed." what does this mean? can someone help?

**Comment by DennisLfromGA** [comment]
@hqnt,

The first 'noexec' warning you show above is because you have not *installed* crouton. It now needs to be installed under `/usr/local/bin`. See steps 1 through 4 of the guide linked below:
- [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

The second warning is because you chose to install the trusty release which in now at EOL and no longer supported. It would be best to use the current default xenial release for support and fewer problems.

I'm not sure if you're using an online guide, it looks like you may be, if so it's out of date.
Here's one that is fairly recent and has some pretty good ideas IMO:
- [How To Install Ubuntu Linux On Any Chromebook Model Without Replacing Chrome OS (Crouton)](https://www.linuxuprising.com/2018/12/how-to-install-ubuntu-linux-on-any.html)

*Hope this helps,*
-**DennisLfromGA**
