### ISSUE TITLE
I'm confused how to get 2 crouton chroots

### ISSUE THREAD

**Issue by RedcatPhoenix** [dnschneid/crouton#4238]
How do I install Linux Debian Wheezy LXDE as my 2nd Chroot while Linux Ubuntu 16.04 Xenial XFCE is my 1st Chroot?

**Comment by RedcatPhoenix** [comment]
Never mind, I figured it out!

**Comment by DennisLfromGA** [comment]
@RedcatPhoenix,

Glad you figured it out.

For those that may not know how to install & use multiple chroots, just specify a different name and/or release when you install it, like:
- `sudo crouton -t xfce` (defaults to xenial release and is named xenial)
- `sudo crouton -r buster -n buster -t xfce` (installs buster release and is named buster (the default))

When launching your desktop in the chroot of your choice just use the '`-n`' option again:
- `sudo startxfce4 -n xenial`
or
- `sudo startxfce4 -n buster`

------------
Not sure why you reopened this issue since you resolved it, I'll close it again.

*Hope this helps,*
-**DennisLfromGA**

**Comment by RedcatPhoenix2** [comment]
yesnt
