### ISSUE TITLE
Cannot get back to Linux after logging out. Chrome OS

### ISSUE THREAD

**Issue by AlphaRomeo81** [dnschneid/crouton#4260]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200116214215~master:9017d640
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12871.67.0 (Official Build) stable-channel nami 
kernel: Linux localhost 4.4.211-17198-ga431862f6e61 #1 SMP PREEMPT Thu Apr 2 18:28:00 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

Im new to Linux and coding. I logged out of Linux which took me back to Chrome OS and now I cant get back to Linux. Not sure what Im doing wrong. Thank you for the help.

**Comment by saqikawaay** [comment]
Hey @AlphaRomeo81 . 

What you'll need to do from the CROS shell (from ChromeOS, the one you get to with ctrl-alt-t) is first type `shell` to get to the shell, then type `sudo startxfce4` since you have xenial with xfce installed (the command would vary if you installed other desktop environments. For example, gnome would be `sudo startgnome` by default). 

One more little thing, if you are in linux and just need to go back to ChromeOS for something quick, you don't have to fully logout. You can go back and forth between ChromeOS and your chroot by using `ctrl+alt+shift+"back arrow"` and `ctrl+alt+shift+"forward arrow"`.

**Comment by SemiZhang** [comment]
I'm in the same situation.
Actually the problem is that once you logged out for the first time, the desktop doesn't work anymore after typing `startgnome` or any command for other desktop.
The `startgnome` script does run and pulled up the desktop, but it exit after the cursor showed up for about 1 second on the black screen. All seems like that the "logout" button has been automatically pressed.
