### ISSUE TITLE
No Microphone Input in linux

### ISSUE THREAD

**Issue by explodersname** [dnschneid/crouton#4268]
```
Please paste the output of the following command here: sudo startkde
```

**Comment by BensonBear** [comment]
I have also been struggling with this problem (presumably due to the same cause)  for a couple of days.   This happened with the most recent update to 81.0.4044.94 on an HP 11 G5 (setzer) which was forced upon us by the chromebook hanging and requiring a reboot after a long time up.   I was in the process of making a detailed post about what I have tried in order to diagnose or fix it.   This is crucial for me to fix since my friend is using Skype to communicate while being locked down due to coronavirus.   Will post some details later but just want to acknowledge that others are probably having the same issue.
