### ISSUE TITLE
"Unity" target installs gnome Ubuntu Bionic and Focal

### ISSUE THREAD

**Issue by saltedcoffii** [dnschneid/crouton#4284]
The unity target installs Ubuntu's version of gnome into the chroot and not the community supported versions of Unity from the Universe repositories. Is this intentional, an oversight, or a lack of crouton demand for Unity in 18.04+?

**Comment by DennisLfromGA** [comment]
@kingliamb,

The 'unity' target installs the minimal footprint with gnome-session, see below:
- unity
- -        Installs the Unity desktop environment. (Approx. 700MB)
- https://github.com/dnschneid/crouton/blob/master/targets/unity#L24

The 'unity-desktop' target installs the full Ubuntu  desktop meta-package, see below:
- unity-desktop
- -        Installs Unity along with common applications. (Approx. 1100MB)
- https://github.com/dnschneid/crouton/blob/master/targets/unity-desktop#L10


Perhaps you just need to install the unity-desktop target in your chroot. 🤔

*Hope this helps,*
-**DennisLfromGA**

**Comment by kingliamb** [comment]
Oh sorry, unity and unity-desktop both install versions of GNOME in Ubuntu Bionic +
The community maintained version of Unity (ubuntu-unity-desktop) isn't installed by either target.

**Comment by DennisLfromGA** [comment]
@kingliamb,

Okay, thanx for the clarification.

Since neither bionic nor focal are supported in crouton as yet, that may well be the case.
I doubt if bionic will be fixed unless someone submits a pull request with the proper additions but focal is on the list of LTS releases to be fully supported. See the crouton author's comment about this below -
- https://github.com/dnschneid/crouton/issues/4265#issuecomment-620366138

*Hope this helps,*
-**DennisLfromGA**
