### ISSUE TITLE
Turned off chromebook, turned on 5 minutes later, broken.

### ISSUE THREAD

**Issue by deaddandilion** [dnschneid/crouton#4298]
```
sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
```

#### Please describe your issue:
I turned off my chromebook, came back five minutes later, and I get the message on my screen saying "OS Verification is off". I tried to put it in developer mode, it worked, and then I tried installing crouton... It gave the message above. I had used crouton to install Ubuntu before this.

**Comment by DennisLfromGA** [comment]
@deaddandilion,

The error message you show above indicates that you did not install crouton using the new method.
See this troubleshooting guide for help:
- [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisLfromGA**

Closing. Please re-open if this issue is still a concern.
