### ISSUE TITLE
This isnt so much an issue rather a 'cinnamon' question

### ISSUE THREAD

**Issue by explodersname** [dnschneid/crouton#4328]
Is it possible to install multiple desktop environments with crouton, I have gnome installed and would like to use the cinnamon desktop environment. If there is some way to get this working please let me know. Thanks :)

**Comment by DennisLfromGA** [comment]
@explodersname,

Yes, you can install other desktops that crouton supports, just run the below command to see what's available:
- `sudo crouton -t list`

Unfortunately, the cinnamon desktop is not an option any longer due to a lack of support on ARM chips at the time.
You could try to install the cinnamon desktop in the chroot and then make the appropriate start* scripts, it may just work.

See below for the discussions and the actual pull request that removed it:

> Question: Why was Cinnamon DE removed? · Issue #3703 · dnschneid/crouton
> https://github.com/dnschneid/crouton/issues/3703

> Can't install Cinnamon on any distro · Issue #812 · dnschneid/crouton
> https://github.com/dnschneid/crouton/issues/812#issuecomment-43784309

> remove cinnamon target by smibarber · Pull Request #832 · dnschneid/crouton
> https://github.com/dnschneid/crouton/pull/832

*Hope this helps,*
-**DennisLfromGA**

**Comment by TheRealFanjin** [comment]
Is it possible to install your own DE?

**Comment by DennisLfromGA** [comment]
@TheRealFanjin 

You can install other desktops in the chroot and even create your own start scripts but since they're not supported in crouton you have to do it yourself.

For proper crouton support it's best to file a pull request, see below for some a couple the past that, unfortunately, didn't get merged due to unresolved conflicts:

> LXQT by zxvv · Pull Request #2525 · dnschneid/crouton
> https://github.com/dnschneid/crouton/pull/2525

> Mate by zxvv · Pull Request #2532 · dnschneid/crouton
> https://github.com/dnschneid/crouton/pull/2532 

*Hope this helps,*
-**DennisLfromGA**
