### ISSUE TITLE
Display just turns off

### ISSUE THREAD

**Issue by Codeer12** [dnschneid/crouton#4329]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 83.4.4 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 5.4.25+ #3 SMP Tue Jul 21 07:01:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
#### Please describe your issue:
When i go to crosh shell to start it using `sudo enter-chroot startxfce4`, my display just shuts off. I have to do a reboot to get it back up again. I am using Cloud Ready v83.

#### If known, describe the steps to reproduce the issue:
enter `sudo enter-chroot startxfce4` and issue is there

**Comment by DennisLfromGA** [comment]
@Codeer12,

Hmmm, do you get any errors or warnings at all?

See if just entering: `sudo startxfce4` makes any difference at all.

You could also try installing and using the 'xiwi' method which may help in this situation.

Since it's a CloudReady (Chromium OS) installation there may be issues unique to it tho.

*Hope this helps,*
-**DennisLfromGA**
