### ISSUE TITLE
pulseaudio won't connect to cras

### ISSUE THREAD

**Issue by wymby** [dnschneid/crouton#434]
After the last crouton update, including the new audio connection to cras, audio fails on my Acer C7.  E.g., audacious gives:

> pulseaudio: Failed to connect to server: Connection refused
> Couldn't connect to cras.
> alsa: snd_mixer_attach failed: Operation not permitted.
> Couldn't connect to cras.

Suggestions?

**Comment by gerroon** [comment]
Debian Jessie 64

Is this related?

W: [pulseaudio] sink.c: Default and alternate sample rates are the same.
W: [pulseaudio] source.c: Default and alternate sample rates are the same.
E: [pulseaudio] socket-server.c: socket(PF_INET6): Address family not supported by protocol
E: [pulseaudio] ltdl-bind-now.c: Failed to open module module-esound-protocol-tcp.so: module-esound-protocol-tcp.so: cannot open shared object file: No such file or directory
E: [pulseaudio] module.c: Failed to open module "module-esound-protocol-tcp".
E: [pulseaudio] module-gconf.c: pa_module_load() failed
W: [pulseaudio] module.c: module-combine is deprecated: Please use module-combine-sink instead of module-combine!
W: [pulseaudio] module-combine.c: We will now load module-combine-sink. Please make sure to remove module-combine from your configuration.
E: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
