### ISSUE TITLE
"UID 1000 not found in xenial" when using 'sudo startxfce4'

### ISSUE THREAD

**Issue by Alex-doesnt-know-how-to-code** [dnschneid/crouton#4432]
```
Please paste the output of the following command here: Entering /mnt/stateful_partition/crouton/chroots/xenial...
UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### If known, describe the steps to reproduce the issue: enter shell, type `sudo startxfce4`

**Comment by DennisLfromGA** [comment]
Please follow these troubleshooting steps -
- Common issues and reporting · dnschneid/crouton Wiki
https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting   

*Hope this helps,*
-**DennisLfromGA**

**Comment by Alex-doesnt-know-how-to-code** [comment]
Thank you for sending that link Dennis, But unfortunately none of the solutions worked :(. Im not sure what to do next. As my name states I dont know anything about coding so if I dont understand basic things it because this is the first thing to do with code I have ever dealt with.

**Comment by DennisLfromGA** [comment]
@Alex-doesnt-know-how-to-code 

Usually, the error "UID 1000 not found in xenial" indicates that the chroot did not install or finish installing and the user (UID 1000) did not get created. That's why I suggested following the troubleshooting guide.

If an update cannot fix it (`sudo crouton -u`) or if you are not prompted to finish the set up then it may be best to delete the chroot (`sudo delete chroot *`) and start over.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Phe0nyx** [comment]
> @Alex-doesnt-know-how-to-code
> 
> Usually, the error "UID 1000 not found in xenial" indicates that the chroot did not install or finish installing and the user (UID 1000) did not get created. That's why I suggested following the troubleshooting guide.
> 
> If an update cannot fix it (`sudo crouton -u`) or if you are not prompted to finish the set up then it may be best to delete the chroot (`sudo delete chroot *`) and start over.
> 
> _Hope this helps,_
> -**DennisLfromGA**

I tried to delete the chroot, but it only got me this: `sudo: delete: command not found`. I also tried updating it, but it only gave me this: `Failed to complete chroot setup.`, then unmounted the partition. What do I do now?

**Comment by DennisLfromGA** [comment]
@Alex-doesnt-know-how-to-code,

So sorry, I mistyped the command to delete the chroot above, I've since corrected it but here it is just to remove any confusion:   
- `cd /usr/local/chroots && sudo delete-chroot *`

You will still be prompted to be sure you want to delete it/them.

*Hope this helps,*
-**DennisLfromGA**

**Comment by dnschneid** [comment]
Please try the latest release of crouton and re-open if it doesn't fix the failure.

**Comment by DeviateBacon3** [comment]
UID 1000 not found in xenial
