### ISSUE TITLE
Xiwi Scrolling does not work

### ISSUE THREAD

**Issue by leonbollerup** [dnschneid/crouton#4448]
Hi there,

I tried searching around and have tried different solutions to no end.

I have a pixelbook i7 with crouton, running latest debian with xfce4 thru xiwi - but scroll (eg. two finger scroll) does not work.

Does anyone happend to have a solution ?

**Comment by mdegalli** [comment]
I have the same problem on Jessie.  Broke with the latest Chrome OS update 90.  Help!

**Comment by Alizter** [comment]
Same here!

**Comment by srolls25** [comment]
Setting AutoAddDevices to true in /etc/X11/xorg-dummy.conf seems to have resolved this for me

**Comment by Alizter** [comment]
@srolls25 I've also set this, but it didn't seem to change anything. Am I correct in setting this inside my chroot?

**Comment by mdegalli** [comment]
@srolls25 Thanks, that worked for me too.  Although, I updated my system now to a new chroot, Ubuntu Focus, without Xiwi and am happy without using the window.  After a week, I will now get back to work!

**Comment by srolls25** [comment]
As @Alizter noted, setting AutoAddDevices does have a nasty side effect in that keyboard input in chromeos is also received by the chroot.
I checked the log files again, and the issue seems to be caused by xorg using the xorg-dummy-conf file. In any chroot I have tried (other than xenial xorg), the log contains `Using` config file: "/etc/X11/xorg-dummy.conf" and touchpad scrolling does not work. It appears that the InputClasses defined in config files in /usr/share/X11/xorg.conf.d have no effect.

In xenial (xorg, not xiwi) xorg-dummy.conf is not used and touchpad scrolling works.
(II) config/udev: Adding input device Elan Touchpad (/dev/input/event6)
(**) Elan Touchpad: Applying InputClass "evdev touchpad catchall"

**Comment by maxsalibe** [comment]
> Setting AutoAddDevices to true in /etc/X11/xorg-dummy.conf seems to have resolved this for me

Does this work on mouse scroll too? I cannot scroll with the mouse wheel in Xenial Unity (I think that's the name). If so, what exactly should I do to implement that autoadddevices stuff?

**Comment by mdegalli** [comment]
I ended up reinstalling without xiwi.  The Autoadddevices sort of worked
but scrolling in Chrome simultaneously scrolled in my Linux window.

**Comment by maxsalibe** [comment]
Will I still be able to open Linux on a window if I don't pass the xiwi
target to the crouton installation? I mean, it's important for me to see
Chrome and Linux interfaces at the same time, split in two halves of the
screen.

**Comment by mdegalli** [comment]
I don't think so.  It was important to me also, but I learned to live with
it.

--Mark

**Comment by gabrys** [comment]
> Setting AutoAddDevices to true in /etc/X11/xorg-dummy.conf seems to have resolved this for me

@srolls25 worked for me too, although it does have an undesired effect of sending key and mouse events to the xiwi window even when it's not in focus, i.e. open a text editor though xiwi, switch to chrome, whatever you type to the URL bar, or anywhere else appears also in the text editor :o
