### ISSUE TITLE
Can't delete chroot!

### ISSUE THREAD

**Issue by yoiammaac** [dnschneid/crouton#4477]
Please help!!
chronos@localhost / $ sudo crouton -r buster -t gnome-desktop,audio,core,xorg,x11,extension,keyboard    
/usr/local/chroots/buster already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.
chronos@localhost / $ sudo delete-chroot
sudo: delete-chroot: command not found
chronos@localhost / $ sudo delete-chroot -a
sudo: delete-chroot: command not found
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
It appears that the crouton scripts may have been deleted since the `delete-chroot` command cannot be found.
I would enter the following command to restore them:
- `sudo crouton -b`  

Then try the command again but with the name of the chroot you want to delete, like:
- `sudo delete-chroot buster`  

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
![image](https://user-images.githubusercontent.com/3418772/117545052-2bfed700-aff2-11eb-8033-f23ce151b929.png)

**Comment by Just-Randomly-Me** [comment]
This worked for me so ty
