### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Jeffrey324** [dnschneid/crouton#4501]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Creating hwaudio group with GID 18...
su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:

Every time I've tried to run the installation, within around 3 minutes or so the installation halts and greets me with this error note [(Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb is at fault)] Any idea how to fix this?

#### If known, describe the steps to reproduce the issue: 
I literally just run the installation.

**Comment by Just-Randomly-Me** [comment]
try sudo crouton -r xenial -u

**Comment by samzofkie** [comment]
I also have this problem now :(

**Comment by ncisoft** [comment]
I got the solution, follow the steps:

1. do factory reset
    - change chromebook to stable channel
    - it will promote to reboot  and powerwash, just do it
    - when enter initialized screen,  connect wifi, dont do registering process
    - **visit via guest**
    - check chrome version, it will be set to factory version, e.g. my shown version was 72.0.03626.122, it is an **important step**
2. crouton installation  
    - do crouton installation, it will be sucessful
    - double check, then reboot  
    - do the rest chromebook progress
    - Chrome OS was upgraded to the lastest version, my version is 91.0,4472.81, and crouton will work perfect


Good luck.
.

**Comment by DennisLfromGA** [comment]
@ncisoft,

A point of clarification:

The stable channel version for most devices is currently: [13904.41.0 / 91.0.4472.81](https://cros-updates-serving.appspot.com/)
That's what version most will have after moving to the stable channel and powerwashing, not 72.0.03626.122

**Comment by ncisoft** [comment]
> @ncisoft,
> 
> #### A point of clarification:
> The stable channel version for most devices is currently: [13904.41.0 / 91.0.4472.81](https://cros-updates-serving.appspot.com/)
> That's what version most will have after moving to the stable channel and powerwashing, not 72.0.03626.122

@DennisLfromGA ,

Please see the attachment, I have verified the above steps. ![72.0.0.3626.122](https://ftp.bmp.ovh/imgs/2021/06/22b8ec3cea4407ed.jpg)

**Comment by DennisLfromGA** [comment]
@ncisoft,

As I said, the stable channel version for most devices is currently: 13904.41.0 / 91.0.4472.81
I'm not sure why you have 72.0.03626.122 but that is *way* behind the current one.

See the below link for the current versions in the stable, beta & dev channels for all devices -
- CrOS Updates Serving
https://cros-updates-serving.appspot.com/

Of note, you can also download the current and several previous stable channel versions for your device(s) on that site too if you can't find it elsewhere.

*Hope this helps,*
-**DennisLfromGA**

**Comment by ncisoft** [comment]
@DennisLfromGA,

After the above steps, my toy was upgraded to the latest version.

![current version](https://ftp.bmp.ovh/imgs/2021/06/664c882a6d62c969.png) ![EOL](https://ftp.bmp.ovh/imgs/2021/06/2ee116e1266c8de0.png)

**Comment by Saswotb9** [comment]
**I GOT A WORKING SOLUTION**
At First, I also got the same error, It is not the problem with crouton or it's packages instead its due to the latest chrome os 91 update. 
STEP 1--Backup any important data from the chromebook to external drive or the cloud. 
STEP 2--Visit the website "cros.tech" and search for your chromebook model then, download the chrome os 78 or the least version (NOT version 91)
![image](https://user-images.githubusercontent.com/80771042/121726218-faee5680-cb09-11eb-93a1-4c273b73037a.png)
STEP 3-- Create a recovery media using the chromebook recovery utility. 
STEP  4-- Hold the following buttons;
1. esc+reload.....then, click power button. 
STEP 5-- insert the recovery media into your chromebook
STEP 6--recover your chromebook and boot into chrome os 78 after network and sign in process. 
STEP 7--Download the crouton setup script file and save it in downloads folder. 
STEP 8--press CTRL+ALT+T then, run the following commands;
```
1. shell
2. sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton 
3. sudo crouton -t xfce
```
set your username and password after the setup completes.
STEP 9-- Now, go to settings;
About Chrome OS
Then, Check for updates............
Now, If you update your chromebook to 91, your chroot will NOT be affected. 

**Final Work;**
![crouton-works](https://user-images.githubusercontent.com/80771042/121727401-92a07480-cb0b-11eb-9d8b-38b7fea8950b.png)

**Comment by dnschneid** [comment]
Latest crouton release should work fine even with 91, so please try again and re-open if you still get failures.
