### ISSUE TITLE
Please i really need help with CRAS not working!

### ISSUE THREAD

**Issue by Ultimatechno** [dnschneid/crouton#4508]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: xenial
encrypted: no
crouton: version 1-20200724165050
release: xenial
architecture: amd64
```

#### Please describe your issue:
So I recently had a problem with Ubuntu unity on my ChromeOS, so I decided to uninstall the chroot to reinstall it after. I did these commands in order, to install unity, in Crosh:

```
shell
sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
sudo crouton -t unity
```

I waited for it to finish installing but at the end, instead of having the "enter your username" I got a bunch of errors from CRAS as seen in the screenshot. Btw I'm on the stable version of ChromeOS with the developer mode enabled. I tried installing xfce instead of Unity and many others + i tried a LOT of others things, even powerwashing and nothing worked.

Please help me and thank you all.

![image](https://user-images.githubusercontent.com/81396442/121033400-2b389c80-c77a-11eb-9c25-44261039e8af.png)
![image](https://user-images.githubusercontent.com/81396442/121033456-368bc800-c77a-11eb-962e-c912d750649f.png)

**Comment by UmashankarTriforce** [comment]
@DennisLfromGA The issue you've linked is not what @Ultimatechno is facing. 

This issue from CRAS is because Xenial runs an old version of gcc (i think gcc-4 or gcc-5), which is not able to recognize the command line option. That command line option was added to make sure that CRAS can be compiled on older versions of ChromeOS.

There are a couple of ways you can actually fix your issue -

Shift to a distro which ships with gcc-7 or higher (like bionic or something)

If you want to stick with Xenial, for whatever reason, then first create the chroot with core target, install gcc-7 or higher in your chroot, and then update your chroot with unity.

But recently, CRAS has broken its makefiles, so I have opened an issue here and mentioned a quick fix! If you're facing the same issue after working on above steps, you can try out the solution on the link!

**Comment by DennisLfromGA** [comment]
@UmashankarTriforce,

[Pull request 4507](https://github.com/dnschneid/crouton/pull/4507/) looks to be a fix for the '-Werror' issue to me but I could be wrong.
Both this issue and issue #4506 start with:
```
Compiling CRAS (i386)...
In file included from libcras/cras_client.c:47:
```
Granted they are different errors.
 
I'll leave this issue closed though since you've given the OP some workarounds.

*Hope this helps,*
-**DennisLfromGA**
