### ISSUE TITLE
How to make ALSA a working audio device (REAPER)

### ISSUE THREAD

**Issue by unanamis** [dnschneid/crouton#4525]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
This might be the wrong forum to post to, but long story short, I'm trying to use REAPER https://www.reaper.fm/ in Ubuntu (xenial, bionic, focal... the results are the same), and no matter what I try I can't make my UMC 1820 audio interface a working audio device in REAPER. The error message "ALSA: error opening audio input device" even appears when I use the computer's own I/Os. Pulseaudio works fine, but I can't select multiple inputs with it, hence why I need ALSA. The UMC is recognized as a soundcard, but isn't recognized in REAPER's audio device drop down menu.

This is what runs in the Cros terminal when I'm in ubuntu getting "ALSA: error opening audio input device"
```
audio: executing pasuspender
ALSA lib pcm_hw.c:1700_snd_pcm_hw_open) Invalid value for card
```

We've been trying to figure it out in the REAPER forums, but to no avail: https://forum.cockos.com/showthread.php?t=254563

I don't know if anyone can help me, but I figured I'd contact the chromebook gurus for help. If it's just an incompatability thing, I can accept that, but I'd just like to know if that's the case.

**Comment by BobUnderwoodSF** [comment]
"Would it help to know that my pulseaudio I/O options are "cras?" I'm dual booting from a chromebook, so maybe it's just because my computer doesn't allow this kind of thing."

I submit it might help your troubleshooting efforts to realize you're not "dual-booting" your Chromebook. It first boots into Chrome OS; the Crouton scripts create a chroot into which a Linux (Ubuntu, etc) is installed and run (I guess it depends on how you define dual-booting).

CRAS is ChRomiumAudioSystem.

I suggest you stick with Focal and, running with Glenbo's thought (The original "error opening audio input device" message still sounds to me like the hardware was grabbed by another process that won't relinquish control.), I'd try removing the audio target by deleting the Focal chroot and reinstalling with minimal targets.

sudo delete-chroot focal
sudo crouton -r focal -t xfce

**Comment by unanamis** [comment]
Did all of that and am still getting the same problem. Any advice as to where to go from here?
```
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
audio: executing pasuspender
Connection failure: Connection refused
pa_context_connect() failed: Invalid argument
```

**Comment by BobUnderwoodSF** [comment]
Can you boot from a Live CD .iso of Focal?
Have you looked at Ubuntu Studio?https://ubuntustudio.org/
    On Friday, June 25, 2021, 11:11:59 AM PDT, unanamis ***@***.***> wrote:  
 
 


Did all of that and am still getting the same problem. Any advice as to where to go from here?
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
audio: executing pasuspender
Connection failure: Connection refused
pa_context_connect() failed: Invalid argument

**Comment by unanamis** [comment]
I don't have the ability for a CD. Also, I would like not to do Ubuntu Studio as I've already invested a good few years in Reaper. 

> Can you boot from a Live CD .iso of Focal? Have you looked at Ubuntu Studio?https://ubuntustudio.org/ On Friday, June 25, 2021, 11:11:59 AM PDT, unanamis ***@***.***> wrote: Did all of that and am still getting the same problem. Any advice as to where to go from here? ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card audio: executing pasuspender Connection failure: Connection refused pa_context_connect() failed: Invalid argument — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by unanamis** [comment]
Is there anything that I would need to do after that code-wise?

> "Would it help to know that my pulseaudio I/O options are "cras?" I'm dual booting from a chromebook, so maybe it's just because my computer doesn't allow this kind of thing."
> 
> I submit it might help your troubleshooting efforts to realize you're not "dual-booting" your Chromebook. It first boots into Chrome OS; the Crouton scripts create a chroot into which a Linux (Ubuntu, etc) is installed and run (I guess it depends on how you define dual-booting).
> 
> CRAS is ChRomiumAudioSystem.
> 
> I suggest you stick with Focal and, running with Glenbo's thought (The original "error opening audio input device" message still sounds to me like the hardware was grabbed by another process that won't relinquish control.), I'd try removing the audio target by deleting the Focal chroot and reinstalling with minimal targets.
> 
> sudo delete-chroot focal
> sudo crouton -r focal -t xfce

**Comment by BobUnderwoodSF** [comment]
Sorry if I was unclear. Can you boot from a USB drive? 

What make and model of Chromebook do you have?

    On Friday, June 25, 2021, 2:59:13 PM PDT, unanamis ***@***.***> wrote:  
 
 


I don't have the ability for a CD. Also, I would like not to do Ubuntu Studio as I've already invested a good few years in Reaper.


Can you boot from a Live CD .iso of Focal? Have you looked at Ubuntu Studio?https://ubuntustudio.org/ On Friday, June 25, 2021, 11:11:59 AM PDT, unanamis @.***> wrote: Did all of that and am still getting the same problem. Any advice as to where to go from here? ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card audio: executing pasuspender Connection failure: Connection refused pa_context_connect() failed: Invalid argument — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by BobUnderwoodSF** [comment]
I don't know how to tweak the configuration to get it to work.

    On Friday, June 25, 2021, 3:00:54 PM PDT, unanamis ***@***.***> wrote:  
 
 


Is there anything that I would need to do after that code-wise?


"Would it help to know that my pulseaudio I/O options are "cras?" I'm dual booting from a chromebook, so maybe it's just because my computer doesn't allow this kind of thing."

I submit it might help your troubleshooting efforts to realize you're not "dual-booting" your Chromebook. It first boots into Chrome OS; the Crouton scripts create a chroot into which a Linux (Ubuntu, etc) is installed and run (I guess it depends on how you define dual-booting).

CRAS is ChRomiumAudioSystem.

I suggest you stick with Focal and, running with Glenbo's thought (The original "error opening audio input device" message still sounds to me like the hardware was grabbed by another process that won't relinquish control.), I'd try removing the audio target by deleting the Focal chroot and reinstalling with minimal targets.

sudo delete-chroot focal
sudo crouton -r focal -t xfce

**Comment by unanamis** [comment]
You weren't unclear, I just have no understanding of anything relating to computing. Most of this stuff I've just learned from forums.

Technically I can boot from a USB. At least I'm pretty sure I can. I'm working a Samsung 4+, 32GB. I d

> Sorry if I was unclear. Can you boot from a USB drive? What make and model of Chromebook do you have? On Friday, June 25, 2021, 2:59:13 PM PDT, unanamis ***@***.***> wrote: I don't have the ability for a CD. Also, I would like not to do Ubuntu Studio as I've already invested a good few years in Reaper. Can you boot from a Live CD .iso of Focal? Have you looked at Ubuntu Studio?https://ubuntustudio.org/ On Friday, June 25, 2021, 11:11:59 AM PDT, unanamis @.***> wrote: Did all of that and am still getting the same problem. Any advice as to where to go from here? ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card audio: executing pasuspender Connection failure: Connection refused pa_context_connect() failed: Invalid argument — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by BobUnderwoodSF** [comment]
Does it have a BIOS/UEFI that you can access when you first power it up?

    On Friday, June 25, 2021, 4:18:56 PM PDT, unanamis ***@***.***> wrote:  
 
 


You weren't unclear, I just have no understanding of anything relating to computing. Most of this stuff I've just learned from forums.

Technically I can boot from a USB. At least I'm pretty sure I can. I'm working a Samsung 4+, 32GB.


Sorry if I was unclear. Can you boot from a USB drive? What make and model of Chromebook do you have? On Friday, June 25, 2021, 2:59:13 PM PDT, unanamis @.> wrote: I don't have the ability for a CD. Also, I would like not to do Ubuntu Studio as I've already invested a good few years in Reaper. Can you boot from a Live CD .iso of Focal? Have you looked at Ubuntu Studio?https://ubuntustudio.org/ On Friday, June 25, 2021, 11:11:59 AM PDT, unanamis @.> wrote: Did all of that and am still getting the same problem. Any advice as to where to go from here? ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card audio: executing pasuspender Connection failure: Connection refused pa_context_connect() failed: Invalid argument — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by unanamis** [comment]
Looks like I'm running BIOS from what I can tell. As to having acess to it, I'm not entirely sure what that means. 

> Does it have a BIOS/UEFI that you can access when you first power it up? On Friday, June 25, 2021, 4:18:56 PM PDT, unanamis ***@***.***> wrote: You weren't unclear, I just have no understanding of anything relating to computing. Most of this stuff I've just learned from forums. Technically I can boot from a USB. At least I'm pretty sure I can. I'm working a Samsung 4+, 32GB. Sorry if I was unclear. Can you boot from a USB drive? What make and model of Chromebook do you have? On Friday, June 25, 2021, 2:59:13 PM PDT, unanamis @.> wrote: I don't have the ability for a CD. Also, I would like not to do Ubuntu Studio as I've already invested a good few years in Reaper. Can you boot from a Live CD .iso of Focal? Have you looked at Ubuntu Studio?https://ubuntustudio.org/ On Friday, June 25, 2021, 11:11:59 AM PDT, unanamis @.> wrote: Did all of that and am still getting the same problem. Any advice as to where to go from here? ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card audio: executing pasuspender Connection failure: Connection refused pa_context_connect() failed: Invalid argument — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by BobUnderwoodSF** [comment]
It turns out that your Intel (GeminiLake) Chromebook does not support booting from USB.
https://mrchromebox.tech/#devices
I'm out of ideas - you could try

https://linuxmusicians.com/index.php

    On Friday, June 25, 2021, 5:44:57 PM PDT, unanamis ***@***.***> wrote:  
 
 


Looks like I'm running BIOS from what I can tell. As to having acess to it, I'm not entirely sure what that means.


Does it have a BIOS/UEFI that you can access when you first power it up? On Friday, June 25, 2021, 4:18:56 PM PDT, unanamis @.***> wrote: You weren't unclear, I just have no understanding of anything relating to computing. Most of this stuff I've just learned from forums. Technically I can boot from a USB. At least I'm pretty sure I can. I'm working a Samsung 4+, 32GB. Sorry if I was unclear. Can you boot from a USB drive? What make and model of Chromebook do you have? On Friday, June 25, 2021, 2:59:13 PM PDT, unanamis @.> wrote: I don't have the ability for a CD. Also, I would like not to do Ubuntu Studio as I've already invested a good few years in Reaper. Can you boot from a Live CD .iso of Focal? Have you looked at Ubuntu Studio?https://ubuntustudio.org/ On Friday, June 25, 2021, 11:11:59 AM PDT, unanamis @.> wrote: Did all of that and am still getting the same problem. Any advice as to where to go from here? ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card audio: executing pasuspender Connection failure: Connection refused pa_context_connect() failed: Invalid argument — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by unanamis** [comment]
Alright. Thanks for the help. I'll try and see what I can get over there. See ya later!
