### ISSUE TITLE
Crouton is now maintainance only. Does that mean it will be shut down soon?

### ISSUE THREAD

**Issue by yoiammaac** [dnschneid/crouton#4655]
i was pretty shocked:
>crouton is now maintenance-only
>This means that:

>Only bugfix and release list PRs will be accepted.
>New distro releases will be added to the list

**Comment by BetaPictoris** [comment]
Crouton is an open source project so "shutting down" wouldn't really happen unless all the forks, and this repo, where blown out of existence (something plausible in the year 2459 when GitHub shuts down). In the event that GitHub does shut down in the next few years (something I wouldn't bet on) your chroot would still be safely at home on your Chromebook because it doesn't require to connect to a server anywhere. It was pretty much the writing on the wall that Crouton would stop getting new features, even through PRs, and go "maintenance-only".

**Comment by bdombro** [comment]
Why is croton in maintenance mode? Is there a modern alternative or something?
