### ISSUE TITLE
Jammy?

### ISSUE THREAD

**Issue by hiddensea** [dnschneid/crouton#4725]
Can crouton support the latest version of ubuntu (22.04 LTS) Jammy Jellyfish?

**Comment by DennisLfromGA** [comment]
No, jammy is not a **[listed release](https://github.com/dnschneid/crouton/blob/master/installer/ubuntu/releases)** in crouton, supported or unsupported.   

And since crouton is now 'maintenance only' I'm not sure it will be added.   

You could make a pull request for it and see if the crouton devs will add it.

*Hope this helps,*
-**DennisLfromGA**

**Comment by dnschneid** [comment]
I'm happy to merge updates to release lists, if someone creates the MR

**Comment by TomTravis** [comment]
PR added

**Comment by TomTravis** [comment]
![Screenshot at 2022-05-09 02-29-00](https://user-images.githubusercontent.com/46386261/167391553-26896305-b2f3-49cd-8bab-229c05b0ba0e.png)

**Comment by TomTravis** [comment]
> No, jammy is not a **[listed release](https://github.com/dnschneid/crouton/blob/master/installer/ubuntu/releases)** in crouton, supported or unsupported.
> 
> And since crouton is now 'maintenance only' I'm not sure it will be added.
> 
> You could make a pull request for it and see if the crouton devs will add it.
> 
> _Hope this helps,_ -**DennisLfromGA**

yes now debootstrap supports the install just and in the crouton entry to the release file and it installs support by the people who made it chroot has issues yes

_Hope this helps,_

**Comment by dnschneid** [comment]
Try installing using `CROUTON_BRANCH=slowpoke_fixes crouton` and let me know if things work

**Comment by hiddensea** [comment]
I no longer use Chrome os devices
