### ISSUE TITLE
I need a way to run my chroot

### ISSUE THREAD

**Issue by Arvin2A** [dnschneid/crouton#4748]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
sudo sh ./edit-chroot -all
name: bionic
encrypted: yes, locked
Unmounting /media/removable/USB Drive/chroots/bionic...

#### Please describe your issue:
sudo sh ./startcli
Enter encryption passphrase for bionic: 
Entering /media/removable/USB Drive/chroots/bionic...
Cannot execute /bin/bash: Permission denied
Unmounting /media/removable/USB Drive/chroots/bionic...

I need a way to execute crouton in external device

**Comment by Arvin2A** [comment]
Now this happened!!!
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory

**Comment by TomTravis** [comment]
yes you may need to remount and change the exec privs
it run without errors after remount new crouton need to update privs
chronos@localhost / $ sudo mount -o remount,exec,suid,nosymfollow /media/removable/sd200
chronos@localhost / $ sudo mount -o remount,exec,suid,symfollow /tmp
every time my machine start i have to do this i set up a script all i use is external devices
/tmp is causing problems

**Comment by Arvin2A** [comment]
i still have this after i did those commands:

Enter encryption passphrase for bionic: 
Entering /media/removable/USB Drive/chroots/bionic...
Cannot execute /bin/bash: Permission denied
Unmounting /media/removable/USB Drive/chroots/bionic...

**Comment by TomTravis** [comment]
yes the fS is protected and bash runs in /tmp so maybe the experts can chime in, you have to look at you FS now

**Comment by Arvin2A** [comment]
I just tried this command:
**chronos@localhost /media/removable/USB Drive/bin $**  sudo bash startcli -b
A command must be specified in order to run in the background.

**Comment by Arvin2A** [comment]
And this...
**chronos@localhost /media/removable/USB Drive/bin $** sudo sh ./enter-chroot bionic
Enter encryption passphrase for bionic: 
Entering /media/removable/USB Drive/chroots/bionic...
Cannot execute /bin/sh
Unmounting /media/removable/USB Drive/chroots/bionic...

**Comment by Arvin2A** [comment]
Maybe a new installation of crouton?

**Comment by Arvin2A** [comment]
I didn't set the key file yet on this installation but I came with this in my new chroot:
name: bionic_two
encrypted: no
Entering /media/removable/USB Drive/chroots/bionic_two...
crouton: version 1-20220111101058~master:a9eafaee
release: bionic
architecture: 
targets: core,cli-extra
host: version 14588.123.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.254-18805-g12d6850827f5 #1 SMP PREEMPT Wed May 18 19:53:03 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB Drive/chroots/bionic_two...

**Comment by TomTravis** [comment]
ok very good, you can look at the FS system with Just the shell not  enter-chroot to look at the FS. no issue then check the status of bash
crosh> shell
chronos@localhost / $ cd /media/removable/sd200/
chronos@localhost /media/removable/sd200 $ pwd
/media/removable/sd200
chronos@localhost /media/removable/sd200 $ cd bull
chronos@localhost /media/removable/sd200/bull $ cd chroots
chronos@localhost /media/removable/sd200/bull/chroots $ pwd 
/media/removable/sd200/bull/chroots
chronos@localhost /media/removable/sd200/bull/chroots $ cd bullseye
chronos@localhost /media/removable/sd200/bull/chroots/bullseye $ ls
bin  boot  dev  etc  home  lib  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
chronos@localhost /media/removable/sd200/bull/chroots/bullseye $ cd bin
bash: cd: bin: Too many levels of symbolic links
chronos@localhost /media/removable/sd200/bull/chroots/bullseye $ pe
chronos@localhost /media/removable/sd200/bull/chroots/bullseye $ cd bin
chronos@localhost /media/removable/sd200/bull/chroots/bullseye/bin $ ls bash
bash
chronos@localhost /media/removable/sd200/bull/chroots/bullseye/bin $ ls -la bash
**-rwxr-xr-x. 1 root root 1282512 Aug  4  2021 bash**
chronos@localhost /media/removable/sd200/bull/chroots/bullseye/bin $

it the same with FS 
crosh> shell
chronos@localhost / $ cd /usr/local/bin
chronos@localhost /usr/local/bin $ more pe
sudo mount -o remount,exec,suid,dev,nosymfollow /media/removable/sd200/
sudo mount -o remount,exec,suid,dev,symfollow /media/removable/sd200/
sudo mount -o remount,exec,suid,symfollow /tmp
sudo mount -o remount,exec,suid,symfollow /
chronos@localhost /usr/local/bin $ more enter-chroot
#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

APPLICATION="${0##*/}"
BACKGROUND=''
BINDIR="`dirname "\`readlink -f -- "$0"\`"`"
CHROOTS="`readlink -m -- "$BINDIR/../chroots"`"
KEYFILE=''
LOGIN=''
NAME=''
TARGET=''
USERNAME='1000'
TMPXMETHOD=''
NOLOGIN=''
SETUPSCRIPT='/prepare.sh'

USAGE="$APPLICATION [options] [command [args...]]

Enters an installed Debian-based chroot for running alongside Chromium OS.

By default, it will log into the primary user on the first chroot found.
You can specify a command and parameters to run instead of an interactive shell.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: $CHROOTS
    -l          Make the command part of a login. Parameters are passed directly
                to the chroot command, and a call to su is appended.
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
--More--(3%)

chroot has special status you have to command the files a bit different
IE
-rwxr-xr-x. 1 root root 1282512 Aug  4  2021 bash
chronos@localhost /media/removable/sd200/bull/chroots/bullseye/bin $ ./bash
bash: ./bash: No such file or directory
chronos@localhost /media/removable/sd200/bull/chroots/bullseye/bin $ pwd
/media/removable/sd200/bull/chroots/bullseye/bin
chronos@localhost /media/removable/sd200/bull/chroots/bullseye/bin $ /media/removable/sd200/bull/chroots/bullseye/bin/bash
bash: /media/removable/sd200/bull/chroots/bullseye/bin/bash: No such file or directory
chronos@localhost /media/removable/sd200/bull/chroots/bullseye/bin $ 

[read](https://linux.die.net/man/1/chroot)
you have to configure chroot
chronos@localhost /media/removable/sd200/bull/chroots $ sudo chroot bullseye
(bullseye)root@localhost:/# bash -v
# System-wide .bashrc file for interactive bash(1) shells.

# To enable the settings / commands in this file for login shells as well,
# this file has to be sourced in /etc/profile.

see you under multiple chroots many processes, this is the file system for me
sda                                                                  8:0    1  29.3G  0 disk 
|-sda1                                                               8:1    1   9.8G  0 part /media/removable/root
|-sda2                                                               8:2    1   8.8G  0 part /media/removable/tmp
`-sda3                                                               8:3    1  10.7G  0 part /media/removable/home
sdb                                                                  8:16   1 183.3G  0 disk /media/removable/sd200

for crouton
mmcblk0                                                            179:0    0  58.2G  0 disk 
|-mmcblk0p1                                                        179:1    0  50.1G  0 part /mnt/stateful_partition

the mount enter-chroot defines
bindmount /dev
bindmount /dev/pts
bindmount /dev/shm
bindmount /tmp /tmp exec
bindmount /proc
tmpfsmount /var/run 'noexec,nosuid,mode=0755,size=10%'
tmpfsmount /var/run/lock 'noexec,nosuid,nodev,size=5120k'
bindmount /var/run/dbus /var/host/dbus
bindmount /var/run/shill /var/host/shill
bindmount /var/lib/timezone /var/host/timezone
for m in /lib/modules/*; do
    if [ -d "$m" ]; then
        bindmount '-o ro' "$m"

it is a machine

[crosh.txt](https://github.com/dnschneid/crouton/files/8780062/crosh.txt)
[crosh  shell.txt](https://github.com/dnschneid/crouton/files/8780065/crosh.shell.txt)

**Comment by Arvin2A** [comment]
update:
sh: 0: getcwd() failed: Input/output error
sh: 0: Can't open ./startcli

**Comment by DennisLfromGA** [comment]
@Arvin2A,

There is no need whatsoever to remount *anything* if you use the default location under `/usr/local/bin` to install your crouton scripts. If your crouton chroots are located on external media just see the built-in `-c` option when launching your desktop, see below:

- `-c CHROOTS  Directory the chroots are in. Default: /usr/local/chroots`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Masong19hippows** [comment]
This guy just has scripts in an external drive and is failing to execute them. He made a reddit post but then deleted it. He completely reinstalled crouton and the chroot, and is just trying to use `chroot`, without the proper steps outlined above, to access the chroot.  I couldn't talk sense into him

Reddit post  is here for more context. Probably good to close since its user error. 
https://www.reddit.com/r/Crouton/comments/uyai9r/cannot_execute_binbash_permission_denied_need/?utm_medium=android_app&utm_source=share

**Comment by Arvin2A** [comment]
I successfully entered the chroot but now I am moving to a new problem in installing. I am opening a new issue post in github

**Comment by githubbin765** [comment]
Anyone else run into permissions errors when trying to run chroot independently of crouton? I set the permissions to chronos for the user, group for /bin/bash. I still receive permissions errors when trying to execute chroot commands also with sudo stating permission denied with /bin/bash & with other means. 

This seems like the OS is malfunctioning entirely with permissions in this case maybe due to OS changes. 

Seems like a possible solution is to reinstall bash somehow to a different location then re-executing bash. 

If there is a better repository to post this, please let me know. I did see the crostini repo however since it's dated 2018 I didn't see it being that relevant.
