### ISSUE TITLE
Debootstrap Error

### ISSUE THREAD

**Issue by RAMBoykott** [dnschneid/crouton#4824]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
sudo: edit-chroot: command not found

#### Please describe your issue:
Failed to run debootstrap

I tried this:

chronos@localhost / $ sudo crouton -d -f ~/Downloads/mybootstrap.tar.bz2
Downloading xenial-amd64 bootstrap to /home/chronos/user/Downloads/mybootstrap.tar.bz2
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.E9z/installer/ubuntu/bootstrap: /tmp/crouton.Do7/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.Do7/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
**Failed to run debootstrap.**

**Comment by TomTravis** [comment]
yes the /tmp dir is noexec this can be changed
Are you trying to create a chroot in your chroot 
You can do this directly no need to use the crouton cmd. Please explain what your idea is?

I just used debootstrap it work just fine

**Comment by RAMBoykott** [comment]
I Use chromebook so i got no cmd.... i got Nothing on my Laptop. I just want kali linux.

**Comment by RAMBoykott** [comment]
I dont know how to do that

**Comment by TomTravis** [comment]
google 'man mount' and read about exec  int the man pages 
Kail  cannot install via crouton Usrmerge fails and the install stops

What Chrome book do you  have ?

**Comment by RAMBoykott** [comment]
@TomTravis did you found sth. out about how it works? If yes, please write the code in here.... thanks

**Comment by TomTravis** [comment]
https://linux.die.net/man/8/mount
defaults
Use default options: rw, suid, dev, exec, auto, nouser, async, and relatime.
dev
Interpret character or block special devices on the filesystem.

nodev

Do not interpret character or block special devices on the file system.

diratime
Update directory inode access times on this filesystem. This is the default.
nodiratime
Do not update directory inode access times on this filesystem.
dirsync
All directory updates within the filesystem should be done synchronously. This affects the following system calls: creat, link, unlink, symlink, mkdir, rmdir, mknod and rename.
exec
Permit execution of binaries.

noexec

Do not allow direct execution of any binaries on the mounted filesystem. (Until recently it was possible to run binaries anyway using a command like /lib/ld*.so /mnt/binary. This trick fails since Linux 2.4.25 / 2.6.0.)

remount
Attempt to remount an already-mounted filesystem. This is commonly used to change the mount flags for a filesystem, especially to make a readonly filesystem writeable. It does not change device or mount point.
The remount functionality follows the standard way how the mount command works with options from fstab. It means the mount command doesn't read fstab (or mtab) only when a device and dir are fully specified.

mount -o remount,rw /dev/foo /dir

After this call all old mount options are replaced and arbitrary stuff from fstab is ignored, except the loop= option which is internally generated and maintained by the mount command.

mount -o remount,rw /dir

After this call mount reads fstab (or mtab) and merges these options with options from command line ( -o ).

ro
Mount the filesystem read-only.

The cmd is 
sudo  mount -o remount,symfollow,exec /tmp or file system needed

The attached file is Crosh Mount --help text capture
[mnt.txt](https://github.com/dnschneid/crouton/files/9852811/mnt.txt)

**Comment by RAMBoykott** [comment]
At first Thanks to you @TomTravis 

Now.... thats a lloooootttt of code. Im a little bit dumb and I understand mostly nothing.
Could you please give me it like that:

**_The easy way (assuming you want an Ubuntu LTS with Xfce)_**
Download crouton
Open a shell (Ctrl+Alt+T, type shell and hit enter)
Copy the installer to an executable location by running sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
Now that it's executable, run the installer itself: sudo crouton -t xfce
Wait patiently and answer the prompts like a good person.
Done! You can jump straight to your Xfce session by running sudo enter-chroot startxfce4 or, as a special shortcut, sudo startxfce4
Cycle through Chromium OS and your running graphical chroots using Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.
Exit the chroot by logging out of Xfce.



It still says:

chronos@localhost / $ sudo crouton -t xfce
Downloading latest crouton installer...
############################################################################ 100.0%
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.okr/installer/ubuntu/bootstrap: /tmp/crouton.FbM/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.FbM/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.




I JUST WANT KALI LINUX! I want a easy way to get it. BUT IT FAILS. THATS HOW I STARTED, THATS HOW I ENDED UP! Please help me and give me a few lines of code which I need to copy and than it should work. please? please.... thanks

**Comment by RAMBoykott** [comment]
However its the "Failed to run debootstrap." error

**Comment by RAMBoykott** [comment]
Ok I run that but now it says 

mount: bad usage 
Try mount--help for more information

**Comment by TomTravis** [comment]
it works here
sudo mount -o remount,symfollow,exec /tmp
chronos@localhost ~ $ sudo mount -o remount,symfollow,exec /tmp
Password: 
chronos@localhost ~ $

**Comment by RAMBoykott** [comment]
I will try in Same minutes

**Comment by RAMBoykott** [comment]
chronos@localhost / $ sudo mount -o remount,symfollow,exec /tmp
chronos@localhost / $ 

Nothing happend

**Comment by TomTravis** [comment]
sudo mount -o remount,symfollow,exec /tmp

**Comment by RAMBoykott** [comment]
It run sucessfull I think.... what to do now?

**Comment by TomTravis** [comment]
well

here is my take install bullseye and update the sources list to get a stable release 
read up on 
https://wiki.debian.org/chroot and make a kali  chroot  on a bullseye setup via crouton

**Comment by RAMBoykott** [comment]
@TomTravis 
If I type in it in that happens:

chronos@localhost / $ apt-get install binutils debootstrap
bash: apt-get: command not found

**Comment by TomTravis** [comment]
yes sudo apt-get

you cannot forget sudo or login as su after setting the root password

**Comment by RAMBoykott** [comment]
Ok but how do i start Kali Linux now?

**Comment by RAMBoykott** [comment]
Oh i understand

**Comment by RAMBoykott** [comment]
I will try later

**Comment by MADOK1** [comment]
I seem to be having the same problem as @RAMBoykott

**Comment by RAMBoykott** [comment]
What chromebook do you have?

**Comment by RAMBoykott** [comment]
Guys! Im getting angry.... I still get this error:

chronos@localhost / $ sudo crouton -d -f ~/Downloads/mybootstrap.tar.bz2
Downloading latest crouton installer...
############################################################################ 100.0%
Downloading xenial-amd64 bootstrap to /home/chronos/user/Downloads/mybootstrap.tar.bz2
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.pHm/installer/ubuntu/bootstrap: /tmp/crouton.jKa/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.jKa/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.

**Comment by RAMBoykott** [comment]
Please help me @DennisLfromGA @TomTravis

**Comment by TomTravis** [comment]
i have no idea what your doing
forget xenial  for the time being
set the privs and exec state on the device you use privs RWX state is sysfollow and exec
the permission denial it a priv issue use sudo in chrosh it , the may require password

**Comment by MADOK1** [comment]
Changing the update channel in my system settings to "stable" and then powerwashing my device seemed to fix the problem.

**Comment by TomTravis** [comment]
![Uploading Screenshot at 2022-10-25 14:22:51.png…]()

**Comment by dnschneid** [comment]
#4799

**Comment by RAMBoykott** [comment]
@MADOK1 At this moment my Chanel is dev should i change it now to stabil?
