### ISSUE TITLE
How do I prevent my Acer C7 from sleeping when lid is closed?

### ISSUE THREAD

**Issue by lrvaka** [dnschneid/crouton#5]
Just want to know if there is a way that I can edit the sleep settings.

**Comment by spookyboogy** [comment]
Hi dnschneid, my chromebook shut off due to a power surge while I had powerd stopped, and now it no longer boots and the charge light does not turn on. I've tried holding the power button for a while, in combination with esc and/or refresh, but to no avail. 

Is it impossible to reboot in this case? What can I do? Any help would be greatly appreciated.

**Comment by dnschneid** [comment]
That has nothing to do with powerd or crouton; it has to do with the power surge that you edited out of your post for some reason.  I'd contact support because it's possible something's fried.

**Comment by spookyboogy** [comment]
Ah, well, I opened up my chromebook and disconnected/reconnected the battery and all is well now. Thanks anyway.
