### ISSUE TITLE
Sudo commands in crosh

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [dnschneid/crouton#5016]
I can not use sudo in crosh. I am incapable of setting the flags no matter what I do to be able to use sudo commands. No, I am not on the DEV channel. Any help would be much appreciated

**Comment by githubcitc** [comment]
shell
Sudo commands will not succeed by default.
If you want to use sudo commands, use the VT-2 shell
(Ctrl-Alt-{F2/Right arrow/Refresh}) or build the image with the
login_enable_crosh_sudo USE flag:

$ USE=login_enable_crosh_sudo emerge-$BOARD chromeos-login
or
$ USE=login_enable_crosh_sudo cros build-packages --board=$BOARD
    
chronos@ampton-rev4 / $ sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.

**Comment by DennisLfromGA** [comment]
See:
- https://github.com/dnschneid/crouton/discussions/5005
- https://github.com/dnschneid/crouton/wiki/Crouton-Quick-Start

-**DennisLfromGA**

**Comment by githubcitc** [comment]
> See:
> 
>     * [M117+ removes the 'sudo' command. #5005](https://github.com/dnschneid/crouton/discussions/5005)
> 
>     * https://github.com/dnschneid/crouton/wiki/Crouton-Quick-Start
> 
> 
> -**DennisLfromGA**

Sorry those web pages contain information that is far too complicated; not a computer science person! The information about using 'vt-2' shell was not understood. The user 'chronos' required a password, the shell includes some statement about set password via root, but could not enter as root because root password not known either.

Really liked crouton. Enjoyed simple process of switch on computer, shell, sudo startxfce4. The computer was used for very simple use as a school teacher

Will now try to use the crostini way. Initial thoughts are a disappointment. See the blog: 'chemistryinthecity.neocities.org'

**Comment by amogus-technologies** [comment]
> > See:
> > ```
> > * [M117+ removes the 'sudo' command. #5005](https://github.com/dnschneid/crouton/discussions/5005)
> > 
> > * https://github.com/dnschneid/crouton/wiki/Crouton-Quick-Start
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > -**DennisLfromGA**
> 
> Sorry those web pages contain information that is far too complicated; not a computer science person! The information about using 'vt-2' shell was not understood. The user 'chronos' required a password, the shell includes some statement about set password via root, but could not enter as root because root password not known either.
> 
> Really liked crouton. Enjoyed simple process of switch on computer, shell, sudo startxfce4. The computer was used for very simple use as a school teacher
> 
> Will now try to use the crostini way. Initial thoughts are a disappointment. See the blog: 'chemistryinthecity.neocities.org'

The chronos password is `test0000`
