### ISSUE TITLE
Can't login to ubuntu after machine is off

### ISSUE THREAD

**Issue by Iluvatari** [dnschneid/crouton#556]
I was having no trouble logging in to crouton yesterday (which was the day I installed it), but now it prompts me for a "localhost login" (the screen with "developer console" at the top). It does not accept "root" (or rather, after I enter root it asks for a password), and it does not accept the login/password combination I set, saying "login incorrect" and prompting again for another. I am running on an acter C720 Chromebook and installed the Ubuntu Unity desktop.

I have tried restarting the machine, but come out with the same result.

**Comment by artemisfowl123** [comment]
okay, just go to the terminal and type in what it said tot type when you installed it to activate it. For example , i have unity, so type i would type in the terminal sudo startunity, and it will work.
shell
sudo start(name)

**Comment by giebasjo** [comment]
I have everything set up so that I should be able to just 

'startkde' or 'startxfce4'

but when I run this commands in the crosh shell, they always come back saying 

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

or that

$DISPLAY is not set or cannot connect to the X server.

How do I fix this so that I can actually do things as a linux machine?
