### ISSUE TITLE
Wordpress Target

### ISSUE THREAD

**Issue by moocow1452** [dnschneid/crouton#572]
Yeah I know, another target request, but how cool would it be to add a sudo startwordpress command and be able to log onto a localhost blog, no muss, no fuss? I'm pretty sure even an ARMBook can run a lamp server, and while it could be put together easy enough with already existing functionality, Ubuntu doesn't work let me start up the server on a proper socket, and Debian works alright, but I'm having trouble using the credentials for some reason. So could something like Cloud 9's solution for starting a Wordpress blog where you startup and go be a feasible project for Crouton, or is it more niche than anything?

**Comment by brandwaffle** [comment]
I built a target for WordPress development here https://github.com/10up/word-salad.

Pull requests are always welcome. @dnschneid if you think this is something worthwhile to add to the default targets, I'd love to do so. I'm not sure it makes sense to add since it's more of an "app" environment than an OS build, but I know there's a lot of people out there doing WP development, so I could see going either way.
