### ISSUE TITLE
Raise notification in Chrome OS from chrooted environment

### ISSUE THREAD

**Issue by sgtpep** [dnschneid/crouton#581]
There is a script croutonurlhandler for opening URL in Chrome OS and optionally switching to it. It could be great to be able to raise HTML5/Chrome notifications like this. So someone who prefer to work with crouton from crosh/Secure Shell could be notified using the command like notify-send.

**Comment by dnschneid** [comment]
FWIW we would basically make a libnotify implementation that would either dispatch to another notify daemon or to the extension, depending on the focus.

**Comment by ticviking** [comment]
is there a how to on how to do this on the wiki? I'd love to be able to have a shell script send a notification

**Comment by dnschneid** [comment]
Nope, no wiki yet.
1. Install the extension target into your chroot, and make sure the crouton extension is installed on Chromium OS (it'll let you know at the end of the terminal output if you don't have the extension installed and will give you a link to download it).
2. Inside the chroot, make sure the websocket server is running.  If you have some graphical session open, it's running.  Otherwise, you may have to run it manually: `croutonwebsocket &`.  The extension icon will turn green if it's connected.
3. Play with the `croutonnotify` command.  If you run it without parameters, it'll print out help text.

**Comment by ticviking** [comment]
Thanks,

I'll take some time this weekend to play with it, and post a how-to
somewhere.

On Fri, Feb 20, 2015 at 4:35 PM, David Schneider <notifications@github.com>
wrote:

> Nope, no wiki yet.
> 1. Install the extension target into your chroot, and make sure the
> crouton extension is installed on Chromium OS (it'll let you know at the
> end of the terminal output if you don't have the extension installed and
> will give you a link to download it).
> 2. Inside the chroot, make sure the websocket server is running. If you
> have some graphical session open, it's running. Otherwise, you may have to
> run it manually: croutonwebsocket &. The extension icon will turn green
> if it's connected.
> 3. Play with the croutonnotify command. If you run it without parameters,
> it'll print out help text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/581#issuecomment-75339316>.
>



-- 
ahamblin
--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es
