### ISSUE TITLE
E: The method driver /usr/lib/apt/methods/https could not be found.

### ISSUE THREAD

**Issue by LiquidExecute** [dnschneid/crouton#593]
I cant update crouton. I was trying to install the keyboard target to get the volume/brightness keys working, and I get this error. "E: The method driver /usr/lib/apt/methods/https could not be found."
After trying to do any update, whether it is crouton itself or just the keyboard, when I try to enter linux the shell tells me there is a setup script that still exists. Linux does not seem to be having any related issues. 
Here is the text of the terminal:
http://i.imgur.com/8rwctsK.png

**Comment by GYashen** [comment]
Hi,
Could anyone please elaborate the exact steps to download and copy to the directory.

**Comment by DennisLfromGA** [comment]
@GYashen,

> Could anyone please elaborate the exact steps to download and copy to the directory.

Not sure what you mean by that but if it doesn't pertain to this issue please [open a new one](https://github.com/dnschneid/crouton/issues/new).

----
This issue was fixed years ago so if you're still having this problem update your chroot(s).

*Hope this helps,*
-**DennisL**

**Comment by GYashen** [comment]
@DennisLfromGA 

I am getting the below error with this command "sudo apt-get update && sudo apt-get install yarn"
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?

Would it be resolved by updating chroot(s), if yes, then could you please tell me how to update it. I am using Cloud9 IDE. 

Thanks

**Comment by DennisLfromGA** [comment]
@GYashen,

> Would it be resolved by updating chroot(s), .... I am using Cloud9 IDE.

If you installed your chroot recently then the fix has already been merged so that *may* not be your problem. Unfortunately, I don't have any experience with Cloud9 IDE so I can't tell if that's causing the problem.

> .... if yes, then could you please tell me how to update it. 

See this wiki page for instructions to troubleshoot & update your chroot:

- **[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)**

*Hope this helps,*
-**DennisL**
