### ISSUE TITLE
What about wayland?

### ISSUE THREAD

**Issue by edge226** [dnschneid/crouton#605]
Has anyone tried to get wayland working instead of X for the chromebooks? 

Might be a potential fix to the issues people are having with the pixel with beta Chrome OS. If that happens to go live I dont think testing this to get it working will be as nice.

**Comment by mildred** [comment]
I'm looking into it using the cyan platform with chromiumos r52 (it's using freon). Basically, everything is different because there is no tty.

Here is my strategy:

- use a systemd chroot (there is another pull request I improved that deals with entering the chroot using nsenter to emulate a full system using systemd)
- use systemd-logind which can handle user sessions when there is no tty present
- register a croutonfreon session to systemd-logind. It's a session that will grab the DRI device by default, and forward the dbus calls to pause and resume access to the device to the host cros dbus service
- have a way to enter the chroot in a new session that is associated with seat0 in logind
- make sure weston doesn't need a tty and use all the dbus calls to logind that are appropriate

So far, I could get rid of the LD_PRELOAD hack (bacause logind works well when there is no tty). The only patchs that will need to happen is for display managers (weston, xorg if we want to run it in the same mode) to make sure they do not access the devices directly (through /dev) but through logind, and to make sure they don't use a tty at all.

I'm learning many things here.

**Comment by mildred** [comment]
weston needs quite a bit of modifications.

First, it needs to continue even when there is no VT. This is a simple removal of `goto err_session` in function `launcher_logind_connect`.

Then, there is a timing problem. When weston starts, it tells logind it needs a DRM device. logind takes the device from the croutonfreonsession wrapper. it doesn't wait to get the feedback from the wrapper before giving it back to weston.

Unfortunately, freon doesn't release the DRM master instantly. logind assumes it can take the device away because it had given it away in the first place. Unfortunately, on chromiumos, freon is the first one here to get to the DRM device, and logind cannot take the device instantly.

logind then gives the device to weston, but without the DRM_MASTER because for a short time, freon still has it. This is a very weird scenario for weston because the device opens up successfully, but without DRM_MASTER as expected. Trying to draw on it will fail, and weston won't even imagine it can take the DRM_MASTER and it will work.

For the moment, I modified weston to detect when logind gives it a drm device that isn't master. In such cases, it will wait a little, release the device, and take it again from logind, hoping this time it will be master. if this fails, it aborts after 5 times.

I'm not sure this is the best way to do it. Ideally, freon should be able to run using the DRM device given by logind (a file descriptor given through dbus) instead of opening it from /dev. This way, logind can take the DRM_MASTER forcefully.

Or, we could tell logind that the freon session is special and cannot release the DRM device instantly. Logind should wait for the freon session before giving the DRM device to anyone else.

**Comment by DennisLfromGA** [comment]
[Google Chrome 50 Released With Wayland Support](http://www.phoronix.com/scan.php?page=news_item&px=Google-Chrome-50)
