### ISSUE TITLE
vlc network streaming does not work

### ISSUE THREAD

**Issue by frederic-parrenin** [dnschneid/crouton#664]
I installed vlc and tried to watch TV on my freebox adsl modem.
However, I have the following errors:

Votre média d'entrée ne peut être ouvert:
VLC ne peut pas ouvrir « rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=404&flavour=sd ». Vérifiez les messages pour plus de détails.

This perfectly works on a standard ubuntu system.

**Comment by samtap** [comment]
I discovered the same issue today when trying to open a rtsp stream using VLC in crouton

crouton: version 1-20151013174138~master:488c9e21
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,xiwi,extension,keyboard,kde,xbmc
host: version 7390.68.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu Nov 5 13:16:19 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Google results (http://unix.stackexchange.com/questions/48435/enable-rtsp-in-iptables) suggested opening port UDP/15947 but this didn't resolve anything. I also set the INPUT, FORWARD and OUTPUT policy to accept but no difference. 

Any ideas?

**Comment by poxin13** [comment]
I'm also having this issue attempting to stream RTSP via VLC.
"Unable to determine our source address: This computer has an invalid IP address: 0.0.0.0"

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.

**Comment by alex3d** [comment]
This issue is still there, but there are some workarounds:
1) If your RTSP server supports tcp interleaved mode:
  Go to Vlc -> Tools -> Preferences -> Show all -> Input /Codecs -> Demuxer -> RTP/RTSP -> Use RTP over RTSP (TCP)
2) To detect client IP address vlc/live555 [trying to resolve](https://github.com/xanview/live555/blob/41a5ec5f65bd626918a43951f743b4c9ffc52289/groupsock/GroupsockHelper.cpp#L597) `hostname` (in crouton it is `localhost`)
  You can set relevant hostname and it's ip address in /etc/hosts

**Comment by minterm** [comment]
The above didn't help me. Eventually, I got it working after using simply:
$ sudo hostname <internal IP address>
