### ISSUE TITLE
Mysqld Having to Manually Start

### ISSUE THREAD

**Issue by judsonmitchell** [dnschneid/crouton#73]
Thanks for this wonderful software!  I'm running a LAMP stack on the cli-extra target and I'm encountering this problem:  Every time I enter the chroot, I have to manually start mysqld and sshd.  I notice that trying to start these as an upstart job (sudo service mysql start) returns "mysqld: unrecognized service" and I have to: sudo mysqld.

Is this just a botched install or does this have something to do with the chroot?

**Comment by zopefiend** [comment]
Re. the comment from March 25, 2013, which states:

' the chroot's /etc/rc.local to launch whatever you need it to. It will only launch it once per mount (e.g. you can enter the chroot multiple times and it will only launch it once until all instances close).'

If I understand this correctly, it means that rc.local will only run once, when the first chroot is mounted, no  matter how many targets exist, and are mounted and running simultaneously.

I other words, even though multiple targets may exist, and are mounted by name ( -n ), they are all seen as 'instances' , and so will not run rc.local per each, after the first mounted instance, which 'wins', because it gets to run rc.local, by virtue of being the 'early bird'.

If that is correct, then it explains why I am having trouble enabling an ssh server on each chroot, and opening ssh terminals between chroots. As it turns out, I can only ssh into the first chroot to be mounted.

I was expecting to be able to develop / test Ansible playbooks, with one chroot running Ansible, and configuring the others over ssh, as a convenient / lightweight / inexpensive way to build a web development sandbox, prior to moving everything over to a full blown dev cluster with multiple hosts / VMs. 

It looks like I will have to be a bit more clever about how to set up and test my sandbox, by starting the chroot to be configured first, and only run the Ansible host in addition, at any given point. Also, it looks as if testing interactions between db server, web server, etc. will be 'limited'.

**Comment by dnschneid** [comment]
No, each chroot is mounted separately and will have its own rc.local run on mount.  But if you don't change the port of the SSH server, whichever one you start first will own the port.  These aren't virtual machines.

**Comment by zopefiend** [comment]
Hmm, well I did assign unique ssh port #s for each chroot, so now I.m confused again.

Right, not VMS, and That Is A Good Thing!

See error messages in current latest post here:

https://github.com/dnschneid/crouton/issues/203

Unique ports not recognized, and /  or connection refused.

**Comment by zopefiend** [comment]
It turns out that assigning the chroot name, and port# in the iptables command (in /etc/rc.local), and the corresponding IP address in /etc/hosts, is inadequate. 

The file:

/etc/ssh/sshd_config 

must also be edited so that the port# stays in sync with /etc/rc.local.

No explanation for the prior odd behavior, but at this point the desired functionality is repeatable.

**Comment by zopefiend** [comment]
OK, this is running now. After following the instructions here:

https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton

which explain how to open a port # (for iptables), and start sshd, it was found to be inadequate when using multiple chroots.

For example, IF you decide to use a non-standard port #, as is often recommended, and is required in this case, for each chroot to have a dedicated port #, then you also have to set the -p (port #) option when starting sshd:

/sbin/iptables -I INPUT -p tcp --dport 2222 -j ACCEPT

mkdir -p -m0755 /var/run/sshd

/usr/sbin/sshd -p 2222

making sure the port # opened in the iptables setting matches the selected port # for sshd, for each chroot

**Comment by terinjokes** [comment]
@dnschneid Did you ever port something like upstart-dummy?

**Comment by dnschneid** [comment]
Nope...

**Comment by yohnjang** [comment]
To anyone seeing this!

   I'm using Crouton on a Toshiba Chromebook 2 and I get the following error when I try to run MySQL from the command line.  I'm also having problems with other libraries like node.js as well.  

Is there some other package that I have to install to make these packages run like iptables?

Or is there a path I need to edit like /etc/rc.local ?

*ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)*
