### ISSUE TITLE
Trouble re-installing crouton

### ISSUE THREAD

**Issue by jackjameshoward** [dnschneid/crouton#968]
I have previously installed crouton with no problems at all. However I have since turned off developers mode clearing the local data.
I have tried to revert back to developers mode and re-install crouton but nothing seem to happen. I have pasted the command lines I've used below. If somebody can tell what I'm doing wrong I would appreciate it.

Welcome to crosh, the Chrome OS developer shell.
If you got here by mistake, don't panic!  Just close this tab and carry on.
Type 'help' for a list of commands.
crosh> shell
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -t xfce
chronos@localhost / $

**Comment by chcschmid** [comment]
I am running into the same issue. The crouton version that I downloaded just a few moments ago is 1-20161116131524~master:9db73043.

**Comment by DennisLfromGA** [comment]
@chcschmid,

Which issue? 
Please give us more details -

- Did you also get out of and back into Dev mode?
- When you run crouton do get no error and no output?
or
- It says sh : can t open /home/chronos/user/downloads/crouton?

-**DennisL**

**Comment by chcschmid** [comment]
I did get out of and back into Dev mode.

I downloaded the crouton yesterday evening and ran the following command
from 'shell'...

sudo sh -e ~/Downloads/crouton -r trusty -t xfce-desktop keyboard, chrome

It starts the installation and gets to 100%, then I get the following
result...

[image: 1.png]
[image: 2.png]
I checked for /usr/local/chroots to see if symlink existed, but the chroot
folder doesn't even exist in local.

- Christiaan
On Mon, Nov 21, 2016 at 6:27 AM DennisL <notifications@github.com> wrote:

@chcschmid <https://github.com/chcschmid>,

Which issue?
Please give us more details -

   - Did you also get out of and back into Dev mode?
   - When you run crouton do get no error and no output?
   or
   - It says sh : can t open /home/chronos/user/downloads/crouton?

-*DennisL*

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dnschneid/crouton/issues/968#issuecomment-261938269>,
or mute the thread

**Comment by DennisLfromGA** [comment]
@chcschmid,

> sudo sh -e ~/Downloads/crouton -r trusty -t xfce-desktop keyboard, chrome

I don't know if the command-line you show above is exactly what you typed but you need a comma ',' between targets and without any spaces (I think) - like:

> `sudo sh ~/Downloads/crouton -r trusty -t xfce-desktop,keyboard,chrome`

  
> It starts the installation and gets to 100%, then I get the following
result...

That doesn't sound like that was the hangup though if you got '100%'.
Your images/links above don't seem to work so we can't tell where it's failing.

*Sorry,*
-**DennisL**

**Comment by chcschmid** [comment]
Ah, your solution was what I needed. I was following instructions from a blog I found and the command used there didn't have a comma between xfce-desktop and keyboard. Thanks for your help @DennisLfromGA! It seems to be working now.

**Comment by DennisLfromGA** [comment]
@chcschmid, *Cool!* Glad I could help.

**Comment by sammymay97** [comment]
crouton still isnt working its saying illegal :/ wouldnt mind but i really wanna be able to use windows

**Comment by DennisLfromGA** [comment]
@sammymay97,

This issue was closed literally years ago.
If you are having trouble reinstalling crouton please follow this troubleshooting guide:
- [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)   

Then if you still have are having problems please open a new issue and tell us in detail what is wrong and what errors you're getting.

*Hope this helps,*
-**DennisLfromGA*
