### ISSUE TITLE
more of a question  - will Crouton run on Tegras k1 - the new acer 13.3 chromebook

### ISSUE THREAD

**Issue by ipstone** [dnschneid/crouton#979]
Really interested in getting the new acer Tegras K1, will crouton run on the device?
I am guessing yes, since crouton works on Samsung chromebook - which is arm based. 

does someone know? thanks

**Comment by Jscottkasten** [comment]
Hi, this comment is directed to @marcino239 in that last exchange with @alextnewman and @drinkcat above. I very nearly have CUDA working on the HP 14" Tegra-K1, but seem to be missing something.

Your comment mentions using the Acer stock kernel, and T4L R19 drivers, and you show output from deviceQuery and matrixMulCUBLAS.  On my HP, under ChromeOS + crouton, I was able to get deviceQuery to identify the hardware successfully.  However, every attempt at doing any real computation with any of the other samples ultimately fails in cudaMalloc().  I'm a bit unclear as to whether the HP has a slightly different version of the nVidia kernel driver than the Acer, or if I still have some config issues.  I also pulled down "chromeos-3.10" branch from "kernel", built a USB stick from Debian Jessie, and same result in a more "normal" user space.

Interestingly, in both cases, when cudaMalloc() fails, there is a kernel syslog trace from the driver which I traced to a specific line in the gk20a sources in linux-3.10.18 from the repo.  Both the stock kernel and the repo kernel trace back to this same message.  Basically a memory allocation within a fixed address range is unimplemented and listed as "todo" in the sources.  So again, I was left wondering if the Acer sources are not really represented by what's in the kernel repo.

I too looked at pulling the gk20a driver from the Jetson K1 sources from nVidia.  It would be a total nightmare due to the dependencies on a substantially different infrastructure.

Of course I've seen the news flash about nVidia pushing gk20a sources into the main-line.  And supposedly the main-line has support for most chrome devices...so, I dove in and actually got the main-line 4.1.3 running on top of Debian Jessie on USB stick.  Anyone interested in the config can get it from my public drive space:

https://drive.google.com/folderview?id=0B6wc5jYvaeo-fnQ3eV83cDFaMkNvRjRrYW1CZGhSX0k3SjVzZWZROWRqSnVYR3RJYV9HdmM&usp=sharing

Anyway, I built in nouveau + tegra anything, etc...

I had to create the /dev/nvmap entry, and symlink nvhost-as-gpu to /dev/dri/card0, and voila.... deviceQuery runs and details the hardware correctly.

But alas, I still can't run an actual program as they still fail on the cudaMalloc().  I started looking at the strace output of all the action in more detail, and notice it does try to open /dev/shm/cuda_injection_path_shm, which fails since it is not initialized.  I've searched on this and found nothing.  Maybe this is related to the cudaMalloc() failure and I still have some sort of configuration issue, or maybe the HP driver and nouveau are both not up to snuff.

I'm not sure what to make of this and would welcome any insights you guys might have.

Regards,

-S-

**Comment by marcino239** [comment]
Whey

I think most likely stock kernel is older version or there might be
hardware differences between HP and Acer 13.  I would try different
versions of kernel and see if you can get them to work.  Take a look at my
post at http://marcino239.github.io how I solved similar problem when
chromeos devs updated the kernel.

**Comment by Jscottkasten** [comment]
OK, looks interesting indeed.  Thanks, will spin it tomorrow and let you know.

Despite not getting what I was after yet, I was certainly surprised and encouraged that the latest stable main-line built and ran, that certainly indicates this hardware has a future and will make life easier down the road.

Cheers!

**Comment by Jscottkasten** [comment]
FANTASTIC!  It worked!  I'll have to diff the two and see what they did that broke things.  I also wonder what is going on in main-line that this wasn't working there either.

Anyway, your tip unlocked a few GFlops of brute force for me.  Thank you!

**Comment by marcino239** [comment]
Good news!  It will be great if you could share which version you have used
or perhaps write a blog post somewhere.

I really like cuda on tegra form factor.   It's not as fast as desktop but
it makes a really nice and portable machine for working on neural nets for
example.

**Comment by Jscottkasten** [comment]
I totally agree with you.  That's exactly why I chose this machine.  I dove in this past week to get this all working and thanks to your help, it finally is.

So what I have is a basic rootfs tarball based on Debian Jessie for a "compute only" system (no configured graphics) with the gnu compilers pre-configured to support SDK 6.0 and/or SDK 6.5 apps.  You just need to parted/cgpt your stick, mkfs, unpack the provided rootfs, drop down the files from the nVidia SDK and the L4T driver package according to the provided README pdf, adjust the symlinks for 6.0 or 6.5, copy the provided kernel to your boot partition, and voila - compute environment on a stick.  I broke the instructions down a bit for newbies in the README.

https://drive.google.com/open?id=0B6wc5jYvaeo-fnQ3eV83cDFaMkNvRjRrYW1CZGhSX0k3SjVzZWZROWRqSnVYR3RJYV9HdmM

Now that I know this was a kernel issue, I found references to it on nVidia developer zone, and on the ChromeOS lists.  So it seems the relevant parties are aware that things got borked.  Hopefully they will fix it later in the release channel.

Enjoy!

**Comment by gregnwosu** [comment]
ill see if i can get it to work also , or can we just create a crouton script to do this so that its completely easy

**Comment by Jscottkasten** [comment]
Hi @gregnwosu ,

Unfortunately, the real issue right now is that the "factory" kernel shipped for the T-K1 devices is broken in that the built in (not a module) nVidia driver is not adequately supporting the CUDA user space tools.  As @marcino239 so kindly pointed out, there is a roll-back that gets things going again.  Replacing the running kernel and modules is a little beyond the scope of a crouton or chrubuntu style script.  As mentioned in my earlier posts, I found evidence of discussion on this kernel issue over at nVidia Dev Zone and at one of the ChromeOS sites.  So hopefully the release channel will eventually get fixed if we all make enough noise.

Once the kernel is fixed, then yes, we can do a lot of user space fix ups with scripts and full CUDA and accelerated X support becomes at least theoretically possible.  Although we do have the feasibility issues raised above about getting the "Guest OS" full access to the Chrome X11, or somehow running dual X11 for host and guest both.

On bootable USB stick, we have none of these issues, which is why I posted a minimal base from which people could build.  It would most certainly be possible to take my bootable image and follow the work of these guys above to add proper accelerated X11 to it.  I did not take it that far yet as my immediate need is portable scientific number crunching.  If I do get around to accel-X anytime soon, I will certainly post the image.

Cheers,
-S-

**Comment by oleid** [comment]
@Jscottkasten Hey, I'm trying to get a mainline kernel going (currently 4.4-rc1; before I tried 4.3) on my Acer Chromebook 13 (nyan-big), going, which is also tegra K1 based. Yet, I never get any output on the screen. I tried your config, but to no avail. Any suggestions how to debug the situation? I know there is a JTAG port on the board, but I'm still reluctant do disassemble the device ;)

**Comment by Jscottkasten** [comment]
Ask, and you just might get lucky.  As it happens, I did play around with the 4.x series and here is the .config for 4.1.3 which was running on my machine.  The GA206 adapter is found by the DRI module.  I found that I could toy with the /dev nodes and get the CUDA stuff recognizing the hardware, but the DRI driver seems insufficient to actually run CUDA based software.  Your luck might be better on even newer kernels as I'm sure they are pulling in more of the work nVidia is supposedly pushing into the main line.

Unfortunately, my own work ground to a halt when the HP machine I have died.  I was typing on it, the screen went black, and I've never been able to power it back on since.  Have to send it in for warranty replacement.  :-(

Anyway, attached for everyone's enjoyment...

[config-linux-4.1.3.txt](https://github.com/dnschneid/crouton/files/35530/config-linux-4.1.3.txt)

One comment.  The screen stays black for some period of time while it boots.  Don't fret.  Give it a minute.  It does boot (my HP anyway).

**Comment by Jscottkasten** [comment]
@oleid   Sorry, forgot to tag you so you would get the email notification.  My bad.  See previous comment.  Cheers,  -S-

**Comment by oleid** [comment]
@Jscottkasten Thanks for the quick reply. Yep, that's the config I tried. Probably my machine boots but WiFi doesn't come up. So you don't have console output, too, but only see something on the screen as soon as X starts?

**Comment by Jscottkasten** [comment]
@oleid  Hi, my boot usb did not yet have X11 installed, so it was booting to console.  Still, took about 30 - 45 seconds to get to a visible screen.  Once there, it worked.  Never did get to try X11 though.

**Comment by oleid** [comment]
@Jscottkasten Okay, I definitively waited more than a minute.

**Comment by jonbiddell** [comment]
How do I unsubscribe from this list ?  I've looked on Github and it doesn't
seem to have an option.

**Comment by DennisLfromGA** [comment]
@jonbiddell - Up at the top of the page there is an '**Unwatch**' drop-down button, just select '*Ignoring*'.
![screenshot 2015-11-16 at 9 17 41 pm](https://cloud.githubusercontent.com/assets/3418772/11200925/b0bb24e0-8ca7-11e5-978e-41e71bc7a72a.png)
