### ISSUE TITLE
Elementary OS?

### ISSUE THREAD

**Issue by tejasmanohar** [dnschneid/crouton#994]
Can I install elementary os instead of original ubuntu?

**Comment by PinkaSSek** [comment]
I have Acer C720 4GB RAM,
I wanted install Elementary OS Luna. I did everything from http://jeanlouisnguyen.blogspot.com/2014/01/guide-how-to-install-elementary-os-on.html

And now when I'm typing 'sudo startelementary" I recived:

Entering /mnt/stateful_partition/crouton/chroots/elementary...
Unknown username "dnsmasq" in message bus configuration file
/usr/bin/startxfce4: Starting X server


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-58-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Dec 10 14:38:47 PST 2014 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=133b0ee8-e918-2342-bcb9-78d656236e9a/PARTNROFF=1 hashtree=PARTUUID=133b0ee8-e918-2342-bcb9-78d656236e9a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=58ba04712f08cbabcf5d65972ef3d67cc0674ca0 salt=c05ac168f3096f515e035b4cc0b6196e8db1a55f3f1432ab7395db6b1efd9ee2" noinitrd vt.global_cursor_default=0 kern_guid=133b0ee8-e918-2342-bcb9-78d656236e9a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3 
Build Date: 09 December 2014  11:03:52PM
xorg-server 2:1.15.1-0ubuntu2~precise4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Fri Jan  2 14:35:13 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied

(bluetooth-applet:505): Bluetooth-WARNING **: Could not open RFKILL control device, please verify your installation

(polkit-gnome-authentication-agent-1:535): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:535): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

** (nm-applet:518): WARNING **: Could not initialize NMClient /org/freedesktop/NetworkManager: The name org.freedesktop.NetworkManager was not provided by any .service files
** Message: applet now removed from the notification area

** (nm-applet:518): WARNING **: Failed to register as an agent: (2) The name org.freedesktop.NetworkManager was not provided by any .service files
** Message: using fallback from indicator to GtkStatusIcon
** Message: applet now embedded in the notification area

(xfdesktop:473): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:473): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:473): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(midori4:568): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.32.4/./gobject/gsignal.c:2361: signal `page-reordered' is invalid for instance `0x7f9ab81c86a0'

(midori4:568): Gtk-CRITICAL **: gtk_notebook_reorder_child: assertion `GTK_IS_NOTEBOOK (notebook)' failed

(midori4:568): Gtk-CRITICAL **: gtk_notebook_reorder_child: assertion `GTK_IS_NOTEBOOK (notebook)' failed

(midori4:568): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.32.4/./gobject/gsignal.c:2361: signal `page-reordered' is invalid for instance `0x7f9ab81c86a0'
** Message: Starting applet secret agent because GNOME Shell disappeared

** (nm-applet:518): WARNING **: Failed to register as an agent: (2) The name org.freedesktop.NetworkManager was not provided by any .service files
Timeout waiting for extension to connect.
croutonwebsocket error: Error: not connected.
(xfce4-terminal:477): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion `GDK_IS_WINDOW (window)' failed
** Message: applet now removed from the notification area
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down xscreensaver: 14:38:24: SIGHUP received: restarting...
xscreensaver: 14:38:24: running as pinky/pinky (1000/1000)

Hangup
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
xscreensaver: 14:38:24: Can't open display: :1.0
xscreensaver: 14:38:24: running as pinky/pinky (1000/1000)

xscreensaver: 14:38:24: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html

(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/elementary...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/elementary...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/elementary...

What should I do to fix this problem?

**Comment by crenwick** [comment]
Hi @PinkaSSek did you solve this issue? I'm running into the same error.
